CREATE OR REPLACE FUNCTION OFSMDM.TEST_MANIFEST_FN (BATCHID IN VARCHAR2)
RETURN NUMBER IS
BEGIN
  INSERT INTO STG_TEST_TABLE (N_AMOUNT)
  SELECT 1 FROM DUAL;
  COMMIT;
  RETURN 1;
END TEST_MANIFEST_FN;
/
