-- =============================================================================
-- OFSERM Schema — Enterprise Risk Management tables for OFSAA FSAPPS
-- =============================================================================
-- This file is auto-generated by RTIE /refresh-schema command.
-- Manual edits will be overwritten on next schema sync.
-- =============================================================================

-- Placeholder: tables will be populated by /refresh-schema command
-- which queries ALL_TAB_COLUMNS and generates DDL from Oracle metadata.
