-- =====================================================================
-- Task: ABL_MKT_RISK_WTDPOS_MATURITY_APPROACH_IR
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.ABL_MKT_RISK_WTDPOS_MATURITY_APPROACH_IR(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_CAPITAL(V_CCY_CODE,N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_GAAP_SKEY,N_IRC_BENCHMARK_SKEY,N_LONG_POSITION_AMT,N_REF_INDEX_SKEY,N_REP_LINE_SKEY,N_SHORT_POSTION_AMT,N_TIME_BAND_SKEY,N_TIME_ZONE_SKEY,N_WEIGHTED_LONG_POSITION_AMT,N_WEIGHTED_SHORT_POSITION_AMT,V_COMMODITY_GROUP_CODE)SELECT  /*+PARALLEL (4)*/ DIM_CURRENCY.V_ISO_CURRENCY_CD,to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),MAX(DIM_GAAP.n_gaap_skey),MAX((SELECT max(FSI_IRCS.Interest_Rate_Cd) FROM FSI_IRCS where FSI_IRCS.Irc_Name='OTH' OR FSI_IRCS.Irc_Name = 'PKR-V' )),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code = 'LONG' THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END),MAX((SELECT max(n_Mkt_Var_Skey) FROM DIM_MARKET_VARIABLES WHERE v_Mkt_Var_Code='OTH')),MAX((SELECT MAX(n_rep_line_skey) from DIM_MARKET_RISK_REP_LINE where DIM_MARKET_RISK_REP_LINE.v_rep_line_code ='IR')),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code = 'SHORT' THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END)*-1,DIM_MR_TIME_BAND.N_BAND_SKEY,MAX(CASE WHEN DIM_MR_TIME_BAND.v_band_sub_category in ('IRBN1','IRBN2','IRBN3','IRBN4') THEN (SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code ='Z1') WHEN DIM_MR_TIME_BAND.v_band_sub_category in('IRBN5','IRBN6','IRBN7') THEN (SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code ='Z2') WHEN DIM_MR_TIME_BAND.v_band_sub_category in('IRBN8','IRBN9','IRBN10','IRBN11','IRBN12','IRBN13','IRBN14','IRBN15') THEN (SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code ='Z3') END),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code like 'LONG' THEN FCT_MARKET_RISK_EXPOSURES.n_weighted_position_amt ELSE 0 END),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code like 'SHORT' THEN FCT_MARKET_RISK_EXPOSURES.n_weighted_position_amt ELSE 0 END)*-1,'NA' FROM FCT_MARKET_RISK_EXPOSURES LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_EXPOSURES.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.n_instr_type_skey = DIM_INSTRUMENT_TYPE.n_instr_type_skey LEFT OUTER JOIN DIM_BANDS DIM_MR_TIME_BAND ON FCT_MARKET_RISK_EXPOSURES.n_time_band_skey = DIM_MR_TIME_BAND.n_band_skey AND DIM_MR_TIME_BAND.v_Band_Type = 'MR TIME BAND' LEFT OUTER JOIN DIM_MARKET_RISK_POSITION ON FCT_MARKET_RISK_EXPOSURES.n_position_skey = DIM_MARKET_RISK_POSITION.n_position_skey LEFT OUTER JOIN DIM_DATES ON FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_EXPOSURES.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_EXPOSURES.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN DIM_CURRENCY ON COALESCE(FCT_MARKET_RISK_EXPOSURES.v_buy_rec_ccy_code, FCT_MARKET_RISK_EXPOSURES.v_sell_pay_ccy_code) = DIM_CURRENCY.v_iso_currency_cd AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_CURRENCY.D_RECORD_START_DATE AND DIM_CURRENCY.D_RECORD_END_DATE LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_EXPOSURES.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON DIM_RUN_IDENTIFIER.n_Run_Identifier_Skey = FCT_MARKET_RISK_EXPOSURES.n_run_identifier_skey LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND RUN_PARAMETERS.n_run_skey = '870' AND FCT_MARKET_RISK_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY=RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY /*AND ( DIM_RUN.f_run_definition_mode = 'U' OR ( DIM_RUN.f_run_definition_mode = 'R' AND DIM_RUN_IDENTIFIER.v_run_identifier_code = RUN_PARAMETERS.v_run_identifier_code ) )*/ WHERE 1=1 AND 1=1 AND FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey = DIM_DATES.N_DATE_SKEY AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' AND DIM_MR_TIME_BAND.v_band_sub_category LIKE 'IRBN%' AND DIM_INSTRUMENT_TYPE.V_BASEL_INSTR_TYPE_CODE_LVL1 = 'IR' AND COALESCE(FCT_MARKET_RISK_EXPOSURES.f_internal_cust_ind, 'N') = 'N' AND COALESCE(FCT_MARKET_RISK_EXPOSURES.f_gmr_indicator, 'Y') = 'Y' AND FCT_MARKET_RISK_EXPOSURES.n_var_port_skey IS NULL AND RUN_PARAMETERS.v_mrs_interest_rate_method = 'OPT1004' GROUP BY DIM_MR_TIME_BAND.N_BAND_SKEY, DIM_CURRENCY.v_iso_currency_cd, DIM_DATES.N_DATE_SKEY, DIM_RUN.N_RUN_SKEY LOG ERRORS INTO FCT_MARKET_RISK_CAPITAL$ ('1776769373413_33723721_20260331_1_Job_70b4b056b84e40f080b4c2ee29fc088b') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
