-- =====================================================================
-- Task: ABL_NON_SEC_RISK_WEIGHT_MAP_POP_CSTM
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.ABL_NON_SEC_RISK_WEIGHT_MAP_POP_CSTM(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_RW_MAP_MASTER(N_BASEL_TYPE_SKEY,N_BASEL_RATING,N_MIS_DATE_SKEY,F_BASEL_TYPE_IND,F_ST_LT_RATING_FLAG,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_ASSET_CLASS.N_BASEL_ASSET_CLASS_SKEY),to_char(DIM_BASEL_CREDIT_RATING.N_BASEL_RATING),to_char(DIM_DATES.N_DATE_SKEY),'A',F_ST_LT_RATING_FLAG,'870' FROM DIM_BASEL_ASSET_CLASS,DIM_BASEL_CREDIT_RATING,DIM_DATES,(SELECT 'L' F_ST_LT_RATING_FLAG FROM sys.DUAL) WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE=to_date('20260331','YYYYMMDD') LOG ERRORS INTO FSI_RW_MAP_MASTER$ ('1776768219901_31483504_20260331_1_Job_a32014ee2e864016b463f80e70538b3c') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
