-- =====================================================================
-- Task: ACCT_MITIGANT_MAPPING_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.ACCT_MITIGANT_MAPPING_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_EXP_MITIGANT_MAPPING(N_COUNTRY_SKEY,N_MIS_DATE_SKEY,N_ACCT_SKEY,N_MITIGANT_SKEY,N_REGION_SKEY,F_NETTABILITY_FLAG,N_RUN_SKEY,V_APPROACH_TYPE,N_LOAD_RUN_ID,N_CAP_APPROACH_TYPE_SKEY,N_RUN_PARAMETER_SETUP_SKEY,F_BORWR_RSK_DPND_MITIGANT_IND,F_DOUBLE_DEFAULT_IND,F_ELIGIBILITY_FLAG,F_EXP_MIT_POSITIVE_CORR_FLAG,F_MITIGANT_AMT_DPND_OBLGR_IND,N_MITIGANT_POOL_ID,N_MITIGANT_WEIGHT,V_MITIGANT_SENIORITY_LEVEL)SELECT  /*+PARALLEL (4)*/ to_char(DIM_COUNTRY.N_COUNTRY_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_EXPOSURE.N_ACCT_SKEY),to_char(DIM_MITIGANT.N_MITIGANT_SKEY),to_char(DIM_REGION.N_REGION_SKEY),CASE WHEN COALESCE(DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY,0) > 0 THEN 'Y' ELSE 'N' END,'870',FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE,to_char(FSI_CAP_ACCOUNT_LOAD_RUN_MAP.N_LOAD_RUN_ID),to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),to_char(FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY),STG_ACCOUNT_MITIGANT_MAP.F_BORWR_RSK_DPND_MITIGANT_IND,STG_ACCOUNT_MITIGANT_MAP.F_DOUBLE_DEFAULT_FLAG,STG_ACCOUNT_MITIGANT_MAP.F_ELIGIBILITY_FLAG,STG_ACCOUNT_MITIGANT_MAP.F_EXP_MIT_POSITIVE_CORR_FLAG,STG_ACCOUNT_MITIGANT_MAP.F_MITIGANT_AMT_DPND_OBLGR_IND,to_char(STG_ACCOUNT_MITIGANT_MAP.N_MITIGANT_POOL_ID),to_char(STG_ACCOUNT_MITIGANT_MAP.N_MITIGANT_WEIGHT),STG_MITIGANTS.V_MITIGANT_SENIORITY_LEVEL FROM STG_ACCOUNT_MITIGANT_MAP INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = STG_ACCOUNT_MITIGANT_MAP.FIC_MIS_DATE AND STG_ACCOUNT_MITIGANT_MAP.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_EXPOSURE ON STG_ACCOUNT_MITIGANT_MAP.V_ACCOUNT_NUMBER = DIM_EXPOSURE.V_EXPOSURE_ID AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_EXPOSURE.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_EXPOSURE.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) INNER JOIN DIM_MITIGANT ON STG_ACCOUNT_MITIGANT_MAP.V_MITIGANT_CODE = DIM_MITIGANT.V_MITIGANT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_MITIGANT.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_MITIGANT.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) INNER JOIN STG_MITIGANTS ON STG_MITIGANTS.V_MITIGANT_CODE = STG_ACCOUNT_MITIGANT_MAP.V_MITIGANT_CODE AND STG_MITIGANTS.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_NETTING_AGREEMENT ON DIM_NETTING_AGREEMENT.V_NETTING_AGREEMENT_CODE = STG_MITIGANTS.V_NETTING_AGREEMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_NETTING_AGREEMENT.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_NETTING_AGREEMENT.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN DIM_REGION ON DIM_REGION.V_D_REGION_CODE = DIM_EXPOSURE.V_ACCT_REGION_CODE AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_REGION.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_REGION.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN DIM_COUNTRY ON DIM_COUNTRY.V_COUNTRY_ID = COALESCE(DIM_EXPOSURE.V_COUNTRY_CODE, 'MSG') AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_COUNTRY.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_COUNTRY.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'NONSEC' INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE INNER JOIN FSI_CAP_ACCOUNT_LOAD_RUN_MAP ON DIM_EXPOSURE.V_EXPOSURE_ID = FSI_CAP_ACCOUNT_LOAD_RUN_MAP.V_ACCOUNT_NUMBER AND FSI_CAP_ACCOUNT_LOAD_RUN_MAP.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND FSI_CAP_ACCOUNT_LOAD_RUN_MAP.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = FSI_RUN_PARAMETER.N_RUN_PARAMETER_SKEY WHERE 1=1 LOG ERRORS INTO FSI_CAP_EXP_MITIGANT_MAPPING$ ('1776768236968_80863692_20260331_1_Job_72841aa0ac69403d96d067e8661733f1') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
