-- =====================================================================
-- Task: Allocation_Rank_Assignment
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Allocation_Rank_Assignment(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_OPTIMIZER_PROCESSING TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_OPTIMIZER_PROCESSING.N_ACCT_SKEY,FSI_OPTIMIZER_PROCESSING.N_DM_MITIGANT_SKEY,FSI_OPTIMIZER_PROCESSING.N_GAAP_SKEY,FSI_OPTIMIZER_PROCESSING.N_MIS_DATE_SKEY,FSI_OPTIMIZER_PROCESSING.N_MITIGANT_SKEY,FSI_OPTIMIZER_PROCESSING.N_RUN_SKEY,FSI_OPTIMIZER_PROCESSING.F_DRAWN_EXP_FLAG,FSI_OPTIMIZER_PROCESSING.N_MTG_TREATMENT_TYPE_SKEY,(FSI_OPTIMIZER_PROCESSING.N_ALLOCATION_RANK) AS  T_1537178524916_0,   (CASE  WHEN  ( (((FSI_OPTIMIZER_PROCESSING.V_EXP_MIT_POOL_CARDINALITY = '1-1'))) ) THEN 10 WHEN  ( (((FSI_OPTIMIZER_PROCESSING.V_EXP_MIT_POOL_CARDINALITY = '1-N'))) ) THEN 11 ELSE 12 END)  AS COND_1537178524916_10 ,  (DENSE_RANK() OVER (PARTITION BY CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.n_pool_id ELSE NULL END  ORDER BY CASE WHEN CASE WHEN 1 = 1 THEN DIM_STD_MITIGANT_TYPE.v_std_mitigant_type_code ELSE NULL END  = 'UNCOV' THEN 9999 ELSE CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.N_STD_MITIGANT_TYPE_SKEY ELSE NULL END  END,CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.F_DRAWN_UNDRAWN_IND ELSE NULL END )) AS EXP_1537178524916_10,(DENSE_RANK() OVER (PARTITION BY CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.n_pool_id ELSE NULL END  ORDER BY CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.F_DRAWN_UNDRAWN_IND ELSE NULL END , COALESCE(CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.n_risk_weight ELSE NULL END , CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.N_CAPITAL_UL ELSE NULL END ), CASE upper(CASE WHEN 1 = 1 THEN DIM_STD_MITIGANT_TYPE.V_FUND_CLASS ELSE NULL END ) WHEN upper('FUND BASED') THEN CASE upper(CASE WHEN 1 = 1 THEN DIM_STD_MITIGANT_TYPE.V_FINANCIAL_CLASS ELSE NULL END ) WHEN upper('FINANCIAL COLLATERAL') THEN 1 WHEN upper('NON FINANCIAL COLLATERAL') THEN 2 END WHEN upper('NON-FUND BASED') THEN CASE WHEN upper(CASE WHEN 1 = 1 THEN DIM_STD_MITIGANT_TYPE.V_FINANCIAL_CLASS ELSE NULL END ) = upper('FINANCIAL COLLATERAL') THEN 3 ELSE CASE WHEN coalesce(upper(CASE WHEN 1 = 1 THEN DIM_STD_MITIGANT_TYPE.V_FINANCIAL_CLASS ELSE NULL END ), upper('NON FINANCIAL COLLATERAL')) = upper('NON FINANCIAL COLLATERAL') 	THEN 4 END END WHEN upper('UNCOVERED') THEN 9999 ELSE 10 END, CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.n_net_mitigant_value ELSE NULL END  *((1- coalesce(CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.n_volatility_haircut ELSE NULL END ,0) - coalesce(CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.N_FOREX_HAIRCUT ELSE NULL END ,0)) * coalesce(CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.N_MATURITY_MISMATCH_HAIRCUT ELSE NULL END ,1)) DESC, CASE WHEN 1 = 1 THEN FSI_OPTIMIZER_PROCESSING.N_MITIGANT_SKEY ELSE NULL END )) AS EXP_1537178524916_11,(FSI_OPTIMIZER_PROCESSING.N_ALLOCATION_RANK) AS EXP_1537178524916_12  FROM  fsi_optimizer_processing INNER JOIN dim_dates ON fsi_optimizer_processing.n_mis_date_skey = dim_dates.n_date_skey  AND dim_dates.d_calendar_date = TO_DATE('20260331','yyyymmdd') INNER JOIN dim_run ON fsi_optimizer_processing.n_run_skey = dim_run.n_run_skey   AND dim_run.n_run_skey = '870' LEFT OUTER JOIN dim_std_mitigant_type ON fsi_optimizer_processing.n_std_mitigant_type_skey = dim_std_mitigant_type.n_std_mitigant_type_skey INNER JOIN dim_basel_product_type ON fsi_optimizer_processing.n_basel_prod_type_skey = dim_basel_product_type.n_basel_prod_type_skey INNER JOIN dim_basel_asset_class ON fsi_optimizer_processing.n_basel_asset_class_skey = dim_basel_asset_class.n_basel_asset_class_skey LEFT OUTER JOIN run_parameters ON fsi_optimizer_processing.n_run_parameter_setup_skey = run_parameters.n_run_parameter_setup_skey   AND run_parameters.n_run_skey = fsi_optimizer_processing.n_run_skey   AND run_parameters.n_date_skey = fsi_optimizer_processing.n_mis_date_skey LEFT OUTER JOIN dim_run_identifier ON dim_run_identifier.n_run_identifier_skey = fsi_optimizer_processing.n_run_identifier_skey   WHERE (1=1)  AND ((((FSI_OPTIMIZER_PROCESSING.V_EXPOSURE_TYPE = 'NON-SEC')) ) AND (((((1 - COALESCE(fsi_optimizer_processing.n_volatility_haircut, 0) - COALESCE(fsi_optimizer_processing.n_forex_haircut, 0)) * COALESCE(fsi_optimizer_processing.n_maturity_mismatch_haircut, 1)) > 0)) ))  ) WHERE (   (COND_1537178524916_10 <> 12)  ) ) SS ON ( TT.N_ACCT_SKEY= SS.N_ACCT_SKEY AND TT.N_DM_MITIGANT_SKEY= SS.N_DM_MITIGANT_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_MITIGANT_SKEY= SS.N_MITIGANT_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.F_DRAWN_EXP_FLAG= SS.F_DRAWN_EXP_FLAG AND TT.N_MTG_TREATMENT_TYPE_SKEY= SS.N_MTG_TREATMENT_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_ALLOCATION_RANK=  CASE  WHEN  COND_1537178524916_10=10 THEN EXP_1537178524916_10 WHEN  COND_1537178524916_10=11 THEN EXP_1537178524916_11 ELSE EXP_1537178524916_12 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
