-- =====================================================================
-- Task: AMORTIZATION_SCHEDULE_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.AMORTIZATION_SCHEDULE_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_SCHEDULE(N_ACCT_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_SCHEDULE_SKEY,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,D_SCHEDULE_DATE)SELECT  /*+PARALLEL (4)*/ (SELECT n_acct_skey FROM DIM_EXPOSURE WHERE v_exposure_id = STG_INSTRUMENT_SCHEDULE.V_INSTRUMENT_CODE AND STG_INSTRUMENT_SCHEDULE.FIC_MIS_DATE BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE),DIM_DATES.N_DATE_SKEY,'870',ROWNUM,to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_IDENTIFIER_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY),STG_INSTRUMENT_SCHEDULE.D_SCHEDULE_DATE FROM STG_INSTRUMENT_SCHEDULE INNER JOIN DIM_DATES ON STG_INSTRUMENT_SCHEDULE.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE INNER JOIN DIM_INSTRUMENT_CONTRACT ON DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE = STG_INSTRUMENT_SCHEDULE.V_INSTRUMENT_CODE AND STG_INSTRUMENT_SCHEDULE.FIC_MIS_DATE BETWEEN DIM_INSTRUMENT_CONTRACT.d_record_start_date and DIM_INSTRUMENT_CONTRACT.d_record_end_date INNER JOIN FCT_MARKET_RISK_EXPOSURES ON /*FCT_MARKET_RISK_EXPOSURES.FIC_MIS_DATE = STG_INSTRUMENT_SCHEDULE.FIC_MIS_DATE AND*/ FCT_MARKET_RISK_EXPOSURES.N_ACCT_SKEY = DIM_INSTRUMENT_CONTRACT.N_INSTRUMENT_SKEY AND FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey = DIM_DATES.N_DATE_SKEY WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND STG_INSTRUMENT_SCHEDULE.V_SCHEDULE_TYPE = 'A' LOG ERRORS INTO FCT_SCHEDULE$ ('1776768905109_82614187_20260331_1_Job_c6f15dff89ef44a1979799c9c285cc0d') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
