-- =====================================================================
-- Task: Basel_III_Intra_Group_Party_based_on_Regulatory_Relationship_Type
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Basel_III_Intra_Group_Party_based_on_Regulatory_Relationship_Type(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_PARTY_PARTY_RELATIONSHIP TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_PARTY_PARTY_RELATIONSHIP.N_RUN_SKEY,FSI_PARTY_PARTY_RELATIONSHIP.N_MIS_DATE_SKEY,FSI_PARTY_PARTY_RELATIONSHIP.N_PARTY_SKEY,FSI_PARTY_PARTY_RELATIONSHIP.N_RELATED_PARTY_SKEY,(FSI_PARTY_PARTY_RELATIONSHIP.F_INTRA_GROUP_FLAG) AS  T_1471441594650_0,   (CASE  WHEN  ( ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'SOLPRP')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'SPPURVEH')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'SBSDRY')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'AFFILIATE')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'COMBRNDNM')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'JNTVENT')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'PRMTER')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'PRNTHSHLD')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'SIBLING')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'SPOUSE')) OR ((DIM_REG_PARTY_RELATIONSHP_TYPE.V_REG_RELATIONSHIP_TYPE_CODE  = 'PRNTBIZ')) ) THEN 10 ELSE 11 END)  AS COND_1471441594650_10 ,  ('Y') AS EXP_1471441594650_10,(FSI_PARTY_PARTY_RELATIONSHIP.F_INTRA_GROUP_FLAG) AS EXP_1471441594650_11  FROM  FSI_PARTY_PARTY_RELATIONSHIP LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_PARTY_PARTY_RELATIONSHIP.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_PARTY_PARTY_RELATIONSHIP.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_PARTY_RELATIONSHIP_TYPE ON DIM_PARTY_RELATIONSHIP_TYPE.N_RELATIONSHIP_TYPE_SKEY = FSI_PARTY_PARTY_RELATIONSHIP.N_RELATIONSHIP_TYPE_SKEY LEFT OUTER JOIN DIM_REG_PARTY_RELATIONSHP_TYPE ON DIM_REG_PARTY_RELATIONSHP_TYPE.N_REG_RELATIONSHIP_TYPE_SKEY = FSI_PARTY_PARTY_RELATIONSHIP.N_REG_RELATIONSHIP_TYPE_SKEY /*Related Party and Type*/ LEFT OUTER JOIN DIM_PARTY ON DIM_PARTY.N_PARTY_SKEY = FSI_PARTY_PARTY_RELATIONSHIP.N_RELATED_PARTY_SKEY LEFT OUTER JOIN DIM_PARTY_TYPE ON DIM_PARTY_TYPE.V_PARTY_TYPE_CODE = DIM_PARTY.V_PARTY_TYPE AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_PARTY_TYPE.D_RECORD_START_DATE AND DIM_PARTY_TYPE.D_RECORD_END_DATE LEFT OUTER JOIN FSI_PARTY_TYPE_CLASSIFICATION ON FSI_PARTY_TYPE_CLASSIFICATION.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_PARTY_TYPE_CLASSIFICATION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_PARTY_TYPE_CLASSIFICATION.N_PARTY_TYPE_SKEY = DIM_PARTY_TYPE.N_PARTY_TYPE_SKEY LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE ON DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY = FSI_PARTY_TYPE_CLASSIFICATION.N_STANDARD_PARTY_TYPE_SKEY /*Parent of Related Party and its Type*/ LEFT OUTER JOIN DIM_PARTY PARENT_PARTY ON PARENT_PARTY.N_PARTY_SKEY = FSI_PARTY_PARTY_RELATIONSHIP.N_PARENT_RELATED_PARTY_SKEY LEFT OUTER JOIN DIM_COUNTRY ON DIM_COUNTRY.V_COUNTRY_ID = PARENT_PARTY.V_COUNTRY_ID AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_COUNTRY.D_RECORD_START_DATE AND DIM_COUNTRY.D_RECORD_END_DATE LEFT OUTER JOIN DIM_PARTY_TYPE PARENT_PARTY_TYPE ON PARENT_PARTY_TYPE.V_PARTY_TYPE_CODE = PARENT_PARTY.V_PARTY_TYPE AND DIM_DATES.D_CALENDAR_DATE BETWEEN PARENT_PARTY_TYPE.D_RECORD_START_DATE AND PARENT_PARTY_TYPE.D_RECORD_END_DATE LEFT OUTER JOIN FSI_PARTY_TYPE_CLASSIFICATION PARENT_PARTY_TYPE_RECLASS ON PARENT_PARTY_TYPE_RECLASS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND PARENT_PARTY_TYPE_RECLASS.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND PARENT_PARTY_TYPE_RECLASS.N_PARTY_TYPE_SKEY = PARENT_PARTY_TYPE.N_PARTY_TYPE_SKEY LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE PARENT_STANDARD_PARTY_TYPE ON PARENT_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY = PARENT_PARTY_TYPE_RECLASS.N_STANDARD_PARTY_TYPE_SKEY   WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = TO_DATE('20260331','yyyymmdd'))  ) WHERE (   (COND_1471441594650_10 <> 11)  ) ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_PARTY_SKEY= SS.N_PARTY_SKEY AND TT.N_RELATED_PARTY_SKEY= SS.N_RELATED_PARTY_SKEY) WHEN MATCHED THEN UPDATE SET  TT.F_INTRA_GROUP_FLAG=  CASE  WHEN  COND_1471441594650_10=10 THEN EXP_1471441594650_10 ELSE EXP_1471441594650_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
