-- =====================================================================
-- Task: CALC_ACCT_HEAD_PHASE_IN_TREATMENT_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CALC_ACCT_HEAD_PHASE_IN_TREATMENT_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_PHASE_IN_TREATMENT(N_REG_ADJUSTMENT_PHASE_IN_AMT,N_ENTITY_SKEY,N_FORECAST_DATE_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY,V_STRESS_SCENARIO_CODE)SELECT  /*+PARALLEL (4)*/ SUM(COALESCE(FCT_CALC_ACCT_HEAD.N_CALC_ACCT_HEAD_AMT,0)),FCT_ENTITY_INFO.N_ENTITY_SKEY,to_char(FCT_CALC_ACCT_HEAD.N_FORECAST_DATE_SKEY),to_char(FCT_CALC_ACCT_HEAD.N_GAAP_SKEY),to_char(FCT_CALC_ACCT_HEAD.N_MIS_DATE_SKEY),to_char(FCT_CALC_ACCT_HEAD.N_RUN_SKEY),to_char(FCT_CALC_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),FCT_CALC_ACCT_HEAD.V_STRESS_SCENARIO_CODE FROM FCT_CALC_ACCT_HEAD LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_CALC_ACCT_HEAD.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_CALC_ACCT_HEAD.n_mis_date_skey LEFT OUTER JOIN  FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = FCT_CALC_ACCT_HEAD.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = FCT_CALC_ACCT_HEAD.N_MIS_DATE_SKEY AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = FCT_CALC_ACCT_HEAD.N_FORECAST_DATE_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND COALESCE(FCT_CALC_ACCT_HEAD.F_CAP_DED_IND,'N') = 'Y' GROUP BY FCT_CALC_ACCT_HEAD.N_RUN_SKEY, FCT_CALC_ACCT_HEAD.n_mis_date_skey, DIM_DATES.N_DATE_SKEY, FCT_CALC_ACCT_HEAD.N_GAAP_SKEY, FCT_CALC_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY, FCT_CALC_ACCT_HEAD.N_FORECAST_DATE_SKEY, FCT_CALC_ACCT_HEAD.V_STRESS_SCENARIO_CODE,fct_entity_info.n_entity_skey LOG ERRORS INTO FSI_PHASE_IN_TREATMENT$ ('1776771193062_11424880_20260331_1_Job_1587398336754') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
