-- =====================================================================
-- Task: Cap_Consl_Effective_Shareholding_Percent_for_an_Entity_Based_on_Consolidation_Approach
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Cap_Consl_Effective_Shareholding_Percent_for_an_Entity_Based_on_Consolidation_Approach(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_ENTITY_INFO TT USING (   SELECT  /*+ PARALLEL(4) */ FCT_ENTITY_INFO.N_RUN_SKEY,FCT_ENTITY_INFO.N_ENTITY_SKEY,FCT_ENTITY_INFO.N_MIS_DATE_SKEY,FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY, MIN(FCT_ENTITY_INFO.N_SHAREHOLDING_PERCENT) AS  T_1349907885504_0,   MIN(CASE  WHEN  ( ((DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE  = 'FAGR') AND ((COALESCE(FCT_ENTITY_INFO.f_regulatory_entity_ind, 'Y') = 'Y'))) OR ((DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE  = 'FLCS') AND ((COALESCE(FCT_ENTITY_INFO.f_regulatory_entity_ind, 'Y') = 'Y'))) OR ((1=1) AND ((COALESCE(FCT_ENTITY_INFO.f_regulatory_entity_ind, 'Y') = 'N'))) ) THEN 10 ELSE 11 END)  AS COND_1349907885504_10 ,  (1) AS EXP_1349907885504_10,MIN(FCT_ENTITY_INFO.N_SHAREHOLDING_PERCENT) AS EXP_1349907885504_11  FROM   FCT_ENTITY_INFO LEFT OUTER JOIN DIM_DATES ON FCT_ENTITY_INFO.n_mis_date_skey = DIM_DATES.n_date_skey LEFT OUTER JOIN DIM_RUN ON FCT_ENTITY_INFO.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_ORG_STRUCTURE ON DIM_ORG_STRUCTURE.n_entity_skey = FCT_ENTITY_INFO.n_entity_skey LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.n_gaap_skey = FCT_ENTITY_INFO.n_gaap_skey LEFT OUTER JOIN DIM_COUNTRY ON DIM_COUNTRY.n_country_skey = FCT_ENTITY_INFO.n_country_skey LEFT OUTER JOIN DIM_BANK_CAP_CONSL_APPR ON DIM_BANK_CAP_CONSL_APPR.n_bank_cap_consl_appr_skey = FCT_ENTITY_INFO.n_bank_cap_consl_appr_skey LEFT OUTER JOIN DIM_BASEL_CAP_CONSL_APPR ON DIM_BASEL_CAP_CONSL_APPR.n_basel_cap_consl_appr_skey = FCT_ENTITY_INFO.n_basel_cap_consl_appr_skey LEFT OUTER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON DIM_BASEL_CONSL_OPTION_TYPE.n_basel_consl_optn_type_skey = FCT_ENTITY_INFO.n_basel_consl_optn_type_skey LEFT OUTER JOIN DIM_PARTY_TYPE ON DIM_PARTY_TYPE.n_party_type_skey = FCT_ENTITY_INFO.n_entity_type_skey LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE ON DIM_STANDARD_PARTY_TYPE.n_STANDARD_PARTY_Type_Skey = FCT_ENTITY_INFO.n_basel_entity_type_skey  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  AND ( (((DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE  = 'FAGR') AND ((COALESCE(FCT_ENTITY_INFO.f_regulatory_entity_ind, 'Y') = 'Y'))) OR ((DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE  = 'FLCS') AND ((COALESCE(FCT_ENTITY_INFO.f_regulatory_entity_ind, 'Y') = 'Y'))) OR ((1=1) AND ((COALESCE(FCT_ENTITY_INFO.f_regulatory_entity_ind, 'Y') = 'N'))))  )  GROUP BY FCT_ENTITY_INFO.N_RUN_SKEY,FCT_ENTITY_INFO.N_ENTITY_SKEY,FCT_ENTITY_INFO.N_MIS_DATE_SKEY,FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_SHAREHOLDING_PERCENT=  CASE  WHEN  COND_1349907885504_10=10 THEN EXP_1349907885504_10 ELSE EXP_1349907885504_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
