-- =====================================================================
-- Task: CAP_CVA_RWA_STD_ACCT_HEAD_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CAP_CVA_RWA_STD_ACCT_HEAD_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_STD_ACCT_HEAD_SKEY,N_GAAP_SKEY,N_ORIG_STD_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_AMT,N_UPD_CAP_COMP_GROUP_SKEY,N_ENTITY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),FCT_ENTITY_INFO.N_GAAP_SKEY,COALESCE(FSI_CAP_CVA_SUMMARY.N_CVA_RWA,0),COALESCE(FSI_CAP_CVA_SUMMARY.N_CVA_RWA,0),DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,to_char(FSI_CAP_CVA_SUMMARY.N_ENTITY_SKEY),to_char(FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY),to_char(FSI_CAP_CVA_SUMMARY.N_RUN_SKEY) FROM FSI_CAP_CVA_SUMMARY INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_CVA_SUMMARY.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = FSI_CAP_CVA_SUMMARY.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' LEFT JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP954' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE LEFT JOIN FSI_SETUP_CAPITAL_SOURCE ON FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID AND FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE = DIM_RUN.V_JURISDICTION_CODE LEFT JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = FSI_SETUP_CAPITAL_SOURCE.V_INITIAL_CAP_COMP_GROUP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY = '870' LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776771935304_75143051_20260331_1_JOB_6644791923780437') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
