-- =====================================================================
-- Task: CAP_ACCOUNT_LOAD_RUN_MAP_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CAP_ACCOUNT_LOAD_RUN_MAP_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_ACCOUNT_LOAD_RUN_MAP(N_MIS_DATE_SKEY,N_ACCT_SKEY,N_GAAP_SKEY,N_RUN_SKEY,FIC_MIS_DATE,N_LOAD_RUN_ID,V_ACCOUNT_NUMBER,V_GAAP_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_EXPOSURE.N_ACCT_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),'870',FSI_ACCOUNT_LOAD_RUN_MAP.FIC_MIS_DATE,to_char(FSI_ACCOUNT_LOAD_RUN_MAP.N_LOAD_RUN_ID),FSI_ACCOUNT_LOAD_RUN_MAP.V_ACCOUNT_NUMBER,FSI_ACCOUNT_LOAD_RUN_MAP.V_GAAP_CODE FROM FSI_ACCOUNT_LOAD_RUN_MAP INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = FSI_ACCOUNT_LOAD_RUN_MAP.FIC_MIS_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_EXPOSURE ON DIM_EXPOSURE.V_EXPOSURE_ID = FSI_ACCOUNT_LOAD_RUN_MAP.V_ACCOUNT_NUMBER  AND to_date('20260331','YYYYMMDD') BETWEEN DIM_EXPOSURE.D_RECORD_START_DATE AND DIM_EXPOSURE.D_RECORD_END_DATE INNER JOIN DIM_GAAP ON DIM_GAAP.V_GAAP_CODE = FSI_ACCOUNT_LOAD_RUN_MAP.V_GAAP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE INNER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' WHERE 1=1 AND FSI_ACCOUNT_LOAD_RUN_MAP.F_LATEST_LOAD_RUN_FLAG = 'Y' AND ( (COALESCE(FSI_CAP_RUN_EXE_PARAMETERS.F_INCREMENTAL_RUN_FLAG, 'N') = 'N') OR ( COALESCE(FSI_CAP_RUN_EXE_PARAMETERS.F_INCREMENTAL_RUN_FLAG, 'N') = 'Y' AND EXISTS ( SELECT 1 FROM FSI_CAP_INCR_ACCOUNT_MAP WHERE FSI_CAP_INCR_ACCOUNT_MAP.N_RUN_SKEY = '870' AND FSI_CAP_INCR_ACCOUNT_MAP.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_INCR_ACCOUNT_MAP.V_ACCOUNT_NUMBER = FSI_ACCOUNT_LOAD_RUN_MAP.V_ACCOUNT_NUMBER ) ) ) LOG ERRORS INTO FSI_CAP_ACCOUNT_LOAD_RUN_MAP$ ('1776768014660_92709371_20260331_1_JOB_16373091174755') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
