-- =====================================================================
-- Task: CAP_DEF_INCR_ACCOUNT_MAP_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CAP_DEF_INCR_ACCOUNT_MAP_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_INCR_ACCOUNT_MAP(N_MIS_DATE_SKEY,N_RUN_SKEY,F_REC_TYPE_IND,V_ACCOUNT_NUMBER)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),FSI_INCR_ACCOUNT_MAP.F_REC_TYPE_IND,FSI_INCR_ACCOUNT_MAP.V_ACCOUNT_NUMBER FROM FSI_INCR_ACCOUNT_MAP INNER JOIN DIM_RUN ON FSI_INCR_ACCOUNT_MAP.V_APP_ID = COALESCE(DIM_RUN.V_PRODUCT,'BASEL') AND FSI_INCR_ACCOUNT_MAP.V_RUN_ID = '-1' INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = FSI_INCR_ACCOUNT_MAP.FIC_MIS_DATE WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND FSI_INCR_ACCOUNT_MAP.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND FSI_INCR_ACCOUNT_MAP.F_REC_TYPE_IND <> 'C'  AND NOT EXISTS (SELECT 1 FROM FSI_CAP_INCR_ACCOUNT_MAP WHERE FSI_CAP_INCR_ACCOUNT_MAP.N_RUN_SKEY = '870') LOG ERRORS INTO FSI_CAP_INCR_ACCOUNT_MAP$ ('1776768004712_20654705_20260331_1_JOB_1641152480644') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
