-- =====================================================================
-- Task: CAPITAL_SETUP_STANDARD_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CAPITAL_SETUP_STANDARD_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_UPD_CAP_COMP_GROUP_SKEY,N_STD_ACCT_HEAD_SKEY,N_ORIG_STD_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_AMT,N_ENTITY,N_FORECAST_DATE_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,V_CCY_CODE,V_STRESS_SCENARIO_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),COALESCE(FSI_SETUP_CAPITAL_HEAD.N_CAPITAL_COMPONENT_VALUE,0),COALESCE(FSI_SETUP_CAPITAL_HEAD.N_CAPITAL_COMPONENT_VALUE,0),to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),to_char(FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY),to_char(FCT_ENTITY_INFO.N_GAAP_SKEY),to_char(FCT_ENTITY_INFO.N_MIS_DATE_SKEY),to_char(FCT_ENTITY_INFO.N_RUN_SKEY),FCT_ENTITY_INFO.V_CCY_CODE,FCT_ENTITY_INFO.V_STRESS_SCENARIO_CODE FROM FSI_SETUP_CAPITAL_SOURCE INNER JOIN DIM_RUN ON DIM_RUN.V_JURISDICTION_CODE = FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE AND FSI_SETUP_CAPITAL_SOURCE.V_SOURCE_CD = 'SD' AND DIM_RUN.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE INNER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' AND FCT_ENTITY_INFO.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY INNER JOIN DIM_DATES ON FCT_ENTITY_INFO.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = FSI_SETUP_CAPITAL_SOURCE.V_INITIAL_CAP_COMP_GROUP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE INNER JOIN FSI_SETUP_CAPITAL_HEAD ON FSI_SETUP_CAPITAL_HEAD.V_STD_ACCT_HEAD_ID = FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID AND FSI_SETUP_CAPITAL_HEAD.V_CAPITAL_ADEQUACY_REGULATOR = FCT_ENTITY_INFO.V_CAPITAL_ADEQUACY_REGULATOR AND to_date('20260331','YYYYMMDD') BETWEEN FSI_SETUP_CAPITAL_HEAD.D_START_DATE AND FSI_SETUP_CAPITAL_HEAD.D_END_DATE WHERE 1=1 LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776771007747_47518481_20260331_1_JOB_6997886344753209') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
