-- =====================================================================
-- Task: CAPITAL_ACCT_HEAD_PHASE_IN_TREATMENT_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CAPITAL_ACCT_HEAD_PHASE_IN_TREATMENT_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_PHASE_IN_TREATMENT(N_REG_ADJUSTMENT_PHASE_IN_AMT,N_ENTITY_SKEY,N_FORECAST_DATE_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY,V_STRESS_SCENARIO_CODE)SELECT  /*+PARALLEL (4)*/ SUM(COALESCE(fct_capital_acct_head.n_capital_acct_head_amt,0)),FCT_ENTITY_INFO.N_ENTITY_SKEY,to_char(FCT_CAPITAL_ACCT_HEAD.N_FORECAST_DATE_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_GAAP_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_MIS_DATE_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),FCT_CAPITAL_ACCT_HEAD.V_STRESS_SCENARIO_CODE FROM FCT_CAPITAL_ACCT_HEAD LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_CAPITAL_ACCT_HEAD.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FCT_CAPITAL_ACCT_HEAD.N_GAAP_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FCT_CAPITAL_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY = FCT_CAPITAL_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = FCT_CAPITAL_ACCT_HEAD.N_FORECAST_DATE_SKEY LEFT OUTER JOIN FSI_SETUP_CAPITAL_HEAD ON FSI_SETUP_CAPITAL_HEAD.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID AND FSI_SETUP_CAPITAL_HEAD.V_CAPITAL_ADEQUACY_REGULATOR = FCT_ENTITY_INFO.V_CAPITAL_ADEQUACY_REGULATOR AND DIM_DATES.D_CALENDAR_DATE BETWEEN FSI_SETUP_CAPITAL_HEAD.D_START_DATE AND FSI_SETUP_CAPITAL_HEAD.D_END_DATE LEFT OUTER JOIN DIM_ORG_STRUCTURE ON DIM_ORG_STRUCTURE.V_ENTITY_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_ORG_STRUCTURE.D_RECORD_START_DATE AND DIM_ORG_STRUCTURE.D_RECORD_END_DATE LEFT OUTER JOIN FSI_STD_ACCT_HEAD_COMP_GRP_MAP ON FSI_STD_ACCT_HEAD_COMP_GRP_MAP.N_STD_ACCT_HEAD_SKEY = FCT_CAPITAL_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY AND FSI_STD_ACCT_HEAD_COMP_GRP_MAP.N_RUN_SKEY = FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY AND FSI_STD_ACCT_HEAD_COMP_GRP_MAP.N_MIS_DATE_SKEY = FCT_CAPITAL_ACCT_HEAD.N_MIS_DATE_SKEY AND FSI_STD_ACCT_HEAD_COMP_GRP_MAP.V_CAP_COMP_GRP_PURPOSE_CD = 'BALAMTPHASEIN' LEFT OUTER JOIN FSI_CAP_PARTY_FINANCIALS ON FSI_CAP_PARTY_FINANCIALS.N_PARTY_SKEY = FCT_ENTITY_INFO.N_PARTY_SKEY AND FSI_CAP_PARTY_FINANCIALS.N_MIS_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY AND FSI_CAP_PARTY_FINANCIALS.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = FCT_CAPITAL_ACCT_HEAD.N_FORECAST_DATE_SKEY WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE IN ('DEDCET1', 'DEDAT1', 'DEDT2') AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID <> 'CAP872' GROUP BY FCT_CAPITAL_ACCT_HEAD.N_MIS_DATE_SKEY, DIM_DATES.N_DATE_SKEY, FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY, FCT_CAPITAL_ACCT_HEAD.N_GAAP_SKEY, FCT_CAPITAL_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY, FCT_CAPITAL_ACCT_HEAD.N_FORECAST_DATE_SKEY, FCT_CAPITAL_ACCT_HEAD.V_STRESS_SCENARIO_CODE, FCT_ENTITY_INFO.F_ULTIMATE_PARENT_ENTITY_FLAG,fct_entity_info.n_entity_skey LOG ERRORS INTO FSI_PHASE_IN_TREATMENT$ ('1776771202066_26526028_20260331_1_Job_1587398338931') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
