-- =====================================================================
-- Task: CAPITAL_STD_ACCT_HEAD_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CAPITAL_STD_ACCT_HEAD_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_ENTITY,N_ORIG_STD_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_AMT,N_UPD_CAP_COMP_GROUP_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ MAX(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),FCT_ENTITY_INFO.N_ENTITY_SKEY,SUM(COALESCE(FCT_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_AMT, 0)),SUM(COALESCE(FCT_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_AMT, 0)),MAX(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_GAAP_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_MIS_DATE_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY),to_char(FCT_CAPITAL_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY) FROM FCT_CAPITAL_ACCT_HEAD LEFT OUTER JOIN DIM_CAPITAL_ACCT_HEAD ON DIM_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_SKEY = FCT_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FCT_CAPITAL_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY = FCT_CAPITAL_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_CAPITAL_ACCT_HEAD.n_mis_date_skey LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND FCT_ENTITY_INFO.n_mis_date_skey = DIM_DATES.N_DATE_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND ((DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE NOT IN ('DEDCET1', 'DEDAT1', 'DEDT2') AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID NOT IN ('CAP139', 'CAP360', 'CAP133', 'CAP322', 'CAP867', 'CAP861', 'CAP844', 'CAP845')) OR (DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID IN ('CAP872'))) AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID NOT IN ('CAP841','CAP908','CAP067') GROUP BY FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY, FCT_CAPITAL_ACCT_HEAD.n_mis_date_skey, FCT_CAPITAL_ACCT_HEAD.N_GAAP_SKEY, FCT_CAPITAL_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,DIM_DATES.N_DATE_SKEY, FCT_ENTITY_INFO.N_ENTITY_SKEY LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776770998755_40160263_20260331_1_JOB_6997886344745528') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
