-- =====================================================================
-- Task: Capital_Head_Attribute_Shareholding_Percent_Multiplication
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Capital_Head_Attribute_Shareholding_Percent_Multiplication(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_CAPITAL_ACCT_HEAD TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_CAPITAL_ACCT_HEAD.N_RUN_SKEY,FCT_CAPITAL_ACCT_HEAD.N_ENTITY_SKEY,FCT_CAPITAL_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_CAPITAL_ACCT_HEAD.N_GAAP_SKEY,FCT_CAPITAL_ACCT_HEAD.N_FORECAST_DATE_SKEY,FCT_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_SKEY,(FCT_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_AMT) AS  T_1354311971526_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1354311971526_10 ,  (CASE WHEN 1 = 1 THEN FCT_CAPITAL_ACCT_HEAD.n_shareholding_percent ELSE NULL END  * CASE WHEN 1 = 1 THEN FCT_CAPITAL_ACCT_HEAD.n_capital_acct_head_amt ELSE NULL END ) AS EXP_1354311971526_10,(FCT_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_AMT) AS EXP_1354311971526_11  FROM  FCT_CAPITAL_ACCT_HEAD LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON FCT_CAPITAL_ACCT_HEAD.n_cap_comp_group_skey = DIM_CAPITAL_COMP_GROUP.n_cap_comp_group_skey LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON FCT_CAPITAL_ACCT_HEAD.n_std_acct_head_skey = DIM_STANDARD_ACCT_HEAD.n_std_acct_head_skey LEFT OUTER JOIN DIM_DATES ON FCT_CAPITAL_ACCT_HEAD.n_mis_date_skey = DIM_DATES.n_date_skey LEFT OUTER JOIN DIM_RUN ON FCT_CAPITAL_ACCT_HEAD.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_GAAP ON FCT_CAPITAL_ACCT_HEAD.n_gaap_skey = DIM_GAAP.n_gaap_skey  LEFT OUTER JOIN ( SELECT n_run_skey , MAX ( v_aoci_opt_out_election_option) v_aoci_opt_out_election_option  FROM RUN_PARAMETERS  GROUP BY  n_run_skey )  RUN_PARAMETERS ON RUN_PARAMETERS.n_run_skey = FCT_CAPITAL_ACCT_HEAD.n_run_skey   WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  ) WHERE (   (COND_1354311971526_10 <> 11)  ) ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY AND TT.N_CAPITAL_ACCT_HEAD_SKEY= SS.N_CAPITAL_ACCT_HEAD_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_CAPITAL_ACCT_HEAD_AMT=  CASE  WHEN  COND_1354311971526_10=10 THEN EXP_1354311971526_10 ELSE EXP_1354311971526_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
