-- =====================================================================
-- Task: CCP_CAPITAL_CALCULATION_DATA_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CCP_CAPITAL_CALCULATION_DATA_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CCP_CAPITAL_CALCULATION(F_QUALIFIED_CCP_FLAG,F_FLOOR_TO_NON_QCCP_CHARGE_IND,N_COUNTERPARTY_SKEY,N_MIS_DATE_SKEY,N_PRE_CRM_RW_UL_NON_QCCP,N_RUN_SKEY,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE)SELECT  /*+PARALLEL (4)*/ DIM_PARTY.F_QUALIFIED_CCP_FLAG,'N',CCP_CAPITAL_CALCULATION.N_CENTRAL_COUNTERPARTY_SKEY,CCP_CAPITAL_CALCULATION.N_MIS_DATE_SKEY,CCP_CAPITAL_CALCULATION.N_PRE_MITIGATION_RW_UL,CCP_CAPITAL_CALCULATION.N_RUN_SKEY,to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE FROM (SELECT CCP_CAPITAL_CALC.N_RUN_SKEY ,CCP_CAPITAL_CALC.N_MIS_DATE_SKEY ,CCP_CAPITAL_CALC.N_CENTRAL_COUNTERPARTY_SKEY ,MAX(CCP_CAPITAL_CALC.N_PRE_MITIGATION_RW_UL) N_PRE_MITIGATION_RW_UL,CCP_CAPITAL_CALC.V_APPROACH_TYPE,CCP_CAPITAL_CALC.N_CAP_APPROACH_TYPE_SKEY FROM (SELECT FSI_CAP_DERIVATIVES.N_RUN_SKEY ,FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY,FSI_CAP_DERIVATIVES.N_CENTRAL_COUNTERPARTY_SKEY ,FSI_CAP_DERIVATIVES.N_PRE_MITIGATION_RW_UL,FSI_CAP_DERIVATIVES.V_APPROACH_TYPE,FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY FROM FSI_CAP_DERIVATIVES INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_DERIVATIVES.N_RUN_SKEY = '870' UNION ALL SELECT FSI_CAP_SFT_EXPOSURES.N_RUN_SKEY ,FSI_CAP_SFT_EXPOSURES.N_MIS_DATE_SKEY,FSI_CAP_SFT_EXPOSURES.N_CENTRAL_COUNTERPARTY_SKEY ,FSI_CAP_SFT_EXPOSURES.N_PRE_MITIGATION_RW_UL,FSI_CAP_SFT_EXPOSURES.V_APPROACH_TYPE,FSI_CAP_SFT_EXPOSURES.N_CAP_APPROACH_TYPE_SKEY FROM FSI_CAP_SFT_EXPOSURES INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_CAP_SFT_EXPOSURES.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_SFT_EXPOSURES.N_RUN_SKEY = '870')CCP_CAPITAL_CALC GROUP BY CCP_CAPITAL_CALC.N_RUN_SKEY ,CCP_CAPITAL_CALC.N_MIS_DATE_SKEY,CCP_CAPITAL_CALC.N_CENTRAL_COUNTERPARTY_SKEY,CCP_CAPITAL_CALC.V_APPROACH_TYPE,CCP_CAPITAL_CALC.N_CAP_APPROACH_TYPE_SKEY)CCP_CAPITAL_CALCULATION INNER JOIN DIM_PARTY ON CCP_CAPITAL_CALCULATION.N_CENTRAL_COUNTERPARTY_SKEY = DIM_PARTY.N_PARTY_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = CCP_CAPITAL_CALCULATION.N_CAP_APPROACH_TYPE_SKEY WHERE 1=1 AND 1=1 AND DIM_PARTY.F_QUALIFIED_CCP_FLAG = 'Y' LOG ERRORS INTO FSI_CCP_CAPITAL_CALCULATION$ ('1776769995231_48841997_20260331_1_Job_67033088dcd946cb9a09d377e5bb2776') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
