-- =====================================================================
-- Task: CDS_Index_Reference_Entity_Basel_Rating_Assignment_STD
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CDS_Index_Reference_Entity_Basel_Rating_Assignment_STD(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CDS_REF_ENTITY_RISK_PARAM TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_CDS_REF_ENTITY_RISK_PARAM.N_RUN_SKEY,FSI_CDS_REF_ENTITY_RISK_PARAM.N_MIS_DATE_SKEY,FSI_CDS_REF_ENTITY_RISK_PARAM.N_PARTY_SKEY, MIN(FSI_CDS_REF_ENTITY_RISK_PARAM.N_BASEL_RATING_SKEY) AS  T_1366965873611_0,   MIN(CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1366965873611_10 ,  (COALESCE(MAX(PARTY_RATING.N_BASEL_RATING_SKEY), 22)) AS EXP_1366965873611_10,MIN(FSI_CDS_REF_ENTITY_RISK_PARAM.N_BASEL_RATING_SKEY) AS EXP_1366965873611_11  FROM  FSI_CDS_REF_ENTITY_RISK_PARAM LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CDS_REF_ENTITY_RISK_PARAM.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CDS_REF_ENTITY_RISK_PARAM.N_MIS_DATE_SKEY LEFT OUTER JOIN (SELECT FSI_PARTY_RATING_DETAILS.N_RUN_SKEY N_RUN_SKEY, FSI_PARTY_RATING_DETAILS.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, FSI_PARTY_RATING_DETAILS.N_PARTY_SKEY N_PARTY_SKEY, CASE WHEN COUNT(FSI_PARTY_RATING_DETAILS.N_BASEL_RATING_SKEY) OVER(PARTITION BY FSI_PARTY_RATING_DETAILS.N_PARTY_SKEY) <= 1 THEN COALESCE(FSI_PARTY_RATING_DETAILS.N_BASEL_RATING_SKEY, 22) WHEN COUNT(FSI_PARTY_RATING_DETAILS.N_BASEL_RATING_SKEY) OVER(PARTITION BY FSI_PARTY_RATING_DETAILS.N_PARTY_SKEY) > 1 THEN COALESCE(CASE WHEN DENSE_RANK() OVER(PARTITION BY FSI_PARTY_RATING_DETAILS.N_PARTY_SKEY ORDER BY FSI_PARTY_RATING_DETAILS.N_BASEL_RATING_SKEY DESC) = 2 THEN FSI_PARTY_RATING_DETAILS.N_BASEL_RATING_SKEY END, 0) END N_BASEL_RATING_SKEY FROM FSI_PARTY_RATING_DETAILS LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_PARTY_RATING_DETAILS.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_PARTY_RATING_DETAILS.N_MIS_DATE_SKEY WHERE DIM_RUN.N_RUN_SKEY = '870' AND UPPER(FSI_PARTY_RATING_DETAILS.V_PURPOSE) = 'DOMESTIC' AND FSI_PARTY_RATING_DETAILS.F_ORIGINAL_CREDIT_RATING_IND = 'N') PARTY_RATING ON PARTY_RATING.N_RUN_SKEY = FSI_CDS_REF_ENTITY_RISK_PARAM.N_RUN_SKEY AND PARTY_RATING.N_MIS_DATE_SKEY = FSI_CDS_REF_ENTITY_RISK_PARAM.N_MIS_DATE_SKEY AND PARTY_RATING.N_PARTY_SKEY = FSI_CDS_REF_ENTITY_RISK_PARAM.N_PARTY_SKEY  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  AND ( (((1=1)))  )  GROUP BY FSI_CDS_REF_ENTITY_RISK_PARAM.N_RUN_SKEY,FSI_CDS_REF_ENTITY_RISK_PARAM.N_MIS_DATE_SKEY,FSI_CDS_REF_ENTITY_RISK_PARAM.N_PARTY_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_PARTY_SKEY= SS.N_PARTY_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_BASEL_RATING_SKEY=  CASE  WHEN  COND_1366965873611_10=10 THEN EXP_1366965873611_10 ELSE EXP_1366965873611_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
