-- =====================================================================
-- Task: Country_wise_Total_EAD_for_Non_Securitized_Exposures
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Country_wise_Total_EAD_for_Non_Securitized_Exposures(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_COUNTRYWISE_RISK_SUMMARY TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_COUNTRYWISE_RISK_SUMMARY.N_ENTITY_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_MIS_DATE_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_RUN_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_COUNTRY_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_BASEL_CONSL_OPTN_TYPE_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_RISK_TYPE_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.V_APPROACH_CODE, MIN(FSI_COUNTRYWISE_RISK_SUMMARY.N_EAD_AMOUNT) AS  T_1582874884332_0,   MIN(CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1582874884332_10 ,  (max(CASE WHEN 1 = 1 THEN FSI_COUNTRYWISE_RISK_SUMMARY.n_ead_amount ELSE NULL END ) + SUM(CASE WHEN 1=1 THEN FSI_CAP_SUB_EXPOSURES.n_ead_post_mitigation ELSE NULL END )) AS EXP_1582874884332_10,MIN(FSI_COUNTRYWISE_RISK_SUMMARY.N_EAD_AMOUNT) AS EXP_1582874884332_11  FROM  FSI_COUNTRYWISE_RISK_SUMMARY LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_COUNTRYWISE_RISK_SUMMARY.N_RUN_SKEY LEFT OUTER JOIN DIM_COUNTRY ON DIM_COUNTRY.N_COUNTRY_SKEY = FSI_COUNTRYWISE_RISK_SUMMARY.N_COUNTRY_SKEY LEFT OUTER JOIN FSI_CAP_SUB_EXPOSURES ON DIM_COUNTRY.N_COUNTRY_SKEY = FSI_CAP_SUB_EXPOSURES.N_EFFECTIVE_COUNTRY_SKEY AND DIM_RUN.N_RUN_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY AND FSI_COUNTRYWISE_RISK_SUMMARY.N_MIS_DATE_SKEY = FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y'   WHERE (1 = 1)  AND (FSI_COUNTRYWISE_RISK_SUMMARY.N_RUN_SKEY = '870' AND TO_DATE(FSI_COUNTRYWISE_RISK_SUMMARY.N_MIS_DATE_SKEY, 'YYYYMMDD') = TO_DATE('20260331','yyyymmdd') AND FSI_CAP_SUB_EXPOSURES.N_EFFECTIVE_COUNTRY_SKEY IS NOT NULL AND COALESCE(FSI_CAP_SUB_EXPOSURES.F_SECURITIZED_FLAG, 'N') <> 'Y' AND FSI_CAP_SUB_EXPOSURES.V_EXPOSURE_TYPE = 'NON-SEC' )  AND ( (((1=1)))  )  GROUP BY FSI_COUNTRYWISE_RISK_SUMMARY.N_ENTITY_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_MIS_DATE_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_RUN_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_COUNTRY_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_BASEL_CONSL_OPTN_TYPE_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.N_RISK_TYPE_SKEY,FSI_COUNTRYWISE_RISK_SUMMARY.V_APPROACH_CODE ) SS ON ( TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_COUNTRY_SKEY= SS.N_COUNTRY_SKEY AND TT.N_BASEL_CONSL_OPTN_TYPE_SKEY= SS.N_BASEL_CONSL_OPTN_TYPE_SKEY AND TT.N_RISK_TYPE_SKEY= SS.N_RISK_TYPE_SKEY AND TT.V_APPROACH_CODE= SS.V_APPROACH_CODE) WHEN MATCHED THEN UPDATE SET  TT.N_EAD_AMOUNT=  CASE  WHEN  COND_1582874884332_10=10 THEN EXP_1582874884332_10 ELSE EXP_1582874884332_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
