-- =====================================================================
-- Task: COUNTRYWISE_RISK_SUMMARY_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.COUNTRYWISE_RISK_SUMMARY_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_COUNTRYWISE_RISK_SUMMARY(N_BASEL_CONSL_OPTN_TYPE_SKEY,N_COUNTRY_SKEY,N_MIS_DATE_SKEY,N_RISK_TYPE_SKEY,N_RUN_SKEY,N_ENTITY_SKEY,N_EAD_AMOUNT,V_APPROACH_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY),to_char(DIM_COUNTRY.N_COUNTRY_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RISK_TYPE.N_RISK_TYPE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),to_char(STG_COUNTRYWISE_RISK_SUMMARY.N_EAD_AMOUNT),STG_COUNTRYWISE_RISK_SUMMARY.V_APPROACH_CODE FROM STG_COUNTRYWISE_RISK_SUMMARY INNER JOIN DIM_DATES ON STG_COUNTRYWISE_RISK_SUMMARY.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN FCT_ENTITY_INFO ON STG_COUNTRYWISE_RISK_SUMMARY.V_LV_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_COUNTRY ON DIM_COUNTRY.V_COUNTRY_ID = COALESCE(STG_COUNTRYWISE_RISK_SUMMARY.V_COUNTRY_ID, 'MSG') AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_COUNTRY.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_COUNTRY.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) INNER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY = FCT_ENTITY_INFO.N_BASEL_CONSL_OPTN_TYPE_SKEY AND DIM_BASEL_CONSL_OPTION_TYPE.V_BASEL_CONSL_OPTN_TYPE_CODE = STG_COUNTRYWISE_RISK_SUMMARY.V_BASEL_CONSL_OPTN_TYPE_CODE INNER JOIN DIM_RISK_TYPE ON DIM_RISK_TYPE.V_RISK_TYPE_ID = STG_COUNTRYWISE_RISK_SUMMARY.V_RISK_TYPE_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_RISK_TYPE.D_RECORD_START_DATE AND DIM_RISK_TYPE.D_RECORD_END_DATE WHERE 1=1 AND DIM_RISK_TYPE.N_RISK_TYPE_SKEY NOT IN ( SELECT DISTINCT N_RISK_TYPE_SKEY FROM FSI_COUNTRYWISE_RISK_SUMMARY WHERE N_RUN_SKEY = '870' ) LOG ERRORS INTO FSI_COUNTRYWISE_RISK_SUMMARY$ ('1776772030511_33277607_20260331_1_Job_8848a61496494754a37fa5baaeca0b99') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
