-- =====================================================================
-- Task: COUNTERPARTY_CVA_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.COUNTERPARTY_CVA_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_COUNTERPARTY_CVA(N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_ASSET_CLASS_SKEY,N_BASEL_METHOD_SKEY,N_BASEL_PARTY_RATING,N_BASEL_SECTOR_SKEY,N_CVA_CHARGE_AT_COUNTERPARTY,N_CVA_RWA_AT_COUNTERPARTY,N_EAD_POST_MITIGATION,N_ENTITY_SKEY,N_MATURITY_ADJ_EAD,N_PD_PERCENT,N_REG_CAP_INDUSTRY_SKEY,N_REG_INDUSTRY_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_STANDARD_PARTY_TYPE_SKEY,N_CAP_APPROACH_TYPE_SKEY,N_COUNTERPARTY_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(FSI_CAP_NETTABLE_POOL.N_BASEL_ASSET_CLASS_SKEY),MAX(FSI_CAP_NETTABLE_POOL.N_CVA_METHOD_SKEY),MAX(FSI_CAP_NETTABLE_POOL.N_BASEL_PARTY_RATING),MAX(COALESCE(FSI_PARTY_TYPE_SECTOR_RECLASS.N_BASEL_SECTOR_SKEY, FSI_CAP_INDUS_SECTOR_RECLASS.N_BASEL_SECTOR_SKEY)),SUM(CASE WHEN COALESCE(DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE,'MSG') IN ('CVACCR') THEN COALESCE(FSI_CAP_NETTABLE_POOL.N_POOL_POST_CRM_RWA_UL,0) ELSE 0 END)/12.5,SUM(CASE WHEN COALESCE(DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE,'MSG') IN ('CVACCR') THEN COALESCE(FSI_CAP_NETTABLE_POOL.N_POOL_POST_CRM_RWA_UL,0) ELSE 0 END),SUM(COALESCE(FSI_CAP_NETTABLE_POOL.N_EAD_POST_MITIGATION, FSI_CAP_NETTABLE_POOL.N_EXP_AMT, 0)),(SELECT FCT_ENTITY_INFO.N_ENTITY_SKEY FROM FCT_ENTITY_INFO LEFT OUTER JOIN DIM_DATES ON FCT_ENTITY_INFO.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY WHERE FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD')),SUM(FSI_CAP_NETTABLE_POOL.N_MATURITY_ADJ_EAD),MAX(FSI_CAP_NETTABLE_POOL.N_NETTABLE_POOL_PD),MAX(FSI_CAP_NETTABLE_POOL.N_REG_CAP_INDUSTRY_SKEY),MAX(FSI_CAP_NETTABLE_POOL.N_REG_INDUSTRY_SKEY),MAX(FSI_CAP_NETTABLE_POOL.N_RUN_PARAMETER_SETUP_SKEY),MAX(FSI_CAP_NETTABLE_POOL.N_STANDARD_PARTY_TYPE_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_CUST_SKEY) FROM FSI_CAP_NETTABLE_POOL INNER JOIN DIM_DATES ON FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY INNER JOIN DIM_RUN ON FSI_CAP_NETTABLE_POOL.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY INNER JOIN DIM_STANDARD_PARTY_TYPE ON DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_STANDARD_PARTY_TYPE_SKEY LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_PARAMETER_SETUP_SKEY AND FSI_RUN_PARAMETER.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_RUN_PARAMETER.N_DATE_SKEY = FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY INNER JOIN DIM_BASEL_METHODOLOGY ON FSI_CAP_NETTABLE_POOL.N_CVA_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT JOIN DIM_REG_CAP_INDUSTRY ON DIM_REG_CAP_INDUSTRY.N_REG_CAP_INDUSTRY_SKEY = FSI_CAP_NETTABLE_POOL.N_REG_CAP_INDUSTRY_SKEY LEFT JOIN FSI_CAP_INDUS_SECTOR_RECLASS ON FSI_CAP_INDUS_SECTOR_RECLASS.N_RUN_SKEY = '870' AND FSI_CAP_INDUS_SECTOR_RECLASS.V_GICS_INDUSTRY_CODE = DIM_REG_CAP_INDUSTRY.V_GICS_INDUSTRY_CODE LEFT JOIN FSI_PARTY_TYPE_SECTOR_RECLASS ON FSI_PARTY_TYPE_SECTOR_RECLASS.N_RUN_SKEY = '870' AND FSI_PARTY_TYPE_SECTOR_RECLASS.N_STD_PARTY_TYPE_SKEY = DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY = '870' AND COALESCE(DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE,'MSG') IN ('CVABHM', 'CVABWH', 'CVACCR', 'CVAIMM', 'CVASTD') GROUP BY DIM_DATES.N_DATE_SKEY, DIM_RUN.N_RUN_SKEY, FSI_CAP_NETTABLE_POOL.N_CUST_SKEY, FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY LOG ERRORS INTO FSI_CAP_COUNTERPARTY_CVA$ ('1776770640293_42997311_20260331_1_JOB_16281530263745') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
