-- =====================================================================
-- Task: COUNTRYWISE_MARKET_RISK_SUMMARY
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.COUNTRYWISE_MARKET_RISK_SUMMARY(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_COUNTRYWISE_RISK_SUMMARY(N_RUN_SKEY,N_BASEL_CONSL_OPTN_TYPE_SKEY,N_COUNTRY_SKEY,N_ENTITY_SKEY,N_EAD_AMOUNT,N_MIS_DATE_SKEY,N_RISK_TYPE_SKEY,V_APPROACH_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_RUN.N_RUN_SKEY),MKT_RISK_EXP.n_basel_consl_optn_type_skey,MKT_RISK_EXP.n_effective_country_skey,MKT_RISK_EXP.n_entity_skey,sum(MKT_RISK_EXP.exp),MKT_RISK_EXP.n_mis_date_skey,MKT_RISK_EXP.n_risk_type_skey,'STD' FROM ( SELECT MAX(FCT_ENTITY_INFO.N_ENTITY_SKEY) N_ENTITY_SKEY ,FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY N_EFFECTIVE_COUNTRY_SKEY ,SUM(COALESCE(FCT_MARKET_RISK_EXPOSURES.N_POST_OFFSET_EXP_AMT, 0)) EXP ,FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY N_MIS_DATE_SKEY ,FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY N_RUN_SKEY ,MAX(DIM_RISK_TYPE.N_RISK_TYPE_SKEY) N_RISK_TYPE_SKEY ,MAX(DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY) N_BASEL_CONSL_OPTN_TYPE_SKEY FROM FCT_MARKET_RISK_EXPOSURES LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' LEFT OUTER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY = FCT_ENTITY_INFO.N_BASEL_CONSL_OPTN_TYPE_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_RISK_TYPE ON UPPER(DIM_RISK_TYPE.V_RISK_TYPE_ID) = 'MR' AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_RISK_TYPE.D_RECORD_START_DATE AND DIM_RISK_TYPE.D_RECORD_END_DATE WHERE FCT_MARKET_RISK_EXPOSURES.N_CONTRACT_ACCT_SKEY IS NULL AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' AND FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY IS NOT NULL GROUP BY FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY ,FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY ,FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY  UNION ALL  SELECT MAX(FCT_ENTITY_INFO.N_ENTITY_SKEY) N_ENTITY_SKEY ,FCT_MARKET_RISK_FOREX.N_COUNTRY_SKEY N_EFFECTIVE_COUNTRY_SKEY ,SUM(ABS(COALESCE(FCT_MARKET_RISK_FOREX.N_EXPOSURE_AMT, 0))) EXP ,FCT_MARKET_RISK_FOREX.N_MIS_DATE_SKEY N_MIS_DATE_SKEY ,FCT_MARKET_RISK_FOREX.N_RUN_SKEY N_RUN_SKEY ,MAX(DIM_RISK_TYPE.N_RISK_TYPE_SKEY) N_RISK_TYPE_SKEY ,MAX(DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY) N_BASEL_CONSL_OPTN_TYPE_SKEY FROM FCT_MARKET_RISK_FOREX LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = FCT_MARKET_RISK_FOREX.N_RUN_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' LEFT OUTER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY = FCT_ENTITY_INFO.N_BASEL_CONSL_OPTN_TYPE_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_MARKET_RISK_FOREX.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_RISK_TYPE ON UPPER(DIM_RISK_TYPE.V_RISK_TYPE_ID) = 'MR' AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_RISK_TYPE.D_RECORD_START_DATE AND DIM_RISK_TYPE.D_RECORD_END_DATE WHERE DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_FOREX.N_RUN_SKEY = '870' AND FCT_MARKET_RISK_FOREX.N_COUNTRY_SKEY IS NOT NULL GROUP BY FCT_MARKET_RISK_FOREX.N_COUNTRY_SKEY ,FCT_MARKET_RISK_FOREX.N_MIS_DATE_SKEY ,FCT_MARKET_RISK_FOREX.N_RUN_SKEY ) MKT_RISK_EXP LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = MKT_RISK_EXP.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = MKT_RISK_EXP.N_MIS_DATE_SKEY WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY = '870' GROUP BY MKT_RISK_EXP.N_ENTITY_SKEY, MKT_RISK_EXP.N_EFFECTIVE_COUNTRY_SKEY, MKT_RISK_EXP.N_MIS_DATE_SKEY, DIM_RUN.N_RUN_SKEY, MKT_RISK_EXP.N_RISK_TYPE_SKEY,MKT_RISK_EXP.N_BASEL_CONSL_OPTN_TYPE_SKEY LOG ERRORS INTO FSI_COUNTRYWISE_RISK_SUMMARY$ ('1776772021497_91605733_20260331_1_Job_92f45b82bd3d4fd898a507c67328e756') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
