-- =====================================================================
-- Task: Counterparty_Default_Risk_Capital
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Counterparty_Default_Risk_Capital(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_COUNTERPARTY_CVA TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY, MIN(FSI_CAP_COUNTERPARTY_CVA.N_DEFAULT_RISK_CAPITAL) AS  T_1628066802815_0,   MIN(CASE  WHEN  ( (((1=1))) ) THEN 10 ELSE 11 END)  AS COND_1628066802815_10 ,  (SUM(CASE WHEN 1=1 THEN FSI_CAP_SUB_EXPOSURES.n_rwa_ul_amt ELSE NULL END * 0.08)) AS EXP_1628066802815_10,MIN(FSI_CAP_COUNTERPARTY_CVA.N_DEFAULT_RISK_CAPITAL) AS EXP_1628066802815_11  FROM  FSI_CAP_COUNTERPARTY_CVA INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY INNER JOIN DIM_BASEL_CREDIT_RATING ON DIM_BASEL_CREDIT_RATING.N_BASEL_RATING = FSI_CAP_COUNTERPARTY_CVA.N_BASEL_PARTY_RATING INNER JOIN FSI_CAP_SUB_EXPOSURES ON FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY = FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY = FSI_CAP_SUB_EXPOSURES.N_EXPOSURE_PARTY_SKEY INNER JOIN DIM_STD_MITIGANT_TYPE ON FSI_CAP_SUB_EXPOSURES.N_STD_MITIGANT_TYPE_SKEY = DIM_STD_MITIGANT_TYPE.N_STD_MITIGANT_TYPE_SKEY  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870')  AND ( ((((1=1))))  )  GROUP BY FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY ) SS ON ( TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_COUNTERPARTY_SKEY= SS.N_COUNTERPARTY_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_DEFAULT_RISK_CAPITAL=  CASE  WHEN  COND_1628066802815_10=10 THEN EXP_1628066802815_10 ELSE EXP_1628066802815_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
