-- =====================================================================
-- Task: CP_NETTING_AGREEMENT_DETAILS_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CP_NETTING_AGREEMENT_DETAILS_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CP_NETTING_AGREEMENT_DTLS(N_MIS_DATE_SKEY,N_NETTING_AGREEMENT_SKEY,N_COUNTERPARTY_SKEY,N_ADDON_AMOUNT,N_GROSS_CURRENT_EXP_AMT,N_GROSS_POTENTIAL_EXP_AMT,N_NET_CURRENT_EXP_AMT,N_NET_POTENTIAL_EXP_AMT,N_POTENTIAL_FUTURE_EXP_AMT,N_REPLACEMENT_COST,N_RUN_SKEY,N_TOTAL_EXPOSURE_AMOUNT,N_EXCHANGE_RATE,N_ADDON_AMOUNT_NCY,N_GROSS_CURRENT_EXP_AMT_NCY,N_GROSS_POTENTIAL_EXP_AMT_NCY,N_NET_CURRENT_EXP_AMT_NCY,N_NET_POTENTIAL_EXP_AMT_NCY,N_POTENTIAL_FUTURE_EXP_AMT_NCY,N_REPLACEMENT_COST_NCY,N_TOTAL_EXPOSURE_AMOUNT_NCY,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),FSI_INPUT_CP_NETTING_AGREEMENT.N_ADDON_AMOUNT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_INPUT_CP_NETTING_AGREEMENT.N_GROSS_CURRENT_EXP_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_INPUT_CP_NETTING_AGREEMENT.N_GROSS_POTENTIAL_EXP_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_INPUT_CP_NETTING_AGREEMENT.N_NET_CURRENT_EXP_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_INPUT_CP_NETTING_AGREEMENT.N_NET_POTENTIAL_EXP_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_INPUT_CP_NETTING_AGREEMENT.N_POTENTIAL_FUTURE_EXP_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_INPUT_CP_NETTING_AGREEMENT.N_REPLACEMENT_COST * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,'870',FSI_INPUT_CP_NETTING_AGREEMENT.N_TOTAL_EXPOSURE_AMOUNT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,to_char(FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_ADDON_AMOUNT),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_GROSS_CURRENT_EXP_AMT),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_GROSS_POTENTIAL_EXP_AMT),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_NET_CURRENT_EXP_AMT),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_NET_POTENTIAL_EXP_AMT),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_POTENTIAL_FUTURE_EXP_AMT),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_REPLACEMENT_COST),to_char(FSI_INPUT_CP_NETTING_AGREEMENT.N_TOTAL_EXPOSURE_AMOUNT),FSI_INPUT_CP_NETTING_AGREEMENT.V_CCY_CODE FROM FSI_INPUT_CP_NETTING_AGREEMENT INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_INPUT_CP_NETTING_AGREEMENT.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_PARTY ON DIM_PARTY.V_PARTY_ID = FSI_INPUT_CP_NETTING_AGREEMENT.V_COUNTERPARTY_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE LEFT OUTER JOIN DIM_NETTING_AGREEMENT ON DIM_NETTING_AGREEMENT.V_NETTING_AGREEMENT_CODE = FSI_INPUT_CP_NETTING_AGREEMENT.V_NETTING_AGREEMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_NETTING_AGREEMENT.D_RECORD_START_DATE AND DIM_NETTING_AGREEMENT.D_RECORD_END_DATE LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = '870' AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = FSI_INPUT_CP_NETTING_AGREEMENT.V_CCY_CODE WHERE 1=1 LOG ERRORS INTO FSI_CP_NETTING_AGREEMENT_DTLS$ ('1776768175393_46555108_20260331_1_JOB_16623672473300') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
