-- =====================================================================
-- Task: CS_Minority_Interest_Capital_attributable_to_Third_Party_included_in_Tier_1_Capital
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Minority_Interest_Capital_attributable_to_Third_Party_included_in_Tier_1_Capital(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_STANDARD_ACCT_HEAD TT USING (   SELECT  /*+ PARALLEL(4) */ FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY, MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS  T_1383806928940_0,   MIN(CASE  WHEN  ( ((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP513')) ) THEN 10 ELSE 11 END)  AS COND_1383806928940_10 ,  (COALESCE(SUM(CASE WHEN CAPITAL_ACCOUNTING.N_STD_ACCT_HEAD_SKEY IN (SELECT DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY FROM DIM_STANDARD_ACCT_HEAD WHERE DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP511') THEN CAPITAL_ACCOUNTING.n_std_acct_head_amt ELSE NULL END ) -SUM( CASE WHEN CAPITAL_ACCOUNTING.N_STD_ACCT_HEAD_SKEY IN (SELECT DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY FROM DIM_STANDARD_ACCT_HEAD WHERE DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP512') THEN CAPITAL_ACCOUNTING.N_STD_ACCT_HEAD_AMT ELSE NULL END ),0)) AS EXP_1383806928940_10,MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS EXP_1383806928940_11  FROM  FCT_STANDARD_ACCT_HEAD LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON FCT_STANDARD_ACCT_HEAD.N_UPD_CAP_COMP_GROUP_SKEY = DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY AND FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_ENTITY = FCT_ENTITY_INFO.N_ENTITY_SKEY AND FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY = FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY LEFT OUTER JOIN FSI_SETUP_CAPITAL_HEAD ON FSI_SETUP_CAPITAL_HEAD.V_STD_ACCT_HEAD_ID = ('CAP936') AND FSI_SETUP_CAPITAL_HEAD.V_CAPITAL_ADEQUACY_REGULATOR = FCT_ENTITY_INFO.V_CAPITAL_ADEQUACY_REGULATOR AND DIM_DATES.D_CALENDAR_DATE BETWEEN FSI_SETUP_CAPITAL_HEAD.D_START_DATE AND FSI_SETUP_CAPITAL_HEAD.D_END_DATE LEFT OUTER JOIN FCT_STANDARD_ACCT_HEAD CAPITAL_ACCOUNTING ON FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY = CAPITAL_ACCOUNTING.N_RUN_SKEY AND FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY = CAPITAL_ACCOUNTING.N_MIS_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY = CAPITAL_ACCOUNTING.N_GAAP_SKEY AND FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY = CAPITAL_ACCOUNTING.N_FORECAST_DATE_SKEY   WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  AND ( (((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP513')))  )  GROUP BY FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_STD_ACCT_HEAD_SKEY= SS.N_STD_ACCT_HEAD_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_ENTITY= SS.N_ENTITY AND TT.N_CAP_COMP_GROUP_SKEY= SS.N_CAP_COMP_GROUP_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_STD_ACCT_HEAD_AMT=  CASE  WHEN  COND_1383806928940_10=10 THEN EXP_1383806928940_10 ELSE EXP_1383806928940_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
