-- =====================================================================
-- Task: CS_Minority_Interest_Third_party_contribution_in_Surplus_Capital
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Minority_Interest_Third_party_contribution_in_Surplus_Capital(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_MINORITY_INTEREST TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_MINORITY_INTEREST.N_ENTITY_SKEY,FSI_MINORITY_INTEREST.N_GAAP_SKEY,FSI_MINORITY_INTEREST.N_RUN_SKEY,FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY,FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY,(FSI_MINORITY_INTEREST.N_MINORITY_INT_DED_AMT_AT1) AS  T_1529408723025_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1529408723025_10 ,  (CASE WHEN 1 = 1 THEN FSI_MINORITY_INTEREST.n_mi_deduction_from_tier1_amt ELSE NULL END  - CASE WHEN 1 = 1 THEN FSI_MINORITY_INTEREST.n_minority_int_ded_amt_cet1 ELSE NULL END ) AS EXP_1529408723025_10,(FSI_MINORITY_INTEREST.N_MINORITY_INT_DED_AMT_AT1) AS EXP_1529408723025_11 ,(FSI_MINORITY_INTEREST.N_MINORITY_INT_DED_AMT_T2) AS  T_1529408723025_1,   (CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1529408723025_20 ,  (CASE WHEN 1 = 1 THEN FSI_MINORITY_INTEREST.n_mi_ded_from_total_capital ELSE NULL END  - CASE WHEN 1 = 1 THEN FSI_MINORITY_INTEREST.n_mi_deduction_from_tier1_amt ELSE NULL END ) AS EXP_1529408723025_20,(FSI_MINORITY_INTEREST.N_MINORITY_INT_DED_AMT_T2) AS EXP_1529408723025_21  FROM  FSI_MINORITY_INTEREST LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_MINORITY_INTEREST.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_MINORITY_INTEREST.N_GAAP_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_ENTITY_SKEY = FSI_MINORITY_INTEREST.N_ENTITY_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY AND FCT_ENTITY_INFO.N_RUN_SKEY = FSI_MINORITY_INTEREST.N_RUN_SKEY AND FCT_ENTITY_INFO.N_GAAP_SKEY = FSI_MINORITY_INTEREST.N_GAAP_SKEY AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY   WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = TO_DATE('20260331','yyyymmdd'))  ) WHERE (   (COND_1529408723025_10 <> 11)   OR  (COND_1529408723025_20 <> 21) ) ) SS ON ( TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_MINORITY_INT_DED_AMT_AT1=  CASE  WHEN  COND_1529408723025_10=10 THEN EXP_1529408723025_10 ELSE EXP_1529408723025_11 END  , TT.N_MINORITY_INT_DED_AMT_T2=  CASE  WHEN  COND_1529408723025_20=20 THEN EXP_1529408723025_20 ELSE EXP_1529408723025_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
