-- =====================================================================
-- Task: CS_Phase_In_Treatment_Aggregate_Threshold_Deduction_Amount_Assignment
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Phase_In_Treatment_Aggregate_Threshold_Deduction_Amount_Assignment(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_PHASE_IN_TREATMENT TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY,FSI_PHASE_IN_TREATMENT.N_RUN_SKEY,FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY,FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY,FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY,FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY, MIN(FSI_PHASE_IN_TREATMENT.N_REG_ADJUSTMENT_PHASE_IN_AMT) AS  T_1351729439458_0,   MIN(CASE  WHEN  ( ((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP946')) ) THEN 10 ELSE 11 END)  AS COND_1351729439458_10 ,  (SUM(COALESCE(CASE WHEN 1 = 1 THEN FSI_THRESHOLD_TREATMENT.n_amt_above_agg_threshold ELSE NULL END ,0))) AS EXP_1351729439458_10,MIN(FSI_PHASE_IN_TREATMENT.N_REG_ADJUSTMENT_PHASE_IN_AMT) AS EXP_1351729439458_11  FROM  FSI_PHASE_IN_TREATMENT LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_PHASE_IN_TREATMENT.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN FSI_THRESHOLD_TREATMENT ON FSI_PHASE_IN_TREATMENT.N_RUN_SKEY = FSI_THRESHOLD_TREATMENT.N_RUN_SKEY AND FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY = FSI_THRESHOLD_TREATMENT.N_MIS_DATE_SKEY AND FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY = FSI_THRESHOLD_TREATMENT.N_GAAP_SKEY AND FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY = FSI_THRESHOLD_TREATMENT.N_FORECAST_DATE_SKEY   WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = TO_DATE('20260331','yyyymmdd'))  AND ( (((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP946')))  )  GROUP BY FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY,FSI_PHASE_IN_TREATMENT.N_RUN_SKEY,FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY,FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY,FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY,FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY ) SS ON ( TT.N_STD_ACCT_HEAD_SKEY= SS.N_STD_ACCT_HEAD_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY AND TT.N_BAL_CAP_COMP_GROUP_SKEY= SS.N_BAL_CAP_COMP_GROUP_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_REG_ADJUSTMENT_PHASE_IN_AMT=  CASE  WHEN  COND_1351729439458_10=10 THEN EXP_1351729439458_10 ELSE EXP_1351729439458_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
