-- =====================================================================
-- Task: CS_Phase_In_Deduction_Amount
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Phase_In_Deduction_Amount(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_PHASE_IN_TREATMENT TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY,FSI_PHASE_IN_TREATMENT.N_RUN_SKEY,FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY,FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY,FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY,FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY,(FSI_PHASE_IN_TREATMENT.N_PHASE_IN_AMT) AS  T_1533124278300_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1533124278300_10 ,  (COALESCE(CASE WHEN 1 = 1 THEN FSI_PHASE_IN_TREATMENT.n_reg_adjustment_phase_in_amt ELSE NULL END ,0)*COALESCE(CASE WHEN 1 = 1 THEN FSI_PHASE_IN_TREATMENT.n_phase_in_percent ELSE NULL END ,0)) AS EXP_1533124278300_10,(FSI_PHASE_IN_TREATMENT.N_PHASE_IN_AMT) AS EXP_1533124278300_11  FROM  FSI_PHASE_IN_TREATMENT LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_PHASE_IN_TREATMENT.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY = FSI_PHASE_IN_TREATMENT.N_CAP_COMP_GROUP_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP BAL_PHASE_IN_CAP_COMP_GROUP ON BAL_PHASE_IN_CAP_COMP_GROUP.N_CAP_COMP_GROUP_SKEY = FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_ENTITY_SKEY = FSI_PHASE_IN_TREATMENT.N_ENTITY_SKEY AND FCT_ENTITY_INFO.N_RUN_SKEY = FSI_PHASE_IN_TREATMENT.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY AND FCT_ENTITY_INFO.N_GAAP_SKEY = FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY LEFT OUTER JOIN FSI_SETUP_CAPITAL_HEAD ON FSI_SETUP_CAPITAL_HEAD.V_CAPITAL_ADEQUACY_REGULATOR = FCT_ENTITY_INFO.V_CAPITAL_ADEQUACY_REGULATOR AND FSI_SETUP_CAPITAL_HEAD.V_STD_ACCT_HEAD_ID = 'CAP936' AND DIM_DATES.D_CALENDAR_DATE BETWEEN FSI_SETUP_CAPITAL_HEAD.D_START_DATE AND FSI_SETUP_CAPITAL_HEAD.D_END_DATE LEFT OUTER JOIN FSI_SETUP_CAPITAL_SOURCE ON FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE = DIM_RUN.V_JURISDICTION_CODE AND FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = TO_DATE('20260331','yyyymmdd'))  ) WHERE (   (COND_1533124278300_10 <> 11)  ) ) SS ON ( TT.N_STD_ACCT_HEAD_SKEY= SS.N_STD_ACCT_HEAD_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY AND TT.N_BAL_CAP_COMP_GROUP_SKEY= SS.N_BAL_CAP_COMP_GROUP_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_PHASE_IN_AMT=  CASE  WHEN  COND_1533124278300_10=10 THEN EXP_1533124278300_10 ELSE EXP_1533124278300_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
