-- =====================================================================
-- Task: CS_Phase_In_and_Balance_Capital_Component_Group_Assignment
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Phase_In_and_Balance_Capital_Component_Group_Assignment(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_PHASE_IN_TREATMENT TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_PHASE_IN_TREATMENT.ROWID source_rowid, (FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY) AS  T_1533194325149_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1533194325149_10 ,  (COALESCE(CASE WHEN 1 = 1 THEN BAL_PHASE_IN_CAP_COMP_GROUP.N_CAP_COMP_GROUP_SKEY ELSE NULL END ,-9999)) AS EXP_1533194325149_10,(FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY) AS EXP_1533194325149_11 ,(FSI_PHASE_IN_TREATMENT.N_CAP_COMP_GROUP_SKEY) AS  T_1533194325149_1,   (CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1533194325149_20 ,  (CASE WHEN 1 = 1 THEN DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY ELSE NULL END ) AS EXP_1533194325149_20,(FSI_PHASE_IN_TREATMENT.N_CAP_COMP_GROUP_SKEY) AS EXP_1533194325149_21  FROM  FSI_PHASE_IN_TREATMENT INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_PHASE_IN_TREATMENT.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY INNER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY INNER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY INNER JOIN FSI_SETUP_CAPITAL_SOURCE ON FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE = DIM_RUN.V_JURISDICTION_CODE AND FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = FSI_SETUP_CAPITAL_SOURCE.V_INITIAL_CAP_COMP_GROUP_CODE AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP BAL_PHASE_IN_CAP_COMP_GROUP ON BAL_PHASE_IN_CAP_COMP_GROUP.V_CAP_COMP_GROUP_CODE = FSI_SETUP_CAPITAL_SOURCE.V_BAL_CAP_COMP_GROUP_CODE AND DIM_DATES.D_CALENDAR_DATE BETWEEN BAL_PHASE_IN_CAP_COMP_GROUP.D_RECORD_START_DATE AND BAL_PHASE_IN_CAP_COMP_GROUP.D_RECORD_END_DATE   WHERE (1 = 1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = TO_DATE('20260331','yyyymmdd'))  ) WHERE (   (COND_1533194325149_10 <> 11)   OR  (COND_1533194325149_20 <> 21) ) ) SS ON ( TT.ROWID = SS.source_rowid) WHEN MATCHED THEN UPDATE SET  TT.N_BAL_CAP_COMP_GROUP_SKEY=  CASE  WHEN  COND_1533194325149_10=10 THEN EXP_1533194325149_10 ELSE EXP_1533194325149_11 END  , TT.N_CAP_COMP_GROUP_SKEY=  CASE  WHEN  COND_1533194325149_20=20 THEN EXP_1533194325149_20 ELSE EXP_1533194325149_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
