-- =====================================================================
-- Task: CS_Required_Buffer_from_Tier1_Capital
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Required_Buffer_from_Tier1_Capital(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_STANDARD_ACCT_HEAD TT USING (   SELECT  /*+ PARALLEL(4) */ FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY, MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS  T_1346690877099_0,   MIN(CASE  WHEN  ( ((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP830')) ) THEN 10 ELSE 11 END)  AS COND_1346690877099_10 ,  (COALESCE(SUM(CASE WHEN CAPITAL_ACCOUNTING.n_upd_cap_comp_group_skey IN (SELECT N_CAP_COMP_GROUP_SKEY FROM DIM_CAPITAL_COMP_GROUP WHERE v_cap_comp_group_code = 'BFT1') THEN CAPITAL_ACCOUNTING.n_std_acct_head_amt ELSE NULL END ),0)) AS EXP_1346690877099_10,MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS EXP_1346690877099_11  FROM  FCT_STANDARD_ACCT_HEAD INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY INNER JOIN DIM_ORG_STRUCTURE ON DIM_ORG_STRUCTURE.N_ENTITY_SKEY = FCT_STANDARD_ACCT_HEAD.N_ENTITY INNER JOIN DIM_STANDARD_ACCT_HEAD ON FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY INNER JOIN FCT_ENTITY_INFO ON FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY AND FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY = FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_ENTITY = FCT_ENTITY_INFO.N_ENTITY_SKEY LEFT OUTER JOIN DIM_COUNTRY ON FCT_STANDARD_ACCT_HEAD.N_COUNTRY_SKEY = DIM_COUNTRY.N_COUNTRY_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN FSI_SETUP_BENCHMARK_LOSS_ABS ON FSI_SETUP_BENCHMARK_LOSS_ABS.N_LOSS_ABSORBENCY_BUCKET = FCT_ENTITY_INFO.N_LOSS_ABSORBENCY_BUCKET AND DIM_DATES.D_CALENDAR_DATE BETWEEN FSI_SETUP_BENCHMARK_LOSS_ABS.D_START_DATE AND FSI_SETUP_BENCHMARK_LOSS_ABS.D_END_DATE AND FSI_SETUP_BENCHMARK_LOSS_ABS.V_CAPITAL_ADEQUACY_REGULATOR = DIM_ORG_STRUCTURE.V_CAPITAL_ADEQUACY_REGULATOR LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY = FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY INNER JOIN FCT_STANDARD_ACCT_HEAD CAPITAL_ACCOUNTING ON FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY = CAPITAL_ACCOUNTING.N_RUN_SKEY AND FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY = CAPITAL_ACCOUNTING.N_MIS_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY = CAPITAL_ACCOUNTING.N_FORECAST_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY = CAPITAL_ACCOUNTING.N_GAAP_SKEY INNER JOIN DIM_STANDARD_ACCT_HEAD DIM_CAPITAL_ACCOUNTING ON CAPITAL_ACCOUNTING.N_STD_ACCT_HEAD_SKEY = DIM_CAPITAL_ACCOUNTING.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN FSI_SETUP_CAPITAL_HEAD ON DIM_DATES.D_CALENDAR_DATE BETWEEN FSI_SETUP_CAPITAL_HEAD.D_START_DATE AND FSI_SETUP_CAPITAL_HEAD.D_END_DATE AND DIM_CAPITAL_ACCOUNTING.V_STD_ACCT_HEAD_ID = FSI_SETUP_CAPITAL_HEAD.V_STD_ACCT_HEAD_ID AND FSI_SETUP_CAPITAL_HEAD.V_CAPITAL_ADEQUACY_REGULATOR = DIM_ORG_STRUCTURE.V_CAPITAL_ADEQUACY_REGULATOR LEFT OUTER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY = FCT_ENTITY_INFO.N_BASEL_CONSL_OPTN_TYPE_SKEY LEFT OUTER JOIN RUN_EXE_PARAMETERS ON FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY = RUN_EXE_PARAMETERS.N_RUN_SKEY AND RUN_EXE_PARAMETERS.V_PARAM_ID = 'APPR'   WHERE (( CASE (SELECT DIM_BASEL_CONSL_OPTION_TYPE.V_BASEL_CONSL_OPTN_TYPE_CODE FROM DIM_BASEL_CONSL_OPTION_TYPE WHERE DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY = (SELECT MAX(F.N_BASEL_CONSL_OPTN_TYPE_SKEY) FROM FCT_ENTITY_INFO F WHERE F.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY AND F.N_MIS_DATE_SKEY= FCT_ENTITY_INFO.N_MIS_DATE_SKEY AND F.N_FORECAST_DATE_SKEY= FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY AND F.N_ENTITY_SKEY = FCT_ENTITY_INFO.N_ENTITY_SKEY ) ) WHEN 'CONSL' THEN FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND ELSE FCT_ENTITY_INFO.F_CAP_CONSL_ENTITY_IND END) = 'Y' AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_ORG_STRUCTURE.D_RECORD_START_DATE AND DIM_ORG_STRUCTURE.D_RECORD_END_DATE)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  AND ( (((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP830')))  )  GROUP BY FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_STD_ACCT_HEAD_SKEY= SS.N_STD_ACCT_HEAD_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_ENTITY= SS.N_ENTITY AND TT.N_CAP_COMP_GROUP_SKEY= SS.N_CAP_COMP_GROUP_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_STD_ACCT_HEAD_AMT=  CASE  WHEN  COND_1346690877099_10=10 THEN EXP_1346690877099_10 ELSE EXP_1346690877099_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
