-- =====================================================================
-- Task: CS_Required_weighted_Average_Countercyclical_Buffer
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Required_weighted_Average_Countercyclical_Buffer(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_STANDARD_ACCT_HEAD TT USING (   SELECT  /*+ PARALLEL(4) */ FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY, MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS  T_1347554740596_0,   MIN(CASE  WHEN  ( ((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP819')) ) THEN 10 ELSE 11 END)  AS COND_1347554740596_10 ,  (CASE WHEN COALESCE((sum(CASE WHEN 1 = 1 THEN FSI_REQUIRED_CNTR_CYC_BUFFER.n_exposure_amt ELSE NULL END )),0) = 0 THEN 0 ELSE COALESCE(((SUM(CASE WHEN 1 = 1 THEN FSI_REQUIRED_CNTR_CYC_BUFFER.n_exposure_amt ELSE NULL END  * CASE WHEN 1 = 1 THEN FSI_REQUIRED_CNTR_CYC_BUFFER.n_benchmark_cntr_cyc_buffer ELSE NULL END ))/sum(CASE WHEN 1 = 1 THEN FSI_REQUIRED_CNTR_CYC_BUFFER.n_exposure_amt ELSE NULL END )),0) END) AS EXP_1347554740596_10,MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS EXP_1347554740596_11  FROM  fct_standard_acct_head inner join dim_dates on fct_standard_acct_head.n_mis_date_skey = dim_dates.n_date_skey inner join dim_standard_acct_head on fct_standard_acct_head.n_std_acct_head_skey = dim_standard_acct_head.n_std_acct_head_skey LEFT OUTER JOIN fsi_required_cntr_cyc_buffer ON fct_standard_acct_head.n_run_skey = fsi_required_cntr_cyc_buffer.n_run_skey AND FCT_STANDARD_ACCT_HEAD.n_mis_date_skey = fsi_required_cntr_cyc_buffer.n_mis_date_skey LEFT OUTER JOIN RUN_EXE_PARAMETERS ON FCT_STANDARD_ACCT_HEAD.n_run_skey = RUN_EXE_PARAMETERS.n_run_skey and RUN_EXE_PARAMETERS.V_PARAM_ID = 'APPR'   WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd')  AND fct_standard_acct_head.n_run_skey = '870')  AND ( (((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP819')))  )  GROUP BY FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_STD_ACCT_HEAD_SKEY= SS.N_STD_ACCT_HEAD_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_ENTITY= SS.N_ENTITY AND TT.N_CAP_COMP_GROUP_SKEY= SS.N_CAP_COMP_GROUP_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_STD_ACCT_HEAD_AMT=  CASE  WHEN  COND_1347554740596_10=10 THEN EXP_1347554740596_10 ELSE EXP_1347554740596_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
