-- =====================================================================
-- Task: CS_Significant_Invst_in_Non_Regulatory_Consl_Entity_Total_Deduction_Amount
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Significant_Invst_in_Non_Regulatory_Consl_Entity_Total_Deduction_Amount(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_NON_REG_CONSL_ENTITY_INVST TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_NON_REG_CONSL_ENTITY_INVST.N_GAAP_SKEY,FSI_NON_REG_CONSL_ENTITY_INVST.N_PARTY_SKEY,FSI_NON_REG_CONSL_ENTITY_INVST.N_RUN_SKEY,FSI_NON_REG_CONSL_ENTITY_INVST.N_MIS_DATE_SKEY,FSI_NON_REG_CONSL_ENTITY_INVST.N_FORECAST_DATE_SKEY,(FSI_NON_REG_CONSL_ENTITY_INVST.N_DEDUCTION_AMOUNT) AS  T_1351557558696_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1351557558696_10 ,  (COALESCE(CASE WHEN 1 = 1 THEN FSI_NON_REG_CONSL_ENTITY_INVST.n_cet1_deduction_amount ELSE NULL END ,0) + COALESCE(CASE WHEN 1 = 1 THEN FSI_NON_REG_CONSL_ENTITY_INVST.n_at1_deduction_amount ELSE NULL END ,0) + COALESCE(CASE WHEN 1 = 1 THEN FSI_NON_REG_CONSL_ENTITY_INVST.n_t2_deduction_amount ELSE NULL END ,0)) AS EXP_1351557558696_10,(FSI_NON_REG_CONSL_ENTITY_INVST.N_DEDUCTION_AMOUNT) AS EXP_1351557558696_11  FROM  FSI_NON_REG_CONSL_ENTITY_INVST LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_NON_REG_CONSL_ENTITY_INVST.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FSI_NON_REG_CONSL_ENTITY_INVST.n_mis_date_skey LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_NON_REG_CONSL_ENTITY_INVST.N_GAAP_SKEY  WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = TO_DATE('20260331','yyyymmdd'))  AND ((((COALESCE(FSI_NON_REG_CONSL_ENTITY_INVST.f_significant_investment_ind, 'N') = 'Y')) ))  ) WHERE (   (COND_1351557558696_10 <> 11)  ) ) SS ON ( TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_PARTY_SKEY= SS.N_PARTY_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_DEDUCTION_AMOUNT=  CASE  WHEN  COND_1351557558696_10=10 THEN EXP_1351557558696_10 ELSE EXP_1351557558696_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
