-- =====================================================================
-- Task: CS_Standard_Account_Head_Capital_Comp_Group_Assignment
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Standard_Account_Head_Capital_Comp_Group_Assignment(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_STANDARD_ACCT_HEAD TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_STANDARD_ACCT_HEAD.ROWID source_rowid, (FCT_STANDARD_ACCT_HEAD.N_UPD_CAP_COMP_GROUP_SKEY) AS  T_1529925511563_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1529925511563_10 ,  (CASE WHEN 1 = 1 THEN DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY ELSE NULL END ) AS EXP_1529925511563_10,(FCT_STANDARD_ACCT_HEAD.N_UPD_CAP_COMP_GROUP_SKEY) AS EXP_1529925511563_11 ,(FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY) AS  T_1529925511563_1,   (CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1529925511563_20 ,  (CASE WHEN 1 = 1 THEN DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY ELSE NULL END ) AS EXP_1529925511563_20,(FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY) AS EXP_1529925511563_21  FROM  FCT_STANDARD_ACCT_HEAD LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY INNER JOIN DIM_DATES ON FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN DIM_RUN ON FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN ( SELECT N_RUN_SKEY ,MAX(V_AOCI_OPT_OUT_ELECTION_OPTION) V_AOCI_OPT_OUT_ELECTION_OPTION FROM RUN_PARAMETERS GROUP BY N_RUN_SKEY ) RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY LEFT OUTER JOIN FSI_SETUP_CAPITAL_SOURCE ON DIM_RUN.V_JURISDICTION_CODE = FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE AND FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = FSI_SETUP_CAPITAL_SOURCE.V_INITIAL_CAP_COMP_GROUP_CODE AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE   WHERE (1 = 1)  AND (DIM_DATES.D_CALENDAR_DATE = TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID NOT IN ('CAP1575', 'CAP1576', 'CAP1577', 'CAP1578', 'CAP1579', 'CAP1580', 'CAP1581', 'CAP1582', 'CAP1583', 'CAP1584', 'CAP1586', 'CAP1587', 'CAP1588', 'CAP1590', 'CAP1591') )  AND ((((COALESCE(FSI_SETUP_CAPITAL_SOURCE.F_ELIGIBLE_FOR_TRANSITION, 'N') = 'N')) ))  ) WHERE (   (COND_1529925511563_10 <> 11)   OR  (COND_1529925511563_20 <> 21) ) ) SS ON ( TT.ROWID = SS.source_rowid) WHEN MATCHED THEN UPDATE SET  TT.N_UPD_CAP_COMP_GROUP_SKEY=  CASE  WHEN  COND_1529925511563_10=10 THEN EXP_1529925511563_10 ELSE EXP_1529925511563_11 END  , TT.N_CAP_COMP_GROUP_SKEY=  CASE  WHEN  COND_1529925511563_20=20 THEN EXP_1529925511563_20 ELSE EXP_1529925511563_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
