-- =====================================================================
-- Task: CS_Total_Investments_in_Private_Equity_Investment_Firm_AT1
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Total_Investments_in_Private_Equity_Investment_Firm_AT1(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_STANDARD_ACCT_HEAD TT USING (   SELECT  /*+ PARALLEL(4) */ FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY, MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS  T_1383732535000_0,   MIN(CASE  WHEN  ( ((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP577')) ) THEN 10 ELSE 11 END)  AS COND_1383732535000_10 ,  (MAX(CASE WHEN CAPITAL_ACCOUNTING.N_STD_ACCT_HEAD_SKEY IN (SELECT DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY FROM DIM_STANDARD_ACCT_HEAD WHERE DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP577') AND CAPITAL_ACCOUNTING.N_CAP_COMP_GROUP_SKEY IN (SELECT DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY FROM DIM_CAPITAL_COMP_GROUP WHERE  DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'DEDAT1') THEN CAPITAL_ACCOUNTING.n_std_acct_head_amt ELSE NULL END )) AS EXP_1383732535000_10,MIN(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT) AS EXP_1383732535000_11  FROM  FCT_STANDARD_ACCT_HEAD LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON FCT_STANDARD_ACCT_HEAD.n_std_acct_head_skey = DIM_STANDARD_ACCT_HEAD.n_std_acct_head_skey LEFT OUTER JOIN DIM_COUNTRY ON FCT_STANDARD_ACCT_HEAD.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_RUN ON FCT_STANDARD_ACCT_HEAD.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_DATES ON FCT_STANDARD_ACCT_HEAD.n_mis_date_skey = DIM_DATES.n_date_skey LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON DIM_RUN.N_RUN_SKEY = FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'CS' AND FSI_CAP_RUN_EXE_PARAMETERS.F_PORTFOLIO_BASED_FLAG = 'N' LEFT OUTER JOIN   RUN_PARAMETERS   ON    RUN_PARAMETERS.N_MIS_DATE_SKEY   = DIM_DATES.n_date_skey AND RUN_PARAMETERS.N_RUN_SKEY       = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_STANDARD_ACCT_HEAD.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON FCT_STANDARD_ACCT_HEAD.n_upd_cap_comp_group_skey = DIM_CAPITAL_COMP_GROUP.n_cap_comp_group_skey INNER JOIN FCT_STANDARD_ACCT_HEAD CAPITAL_ACCOUNTING ON FCT_STANDARD_ACCT_HEAD.n_run_skey = CAPITAL_ACCOUNTING.n_run_skey AND FCT_STANDARD_ACCT_HEAD.n_mis_date_skey = CAPITAL_ACCOUNTING.n_mis_date_skey AND FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY = CAPITAL_ACCOUNTING.N_GAAP_SKEY AND FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY = CAPITAL_ACCOUNTING.N_FORECAST_DATE_SKEY LEFT OUTER JOIN DIM_ORG_STRUCTURE ON FCT_STANDARD_ACCT_HEAD.n_entity=DIM_ORG_STRUCTURE.n_entity_skey LEFT OUTER JOIN RUN_EXE_PARAMETERS ON FCT_STANDARD_ACCT_HEAD.n_run_skey = RUN_EXE_PARAMETERS.n_run_skey AND RUN_EXE_PARAMETERS.V_PARAM_ID = 'APPR' LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY AND FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_ENTITY = FCT_ENTITY_INFO.N_ENTITY_SKEY AND FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY =FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY LEFT OUTER JOIN FSI_PHASE_IN_TREATMENT ON FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY=FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY AND FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY =FSI_PHASE_IN_TREATMENT.N_RUN_SKEY AND FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY =FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY AND FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY =FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY AND FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY =FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY LEFT OUTER JOIN FSI_FORECAST_EXE_MASTER ON FSI_FORECAST_EXE_MASTER.N_RUN_SKEY = FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  AND ( (((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID  = 'CAP577')))  )  GROUP BY FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY,FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY,FCT_STANDARD_ACCT_HEAD.N_ENTITY,FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY,FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY,FCT_STANDARD_ACCT_HEAD.N_FORECAST_DATE_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_STD_ACCT_HEAD_SKEY= SS.N_STD_ACCT_HEAD_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_ENTITY= SS.N_ENTITY AND TT.N_CAP_COMP_GROUP_SKEY= SS.N_CAP_COMP_GROUP_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_STD_ACCT_HEAD_AMT=  CASE  WHEN  COND_1383732535000_10=10 THEN EXP_1383732535000_10 ELSE EXP_1383732535000_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
