-- =====================================================================
-- Task: CS_Threshold_Treatment_Aggregate_Threshold_Assignment
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CS_Threshold_Treatment_Aggregate_Threshold_Assignment(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_THRESHOLD_TREATMENT TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_THRESHOLD_TREATMENT.N_STD_ACCT_HEAD_SKEY,FSI_THRESHOLD_TREATMENT.N_GAAP_SKEY,FSI_THRESHOLD_TREATMENT.N_RUN_SKEY,FSI_THRESHOLD_TREATMENT.N_MIS_DATE_SKEY,FSI_THRESHOLD_TREATMENT.N_FORECAST_DATE_SKEY,(FSI_THRESHOLD_TREATMENT.N_AGGREGATE_THRESHOLD) AS  T_1351726372676_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1351726372676_10 ,  ((CASE WHEN CASE WHEN 1 = 1 THEN FSI_SETUP_CAPITAL_HEAD.d_end_date ELSE NULL END  = TO_DATE('31-DEC-9999') THEN GREATEST(CASE WHEN 1 = 1 THEN FSI_THRESHOLD_TREATMENT.n_net_cet1_post_sig_invst_ded ELSE NULL END  - SUM(CASE WHEN 1 = 1 THEN FSI_THRESHOLD_TREATMENT.n_original_amount ELSE NULL END ) OVER (PARTITION BY CASE WHEN 1 = 1 THEN FSI_THRESHOLD_TREATMENT.n_gaap_skey ELSE NULL END ),0) ELSE CASE WHEN 1 = 1 THEN FSI_THRESHOLD_TREATMENT.n_net_cet1_post_threshold_lmt ELSE NULL END  END)* CASE WHEN FSI_SETUP_CAPITAL_HEAD.v_std_acct_head_id IN (SELECT v_std_acct_head_id FROM DIM_STANDARD_ACCT_HEAD WHERE v_std_acct_head_id = 'CAP975') THEN FSI_SETUP_CAPITAL_HEAD.n_capital_component_value ELSE NULL END ) AS EXP_1351726372676_10,(FSI_THRESHOLD_TREATMENT.N_AGGREGATE_THRESHOLD) AS EXP_1351726372676_11  FROM  FSI_THRESHOLD_TREATMENT LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_THRESHOLD_TREATMENT.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_THRESHOLD_TREATMENT.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_THRESHOLD_TREATMENT.N_GAAP_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FSI_THRESHOLD_TREATMENT.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' AND FCT_ENTITY_INFO.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = FSI_THRESHOLD_TREATMENT.N_FORECAST_DATE_SKEY LEFT OUTER JOIN FSI_SETUP_CAPITAL_HEAD ON DIM_DATES.D_CALENDAR_DATE BETWEEN FSI_SETUP_CAPITAL_HEAD.D_START_DATE AND FSI_SETUP_CAPITAL_HEAD.D_END_DATE AND FSI_SETUP_CAPITAL_HEAD.V_STD_ACCT_HEAD_ID = 'CAP975' AND FSI_SETUP_CAPITAL_HEAD.V_CAPITAL_ADEQUACY_REGULATOR = FCT_ENTITY_INFO.V_CAPITAL_ADEQUACY_REGULATOR   WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = TO_DATE('20260331','yyyymmdd'))  ) WHERE (   (COND_1351726372676_10 <> 11)  ) ) SS ON ( TT.N_STD_ACCT_HEAD_SKEY= SS.N_STD_ACCT_HEAD_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_FORECAST_DATE_SKEY= SS.N_FORECAST_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_AGGREGATE_THRESHOLD=  CASE  WHEN  COND_1351726372676_10=10 THEN EXP_1351726372676_10 ELSE EXP_1351726372676_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
