-- =====================================================================
-- Task: CVA_Idiosyncratic_Risk_Component_for_Portfolio
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CVA_Idiosyncratic_Risk_Component_for_Portfolio(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_CVA_SUMMARY TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_CAP_CVA_SUMMARY.N_ENTITY_SKEY,FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY,FSI_CAP_CVA_SUMMARY.N_RUN_SKEY,FSI_CAP_CVA_SUMMARY.N_CAP_APPROACH_TYPE_SKEY, MIN(FSI_CAP_CVA_SUMMARY.N_IDIOSYNCRATIC_RISK_COMP) AS  T_1628066399057_0,   MIN(CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1628066399057_10 ,  (SUM(0.75*CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_CDS_HEDGE_ADJ_EAD ELSE NULL END *CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_CDS_HEDGE_ADJ_EAD ELSE NULL END )) AS EXP_1628066399057_10,MIN(FSI_CAP_CVA_SUMMARY.N_IDIOSYNCRATIC_RISK_COMP) AS EXP_1628066399057_11  FROM  FSI_CAP_COUNTERPARTY_CVA INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_CAP_CVA_SUMMARY ON FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY AND FSI_CAP_CVA_SUMMARY.N_RUN_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY AND FSI_CAP_CVA_SUMMARY.N_ENTITY_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FSI_CAP_COUNTERPARTY_CVA.N_BASEL_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT OUTER JOIN DIM_BASEL_ASSET_CLASS ON FSI_CAP_COUNTERPARTY_CVA.N_BASEL_ASSET_CLASS_SKEY = DIM_BASEL_ASSET_CLASS.N_BASEL_ASSET_CLASS_SKEY LEFT OUTER JOIN DIM_BASEL_CREDIT_RATING ON FSI_CAP_COUNTERPARTY_CVA.N_BASEL_PARTY_RATING = DIM_BASEL_CREDIT_RATING.N_BASEL_RATING LEFT OUTER JOIN DIM_BANDS ON FSI_CAP_COUNTERPARTY_CVA.N_PD_PERCENT > DIM_BANDS.N_BAND_LOWER_BOUND_VALUE AND FSI_CAP_COUNTERPARTY_CVA.N_PD_PERCENT <= DIM_BANDS.N_BAND_UPPER_BOUND_VALUE AND DIM_BANDS.V_BAND_TYPE = 'CVA PD BAND' AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_BANDS.D_RECORD_START_DATE AND DIM_BANDS.D_RECORD_END_DATE LEFT OUTER JOIN DIM_REG_CAP_INDUSTRY ON FSI_CAP_COUNTERPARTY_CVA.N_REG_CAP_INDUSTRY_SKEY = DIM_REG_CAP_INDUSTRY.N_REG_CAP_INDUSTRY_SKEY INNER JOIN FSI_BASEL_RATING_BAND_MAP ON FSI_BASEL_RATING_BAND_MAP.N_BASEL_RATING = FSI_CAP_COUNTERPARTY_CVA.N_BASEL_PARTY_RATING AND FSI_BASEL_RATING_BAND_MAP.N_RUN_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY AND FSI_BASEL_RATING_BAND_MAP.N_MIS_DATE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY AND FSI_BASEL_RATING_BAND_MAP.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY INNER JOIN DIM_REG_CAP_RATING ON DIM_REG_CAP_RATING.N_REG_CAP_RATING_SKEY = FSI_BASEL_RATING_BAND_MAP.N_REG_CAP_RATING_SKEY LEFT OUTER JOIN FSI_CAP_DISCRETE_VALUE A_PROCESSING_TYPE ON FSI_BASEL_RATING_BAND_MAP.V_PROCESSING_TYPE = A_PROCESSING_TYPE.V_CAP_DISCRETE_VALUE AND A_PROCESSING_TYPE.V_CAP_VALUE_TYPE = 'PROCESSING_TYPE' LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE ON FSI_CAP_COUNTERPARTY_CVA.N_STANDARD_PARTY_TYPE_SKEY = DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_INDICATOR A_INVESTMENT_GRADE_IND ON A_INVESTMENT_GRADE_IND.F_CAP_INDICATOR_VALUE = COALESCE(FSI_CAP_COUNTERPARTY_CVA.F_INVESTMENT_GRADE_IND, 'N') AND A_INVESTMENT_GRADE_IND.V_CAP_INDICATOR_TYPE = 'INVESTMENT_GRADE_IND' LEFT JOIN DIM_BASEL_SECTOR ON DIM_BASEL_SECTOR.N_BASEL_SECTOR_SKEY = COALESCE(FSI_CAP_COUNTERPARTY_CVA.N_BASEL_SECTOR_SKEY,-1)  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870' AND A_PROCESSING_TYPE.V_CAP_DISCRETE_VALUE = 'NONSEC')  AND ( (((1=1)))  )  GROUP BY FSI_CAP_CVA_SUMMARY.N_ENTITY_SKEY,FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY,FSI_CAP_CVA_SUMMARY.N_RUN_SKEY,FSI_CAP_CVA_SUMMARY.N_CAP_APPROACH_TYPE_SKEY ) SS ON ( TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_IDIOSYNCRATIC_RISK_COMP=  CASE  WHEN  COND_1628066399057_10=10 THEN EXP_1628066399057_10 ELSE EXP_1628066399057_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
