-- =====================================================================
-- Task: CVA_RWA_and_Charge_Allocation_to_Nettable_Pool
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CVA_RWA_and_Charge_Allocation_to_Nettable_Pool(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_NETTABLE_POOL TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY,FSI_CAP_NETTABLE_POOL.N_RUN_SKEY,FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY, MIN(FSI_CAP_NETTABLE_POOL.N_CVA_CAPITAL_CHARGE) AS  T_1628227799445_0,   MIN(CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1628227799445_10 ,  (CASE WHEN sum(max(CASE WHEN 1=1 THEN FSI_CAP_NETTABLE_POOL.N_POOL_PRE_CRM_RWA_UL ELSE NULL END )) over (partition by max(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CUST_SKEY ELSE NULL END )) > 0 THEN max(CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_CVA_CHARGE_AT_COUNTERPARTY ELSE NULL END ) * max(CASE WHEN 1=1 THEN FSI_CAP_NETTABLE_POOL.N_POOL_PRE_CRM_RWA_UL ELSE NULL END )/sum(max(CASE WHEN 1=1 THEN FSI_CAP_NETTABLE_POOL.N_POOL_PRE_CRM_RWA_UL ELSE NULL END )) over (partition by max(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CUST_SKEY ELSE NULL END )) ELSE 0 END) AS EXP_1628227799445_10,MIN(FSI_CAP_NETTABLE_POOL.N_CVA_CAPITAL_CHARGE) AS EXP_1628227799445_11 , MIN(FSI_CAP_NETTABLE_POOL.N_CVA_RWA_AMOUNT) AS  T_1628227799445_1,   MIN(CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1628227799445_20 ,  (CASE WHEN sum(max(CASE WHEN 1=1 THEN FSI_CAP_NETTABLE_POOL.N_POOL_PRE_CRM_RWA_UL ELSE NULL END )) over (partition by max(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CUST_SKEY ELSE NULL END )) > 0 THEN max(CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_CVA_RWA_AT_COUNTERPARTY ELSE NULL END ) * max(CASE WHEN 1=1 THEN FSI_CAP_NETTABLE_POOL.N_POOL_PRE_CRM_RWA_UL ELSE NULL END )/sum(max(CASE WHEN 1=1 THEN FSI_CAP_NETTABLE_POOL.N_POOL_PRE_CRM_RWA_UL ELSE NULL END )) over (partition by max(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CUST_SKEY ELSE NULL END )) ELSE 0 END) AS EXP_1628227799445_20,MIN(FSI_CAP_NETTABLE_POOL.N_CVA_RWA_AMOUNT) AS EXP_1628227799445_21  FROM  FSI_CAP_NETTABLE_POOL INNER JOIN DIM_DATES ON FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY INNER JOIN DIM_RUN ON FSI_CAP_NETTABLE_POOL.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_PARAMETER_SETUP_SKEY AND FSI_RUN_PARAMETER.N_RUN_SKEY=FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_RUN_PARAMETER.N_DATE_SKEY=FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_CAP_COUNTERPARTY_CVA ON FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY = FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY = FSI_CAP_NETTABLE_POOL.N_CUST_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_RECORD_TYPE_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FSI_CAP_NETTABLE_POOL.N_CVA_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE ON FSI_CAP_NETTABLE_POOL.N_STANDARD_PARTY_TYPE_SKEY = DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_INDICATOR ALIAS_CLEARED_TRANSACTION_FLAG ON ALIAS_CLEARED_TRANSACTION_FLAG.F_CAP_INDICATOR_VALUE = COALESCE(FSI_CAP_NETTABLE_POOL.F_CLEARED_TRANSACTION_FLAG, 'N') AND ALIAS_CLEARED_TRANSACTION_FLAG.V_CAP_INDICATOR_TYPE = 'F_CLEARED_TRANSACTION_FLAG' LEFT OUTER JOIN FSI_CAP_INDICATOR A_QUALIFIED_CCP ON A_QUALIFIED_CCP.F_CAP_INDICATOR_VALUE = COALESCE(FSI_CAP_NETTABLE_POOL.F_QUALIFIED_CCP_FLAG, 'N') AND A_QUALIFIED_CCP.V_CAP_INDICATOR_TYPE = 'QUALCCP' LEFT OUTER JOIN DIM_BASEL_PRODUCT_TYPE ON FSI_CAP_NETTABLE_POOL.N_BASEL_PROD_TYPE_SKEY = DIM_BASEL_PRODUCT_TYPE.N_BASEL_PROD_TYPE_SKEY  WHERE (1 = 1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870')  AND (((DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABHM') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABWH') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVACCR') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVAIMM') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVASTD') ))  AND ( (((1=1))) OR (((1=1)))  )  GROUP BY FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY,FSI_CAP_NETTABLE_POOL.N_RUN_SKEY,FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY ) SS ON ( TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_CAP_NETTABLE_POOL_SKEY= SS.N_CAP_NETTABLE_POOL_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_CVA_CAPITAL_CHARGE=  CASE  WHEN  COND_1628227799445_10=10 THEN EXP_1628227799445_10 ELSE EXP_1628227799445_11 END  , TT.N_CVA_RWA_AMOUNT=  CASE  WHEN  COND_1628227799445_20=20 THEN EXP_1628227799445_20 ELSE EXP_1628227799445_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
