-- =====================================================================
-- Task: CVA_Charge_for_Counterparty
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CVA_Charge_for_Counterparty(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_COUNTERPARTY_CVA TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY,FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY,(FSI_CAP_COUNTERPARTY_CVA.N_CVA_CHARGE_AT_COUNTERPARTY) AS  T_1628063153134_0,   (CASE  WHEN  ( ((DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABHM')) OR ((DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABWH')) OR ((DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVACCR')) ) THEN 10 WHEN  ( ((DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVASTD')) ) THEN 11 ELSE 12 END)  AS COND_1628063153134_10 ,  (CASE WHEN 1 = 1 THEN FSI_CAP_CVA_SUMMARY.N_TOTAL_CVA_CHARGE ELSE NULL END  * CASE WHEN SUM(COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_EAD_POST_MITIGATION ELSE NULL END ,0)) OVER (PARTITION BY CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY ELSE NULL END ) = 0 THEN 0 ELSE COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_EAD_POST_MITIGATION ELSE NULL END ,0) / SUM(COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_EAD_POST_MITIGATION ELSE NULL END ,0)) OVER (PARTITION BY CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY ELSE NULL END ) END ) AS EXP_1628063153134_10,(CASE WHEN 1 = 1 THEN FSI_CAP_CVA_SUMMARY.N_TOTAL_CVA_CHARGE ELSE NULL END  * CASE WHEN 1 = 1 THEN FSI_CAP_COUNTERPARTY_CVA.N_CVA_WEIGHT ELSE NULL END ) AS EXP_1628063153134_11,(FSI_CAP_COUNTERPARTY_CVA.N_CVA_CHARGE_AT_COUNTERPARTY) AS EXP_1628063153134_12  FROM  FSI_CAP_COUNTERPARTY_CVA INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_CAP_CVA_SUMMARY ON FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY AND FSI_CAP_CVA_SUMMARY.N_RUN_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY AND FSI_CAP_CVA_SUMMARY.N_ENTITY_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FSI_CAP_COUNTERPARTY_CVA.N_BASEL_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT OUTER JOIN DIM_REG_CAP_INDUSTRY ON FSI_CAP_COUNTERPARTY_CVA.N_REG_CAP_INDUSTRY_SKEY = DIM_REG_CAP_INDUSTRY.N_REG_CAP_INDUSTRY_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE ON FSI_CAP_COUNTERPARTY_CVA.N_STANDARD_PARTY_TYPE_SKEY = DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870')  ) WHERE (   (COND_1628063153134_10 <> 12)  ) ) SS ON ( TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_COUNTERPARTY_SKEY= SS.N_COUNTERPARTY_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_CVA_CHARGE_AT_COUNTERPARTY=  CASE  WHEN  COND_1628063153134_10=10 THEN EXP_1628063153134_10 WHEN  COND_1628063153134_10=11 THEN EXP_1628063153134_11 ELSE EXP_1628063153134_12 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
