-- =====================================================================
-- Task: CVA_RWA_and_Charge_Allocation_to_Derivatives
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CVA_RWA_and_Charge_Allocation_to_Derivatives(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_DERIVATIVES TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY,FSI_CAP_DERIVATIVES.N_RUN_SKEY,FSI_CAP_DERIVATIVES.N_GAAP_SKEY,FSI_CAP_DERIVATIVES.N_ACCT_SKEY,FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY,(FSI_CAP_DERIVATIVES.N_CVA_CAPITAL_CHARGE) AS  T_1628173034374_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1628173034374_10 ,  (case when sum(coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )  > 0 then coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CVA_CAPITAL_CHARGE ELSE NULL END ,0)*coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION ELSE NULL END ,0) / (sum(coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )) else 0 end) AS EXP_1628173034374_10,(FSI_CAP_DERIVATIVES.N_CVA_CAPITAL_CHARGE) AS EXP_1628173034374_11 ,(FSI_CAP_DERIVATIVES.N_CVA_RWA_AMOUNT) AS  T_1628173034374_1,   (CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1628173034374_20 ,  (case when sum(coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )  > 0 then coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CVA_RWA_AMOUNT ELSE NULL END ,0)*coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION ELSE NULL END ,0) / (sum(coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )  ) else 0 end ) AS EXP_1628173034374_20,(FSI_CAP_DERIVATIVES.N_CVA_RWA_AMOUNT) AS EXP_1628173034374_21  FROM  FSI_CAP_DERIVATIVES INNER JOIN FSI_CAP_NETTABLE_POOL ON FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY = FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY AND FSI_CAP_NETTABLE_POOL.N_RUN_SKEY = FSI_CAP_DERIVATIVES.N_RUN_SKEY AND FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY = FSI_CAP_DERIVATIVES.N_GAAP_SKEY AND FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY = FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY AND FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN DIM_BASEL_PRODUCT_TYPE ON DIM_BASEL_PRODUCT_TYPE.N_BASEL_PROD_TYPE_SKEY = FSI_CAP_DERIVATIVES.N_BASEL_PROD_TYPE_SKEY LEFT OUTER JOIN DIM_RUN ON FSI_CAP_DERIVATIVES.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_DERIVATIVES.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_INDICATOR A_FAILED_TRADE_FLAG ON COALESCE(FSI_CAP_DERIVATIVES.F_FAILED_TRADE_FLAG, 'N') = A_FAILED_TRADE_FLAG.F_CAP_INDICATOR_VALUE AND A_FAILED_TRADE_FLAG.V_CAP_INDICATOR_TYPE = 'FAILTRADE'  WHERE (1=1)  AND (FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY = TO_NUMBER(TO_CHAR(TO_DATE('20260331','yyyymmdd'),'YYYYMMDD')) AND FSI_CAP_DERIVATIVES.N_RUN_SKEY = '870' )  ) WHERE (   (COND_1628173034374_10 <> 11)   OR  (COND_1628173034374_20 <> 21) ) ) SS ON ( TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_ACCT_SKEY= SS.N_ACCT_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_CVA_CAPITAL_CHARGE=  CASE  WHEN  COND_1628173034374_10=10 THEN EXP_1628173034374_10 ELSE EXP_1628173034374_11 END  , TT.N_CVA_RWA_AMOUNT=  CASE  WHEN  COND_1628173034374_20=20 THEN EXP_1628173034374_20 ELSE EXP_1628173034374_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
