-- =====================================================================
-- Task: CVA_RWA_and_Charge_Allocation_to_SFT_Exposures
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CVA_RWA_and_Charge_Allocation_to_SFT_Exposures(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_SFT_EXPOSURES TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_CAP_SFT_EXPOSURES.N_RUN_SKEY,FSI_CAP_SFT_EXPOSURES.N_MIS_DATE_SKEY,FSI_CAP_SFT_EXPOSURES.N_GAAP_SKEY,FSI_CAP_SFT_EXPOSURES.N_ACCT_SKEY,FSI_CAP_SFT_EXPOSURES.N_CAP_APPROACH_TYPE_SKEY,(FSI_CAP_SFT_EXPOSURES.N_CVA_CAPITAL_CHARGE) AS  T_1628173667910_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1628173667910_10 ,  (case when sum(coalesce(CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.n_ead_pre_mitigation ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )  > 0 then coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CVA_CAPITAL_CHARGE ELSE NULL END ,0)*coalesce(CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.n_ead_pre_mitigation ELSE NULL END ,0) / (sum(coalesce(CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.n_ead_pre_mitigation ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )  ) else 0 end ) AS EXP_1628173667910_10,(FSI_CAP_SFT_EXPOSURES.N_CVA_CAPITAL_CHARGE) AS EXP_1628173667910_11 ,(FSI_CAP_SFT_EXPOSURES.N_CVA_RWA_AMOUNT) AS  T_1628173667910_1,   (CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1628173667910_20 ,  (case when sum(coalesce(CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.n_ead_pre_mitigation ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )  > 0 then coalesce(CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_CVA_RWA_AMOUNT ELSE NULL END ,0)*coalesce(CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.n_ead_pre_mitigation ELSE NULL END ,0) / (sum(coalesce(CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.n_ead_pre_mitigation ELSE NULL END ,0)) over (partition by CASE WHEN 1=1 THEN FSI_CAP_SFT_EXPOSURES.N_CAP_NETTABLE_POOL_SKEY ELSE NULL END )  ) else 0 end ) AS EXP_1628173667910_20,(FSI_CAP_SFT_EXPOSURES.N_CVA_RWA_AMOUNT) AS EXP_1628173667910_21  FROM  FSI_CAP_SFT_EXPOSURES INNER JOIN FSI_CAP_NETTABLE_POOL ON FSI_CAP_NETTABLE_POOL.n_cust_skey = FSI_CAP_SFT_EXPOSURES.n_cust_skey AND FSI_CAP_NETTABLE_POOL.v_basel_prod_type_level1_code = FSI_CAP_SFT_EXPOSURES.v_basel_prod_type_level1_code AND FSI_CAP_NETTABLE_POOL.n_mis_date_skey = FSI_CAP_SFT_EXPOSURES.n_mis_date_skey AND FSI_CAP_NETTABLE_POOL.n_run_skey = FSI_CAP_SFT_EXPOSURES.n_run_skey AND FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY = FSI_CAP_SFT_EXPOSURES.N_GAAP_SKEY AND FSI_CAP_NETTABLE_POOL.n_entity_skey = FSI_CAP_SFT_EXPOSURES.n_entity_skey AND COALESCE(FSI_CAP_NETTABLE_POOL.f_nettability_flag, 'N') = COALESCE(FSI_CAP_SFT_EXPOSURES.f_nettability_flag, 'N') AND COALESCE(FSI_CAP_NETTABLE_POOL.f_long_settlement_txn_flag, 'N') = COALESCE(FSI_CAP_SFT_EXPOSURES.f_long_settlement_txn_flag, 'N') AND COALESCE(FSI_CAP_NETTABLE_POOL.v_product_book_code, 'B') = COALESCE(FSI_CAP_SFT_EXPOSURES.v_product_book_code, 'B') AND COALESCE(FSI_CAP_NETTABLE_POOL.n_netting_agreement_skey, -999) = COALESCE(FSI_CAP_SFT_EXPOSURES.n_netting_agreement_skey, -999) AND FSI_CAP_SFT_EXPOSURES.N_CAP_NETTABLE_POOL_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY LEFT OUTER JOIN DIM_BASEL_PRODUCT_TYPE ON DIM_BASEL_PRODUCT_TYPE.n_basel_prod_type_skey = FSI_CAP_SFT_EXPOSURES.n_basel_prod_type_skey  LEFT OUTER JOIN DIM_RUN ON FSI_CAP_SFT_EXPOSURES.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN RUN_PARAMETERS ON FSI_CAP_SFT_EXPOSURES.n_run_parameter_setup_skey = RUN_PARAMETERS.n_run_parameter_setup_skey AND RUN_PARAMETERS.n_Run_Skey=FSI_CAP_SFT_EXPOSURES.n_Run_Skey AND RUN_PARAMETERS.n_Date_Skey=FSI_CAP_SFT_EXPOSURES.n_Mis_Date_Skey   INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_SFT_EXPOSURES.N_CAP_RECORD_TYPE_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_SFT_EXPOSURES.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_INDICATOR A_FAILED_TRADE_FLAG ON A_FAILED_TRADE_FLAG.F_CAP_INDICATOR_VALUE = COALESCE(FSI_CAP_SFT_EXPOSURES.f_failed_trade_flag,'N') AND A_FAILED_TRADE_FLAG.V_CAP_INDICATOR_TYPE = 'FAILTRADE'  WHERE (1=1)  AND (FSI_CAP_SFT_EXPOSURES.N_MIS_DATE_SKEY = TO_NUMBER(TO_CHAR(TO_DATE('20260331','yyyymmdd'),'YYYYMMDD')) AND FSI_CAP_SFT_EXPOSURES.N_RUN_SKEY = '870')  ) WHERE (   (COND_1628173667910_10 <> 11)   OR  (COND_1628173667910_20 <> 21) ) ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_ACCT_SKEY= SS.N_ACCT_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_CVA_CAPITAL_CHARGE=  CASE  WHEN  COND_1628173667910_10=10 THEN EXP_1628173667910_10 ELSE EXP_1628173667910_11 END  , TT.N_CVA_RWA_AMOUNT=  CASE  WHEN  COND_1628173667910_20=20 THEN EXP_1628173667910_20 ELSE EXP_1628173667910_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
