-- =====================================================================
-- Task: CVA_Charge_for_Portfolio
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CVA_Charge_for_Portfolio(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_CVA_SUMMARY TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_CAP_CVA_SUMMARY.N_ENTITY_SKEY,FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY,FSI_CAP_CVA_SUMMARY.N_RUN_SKEY,FSI_CAP_CVA_SUMMARY.N_CAP_APPROACH_TYPE_SKEY,(FSI_CAP_CVA_SUMMARY.N_TOTAL_CVA_CHARGE) AS  T_1628071499751_0,   (CASE  WHEN  ( (((1=1))) ) THEN 10 ELSE 11 END)  AS COND_1628071499751_10 ,  (2.33*sqrt(1)*sqrt(((COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_CVA_SUMMARY.N_SYSTEMIC_RISK_COMP ELSE NULL END ,0) - COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_CVA_SUMMARY.N_CVA_CDS_INDEX ELSE NULL END ,0) )*(COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_CVA_SUMMARY.N_SYSTEMIC_RISK_COMP ELSE NULL END ,0) - COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_CVA_SUMMARY.N_CVA_CDS_INDEX ELSE NULL END ,0) )) + COALESCE(CASE WHEN 1 = 1 THEN FSI_CAP_CVA_SUMMARY.N_IDIOSYNCRATIC_RISK_COMP ELSE NULL END ,0))) AS EXP_1628071499751_10,(FSI_CAP_CVA_SUMMARY.N_TOTAL_CVA_CHARGE) AS EXP_1628071499751_11  FROM  FSI_CAP_CVA_SUMMARY INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_CVA_SUMMARY.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_CVA_SUMMARY.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY = FSI_CAP_CVA_SUMMARY.N_BASEL_METHOD_SKEY  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870')  ) WHERE (   (COND_1628071499751_10 <> 11)  ) ) SS ON ( TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_TOTAL_CVA_CHARGE=  CASE  WHEN  COND_1628071499751_10=10 THEN EXP_1628071499751_10 ELSE EXP_1628071499751_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
