-- =====================================================================
-- Task: CVA_SUMMARY_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.CVA_SUMMARY_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_CVA_SUMMARY(N_BASEL_METHOD_SKEY,N_CAP_APPROACH_TYPE_SKEY,N_CVA_CDS_INDEX,N_ENTITY_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ MAX(FSI_CAP_COUNTERPARTY_CVA.N_BASEL_METHOD_SKEY),FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY,SUM(COALESCE(FSI_CAP_COUNTERPARTY_CVA.N_MAT_ADJ_INDEX_HEDGE_AMT,0)),to_char(FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY),to_char(FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY),to_char(FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY) FROM FSI_CAP_COUNTERPARTY_CVA INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY INNER JOIN DIM_RUN ON FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY='870' GROUP BY FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY, FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY, FSI_CAP_COUNTERPARTY_CVA.N_CAP_APPROACH_TYPE_SKEY, FSI_CAP_COUNTERPARTY_CVA.N_ENTITY_SKEY LOG ERRORS INTO FSI_CAP_CVA_SUMMARY$ ('1776770763244_78809036_20260331_1_JOB_16281536306645') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
