-- =====================================================================
-- Task: DEPOSITORY_RECEIPTS_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.DEPOSITORY_RECEIPTS_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into DR_ISSUE_MAPPING(N_MIS_DATE_SKEY,N_DR_SKEY,N_RUN_SKEY,N_UNDERLYING_SKEY,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_CONVERSION_FACTOR)SELECT  /*+PARALLEL (4)*/ DIM_DATES.N_DATE_SKEY,(SELECT DIM_EXPOSURE.n_acct_skey FROM DIM_EXPOSURE WHERE DIM_EXPOSURE.v_exposure_id = STG_DR_ISSUE_MAPPING.v_dr_code AND STG_DR_ISSUE_MAPPING.FIC_MIS_DATE BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE),'870',(SELECT DIM_EXPOSURE.n_acct_skey FROM DIM_EXPOSURE WHERE DIM_EXPOSURE.v_exposure_id = STG_DR_ISSUE_MAPPING.v_underlying_issue_code AND STG_DR_ISSUE_MAPPING.FIC_MIS_DATE BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE),to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_IDENTIFIER_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY),to_char(STG_DR_ISSUE_MAPPING.N_CONVERSION_FACTOR) FROM stg_dr_issue_mapping INNER JOIN DIM_DATES ON stg_dr_issue_mapping.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE INNER JOIN DIM_INSTRUMENT_CONTRACT ON stg_dr_issue_mapping.V_DR_CODE = DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE AND stg_dr_issue_mapping.fic_mis_date between DIM_INSTRUMENT_CONTRACT.d_record_start_date and DIM_INSTRUMENT_CONTRACT.d_record_end_date INNER JOIN FCT_MARKET_RISK_EXPOSURES ON FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey = DIM_DATES.N_DATE_SKEY AND FCT_MARKET_RISK_EXPOSURES.N_INSTRUMENT_SKEY = DIM_INSTRUMENT_CONTRACT.N_INSTRUMENT_SKEY WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LOG ERRORS INTO DR_ISSUE_MAPPING$ ('1776769027737_81527687_20260331_1_Job_e28ad5e868024e64834a01d24cad167e') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
