-- =====================================================================
-- Task: DERIVATIVE_INCURRED_CVA_LOSS_CALC_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.DERIVATIVE_INCURRED_CVA_LOSS_CALC_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_INCURRED_CVA_LOSS_CALC(N_RUN_SKEY,F_ORIG_EXPECTED_EXP_CALC_IND,N_CURR_EXP_MTM_VALUE,N_EXP_AGE_IN_DAYS,N_INITIAL_MARGIN_AMOUNT,N_PROJ_EXP_MTM_VALUE,N_ORIG_EXPECTED_EXP_AMOUNT,N_EXCHANGE_RATE,N_ACCT_SKEY,N_BASEL_PARTY_RATING,N_CAP_APPROACH_TYPE_SKEY,N_CAP_RECORD_TYPE_SKEY,N_COUNTERPARTY_SKEY,N_MIS_DATE_SKEY,N_NOTIONAL_AMOUNT,N_ORIGINAL_MATURITY,N_RESIDUAL_MATURITY,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_STD_COUNTERPARTY_TYPE_SKEY,V_APPROACH_TYPE,V_RECORD_TYPE,N_ORIG_EXPECTED_EXP_AMOUNT_NCY,N_PROJ_EXP_MTM_VALUE_NCY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_RUN.N_RUN_SKEY),CASE WHEN FSI_SETUP_EXPECTED_EXPOSURE.V_EXPOSURE_ID IS NULL THEN 'Y' ELSE 'N' END,0,ROUND((FSI_CAP_DERIVATIVES.N_ORIGINAL_MATURITY - FSI_CAP_DERIVATIVES.N_RESIDUAL_MATURITY)*360),STG_EXPOSURES.N_MARGIN_AMOUNT*FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE*FSI_SETUP_PROJECTED_EXPOSURE.N_PROJ_EXP_MTM_VALUE,FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE*FSI_SETUP_EXPECTED_EXPOSURE.N_EXPECTED_EXP_AMOUNT,to_char(FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE),to_char(FSI_CAP_DERIVATIVES.N_ACCT_SKEY),to_char(FSI_CAP_DERIVATIVES.N_BASEL_PARTY_RATING),to_char(FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY),to_char(FSI_CAP_DERIVATIVES.N_CAP_RECORD_TYPE_SKEY),to_char(FSI_CAP_DERIVATIVES.N_CUST_SKEY),to_char(FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY),to_char(FSI_CAP_DERIVATIVES.N_NOTIONAL_PRINCIPAL),to_char(FSI_CAP_DERIVATIVES.N_ORIGINAL_MATURITY),to_char(FSI_CAP_DERIVATIVES.N_RESIDUAL_MATURITY),to_char(FSI_CAP_DERIVATIVES.N_RUN_IDENTIFIER_SKEY),to_char(FSI_CAP_DERIVATIVES.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_CAP_DERIVATIVES.N_STD_COUNTERPARTY_TYPE_SKEY),FSI_CAP_DERIVATIVES.V_APPROACH_TYPE,FSI_CAP_DERIVATIVES.V_RECORD_TYPE,to_char(FSI_SETUP_EXPECTED_EXPOSURE.N_EXPECTED_EXP_AMOUNT),to_char(FSI_SETUP_PROJECTED_EXPOSURE.N_PROJ_EXP_MTM_VALUE) FROM FSI_CAP_DERIVATIVES LEFT OUTER JOIN DIM_RUN ON FSI_CAP_DERIVATIVES.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN RUN_EXE_PARAMETERS RUN_EXE_PARAMETERS_RCY ON RUN_EXE_PARAMETERS_RCY.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND RUN_EXE_PARAMETERS_RCY.V_PARAM_ID = 'RCY' LEFT OUTER JOIN DIM_DATES ON FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN DIM_BASEL_PRODUCT_TYPE ON DIM_BASEL_PRODUCT_TYPE.N_BASEL_PROD_TYPE_SKEY = FSI_CAP_DERIVATIVES.N_BASEL_PROD_TYPE_SKEY LEFT OUTER JOIN DIM_EXPOSURE_UNDERLYING_TYPE ON DIM_EXPOSURE_UNDERLYING_TYPE.N_UNDERLYING_TYPE_SKEY = FSI_CAP_DERIVATIVES.N_UNDERLYING_TYPE_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = FSI_CAP_DERIVATIVES.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY AND FCT_ENTITY_INFO.N_GAAP_SKEY = FSI_CAP_DERIVATIVES.N_GAAP_SKEY AND FCT_ENTITY_INFO.N_ENTITY_SKEY = FSI_CAP_DERIVATIVES.N_ENTITY_SKEY LEFT OUTER JOIN DIM_EXPOSURE ON DIM_EXPOSURE.N_ACCT_SKEY = FSI_CAP_DERIVATIVES.N_ACCT_SKEY LEFT OUTER JOIN FSI_SETUP_EXPECTED_EXPOSURE ON FSI_SETUP_EXPECTED_EXPOSURE.V_EXPOSURE_ID = DIM_EXPOSURE.V_EXPOSURE_ID LEFT OUTER JOIN FSI_SETUP_PROJECTED_EXPOSURE ON FSI_SETUP_PROJECTED_EXPOSURE.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE AND FSI_SETUP_PROJECTED_EXPOSURE.V_EXPOSURE_ID = DIM_EXPOSURE.V_EXPOSURE_ID AND FSI_SETUP_PROJECTED_EXPOSURE.V_CCY_CODE = COALESCE(FSI_SETUP_EXPECTED_EXPOSURE.V_CCY_CODE,FSI_SETUP_PROJECTED_EXPOSURE.V_CCY_CODE) AND (CASE WHEN FSI_SETUP_PROJECTED_EXPOSURE.V_PROJ_TENOR_UNIT = 'Y' THEN ADD_MONTHS(FSI_SETUP_PROJECTED_EXPOSURE.D_EFFECTIVE_DATE,FSI_SETUP_PROJECTED_EXPOSURE.N_PROJ_TENOR * 12) WHEN FSI_SETUP_PROJECTED_EXPOSURE.V_PROJ_TENOR_UNIT = 'M' THEN ADD_MONTHS(FSI_SETUP_PROJECTED_EXPOSURE.D_EFFECTIVE_DATE,FSI_SETUP_PROJECTED_EXPOSURE.N_PROJ_TENOR) WHEN FSI_SETUP_PROJECTED_EXPOSURE.V_PROJ_TENOR_UNIT = 'D' THEN FSI_SETUP_PROJECTED_EXPOSURE.D_EFFECTIVE_DATE + FSI_SETUP_PROJECTED_EXPOSURE.N_PROJ_TENOR END) = ADD_MONTHS(DIM_DATES.D_CALENDAR_DATE,12) LEFT OUTER JOIN (SELECT V_CONTRACT_CODE, V_CCY_CODE, N_MARGIN_AMOUNT FROM STG_OPTION_CONTRACTS WHERE FIC_MIS_DATE = to_date('20260331','YYYYMMDD') UNION SELECT V_CONTRACT_CODE, V_CCY_CODE, N_MARGIN_AMOUNT FROM STG_FUTURES WHERE FIC_MIS_DATE = to_date('20260331','YYYYMMDD')) STG_EXPOSURES ON STG_EXPOSURES.V_CONTRACT_CODE = DIM_EXPOSURE.V_EXPOSURE_ID LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_MIS_DATE_SKEY = FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY AND FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = FSI_CAP_DERIVATIVES.N_RUN_SKEY AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = COALESCE(FSI_SETUP_EXPECTED_EXPOSURE.V_CCY_CODE,FSI_SETUP_PROJECTED_EXPOSURE.V_CCY_CODE) WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_BASEL_PRODUCT_TYPE.V_BASEL_PROD_TYPE_CODE_LEVEL1 = 'OTD' AND FSI_CAP_DERIVATIVES.F_OTC_IND = 'Y' AND NOT ( (DIM_BASEL_PRODUCT_TYPE.V_BASEL_PROD_TYPE_CODE = 'OPT' AND COALESCE(FSI_CAP_DERIVATIVES.F_BUYER_SELLER_IND,'Z') = 'S') OR (COALESCE(DIM_EXPOSURE_UNDERLYING_TYPE.V_UNDERLYING_TYPE_CODE,'ZZZZ') = 'EXRATE' AND ROUND(FSI_CAP_DERIVATIVES.N_ORIGINAL_MATURITY * 360) <= 14) OR (COALESCE(FSI_CAP_DERIVATIVES.F_CLEARED_TRANSACTION_FLAG,'Z') = 'Y')) LOG ERRORS INTO FSI_INCURRED_CVA_LOSS_CALC$ ('1776768496722_71613003_20260331_1_Job_d29d74ab098848969acfcfcc284e35ee') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
