-- =====================================================================
-- Task: DERIVATIVES_NETTING_SET_DETAILS_DATA_POP_SACCR
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.DERIVATIVES_NETTING_SET_DETAILS_DATA_POP_SACCR(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_NETTING_AGREEMENT_DETAILS(N_MIS_DATE_SKEY,N_NETTING_AGREEMENT_SKEY,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE,N_PARTY_SKEY,N_ENTITY_SKEY,N_EXCHANGE_RATE,N_NET_EXPOSURE_AMOUNT,N_GAAP_SKEY,N_RUN_SKEY,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY),-1,'OTH',to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,to_char(FSI_CAP_DERIVATIVES.N_CUST_SKEY),to_char(FSI_CAP_DERIVATIVES.N_ENTITY_SKEY),to_char(FSI_CAP_DERIVATIVES.N_EXCHANGE_RATE),to_char(FSI_CAP_DERIVATIVES.N_EXPOSURE_AMOUNT),to_char(FSI_CAP_DERIVATIVES.N_GAAP_SKEY),to_char(FSI_CAP_DERIVATIVES.N_RUN_SKEY),FSI_CAP_DERIVATIVES.V_CCY_CODE FROM FSI_CAP_DERIVATIVES INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_DATES.N_DATE_SKEY = FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY AND FSI_CAP_DERIVATIVES.N_RUN_SKEY = '870' INNER JOIN DIM_EXPOSURE ON DIM_EXPOSURE.N_ACCT_SKEY = FSI_CAP_DERIVATIVES.N_ACCT_SKEY INNER JOIN DIM_NETTING_AGREEMENT ON DIM_NETTING_AGREEMENT.V_NETTING_AGREEMENT_CODE = 'DUMMY_NA_' || DIM_EXPOSURE.V_EXPOSURE_ID AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_NETTING_AGREEMENT.D_RECORD_START_DATE AND DIM_NETTING_AGREEMENT.D_RECORD_END_DATE INNER JOIN DIM_BASEL_METHODOLOGY DIM_EAD_APPROACH ON DIM_EAD_APPROACH.N_BASEL_METHOD_SKEY = FSI_CAP_DERIVATIVES.N_EAD_APP_SKEY INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_DERIVATIVES.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY WHERE ((1=1) AND ( FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = 'NSSTD' ) AND (9=9) AND (3=3)) AND DIM_EAD_APPROACH.V_BASEL_METHOD_CODE IN ( 'NSSTDSACCR' ,'NSAIRBSACCR' ,'NSFIRBSACCR' ) AND NOT EXISTS ( SELECT 1 FROM FSI_NETTING_AGREEMENT_DETAILS WHERE FSI_NETTING_AGREEMENT_DETAILS.N_NETTING_AGREEMENT_SKEY = DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_RUN_SKEY = FSI_CAP_DERIVATIVES.N_RUN_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_GAAP_SKEY = FSI_CAP_DERIVATIVES.N_GAAP_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_MIS_DATE_SKEY = FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY ) LOG ERRORS INTO FSI_NETTING_AGREEMENT_DETAILS$ ('1776769259240_36509548_20260331_1_Job_f2f0ef6638564521babfe0f2f926e9e7') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
