-- =====================================================================
-- Task: DERIVATIVE_FCT_SOLD_CDP_DATA_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.DERIVATIVE_FCT_SOLD_CDP_DATA_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_SCP_UNDERLYING(N_RUN_IDENTIFIER_SKEY,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE,F_EQUITY_TRADED_FLAG,F_EXP_DEFAULTED_FLAG,F_NETTABILITY_FLAG,F_SECURITIZED_FLAG,N_ACCT_SKEY,N_ADJUSTED_LGD_PERCENT,N_BASEL_ASSET_CLASS_SKEY,N_BASEL_METHOD_SKEY,N_BASEL_PROD_TYPE_SKEY,N_BRANCH_SKEY,N_CUST_TYPE_SKEY,N_COUNTRY_SKEY,N_CUST_SKEY,N_DELQ_DAYS,N_EAD_PRE_MITIGATION,N_EL_AMOUNT,N_EXPOSURE_AMOUNT,N_GAAP_SKEY,N_LOB_SKEY,N_MIS_DATE_SKEY,N_NOTIONAL_PRINCIPAL,N_PARENT_ACCT_SKEY,N_PD_PERCENT,N_POST_MITIGATION_CAPITAL_UL,N_PRE_MITIGATION_CAPITAL_UL,N_PRE_MITIGATION_EL_AMT,N_PRE_MITIGATION_RWA_UL,N_PRE_MITIGATION_RW_UL,N_PROD_SKEY,N_PROVISION_AMOUNT,N_RESIDUAL_MATURITY,N_RUN_SKEY,N_RWA_EL_AMT,N_RWA_UL_AMT,N_SEC_POOL_SKEY,N_STD_ACCT_HEAD_SKEY,N_BASEL_CUST_TYPE_SKEY,N_WRITE_OFF_AMT,V_CCY_CODE,V_PRODUCT_BOOK_CODE,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE,N_RUN_PARAMETER_SETUP_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_RUN_IDENTIFIER.N_RUN_IDENTIFIER_SKEY),to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,FSI_CAP_DERIVATIVES.F_EQUITY_TRADED_FLAG,FSI_CAP_DERIVATIVES.F_EXP_DEFAULTED_FLAG,FSI_CAP_DERIVATIVES.F_NETTABILITY_FLAG,FSI_CAP_DERIVATIVES.F_SECURITIZED_FLAG,to_char(FSI_CAP_DERIVATIVES.N_ACCT_SKEY),to_char(FSI_CAP_DERIVATIVES.N_ADJUSTED_LGD_PERCENT),to_char(FSI_CAP_DERIVATIVES.N_BASEL_ASSET_CLASS_SKEY),to_char(FSI_CAP_DERIVATIVES.N_BASEL_METHOD_SKEY),to_char(FSI_CAP_DERIVATIVES.N_BASEL_PROD_TYPE_SKEY),to_char(FSI_CAP_DERIVATIVES.N_BRANCH_SKEY),to_char(FSI_CAP_DERIVATIVES.N_COUNTERPARTY_TYPE_SKEY),to_char(FSI_CAP_DERIVATIVES.N_COUNTRY_SKEY),to_char(FSI_CAP_DERIVATIVES.N_CUST_SKEY),to_char(FSI_CAP_DERIVATIVES.N_DELQ_DAYS),to_char(FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION),to_char(FSI_CAP_DERIVATIVES.N_EL_AMOUNT),to_char(FSI_CAP_DERIVATIVES.N_EXPOSURE_AMOUNT),to_char(FSI_CAP_DERIVATIVES.N_GAAP_SKEY),to_char(FSI_CAP_DERIVATIVES.N_LOB_SKEY),to_char(FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY),to_char(FSI_CAP_DERIVATIVES.N_NOTIONAL_PRINCIPAL),to_char(FSI_CAP_DERIVATIVES.N_PARENT_ACCT_SKEY),to_char(FSI_CAP_DERIVATIVES.N_PD_PERCENT),to_char(FSI_CAP_DERIVATIVES.N_POST_MITIGATION_CAPITAL_UL),to_char(FSI_CAP_DERIVATIVES.N_PRE_MITIGATION_CAPITAL_UL),to_char(FSI_CAP_DERIVATIVES.N_PRE_MITIGATION_EL_AMT),to_char(FSI_CAP_DERIVATIVES.N_PRE_MITIGATION_RWA_UL),to_char(FSI_CAP_DERIVATIVES.N_PRE_MITIGATION_RW_UL),to_char(FSI_CAP_DERIVATIVES.N_PROD_SKEY),to_char(FSI_CAP_DERIVATIVES.N_PROVISION_AMOUNT),to_char(FSI_CAP_DERIVATIVES.N_RESIDUAL_MATURITY),to_char(FSI_CAP_DERIVATIVES.N_RUN_SKEY),to_char(FSI_CAP_DERIVATIVES.N_RWA_EL_AMT),to_char(FSI_CAP_DERIVATIVES.N_RWA_UL_AMT),to_char(FSI_CAP_DERIVATIVES.N_SEC_POOL_SKEY),to_char(FSI_CAP_DERIVATIVES.N_STD_ACCT_HEAD_SKEY),to_char(FSI_CAP_DERIVATIVES.N_STD_COUNTERPARTY_TYPE_SKEY),to_char(FSI_CAP_DERIVATIVES.N_WRITE_OFF_AMT),FSI_CAP_DERIVATIVES.V_CCY_CODE,FSI_CAP_DERIVATIVES.V_PRODUCT_BOOK_CODE,to_char(FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY),FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE,to_char(RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY) FROM FSI_CAP_DERIVATIVES INNER JOIN DIM_DATES ON FSI_CAP_DERIVATIVES.n_mis_date_skey = DIM_DATES.n_date_skey LEFT OUTER JOIN DIM_RUN ON DIM_RUN.n_run_skey = '870' LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON DIM_RUN_IDENTIFIER.n_run_identifier_skey = FSI_CAP_DERIVATIVES.n_run_identifier_skey LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON DIM_RUN.N_RUN_SKEY = FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'NONSEC' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND RUN_PARAMETERS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_DERIVATIVES.N_CAP_RECORD_TYPE_SKEY WHERE ((1=1) AND ( FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'DRV_NON_SEC_EXP' ) AND ( FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = 'NSSTD' ) AND (9=9) AND (3=3)) AND 1=1 AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND FSI_CAP_DERIVATIVES.n_run_skey = '870' AND v_underlying_data_identifier ='SCP' LOG ERRORS INTO FCT_SCP_UNDERLYING$ ('1776769094172_7924879_20260331_1_Job_c095c3b99bf44bd2b90c3904123394ff') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
