-- =====================================================================
-- Task: ENTITY_SHR_HLD_PERCENT_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.ENTITY_SHR_HLD_PERCENT_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_ENTITY_SHR_HLD_PERCENT(N_MIS_DATE_SKEY,N_INVESTEE_ENTITY_SKEY,N_INVESTOR_ENTITY_SKEY,N_RUN_SKEY,N_EXCHANGE_RATE,F_THIRDPARTY_MINORITY_HOLD_IND,N_CONSOLIDATED_ASSETS_NCY,N_SHAREHOLDING_PERCENT,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_ORG_STRUCTURE.N_ENTITY_SKEY),A.N_ENTITY_SKEY,'870',to_char(FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE),STG_ENTITY_SHR_HLD_PERCENT.F_THIRDPARTY_MINORITY_HOLD_IND,to_char(STG_ENTITY_SHR_HLD_PERCENT.N_CONSOLIDATED_ASSETS),to_char(STG_ENTITY_SHR_HLD_PERCENT.N_SHAREHOLDING_PERCENT),STG_ENTITY_SHR_HLD_PERCENT.V_CCY_CODE FROM STG_ENTITY_SHR_HLD_PERCENT INNER JOIN DIM_DATES ON STG_ENTITY_SHR_HLD_PERCENT.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE AND STG_ENTITY_SHR_HLD_PERCENT.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_ORG_STRUCTURE ON STG_ENTITY_SHR_HLD_PERCENT.V_INVESTEE_ENTITY_CODE = DIM_ORG_STRUCTURE.V_ENTITY_CODE AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_ORG_STRUCTURE.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_ORG_STRUCTURE.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = '870' AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_ENTITY_SHR_HLD_PERCENT.V_CCY_CODE LEFT OUTER JOIN DIM_ORG_STRUCTURE A ON STG_ENTITY_SHR_HLD_PERCENT.V_INVESTOR_ENTITY_CODE = A.V_ENTITY_CODE AND to_date('20260331','YYYYMMDD') BETWEEN A.D_RECORD_START_DATE AND A.D_RECORD_END_DATE WHERE 1=1 AND 1=1 LOG ERRORS INTO FCT_ENTITY_SHR_HLD_PERCENT$ ('1776767948420_81399127_20260331_1_Job_e92c41c62d144c07b83cefe0ea4b06a1') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
