-- =====================================================================
-- Task: EQ_ARBITRAGE_STRGY_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.EQ_ARBITRAGE_STRGY_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into EQ_ARBITRAGE_STRGY_MAPPING(N_MIS_DATE_SKEY,N_INDX_FUT_SKEY,N_RUN_SKEY,N_STCK_INDX_FUT_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),(SELECT DIM_EXPOSURE.n_acct_skey FROM DIM_EXPOSURE WHERE DIM_EXPOSURE.v_exposure_id = STG_EQ_ARBITRAGE_STRGY_MAPPING.v_indx_fut_code AND STG_EQ_ARBITRAGE_STRGY_MAPPING.FIC_MIS_DATE BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE),'870',(SELECT DIM_EXPOSURE.n_acct_skey FROM DIM_EXPOSURE WHERE DIM_EXPOSURE.v_exposure_id = STG_EQ_ARBITRAGE_STRGY_MAPPING.v_stck_indx_fut_code AND STG_EQ_ARBITRAGE_STRGY_MAPPING.FIC_MIS_DATE BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE) FROM STG_EQ_ARBITRAGE_STRGY_MAPPING INNER JOIN DIM_DATES ON STG_EQ_ARBITRAGE_STRGY_MAPPING.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE INNER JOIN DIM_INSTRUMENT_CONTRACT ON DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE = STG_EQ_ARBITRAGE_STRGY_MAPPING.V_INDX_FUT_CODE AND STG_EQ_ARBITRAGE_STRGY_MAPPING.FIC_MIS_DATE BETWEEN DIM_INSTRUMENT_CONTRACT.D_RECORD_START_DATE AND DIM_INSTRUMENT_CONTRACT.D_RECORD_END_DATE INNER JOIN FCT_MARKET_RISK_EXPOSURES ON FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey = DIM_DATES.N_DATE_SKEY AND FCT_MARKET_RISK_EXPOSURES.N_ACCT_SKEY = DIM_INSTRUMENT_CONTRACT.N_INSTRUMENT_SKEY WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LOG ERRORS INTO EQ_ARBITRAGE_STRGY_MAPPING$ ('1776769072243_97598407_20260331_1_Job_ce6997c67055441c92093fdfaff2524b') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
