-- =====================================================================
-- Task: EXCHANGE_RATE_DATA_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.EXCHANGE_RATE_DATA_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_EXCHANGE_RATES(N_RUN_SKEY,FIC_MIS_DATE,N_EXCHANGE_RATE,N_MAX_ANNUAL_VOLATILITY_RATE,N_TENOR,V_FROM_CCY_CODE,V_RATE_DATA_SOURCE_CD,V_TO_CCY_CODE)SELECT  /*+PARALLEL (4)*/ '870',FSI_EXCHANGE_RATES.FIC_MIS_DATE,to_char(FSI_EXCHANGE_RATES.N_EXCHANGE_RATE),to_char(FSI_EXCHANGE_RATES.N_MAX_ANNUAL_VOLATILITY_RATE),to_char(FSI_EXCHANGE_RATES.N_TENOR),FSI_EXCHANGE_RATES.V_FROM_CCY_CODE,FSI_EXCHANGE_RATES.V_RATE_DATA_SOURCE_CD,FSI_EXCHANGE_RATES.V_TO_CCY_CODE FROM FSI_EXCHANGE_RATES WHERE 1=1 AND FSI_EXCHANGE_RATES.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND FSI_EXCHANGE_RATES.N_RUN_SKEY = -1 LOG ERRORS INTO FSI_EXCHANGE_RATES$ ('1776767921973_37098754_20260331_1_Job_4a393ec8436649c7a2bb0f516d34655e') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
