-- =====================================================================
-- Task: FCT_REFERENCE_ISSUE_DATA_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FCT_REFERENCE_ISSUE_DATA_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_REFERENCE_ISSUE(N_MIS_DATE_SKEY,N_ISSUE_SKEY,N_ISSUER_SKEY,N_ORIGINAL_MATURITY,N_RESIDUAL_MATURITY,N_RUN_SKEY,N_STD_SENIORITY_SKEY,N_ISSUE_SENIORITY,V_CCY_CODE,V_ISSUE_ID)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_ISSUE.N_ISSUE_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),DAYS_BETWEEN(STG_ISSUE_DETAILS.D_START_DATE,STG_ISSUE_DETAILS.D_ORIG_MATURITY_DATE),DAYS_BETWEEN(STG_ISSUE_DETAILS.FIC_MIS_DATE,STG_ISSUE_DETAILS.D_MATURITY_DATE),'870',to_char(FSI_SENIORITY_RECLASSIFICATION.N_STD_SENIORITY_SKEY),to_char(STG_ISSUE_DETAILS.N_ISSUE_SENIORITY),STG_ISSUE_DETAILS.V_CCY_CODE,STG_ISSUE_DETAILS.V_ISSUE_ID FROM STG_ISSUE_DETAILS INNER JOIN DIM_DATES ON STG_ISSUE_DETAILS.fic_mis_date = DIM_DATES.d_calendar_date LEFT OUTER JOIN DIM_PARTY ON STG_ISSUE_DETAILS.V_ISSUER_CODE = DIM_PARTY.v_party_id LEFT OUTER JOIN DIM_ISSUE ON STG_ISSUE_DETAILS.V_ISSUE_id = DIM_ISSUE.v_issue_code LEFT OUTER JOIN FSI_SENIORITY_RECLASSIFICATION ON FSI_SENIORITY_RECLASSIFICATION.N_SENIORITY = STG_ISSUE_DETAILS.N_ISSUE_SENIORITY AND FSI_SENIORITY_RECLASSIFICATION.N_RUN_SKEY = '870' AND FSI_SENIORITY_RECLASSIFICATION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY WHERE 1=1 AND 1=1 AND STG_ISSUE_DETAILS.fic_mis_date = to_date('20260331','YYYYMMDD') AND STG_ISSUE_DETAILS.fic_mis_date BETWEEN coalesce(DIM_ISSUE.d_record_start_date, STG_ISSUE_DETAILS.fic_mis_date) AND coalesce(DIM_ISSUE.d_record_end_date, STG_ISSUE_DETAILS.fic_mis_date) AND STG_ISSUE_DETAILS.fic_mis_date BETWEEN coalesce(DIM_PARTY.d_record_start_date, STG_ISSUE_DETAILS.fic_mis_date) AND coalesce(DIM_PARTY.d_record_end_date, STG_ISSUE_DETAILS.fic_mis_date) LOG ERRORS INTO FCT_REFERENCE_ISSUE$ ('1776768203826_13579265_20260331_1_Job_335b5af8df68495a8a5a3a0bf58cf302') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
