-- =====================================================================
-- Task: FIXED_ASSET_PROD_TYPE_RECLASS_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FIXED_ASSET_PROD_TYPE_RECLASS_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_FXD_ASST_PROD_TYPE_RECLASS(N_MIS_DATE_SKEY,N_FIXED_ASSET_TYPE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_FIXED_ASSETS_TYPE.N_FIXED_ASSET_TYPE_SKEY),to_char(DIM_RUN.N_RUN_SKEY) FROM DIM_FIXED_ASSETS_TYPE INNER JOIN DIM_DATES ON 1 = 1 INNER JOIN DIM_RUN ON 1 = 1 WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE BETWEEN COALESCE(DIM_FIXED_ASSETS_TYPE.D_RECORD_START_DATE, DIM_DATES.D_CALENDAR_DATE) AND COALESCE(DIM_FIXED_ASSETS_TYPE.D_RECORD_END_DATE, DIM_DATES.D_CALENDAR_DATE) AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY = '870' LOG ERRORS INTO FSI_FXD_ASST_PROD_TYPE_RECLAS$ ('1776767917834_48762852_20260331_1_Job_cfd6408dc1714d4e940e7f25988d6269') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
