-- =====================================================================
-- Task: Forex_Position_Other_Attribute_Natural_CCY_Conversion_to_Reporting_CCY
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Forex_Position_Other_Attribute_Natural_CCY_Conversion_to_Reporting_CCY(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_MARKET_RISK_FOREX TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_MARKET_RISK_FOREX.V_CCY_CODE,FCT_MARKET_RISK_FOREX.N_RUN_SKEY,FCT_MARKET_RISK_FOREX.N_REP_LINE_SKEY,FCT_MARKET_RISK_FOREX.N_COUNTRY_SKEY,FCT_MARKET_RISK_FOREX.N_MIS_DATE_SKEY,FCT_MARKET_RISK_FOREX.N_GAAP_SKEY,FCT_MARKET_RISK_FOREX.N_ENTITY_SKEY,(FCT_MARKET_RISK_FOREX.N_IRRECOVERABLE_GUARANTEE_AMT) AS  T_1354584278803_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1354584278803_10 ,  (CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_FOREX.n_irrecoverable_guar_amt_ncy ELSE NULL END  * CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_FOREX.n_exchange_rate ELSE NULL END ) AS EXP_1354584278803_10,(FCT_MARKET_RISK_FOREX.N_IRRECOVERABLE_GUARANTEE_AMT) AS EXP_1354584278803_11 ,(FCT_MARKET_RISK_FOREX.N_NET_FUTURE_INEXP_HEDGE) AS  T_1354584278803_1,   (CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1354584278803_20 ,  (CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_FOREX.n_net_future_inexp_hedge_ncy ELSE NULL END  * CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_FOREX.n_exchange_rate ELSE NULL END ) AS EXP_1354584278803_20,(FCT_MARKET_RISK_FOREX.N_NET_FUTURE_INEXP_HEDGE) AS EXP_1354584278803_21 ,(FCT_MARKET_RISK_FOREX.N_NET_FORWARD_POSITION_AMT) AS  T_1354584278803_2,   (CASE  WHEN  ( ((1=1)) ) THEN 30 ELSE 31 END)  AS COND_1354584278803_30 ,  (CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_FOREX.n_net_forward_position_amt_ncy ELSE NULL END  * CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_FOREX.n_exchange_rate ELSE NULL END ) AS EXP_1354584278803_30,(FCT_MARKET_RISK_FOREX.N_NET_FORWARD_POSITION_AMT) AS EXP_1354584278803_31  FROM  FCT_MARKET_RISK_FOREX LEFT OUTER JOIN DIM_MARKET_RISK_REP_LINE ON FCT_MARKET_RISK_FOREX.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE.n_rep_line_skey LEFT OUTER JOIN DIM_DATES ON FCT_MARKET_RISK_FOREX.n_mis_date_skey = DIM_DATES.n_date_skey LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_FOREX.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_FOREX.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_FOREX.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_CURRENCY ON FCT_MARKET_RISK_FOREX.v_ccy_code = DIM_CURRENCY.v_Iso_Currency_Cd LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON FCT_MARKET_RISK_FOREX.n_run_identifier_skey = DIM_RUN_IDENTIFIER.n_run_identifier_skey LEFT OUTER JOIN RUN_PARAMETERS ON FCT_MARKET_RISK_FOREX.n_run_parameter_setup_skey = RUN_PARAMETERS.n_run_parameter_setup_skey AND RUN_PARAMETERS.n_Run_Skey=FCT_MARKET_RISK_FOREX.n_Run_Skey AND RUN_PARAMETERS.n_Date_Skey=FCT_MARKET_RISK_FOREX.n_Mis_Date_Skey  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  ) WHERE (   (COND_1354584278803_10 <> 11)   OR  (COND_1354584278803_20 <> 21)  OR  (COND_1354584278803_30 <> 31) ) ) SS ON ( TT.V_CCY_CODE= SS.V_CCY_CODE AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_REP_LINE_SKEY= SS.N_REP_LINE_SKEY AND TT.N_COUNTRY_SKEY= SS.N_COUNTRY_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_IRRECOVERABLE_GUARANTEE_AMT=  CASE  WHEN  COND_1354584278803_10=10 THEN EXP_1354584278803_10 ELSE EXP_1354584278803_11 END  , TT.N_NET_FUTURE_INEXP_HEDGE=  CASE  WHEN  COND_1354584278803_20=20 THEN EXP_1354584278803_20 ELSE EXP_1354584278803_21 END  , TT.N_NET_FORWARD_POSITION_AMT=  CASE  WHEN  COND_1354584278803_30=30 THEN EXP_1354584278803_30 ELSE EXP_1354584278803_31 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
