-- =====================================================================
-- Task: FSI_SENIORITY_RECLASSIFICATION_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FSI_SENIORITY_RECLASSIFICATION_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_SENIORITY_RECLASSIFICATION(N_MIS_DATE_SKEY,N_SENIORITY,N_RUN_SKEY,V_RECLASS_TYPE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_EXPOSURE_SENIORITY.N_EXP_SENIORITY),'870','DEFAULT' FROM DIM_EXPOSURE_SENIORITY INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') WHERE 1=1 AND to_date('20260331','YYYYMMDD') BETWEEN DIM_EXPOSURE_SENIORITY.D_RECORD_START_DATE AND DIM_EXPOSURE_SENIORITY.D_RECORD_END_DATE LOG ERRORS INTO FSI_SENIORITY_RECLASSIFICATIO$ ('1776767882331_59921230_20260331_1_Job_dae21901f04a4e54bb6705515acc4f89') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
