-- =====================================================================
-- Task: FSI_REG_INDUSTRY_RECLASS_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FSI_REG_INDUSTRY_RECLASS_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_REG_INDUSTRY_RECLASS(N_MIS_DATE_SKEY,N_D_CUST_INDUSTRY_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_INDUSTRY.N_D_CUST_INDUSTRY_SKEY),'870' FROM DIM_INDUSTRY INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') WHERE 1=1 AND to_date('20260331','YYYYMMDD') BETWEEN DIM_INDUSTRY.D_RECORD_START_DATE AND DIM_INDUSTRY.D_RECORD_END_DATE LOG ERRORS INTO FSI_REG_INDUSTRY_RECLASS$ ('1776767900033_99685686_20260331_1_JOB_16310773266725') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
