-- =====================================================================
-- Task: FSI_OPTIMIZER_PROCESSING_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FSI_OPTIMIZER_PROCESSING_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_OPTIMIZER_PROCESSING(N_ACCT_MITIGANT_GROUP_SKEY,N_DM_MITIGANT_SKEY,N_EAD_PRE_MITIGATION,N_EXP_COVERED_FACTOR,N_NET_MITIGANT_VALUE,F_PAST_DUE_FLAG,N_ALLOCATION_RANK,N_BASEL_ASSET_CLASS_SKEY,N_BASEL_PROD_TYPE_SKEY,N_CAPITAL_UL,N_COUNTRY_SKEY,N_DM_FOREX_HARICUT,N_DM_MATURITY_MISMATCH_HAIRCUT,N_DM_VOLATILITY_HAIRCUT,N_EXPOSURE_CONS_COEFF,N_FOREX_HAIRCUT,N_INTEGER_VAR_REFERENCE,N_ISSUER_SKEY,N_MATURITY_MISMATCH_HAIRCUT,N_MIN_COLL_CHECK_NUMERATOR,N_MITIGANT_VALUE,N_PD_PERCENT,N_POOL_ID,N_RISK_WEIGHT,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_STD_MITIGANT_TYPE_SKEY,N_UNCOVERED_AMOUNT,N_VOLATILITY_HAIRCUT,V_EXPOSURE_TYPE,V_EXP_MIT_POOL_CARDINALITY,F_DRAWN_EXP_FLAG,F_DRAWN_UNDRAWN_IND,N_ACCT_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_MITIGANT_SKEY,N_MTG_TREATMENT_TYPE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ DENSE_RANK() OVER ( ORDER BY FSI_OPT_EXPOSURE_MAPPING.N_EXP_SKEY, FSI_OPT_EXPOSURE_MAPPING.N_MIT_SKEY, CASE WHEN DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_TYPE_CODE<> 'UNCOV' THEN NULL ELSE DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_TYPE_CODE END DESC NULLS LAST ),FSI_OPT_EXPOSURE_MAPPING.N_DM_MITIGANT_SKEY,COALESCE(CASE WHEN FSI_OPT_EXPOSURE_MAPPING.F_DRAWN_UNDRAWN_IND ='D' THEN FSI_CAP_SUB_EXPOSURES.N_EAD_PRE_MITIGATION_DRAWN ELSE FSI_CAP_SUB_EXPOSURES.N_EAD_PRE_MITIGATION_UNDRAWN END,0),CASE WHEN FSI_RUN_PARAMETER.V_OPTIMIZER_ALLOCATION_BASIS = 'OPTALLOC2' THEN CASE WHEN DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_TYPE_CODE <> 'UNCOV' AND COALESCE(COALESCE(FSI_CAP_SUB_EXPOSURES.N_EXPECTED_LGD_PERCENT, FSI_CAP_SUB_EXPOSURES.N_CCF_PERCENT), 1) = 0 THEN 0 END END,COALESCE( CASE WHEN DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_TYPE_CODE <> 'UNCOV' THEN FSI_CAP_SUB_EXPOSURES.N_NET_MITIGANT_VALUE WHEN FSI_OPT_EXPOSURE_MAPPING.F_DRAWN_UNDRAWN_IND='D' THEN FSI_CAP_SUB_EXPOSURES.N_EAD_PRE_MITIGATION_DRAWN ELSE FSI_CAP_SUB_EXPOSURES.N_EAD_PRE_MITIGATION_UNDRAWN END ,0),FSI_CAP_SUB_EXPOSURES.F_PAST_DUE_FLAG,to_char(FSI_CAP_SUB_EXPOSURES.N_ALLOCATION_RANK),to_char(FSI_CAP_SUB_EXPOSURES.N_BASEL_ASSET_CLASS_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_BASEL_PROD_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_CAPITAL_UL),to_char(FSI_CAP_SUB_EXPOSURES.N_COUNTRY_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_DM_FOREX_HARICUT),to_char(FSI_CAP_SUB_EXPOSURES.N_DM_MATURITY_MISMATCH_HAIRCUT),to_char(FSI_CAP_SUB_EXPOSURES.N_DM_VOLATILITY_HAIRCUT),to_char(FSI_CAP_SUB_EXPOSURES.N_EXPOSURE_CONS_COEFF),to_char(FSI_CAP_SUB_EXPOSURES.N_FOREX_HAIRCUT),to_char(FSI_CAP_SUB_EXPOSURES.N_INTEGER_VAR_REFERENCE),to_char(FSI_CAP_SUB_EXPOSURES.N_ISSUER_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_MATURITY_MISMATCH_HAIRCUT),to_char(FSI_CAP_SUB_EXPOSURES.N_MIN_COLL_CHECK_NUMERATOR),to_char(FSI_CAP_SUB_EXPOSURES.N_MITIGANT_VALUE),to_char(FSI_CAP_SUB_EXPOSURES.N_PD_PERCENT),to_char(FSI_CAP_SUB_EXPOSURES.N_POOL_ID),to_char(FSI_CAP_SUB_EXPOSURES.N_RISK_WEIGHT),to_char(FSI_CAP_SUB_EXPOSURES.N_RUN_IDENTIFIER_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_STD_MITIGANT_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_UNCOVERED_AMOUNT),to_char(FSI_CAP_SUB_EXPOSURES.N_VOLATILITY_HAIRCUT),FSI_CAP_SUB_EXPOSURES.V_EXPOSURE_TYPE,FSI_CAP_SUB_EXPOSURES.V_EXP_MIT_POOL_CARDINALITY,FSI_OPT_EXPOSURE_MAPPING.F_DRAWN_EXP_FLAG,FSI_OPT_EXPOSURE_MAPPING.F_DRAWN_UNDRAWN_IND,to_char(FSI_OPT_EXPOSURE_MAPPING.N_EXP_SKEY),to_char(FSI_OPT_EXPOSURE_MAPPING.N_GAAP_SKEY),to_char(FSI_OPT_EXPOSURE_MAPPING.N_MIS_DATE_SKEY),to_char(FSI_OPT_EXPOSURE_MAPPING.N_MIT_SKEY),to_char(FSI_OPT_EXPOSURE_MAPPING.N_MTG_TREATMENT_TYPE_SKEY),to_char(FSI_OPT_EXPOSURE_MAPPING.N_RUN_SKEY) FROM FSI_OPT_EXPOSURE_MAPPING INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_OPT_EXPOSURE_MAPPING.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_OPT_EXPOSURE_MAPPING.N_MIS_DATE_SKEY INNER JOIN FSI_CAP_SUB_EXPOSURES ON FSI_OPT_EXPOSURE_MAPPING.F_DRAWN_EXP_FLAG = FSI_CAP_SUB_EXPOSURES.F_DRAWN_EXP_FLAG AND FSI_OPT_EXPOSURE_MAPPING.N_DM_MITIGANT_SKEY = FSI_CAP_SUB_EXPOSURES.N_DM_MITIGANT_SKEY AND FSI_OPT_EXPOSURE_MAPPING.N_MITIGANT_SKEY = FSI_CAP_SUB_EXPOSURES.N_MITIGANT_SKEY AND FSI_OPT_EXPOSURE_MAPPING.N_ACCT_SKEY = FSI_CAP_SUB_EXPOSURES.N_ACCT_SKEY AND FSI_OPT_EXPOSURE_MAPPING.N_RUN_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY AND FSI_OPT_EXPOSURE_MAPPING.N_MTG_TREATMENT_TYPE_SKEY = FSI_CAP_SUB_EXPOSURES.N_MTG_TREATMENT_TYPE_SKEY AND FSI_OPT_EXPOSURE_MAPPING.N_GAAP_SKEY = FSI_CAP_SUB_EXPOSURES.N_GAAP_SKEY AND FSI_OPT_EXPOSURE_MAPPING.N_MIS_DATE_SKEY = FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY AND FSI_CAP_SUB_EXPOSURES.F_ELIGIBILITY_FLAG = 'Y' LEFT OUTER JOIN DIM_STD_MITIGANT_TYPE ON FSI_OPT_EXPOSURE_MAPPING.N_STD_MITIGANT_TYPE_SKEY = DIM_STD_MITIGANT_TYPE.N_STD_MITIGANT_TYPE_SKEY LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY AND FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE=to_date('20260331','YYYYMMDD') AND DIM_RUN.n_run_skey = '870' AND FSI_CAP_SUB_EXPOSURES.V_EXP_MIT_POOL_CARDINALITY IN ('1-1', '1-N', 'N-1', 'N-N') LOG ERRORS INTO FSI_OPTIMIZER_PROCESSING$ ('1776770323993_69095083_20260331_1_JOB_1615362755074') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
