-- =====================================================================
-- Task: FSI_OPTMIZER_EXPOSURE_MAPPING_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FSI_OPTMIZER_EXPOSURE_MAPPING_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_OPT_EXPOSURE_MAPPING(F_DRAWN_UNDRAWN_IND,N_EXP_MAP_SKEY,N_EXP_SKEY,N_MIT_SKEY,F_DRAWN_EXP_FLAG,N_ACCT_SKEY,N_DM_MITIGANT_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_MITIGANT_SKEY,N_MTG_TREATMENT_TYPE_SKEY,N_RUN_SKEY,N_STD_MITIGANT_TYPE_SKEY)SELECT  /*+PARALLEL (4)*/ F_DRAWN_UNDRAWN.F_DRAWN_UNDRAWN_IND,ROWNUM,DENSE_RANK()  OVER   ( ORDER BY FSI_CAP_SUB_EXPOSURES.N_ACCT_SKEY, F_DRAWN_UNDRAWN.F_DRAWN_UNDRAWN_IND DESC NULLS LAST),DENSE_RANK()  OVER   ( ORDER BY FSI_CAP_SUB_EXPOSURES.N_mitigant_SKEY  , FSI_CAP_SUB_EXPOSURES.N_STD_MITIGANT_TYPE_SKEY    ,  case when  dim_std_mitigant_type.v_STD_MITIGANT_TYPE_code<> 'UNCOV' then null else  F_DRAWN_UNDRAWN.F_DRAWN_UNDRAWN_IND end DESC NULLS LAST),FSI_CAP_SUB_EXPOSURES.F_DRAWN_EXP_FLAG,to_char(FSI_CAP_SUB_EXPOSURES.N_ACCT_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_DM_MITIGANT_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_GAAP_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_MITIGANT_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_MTG_TREATMENT_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_STD_MITIGANT_TYPE_SKEY) FROM FSI_CAP_SUB_EXPOSURES inner join dim_run on dim_run.n_run_skey = FSI_CAP_SUB_EXPOSURES.n_run_skey inner join dim_dates on dim_dates.n_date_skey = FSI_CAP_SUB_EXPOSURES.n_mis_date_skey  left outer join dim_std_mitigant_type on FSI_CAP_SUB_EXPOSURES.N_STD_MITIGANT_TYPE_SKEY=dim_std_mitigant_type.N_STD_MITIGANT_TYPE_SKEY, (select  'D' F_DRAWN_UNDRAWN_IND from dual union select 'U' from dual ) F_DRAWN_UNDRAWN WHERE 1=1 AND FSI_CAP_SUB_EXPOSURES.V_EXP_MIT_POOL_CARDINALITY IN ('1-1', '1-N', 'N-1', 'N-N') and DIM_DATES.D_CALENDAR_DATE=to_date('20260331','YYYYMMDD') AND DIM_RUN.n_run_skey = '870' AND FSI_CAP_SUB_EXPOSURES.F_ELIGIBILITY_FLAG = 'Y' AND FSI_CAP_SUB_EXPOSURES.V_EXPOSURE_TYPE='NON-SEC' LOG ERRORS INTO FSI_OPT_EXPOSURE_MAPPING$ ('1776770313943_17352816_20260331_1_JOB_16153625400320') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
