-- =====================================================================
-- Task: FSI_STD_CAPITAL_ACCT_HEAD_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FSI_STD_CAPITAL_ACCT_HEAD_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_CAPITAL_ACCT_HEAD(N_CAPITAL_ACCT_HEAD_SKEY,N_MIS_DATE_SKEY,N_GAAP_SKEY,N_RUN_SKEY,V_JURISDICTION_CODE,N_STD_ACCT_HEAD_SKEY,F_GL_IDENTIFIER,N_CAPITAL_ACCT_HEAD_AMT,N_CAP_COMP_GROUP_SKEY,N_SHAREHOLDING_PERCENT,N_ENTITY_SKEY,N_EXCHANGE_RATE,F_CONSOLIDATION_FLAG,N_CAPITAL_ACCT_HEAD_AMT_NCY,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_RUN.N_RUN_SKEY),DIM_RUN.V_JURISDICTION_CODE,to_char(DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),'N',FSI_STANDARD_ACCT_HEAD.N_AMOUNT*FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,CASE WHEN DIM_BASEL_CAP_CONSL_APPR.v_basel_cap_consl_appr_code IN ('FLCS', 'FAGR') THEN 1 ELSE FCT_ENTITY_INFO.n_shareholding_percent END,to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),to_char(FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE),FSI_STANDARD_ACCT_HEAD.F_CONSOLIDATION_FLAG,to_char(FSI_STANDARD_ACCT_HEAD.N_AMOUNT),FSI_STANDARD_ACCT_HEAD.V_CCY_CODE FROM FSI_STANDARD_ACCT_HEAD LEFT JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = FSI_STANDARD_ACCT_HEAD.FIC_MIS_DATE INNER JOIN ( FCT_ENTITY_INFO LEFT JOIN DIM_BASEL_CAP_CONSL_APPR ON FCT_ENTITY_INFO.N_BASEL_CAP_CONSL_APPR_SKEY = DIM_BASEL_CAP_CONSL_APPR.N_BASEL_CAP_CONSL_APPR_SKEY ) ON FCT_ENTITY_INFO.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND FCT_ENTITY_INFO.V_ENTITY_CODE = FSI_STANDARD_ACCT_HEAD.V_LV_CODE LEFT JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY INNER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY = FCT_ENTITY_INFO.N_BASEL_CONSL_OPTN_TYPE_SKEY INNER JOIN DIM_CAPITAL_ACCT_HEAD ON DIM_CAPITAL_ACCT_HEAD.V_CAPITAL_ACCOUNT_IDENTIFIER = FSI_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_ACCT_HEAD.D_RECORD_START_DATE AND DIM_CAPITAL_ACCT_HEAD.D_RECORD_END_DATE INNER JOIN DIM_GAAP ON DIM_GAAP.V_GAAP_CODE = FSI_STANDARD_ACCT_HEAD.V_GAAP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE LEFT JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND DIM_RUN.N_RUN_SKEY = FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = FSI_STANDARD_ACCT_HEAD.V_CCY_CODE LEFT JOIN FSI_CAP_STD_ACCT_HEAD_RECLASS ON FSI_CAP_STD_ACCT_HEAD_RECLASS.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_STD_ACCT_HEAD_RECLASS.N_RUN_SKEY = '870' AND FSI_CAP_STD_ACCT_HEAD_RECLASS.N_CAPITAL_ACCT_HEAD_SKEY = DIM_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_SKEY LEFT JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FSI_CAP_STD_ACCT_HEAD_RECLASS.N_STD_ACCT_HEAD_SKEY LEFT JOIN FSI_SETUP_CAPITAL_SOURCE ON FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE = DIM_RUN.V_JURISDICTION_CODE AND FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID LEFT JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE WHERE 1=1 AND FSI_STANDARD_ACCT_HEAD.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND FSI_STANDARD_ACCT_HEAD.F_CONSOLIDATION_FLAG = 'S' AND COALESCE(FCT_ENTITY_INFO.F_REGULATORY_ENTITY_IND,'Y') = 'Y'  AND COALESCE(FSI_SETUP_CAPITAL_SOURCE.V_SOURCE_CD,'XX') NOT IN ('CM','PR','BM') LOG ERRORS INTO FCT_CAPITAL_ACCT_HEAD$ ('1776768052574_46128368_20260331_1_JOB_1623752496012') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
