-- =====================================================================
-- Task: FSI_BASEL_ASSET_CATEGRY_MAP_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FSI_BASEL_ASSET_CATEGRY_MAP_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_BASEL_ASSET_CATEGRY_MAP(N_BASEL_ASSET_CLASS_SKEY,N_BASEL_ASSET_CLASS_CAT_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,F_ST_LT_FLAG,V_JURISDICTION_CODE,N_CAP_APPROACH_TYPE_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_ASSET_CLASS.N_BASEL_ASSET_CLASS_SKEY),to_char(DIM_BASEL_ASSET_CLASS_CATEGORY.N_BASEL_ASSET_CLASS_CAT_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),FSI_BASEL_ASSET_CAT_MAP_MASTER.F_ST_LT_FLAG,FSI_BASEL_ASSET_CAT_MAP_MASTER.V_JURISDICTION_CODE,to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY) FROM FSI_BASEL_ASSET_CAT_MAP_MASTER INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.V_JURISDICTION_CODE = FSI_BASEL_ASSET_CAT_MAP_MASTER.V_JURISDICTION_CODE AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_BASEL_ASSET_CLASS_CATEGORY ON DIM_BASEL_ASSET_CLASS_CATEGORY.V_BASEL_ASSET_CLASS_CAT_CODE = FSI_BASEL_ASSET_CAT_MAP_MASTER.V_BASEL_ASSET_CLASS_CAT_CODE AND FSI_BASEL_ASSET_CAT_MAP_MASTER.FIC_MIS_DATE BETWEEN DIM_BASEL_ASSET_CLASS_CATEGORY.D_RECORD_START_DATE AND DIM_BASEL_ASSET_CLASS_CATEGORY.D_RECORD_END_DATE INNER JOIN DIM_BASEL_ASSET_CLASS ON DIM_BASEL_ASSET_CLASS.V_BASEL_ASSET_CLASS_CODE = FSI_BASEL_ASSET_CAT_MAP_MASTER.V_BASEL_ASSET_CLASS_CODE AND FSI_BASEL_ASSET_CAT_MAP_MASTER.FIC_MIS_DATE BETWEEN DIM_BASEL_ASSET_CLASS.D_RECORD_START_DATE AND DIM_BASEL_ASSET_CLASS.D_RECORD_END_DATE INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_ASSET_CAT_MAP_MASTER.V_APPROACH_TYPE INNER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON DIM_RUN.N_RUN_SKEY = FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY  AND DIM_DATES.N_DATE_SKEY = FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY             AND FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE =  FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE INNER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY  AND RUN_PARAMETERS.N_MIS_DATE_SKEY = FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY  AND RUN_PARAMETERS.N_RUN_PARAMETER_SKEY = FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY WHERE 1=1 LOG ERRORS INTO FSI_BASEL_ASSET_CATEGRY_MAP$ ('1776768247003_8462852_20260331_1_Job_1596547179343') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
