-- =====================================================================
-- Task: FSI_PARTY_PARTY_RELATIONSHIP_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.FSI_PARTY_PARTY_RELATIONSHIP_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_PARTY_PARTY_RELATIONSHIP(N_MIS_DATE_SKEY,N_PARTY_SKEY,N_RELATIONSHIP_TYPE_SKEY,N_REG_RELATIONSHIP_TYPE_SKEY,F_INTRA_GROUP_EXEMPTED_FLAG,N_PARENT_PARTY_SKEY,N_PARENT_RELATED_PARTY_SKEY,N_RELATED_PARTY_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),to_char(DIM_PARTY_RELATIONSHIP_TYPE.N_RELATIONSHIP_TYPE_SKEY),to_char(DIM_REG_PARTY_RELATIONSHP_TYPE.N_REG_RELATIONSHIP_TYPE_SKEY),'N',DIM_PARTY_PARENT.N_PARTY_SKEY,PARENT_RELATED_PARTY.N_PARTY_SKEY,DIM_PARTY_RELATED.N_PARTY_SKEY,'870' FROM STG_PARTY_PARTY_RELATIONSHIP INNER JOIN DIM_DATES ON STG_PARTY_PARTY_RELATIONSHIP.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT JOIN DIM_PARTY ON DIM_PARTY.V_PARTY_ID = STG_PARTY_PARTY_RELATIONSHIP.V_PARTY_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE LEFT JOIN DIM_PARTY DIM_PARTY_RELATED ON DIM_PARTY_RELATED.V_PARTY_ID = STG_PARTY_PARTY_RELATIONSHIP.V_RELATED_PARTY_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY_RELATED.D_RECORD_START_DATE AND DIM_PARTY_RELATED.D_RECORD_END_DATE LEFT JOIN DIM_PARTY DIM_PARTY_PARENT ON DIM_PARTY_PARENT.V_PARTY_ID = DIM_PARTY.V_PARENT_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY_PARENT.D_RECORD_START_DATE AND DIM_PARTY_PARENT.D_RECORD_END_DATE LEFT JOIN DIM_PARTY PARENT_RELATED_PARTY ON PARENT_RELATED_PARTY.V_PARTY_ID = DIM_PARTY_RELATED.V_PARENT_ID AND to_date('20260331','YYYYMMDD') BETWEEN PARENT_RELATED_PARTY.D_RECORD_START_DATE AND PARENT_RELATED_PARTY.D_RECORD_END_DATE LEFT JOIN DIM_PARTY_RELATIONSHIP_TYPE ON DIM_PARTY_RELATIONSHIP_TYPE.V_RELATIONSHIP_TYPE_CODE = STG_PARTY_PARTY_RELATIONSHIP.V_RELATIONSHIP_TYPE_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY_RELATIONSHIP_TYPE.D_RECORD_START_DATE AND DIM_PARTY_RELATIONSHIP_TYPE.D_RECORD_END_DATE LEFT JOIN FSI_PARTY_RELATIONSHIP_RECLASS ON FSI_PARTY_RELATIONSHIP_RECLASS.N_RUN_SKEY = '870' AND FSI_PARTY_RELATIONSHIP_RECLASS.N_RELATIONSHIP_TYPE_SKEY = DIM_PARTY_RELATIONSHIP_TYPE.N_RELATIONSHIP_TYPE_SKEY LEFT JOIN DIM_REG_PARTY_RELATIONSHP_TYPE ON DIM_REG_PARTY_RELATIONSHP_TYPE.N_REG_RELATIONSHIP_TYPE_SKEY = FSI_PARTY_RELATIONSHIP_RECLASS.N_REG_RELATIONSHIP_TYPE_SKEY WHERE 1=1 LOG ERRORS INTO FSI_PARTY_PARTY_RELATIONSHIP$ ('1776767880861_42205817_20260331_1_Job_99c19ce6467d4a56a969ade5d0106730') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
