-- =====================================================================
-- Task: GL_CAPITAL_ACCT_HEAD_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.GL_CAPITAL_ACCT_HEAD_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_CAPITAL_ACCT_HEAD(N_CAPITAL_ACCT_HEAD_SKEY,N_GAAP_SKEY,N_RUN_SKEY,V_JURISDICTION_CODE,F_CONSOLIDATION_FLAG,F_GL_IDENTIFIER,N_CAPITAL_ACCT_HEAD_AMT_NCY,N_CAPITAL_ACCT_HEAD_AMT_LCY,N_CAPITAL_ACCT_HEAD_AMT,N_CAP_COMP_GROUP_SKEY,N_EXCHANGE_RATE,N_MINORITY_INTEREST_AMT,N_SHAREHOLDING_PERCENT,V_CCY_CODE,N_ENTITY_SKEY,N_MIS_DATE_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_RUN.N_RUN_SKEY),DIM_RUN.V_JURISDICTION_CODE,Max(STG_GL_DATA.F_CONSOLIDATION_FLAG),'Y',Sum(STG_GL_DATA.N_AMOUNT_ACY),Sum(STG_GL_DATA.N_AMOUNT_LCY),COALESCE(Sum(STG_GL_DATA.N_AMOUNT_LCY),0) * COALESCE(MAX(FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE), 0),DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,MAX(FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE),Sum(STG_GL_DATA.N_MINORITY_INTEREST_AMT),Max(CASE WHEN DIM_BASEL_CAP_CONSL_APPR.v_basel_cap_consl_appr_code IN ('FLCS', 'FAGR') THEN 1 ELSE FCT_ENTITY_INFO.n_shareholding_percent END),Max(STG_GL_DATA.V_CCY_CODE),to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),to_char(FCT_ENTITY_INFO.N_MIS_DATE_SKEY),to_char(FSI_GL_STD_ACCT_HEAD_RECLASS.N_STD_ACCT_HEAD_SKEY) FROM STG_GL_DATA INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND STG_GL_DATA.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND STG_GL_DATA.F_CONSOLIDATION_FLAG = 'S' INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870'   JOIN DIM_CAPITAL_ACCT_HEAD ON STG_GL_DATA.V_GL_CODE = DIM_CAPITAL_ACCT_HEAD.V_CAPITAL_ACCOUNT_IDENTIFIER AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_ACCT_HEAD.D_RECORD_START_DATE AND DIM_CAPITAL_ACCT_HEAD.D_RECORD_END_DATE LEFT OUTER JOIN DIM_GAAP ON STG_GL_DATA.V_GAAP_CODE = DIM_GAAP.V_GAAP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE INNER JOIN FCT_ENTITY_INFO ON STG_GL_DATA.V_LV_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE AND COALESCE(FCT_ENTITY_INFO.F_CAP_CONSL_ENTITY_IND, 'Y') = 'Y' AND COALESCE(FCT_ENTITY_INFO.F_REGULATORY_ENTITY_IND, 'Y') = 'Y' AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' INNER JOIN DIM_ORG_STRUCTURE ON DIM_ORG_STRUCTURE.V_ENTITY_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE AND DIM_DATES.D_CALENDAR_DATE BETWEEN COALESCE(DIM_ORG_STRUCTURE.D_RECORD_START_DATE, DIM_DATES.D_CALENDAR_DATE) AND COALESCE(DIM_ORG_STRUCTURE.D_RECORD_END_DATE, DIM_DATES.D_CALENDAR_DATE) AND COALESCE(DIM_ORG_STRUCTURE.F_FINANCIAL_SUBSIDIARY_IND, 'N') <> 'Y' JOIN DIM_BASEL_CAP_CONSL_APPR ON FCT_ENTITY_INFO.N_BASEL_CAP_CONSL_APPR_SKEY = DIM_BASEL_CAP_CONSL_APPR.N_BASEL_CAP_CONSL_APPR_SKEY AND DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE IN ( 'FLCS', 'PRCS', 'FAGR', 'PRAGR' ) JOIN DIM_GL_ACCOUNT ON STG_GL_DATA.V_GL_CODE = DIM_GL_ACCOUNT.V_GL_ACCOUNT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GL_ACCOUNT.D_RECORD_START_DATE AND DIM_GL_ACCOUNT.D_RECORD_END_DATE LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND DIM_RUN.N_RUN_SKEY = FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_GL_DATA.V_CCY_CODE LEFT OUTER JOIN FSI_GL_STD_ACCT_HEAD_RECLASS ON FSI_GL_STD_ACCT_HEAD_RECLASS.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_GL_STD_ACCT_HEAD_RECLASS.N_RUN_SKEY = '870' AND FSI_GL_STD_ACCT_HEAD_RECLASS.N_GL_ACCOUNT_SKEY = DIM_GL_ACCOUNT.N_GL_ACCOUNT_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE WHERE 1=1 GROUP BY DIM_GAAP.N_GAAP_SKEY, FCT_ENTITY_INFO.N_MIS_DATE_SKEY, FCT_ENTITY_INFO.N_ENTITY_SKEY, DIM_CAPITAL_ACCT_HEAD.N_CAPITAL_ACCT_HEAD_SKEY, FSI_GL_STD_ACCT_HEAD_RECLASS.N_STD_ACCT_HEAD_SKEY, DIM_RUN.N_RUN_SKEY,DIM_RUN.V_JURISDICTION_CODE,DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY LOG ERRORS INTO FCT_CAPITAL_ACCT_HEAD$ ('1776768041529_5812091_20260331_1_JOB_1623752493529') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
