-- =====================================================================
-- Task: GL_STD_ACCT_HEAD_RECLASS_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.GL_STD_ACCT_HEAD_RECLASS_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_GL_STD_ACCT_HEAD_RECLASS(N_MIS_DATE_SKEY,N_GL_ACCOUNT_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GL_ACCOUNT.N_GL_ACCOUNT_SKEY),to_char(DIM_RUN.N_RUN_SKEY) FROM DIM_GL_ACCOUNT inner join DIM_DATES on 1=1 inner join DIM_RUN on 1=1 WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE BETWEEN COALESCE(DIM_GL_ACCOUNT.D_RECORD_START_DATE, DIM_DATES.D_CALENDAR_DATE) AND COALESCE(DIM_GL_ACCOUNT.D_RECORD_END_DATE, DIM_DATES.D_CALENDAR_DATE) AND DIM_DATES.D_CALENDAR_DATE=to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY='870' LOG ERRORS INTO FSI_GL_STD_ACCT_HEAD_RECLASS$ ('1776767881578_32233985_20260331_1_Job_a518df9ab375403c92a9e5e1e53ea3d0') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
