-- =====================================================================
-- Task: Hypothetical_Capital_Computation_for_CCP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Hypothetical_Capital_Computation_for_CCP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_CCP_DETAILS TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_CCP_DETAILS.N_MIS_DATE_SKEY,FCT_CCP_DETAILS.N_GAAP_SKEY,FCT_CCP_DETAILS.N_ENTITY_SKEY,FCT_CCP_DETAILS.N_RUN_SKEY,FCT_CCP_DETAILS.N_CENTRAL_COUNTERPARTY_SKEY,(FCT_CCP_DETAILS.N_CCP_HYPOTHETICAL_CAPITAL) AS  T_1429694123318_0,   (CASE  WHEN  ( ((((DIM_DATES.D_CALENDAR_DATE>=TO_DATE('01012017','MMDDYYYY'))) AND ((COALESCE(FCT_CCP_DETAILS.F_QUALIFIED_CCP_FLAG,'N') = 'Y')))) ) THEN 10 ELSE 11 END)  AS COND_1429694123318_10 ,  (CASE WHEN CASE WHEN 1 = 1 THEN FCT_CCP_DETAILS.n_total_ead_cm ELSE NULL END  IS NOT NULL THEN CASE WHEN 1 = 1 THEN FCT_CCP_DETAILS.n_total_ead_cm ELSE NULL END *0.2*0.08*CASE WHEN 1 = 1 THEN FCT_CCP_DETAILS.n_exchange_rate ELSE NULL END  ELSE CASE WHEN 1 = 1 THEN FCT_CCP_DETAILS.n_ccp_hypothetical_capital ELSE NULL END  END ) AS EXP_1429694123318_10,(FCT_CCP_DETAILS.N_CCP_HYPOTHETICAL_CAPITAL) AS EXP_1429694123318_11  FROM  FCT_CCP_DETAILS LEFT OUTER JOIN DIM_RUN ON FCT_CCP_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON FCT_CCP_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_CCP_DETAILS.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN RUN_PARAMETERS ON FCT_CCP_DETAILS.N_RUN_PARAMETER_SETUP_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY AND RUN_PARAMETERS.N_RUN_SKEY = FCT_CCP_DETAILS.N_RUN_SKEY AND RUN_PARAMETERS.N_DATE_SKEY = FCT_CCP_DETAILS.N_MIS_DATE_SKEY	 LEFT OUTER JOIN RUN_EXE_PARAMETERS ON RUN_EXE_PARAMETERS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND RUN_EXE_PARAMETERS.V_PARAM_ID = 'LE' INNER JOIN DIM_ORG_STRUCTURE ON DIM_ORG_STRUCTURE.V_ENTITY_CODE = RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_ORG_STRUCTURE.D_RECORD_START_DATE AND DIM_ORG_STRUCTURE.D_RECORD_END_DATE LEFT OUTER JOIN FSI_CCP_CAPITAL_CALCULATION ON FCT_CCP_DETAILS.N_CENTRAL_COUNTERPARTY_SKEY = FSI_CCP_CAPITAL_CALCULATION.N_COUNTERPARTY_SKEY AND FCT_CCP_DETAILS.N_RUN_SKEY = FSI_CCP_CAPITAL_CALCULATION.N_RUN_SKEY AND FCT_CCP_DETAILS.N_MIS_DATE_SKEY = FSI_CCP_CAPITAL_CALCULATION.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CCP_CAPITAL_CALCULATION.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870')  ) WHERE (   (COND_1429694123318_10 <> 11)  ) ) SS ON ( TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_CENTRAL_COUNTERPARTY_SKEY= SS.N_CENTRAL_COUNTERPARTY_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_CCP_HYPOTHETICAL_CAPITAL=  CASE  WHEN  COND_1429694123318_10=10 THEN EXP_1429694123318_10 ELSE EXP_1429694123318_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
