-- =====================================================================
-- Task: Incurred_CVA_Loss_Calculation
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Incurred_CVA_Loss_Calculation(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_INCURRED_CVA_LOSS_CALC TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_INCURRED_CVA_LOSS_CALC.N_RUN_SKEY,FSI_INCURRED_CVA_LOSS_CALC.N_MIS_DATE_SKEY,FSI_INCURRED_CVA_LOSS_CALC.N_ACCT_SKEY,FSI_INCURRED_CVA_LOSS_CALC.N_CAP_APPROACH_TYPE_SKEY,(FSI_INCURRED_CVA_LOSS_CALC.N_INCURRED_CVA_LOSS_AMOUNT) AS  T_1472197832600_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1472197832600_10 ,  (GREATEST(COALESCE(CASE WHEN 1=1 THEN FSI_INCURRED_CVA_LOSS_CALC.N_CURR_EXPECTED_EXP_AMOUNT ELSE NULL END ,0)*COALESCE(CASE WHEN 1=1 THEN FSI_INCURRED_CVA_LOSS_CALC.N_CURR_RISK_PREMIUM ELSE NULL END ,0) - COALESCE(CASE WHEN 1 = 1 THEN FSI_INCURRED_CVA_LOSS_CALC.n_orig_expected_exp_amount ELSE NULL END ,0)*COALESCE(CASE WHEN 1 = 1 THEN FSI_INCURRED_CVA_LOSS_CALC.n_orig_risk_premium ELSE NULL END ,0),0)) AS EXP_1472197832600_10,(FSI_INCURRED_CVA_LOSS_CALC.N_INCURRED_CVA_LOSS_AMOUNT) AS EXP_1472197832600_11  FROM  FSI_INCURRED_CVA_LOSS_CALC LEFT OUTER JOIN DIM_RUN ON FSI_INCURRED_CVA_LOSS_CALC.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON FSI_INCURRED_CVA_LOSS_CALC.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN RUN_PARAMETERS ON FSI_INCURRED_CVA_LOSS_CALC.N_RUN_PARAMETER_SETUP_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY AND RUN_PARAMETERS.N_RUN_SKEY = FSI_INCURRED_CVA_LOSS_CALC.N_RUN_SKEY AND RUN_PARAMETERS.N_DATE_SKEY = FSI_INCURRED_CVA_LOSS_CALC.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON DIM_RUN_IDENTIFIER.N_RUN_IDENTIFIER_SKEY = FSI_INCURRED_CVA_LOSS_CALC.N_RUN_IDENTIFIER_SKEY LEFT OUTER JOIN RUN_EXE_PARAMETERS RUN_EXE_PARAMETERS_RCY ON RUN_EXE_PARAMETERS_RCY.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND RUN_EXE_PARAMETERS_RCY.V_PARAM_ID = 'RCY' LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE ON FSI_INCURRED_CVA_LOSS_CALC.N_STD_COUNTERPARTY_TYPE_SKEY = DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY LEFT OUTER JOIN DIM_PARTY ON FSI_INCURRED_CVA_LOSS_CALC.N_COUNTERPARTY_SKEY = DIM_PARTY.N_PARTY_SKEY LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE SPREAD_STANDARD_PARTY_TYPE ON FSI_INCURRED_CVA_LOSS_CALC.N_SPREAD_STD_PARTY_TYPE_SKEY = SPREAD_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_INCURRED_CVA_LOSS_CALC.N_CAP_APPROACH_TYPE_SKEY INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_INCURRED_CVA_LOSS_CALC.N_CAP_RECORD_TYPE_SKEY  WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = TO_DATE('20260331','yyyymmdd'))  ) WHERE (   (COND_1472197832600_10 <> 11)  ) ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_ACCT_SKEY= SS.N_ACCT_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_INCURRED_CVA_LOSS_AMOUNT=  CASE  WHEN  COND_1472197832600_10=10 THEN EXP_1472197832600_10 ELSE EXP_1472197832600_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
