-- =====================================================================
-- Task: INSTRUMENT_TYPE_RECLASSIFICATION_POPULATION_STD
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.INSTRUMENT_TYPE_RECLASSIFICATION_POPULATION_STD(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_INSTR_TYPE_CLASSIFICATION(N_BANK_INSTR_TYPE_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,V_APPROACH)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BANK_INSTRUMENT_TYPE.N_BANK_INSTR_TYPE_SKEY),DIM_DATES.N_DATE_SKEY,'870','STD' FROM DIM_BANK_INSTRUMENT_TYPE, DIM_DATES WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_BANK_INSTRUMENT_TYPE.D_RECORD_START_DATE AND DIM_BANK_INSTRUMENT_TYPE.D_RECORD_END_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND NOT EXISTS (SELECT 1 FROM FSI_INSTR_TYPE_CLASSIFICATION WHERE FSI_INSTR_TYPE_CLASSIFICATION.N_RUN_SKEY = '870' AND FSI_INSTR_TYPE_CLASSIFICATION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_INSTR_TYPE_CLASSIFICATION.N_BANK_INSTR_TYPE_SKEY = DIM_BANK_INSTRUMENT_TYPE.N_BANK_INSTR_TYPE_SKEY  AND FSI_INSTR_TYPE_CLASSIFICATION.V_APPROACH = 'STD') LOG ERRORS INTO FSI_INSTR_TYPE_CLASSIFICATION$ ('1776767895658_15299893_20260331_1_Job_52c96b7811e34c9b920a3e132bb3993b') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
