-- =====================================================================
-- Task: INSTRUMENT_CONTRACT_DETAILS
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.INSTRUMENT_CONTRACT_DETAILS(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_INSTRUMENT_CONTRACT_DTL(N_MIS_DATE_SKEY,N_INSTRUMENT_SKEY,V_RISK_RETURN_PROFILE_GRADE,F_INSTR_PORT_INFO_RECD_FLAG,N_CURR_OUTST_ISSUE_AMT,N_ISSUE_DATE_SKEY,N_OUTST_TOTAL_ISSUE_AMT,N_RUN_SKEY,N_TOTAL_FUND_DEBT_AMT,N_TOTAL_FUND_EQUITY_AMT,F_INFO_VERIFIED_BY_THIRD_PARTY,F_INVS_DEPSTRY_INSTITUTION_IND,F_THIRD_PARTY_DTL_PRV_BNK_FLAG,N_CURR_OUTST_ISSUE_AMT_NCY,N_OUTST_TOTAL_ISSUE_AMT_NCY,N_RISK_WEIGHT,N_TOTAL_FUND_DEBT_AMT_NCY,N_TOTAL_FUND_EQUITY_AMT_NCY,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_INSTRUMENT_CONTRACT.N_INSTRUMENT_SKEY),DIM_INSTRUMENT_CONTRACT.V_RISK_RETURN_PROFILE_GRADE,COALESCE(DIM_INSTRUMENT_CONTRACT.F_PERIOD_PORT_INFO_RECD_FLAG,'N'),N_ISSUE_CURR_OUTST_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,DIM_ISSUE_DATES.N_DATE_SKEY,N_ISSUE_TOTAL_OUTST_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,870,N_TOTAL_FUND_DEBT_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,N_TOTAL_FUND_EQUITY_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,STG_INSTRUMENT_CONTRACT_DTL.F_INFO_VERIFIED_BY_THIRD_PARTY,STG_INSTRUMENT_CONTRACT_DTL.F_INVS_DEPSTRY_INSTITUTION_IND,STG_INSTRUMENT_CONTRACT_DTL.F_THIRD_PARTY_DTL_PRV_BNK_FLAG,to_char(STG_INSTRUMENT_CONTRACT_DTL.N_ISSUE_CURR_OUTST_AMT),to_char(STG_INSTRUMENT_CONTRACT_DTL.N_ISSUE_TOTAL_OUTST_AMT),to_char(STG_INSTRUMENT_CONTRACT_DTL.N_RISK_WEIGHT),to_char(STG_INSTRUMENT_CONTRACT_DTL.N_TOTAL_FUND_DEBT_AMT),to_char(STG_INSTRUMENT_CONTRACT_DTL.N_TOTAL_FUND_EQUITY_AMT),STG_INSTRUMENT_CONTRACT_DTL.V_CCY_CODE FROM STG_INSTRUMENT_CONTRACT_DTL INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON to_char(STG_INSTRUMENT_CONTRACT_DTL.FIC_MIS_DATE, 'YYYYMMDD') = DIM_DATES.N_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_INSTRUMENT_CONTRACT ON STG_INSTRUMENT_CONTRACT_DTL.V_INSTRUMENT_CODE = DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_INSTRUMENT_CONTRACT.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_INSTRUMENT_CONTRACT.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN DIM_CURRENCY ON DIM_CURRENCY.V_ISO_CURRENCY_CD = STG_INSTRUMENT_CONTRACT_DTL.V_CCY_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CURRENCY.D_RECORD_START_DATE AND DIM_CURRENCY.D_RECORD_END_DATE LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_CAP_CURRENCY_CONVERSION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_INSTRUMENT_CONTRACT_DTL.V_CCY_CODE LEFT OUTER JOIN DIM_DATES DIM_ISSUE_DATES ON DIM_ISSUE_DATES.D_CALENDAR_DATE = STG_INSTRUMENT_CONTRACT_DTL.D_ISSUE_DATE WHERE 1=1 LOG ERRORS INTO FCT_INSTRUMENT_CONTRACT_DTL$ ('1776768195819_88552563_20260331_1_Job_17072fc26c4b49fc84468561087522a1') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
