-- =====================================================================
-- Task: INTERNAL_TRANSACTIONS_STANDARD_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.INTERNAL_TRANSACTIONS_STANDARD_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_ENTITY,N_FORECAST_DATE_SKEY,N_ORIG_STD_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_AMT,N_UPD_CAP_COMP_GROUP_SKEY,V_STRESS_SCENARIO_CODE,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,FCT_CALC_ACCT_HEAD.N_ENTITY_SKEY,FCT_CALC_ACCT_HEAD.N_FORECAST_DATE_SKEY,SUM(COALESCE(FCT_CALC_ACCT_HEAD.N_CALC_ACCT_HEAD_AMT, 0)),SUM(COALESCE(FCT_CALC_ACCT_HEAD.N_CALC_ACCT_HEAD_AMT, 0)),DIM_CAPITAL_COMP_GROUP_UDP.N_CAP_COMP_GROUP_SKEY,FCT_CALC_ACCT_HEAD.V_STRESS_SCENARIO_CODE,to_char(FCT_CALC_ACCT_HEAD.N_GAAP_SKEY),to_char(FCT_CALC_ACCT_HEAD.N_MIS_DATE_SKEY),to_char(FCT_CALC_ACCT_HEAD.N_RUN_SKEY),to_char(FCT_CALC_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY) FROM FCT_CALC_ACCT_HEAD LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_CALC_ACCT_HEAD.n_mis_date_skey LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FCT_CALC_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON  DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' AND TO_DATE(to_date('20260331','YYYYMMDD')) BETWEEN COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) AND COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP DIM_CAPITAL_COMP_GROUP_UDP ON DIM_CAPITAL_COMP_GROUP_UDP.V_CAP_COMP_GROUP_CODE = 'OTH' AND TO_DATE(to_date('20260331','YYYYMMDD')) BETWEEN COALESCE(DIM_CAPITAL_COMP_GROUP_UDP.D_RECORD_START_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) AND COALESCE(DIM_CAPITAL_COMP_GROUP_UDP.D_RECORD_END_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) WHERE 1=1 AND FCT_CALC_ACCT_HEAD.N_RUN_SKEY = '870' AND DIM_DATES.d_Calendar_Date = to_date('20260331','YYYYMMDD') AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID IN ('CAP875', 'CAP876', 'CAP877') GROUP BY FCT_CALC_ACCT_HEAD.N_RUN_SKEY, FCT_CALC_ACCT_HEAD.n_mis_date_skey, FCT_CALC_ACCT_HEAD.N_GAAP_SKEY, FCT_CALC_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY, FCT_CALC_ACCT_HEAD.N_FORECAST_DATE_SKEY, FCT_CALC_ACCT_HEAD.V_STRESS_SCENARIO_CODE,FCT_CALC_ACCT_HEAD.N_ENTITY_SKEY,DIM_CAPITAL_COMP_GROUP_UDP.N_CAP_COMP_GROUP_SKEY,DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776771034904_17431626_20260331_1_JOB_6997886344757381') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
