-- =====================================================================
-- Task: INV_DRV_DEDUCTION_CALC_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.INV_DRV_DEDUCTION_CALC_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_CALC_ACCT_HEAD(N_RUN_SKEY,F_CAP_DED_IND,N_COUNTRY_SKEY,N_ENTITY_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_CALC_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_SKEY,V_RISK_TYPE_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_RUN.N_RUN_SKEY),CASE WHEN MAX(FNSE.V_STD_ACCT_HEAD_ID) IN ('CAP875', 'CAP876', 'CAP877', 'CAP502') THEN 'N' ELSE 'Y' END,MAX(FNSE.N_COUNTRY_SKEY),FNSE.N_ENTITY_SKEY,FNSE.N_GAAP_SKEY,FNSE.N_MIS_DATE_SKEY,SUM(FNSE.N_EAD_PRE_MITIGATION),FNSE.N_STD_ACCT_HEAD_SKEY,'CR' FROM ( SELECT FSI_CAP_INVESTMENT_EXPOSURES.N_ENTITY_SKEY ,FSI_CAP_INVESTMENT_EXPOSURES.N_GAAP_SKEY ,FSI_CAP_INVESTMENT_EXPOSURES.N_MIS_DATE_SKEY ,FSI_CAP_INVESTMENT_EXPOSURES.N_RUN_SKEY ,FSI_CAP_INVESTMENT_EXPOSURES.N_STD_ACCT_HEAD_SKEY ,DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID ,FSI_CAP_INVESTMENT_EXPOSURES.N_COUNTRY_SKEY ,FSI_CAP_INVESTMENT_EXPOSURES.N_EAD_PRE_MITIGATION FROM FSI_CAP_INVESTMENT_EXPOSURES LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FSI_CAP_INVESTMENT_EXPOSURES.n_mis_date_skey LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.n_std_acct_head_skey = FSI_CAP_INVESTMENT_EXPOSURES.n_std_acct_head_skey WHERE FSI_CAP_INVESTMENT_EXPOSURES.n_std_acct_head_skey IS NOT NULL AND FSI_CAP_INVESTMENT_EXPOSURES.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID NOT IN ( 'CAP576' ,'CAP574' ,'CAP577' ,'CAP575' ,'CAP573' ,'CAP578' ,'CAP579' ,'CAP928' ) UNION ALL SELECT FSI_CAP_DERIVATIVES.N_ENTITY_SKEY ,FSI_CAP_DERIVATIVES.N_GAAP_SKEY ,FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY ,FSI_CAP_DERIVATIVES.N_RUN_SKEY ,FSI_CAP_DERIVATIVES.N_STD_ACCT_HEAD_SKEY ,DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID ,FSI_CAP_DERIVATIVES.N_COUNTRY_SKEY ,FSI_CAP_DERIVATIVES.N_EAD_PRE_MITIGATION FROM FSI_CAP_DERIVATIVES LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FSI_CAP_DERIVATIVES.n_mis_date_skey LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.n_std_acct_head_skey = FSI_CAP_DERIVATIVES.n_std_acct_head_skey WHERE FSI_CAP_DERIVATIVES.n_std_acct_head_skey IS NOT NULL AND FSI_CAP_DERIVATIVES.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID NOT IN ( 'CAP576' ,'CAP574' ,'CAP577' ,'CAP575' ,'CAP573' ,'CAP578' ,'CAP579' ,'CAP928' ) ) FNSE  LEFT OUTER JOIN dim_run ON dim_run.n_run_skey = FNSE.n_run_skey WHERE 1=1 AND FNSE.n_run_skey = '870' GROUP BY FNSE.N_MIS_DATE_SKEY ,DIM_RUN.N_RUN_SKEY ,FNSE.N_GAAP_SKEY ,FNSE.N_ENTITY_SKEY ,FNSE.N_STD_ACCT_HEAD_SKEY LOG ERRORS INTO FCT_CALC_ACCT_HEAD$ ('1776770899456_55838275_20260331_1_JOB_6649379887755034') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
