-- =====================================================================
-- Task: Market_Risk_Sec_Concentration_Ratio_Calculation
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Market_Risk_Sec_Concentration_Ratio_Calculation(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_SECURITIZATION_TRANCHE TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_SECURITIZATION_TRANCHE.N_RUN_SKEY,FCT_SECURITIZATION_TRANCHE.N_GAAP_SKEY,FCT_SECURITIZATION_TRANCHE.N_MIS_DATE_SKEY,FCT_SECURITIZATION_TRANCHE.N_TRANCHE_SKEY,FCT_SECURITIZATION_TRANCHE.V_TRANCHE_ID,(FCT_SECURITIZATION_TRANCHE.N_CONCENTRATION_RATIO) AS  T_1366976638007_0,   (CASE  WHEN  ( (((FCT_SECURITIZATION_POOL.V_SEC_TRADING_BOOK_APPROACH = 'IRB'))) ) THEN 10 ELSE 11 END)  AS COND_1366976638007_10 ,  (CASE  WHEN SUM(CASE WHEN 1 = 1 THEN FCT_SECURITIZATION_TRANCHE.n_tranche_amount ELSE NULL END ) OVER (PARTITION BY CASE WHEN 1 = 1 THEN FCT_SECURITIZATION_TRANCHE.n_sec_pool_skey ELSE NULL END ) = 0 THEN 0 ELSE SUM(CASE WHEN 1 = 1 THEN FCT_SECURITIZATION_TRANCHE.n_tranche_amount ELSE NULL END ) OVER ( PARTITION BY CASE WHEN 1 = 1 THEN FCT_SECURITIZATION_TRANCHE.n_sec_pool_skey ELSE NULL END  ORDER BY CASE WHEN 1 = 1 THEN FCT_SECURITIZATION_TRANCHE.n_seniority ELSE NULL END  DESC ) / SUM(CASE WHEN 1 = 1 THEN FCT_SECURITIZATION_TRANCHE.n_tranche_amount ELSE NULL END ) OVER (PARTITION BY CASE WHEN 1 = 1 THEN FCT_SECURITIZATION_TRANCHE.n_sec_pool_skey ELSE NULL END ) END  ) AS EXP_1366976638007_10,(FCT_SECURITIZATION_TRANCHE.N_CONCENTRATION_RATIO) AS EXP_1366976638007_11  FROM  FCT_SECURITIZATION_TRANCHE INNER JOIN DIM_RUN ON FCT_SECURITIZATION_TRANCHE.n_run_skey = DIM_RUN.n_run_skey INNER JOIN DIM_DATES ON FCT_SECURITIZATION_TRANCHE.n_mis_date_skey = DIM_DATES.n_date_skey INNER JOIN FCT_SECURITIZATION_POOL ON FCT_SECURITIZATION_TRANCHE.n_run_skey = FCT_SECURITIZATION_POOL.n_run_skey AND FCT_SECURITIZATION_TRANCHE.n_Sec_Pool_Skey = FCT_SECURITIZATION_POOL.n_Sec_Pool_Skey AND FCT_SECURITIZATION_TRANCHE.n_mis_date_skey = FCT_SECURITIZATION_POOL.n_mis_date_skey LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON FCT_SECURITIZATION_TRANCHE.n_run_identifier_skey = DIM_RUN_IDENTIFIER.n_run_identifier_skey LEFT OUTER JOIN RUN_PARAMETERS ON FCT_SECURITIZATION_TRANCHE.n_run_parameter_setup_skey = RUN_PARAMETERS.n_run_parameter_setup_skey AND RUN_PARAMETERS.n_Run_Skey=FCT_SECURITIZATION_TRANCHE.n_Run_Skey AND RUN_PARAMETERS.n_Date_Skey=FCT_SECURITIZATION_TRANCHE.n_Mis_Date_Skey  WHERE (1=1)  AND (DIM_DATES.d_calendar_date = TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  ) WHERE (   (COND_1366976638007_10 <> 11)  ) ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_TRANCHE_SKEY= SS.N_TRANCHE_SKEY AND TT.V_TRANCHE_ID= SS.V_TRANCHE_ID) WHEN MATCHED THEN UPDATE SET  TT.N_CONCENTRATION_RATIO=  CASE  WHEN  COND_1366976638007_10=10 THEN EXP_1366976638007_10 ELSE EXP_1366976638007_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
