-- =====================================================================
-- Task: MINORITY_INTEREST_PHASE_IN_TREATMENT_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MINORITY_INTEREST_PHASE_IN_TREATMENT_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_PHASE_IN_TREATMENT(N_MIS_DATE_SKEY,N_RUN_SKEY,N_ENTITY_SKEY,N_FORECAST_DATE_SKEY,N_GAAP_SKEY,N_REG_ADJUSTMENT_PHASE_IN_AMT,N_STD_ACCT_HEAD_SKEY,V_STRESS_SCENARIO_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),FCT_ENTITY_INFO.N_ENTITY_SKEY,MINORITY_INTEREST.N_FORECAST_DATE_SKEY,MINORITY_INTEREST.N_GAAP_SKEY,MINORITY_INTEREST.N_DEDUCTION_AMOUNT,MINORITY_INTEREST.N_STD_ACCT_HEAD_SKEY,MINORITY_INTEREST.V_STRESS_SCENARIO_CODE FROM ( SELECT FSI_MINORITY_INTEREST.N_RUN_SKEY N_RUN_SKEY, FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, FSI_MINORITY_INTEREST.N_GAAP_SKEY N_GAAP_SKEY, FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY N_FORECAST_DATE_SKEY, FSI_MINORITY_INTEREST.V_STRESS_SCENARIO_CODE V_STRESS_SCENARIO_CODE, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY N_STD_ACCT_HEAD_SKEY, SUM(COALESCE(FSI_MINORITY_INTEREST.N_MINORITY_INT_DED_AMT_CET1, 0)) N_DEDUCTION_AMOUNT FROM FSI_MINORITY_INTEREST, DIM_STANDARD_ACCT_HEAD, DIM_DATES WHERE DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP853' AND FSI_MINORITY_INTEREST.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE GROUP BY FSI_MINORITY_INTEREST.N_RUN_SKEY, FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY, FSI_MINORITY_INTEREST.N_GAAP_SKEY, FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY, FSI_MINORITY_INTEREST.V_STRESS_SCENARIO_CODE, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY UNION SELECT FSI_MINORITY_INTEREST.N_RUN_SKEY N_RUN_SKEY, FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, FSI_MINORITY_INTEREST.N_GAAP_SKEY N_GAAP_SKEY, FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY N_FORECAST_DATE_SKEY, FSI_MINORITY_INTEREST.V_STRESS_SCENARIO_CODE V_STRESS_SCENARIO_CODE, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY N_STD_ACCT_HEAD_SKEY, SUM(COALESCE(FSI_MINORITY_INTEREST.N_MINORITY_INT_DED_AMT_AT1, 0)) N_DEDUCTION_AMOUNT FROM FSI_MINORITY_INTEREST, DIM_STANDARD_ACCT_HEAD, DIM_DATES WHERE DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP854' AND FSI_MINORITY_INTEREST.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE GROUP BY FSI_MINORITY_INTEREST.N_RUN_SKEY, FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY, FSI_MINORITY_INTEREST.N_GAAP_SKEY, FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY, FSI_MINORITY_INTEREST.V_STRESS_SCENARIO_CODE, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY UNION SELECT FSI_MINORITY_INTEREST.N_RUN_SKEY N_RUN_SKEY, FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, FSI_MINORITY_INTEREST.N_GAAP_SKEY N_GAAP_SKEY, FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY N_FORECAST_DATE_SKEY, FSI_MINORITY_INTEREST.V_STRESS_SCENARIO_CODE V_STRESS_SCENARIO_CODE, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY N_STD_ACCT_HEAD_SKEY, SUM(COALESCE(FSI_MINORITY_INTEREST.N_MINORITY_INT_DED_AMT_T2, 0)) N_DEDUCTION_AMOUNT FROM FSI_MINORITY_INTEREST, DIM_STANDARD_ACCT_HEAD, DIM_DATES WHERE DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP855' AND FSI_MINORITY_INTEREST.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE GROUP BY FSI_MINORITY_INTEREST.N_RUN_SKEY, FSI_MINORITY_INTEREST.N_MIS_DATE_SKEY, FSI_MINORITY_INTEREST.N_GAAP_SKEY, FSI_MINORITY_INTEREST.N_FORECAST_DATE_SKEY, FSI_MINORITY_INTEREST.V_STRESS_SCENARIO_CODE, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY ) MINORITY_INTEREST LEFT JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = MINORITY_INTEREST.N_RUN_SKEY LEFT JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = MINORITY_INTEREST.N_MIS_DATE_SKEY LEFT JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = MINORITY_INTEREST.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = MINORITY_INTEREST.N_MIS_DATE_SKEY AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = MINORITY_INTEREST.N_FORECAST_DATE_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') LOG ERRORS INTO FSI_PHASE_IN_TREATMENT$ ('1776771184043_31387057_20260331_1_Job_eedbbde77b014901871ef245ad3ac0a5') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
