-- =====================================================================
-- Task: MKT_RISK_VAR_CAPITAL_CHARGE
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_VAR_CAPITAL_CHARGE(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_SUMMARY(N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_GENERAL_RISK_CHARGE,N_REP_LINE_SKEY,N_CAPITAL_CHARGE,N_GAAP_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),get_method_skey('MRIM',to_date('20260331','YYYYMMDD')),0,((SELECT n_rep_line_skey FROM DIM_MARKET_RISK_REP_LINE WHERE v_rep_line_code = 'VAR')),to_char(FCT_MR_VAR_SUMMARY_DATA.N_CAPITAL_AMOUNT),to_char(FCT_MR_VAR_SUMMARY_DATA.N_GAAP_SKEY) FROM FCT_MR_VAR_SUMMARY_DATA LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_MR_VAR_SUMMARY_DATA.n_mis_date_skey /*LEFT OUTER JOIN DIM_TIME_DATE ON FCT_MR_VAR_SUMMARY_DATA.fic_mis_date = DIM_TIME_DATE.fic_mis_date*/ LEFT OUTER JOIN DIM_RUN ON FCT_MR_VAR_SUMMARY_DATA.n_run_skey = DIM_RUN.n_run_skey INNER JOIN VAR_PORTFOLIO_MASTER ON VAR_PORTFOLIO_MASTER.n_var_port_skey = FCT_MR_VAR_SUMMARY_DATA.n_var_port_skey WHERE 1=1 AND 1=1 AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND FCT_MR_VAR_SUMMARY_DATA.n_run_skey = '870' AND VAR_PORTFOLIO_MASTER.v_var_port_code = 'TOT' LOG ERRORS INTO FCT_MARKET_RISK_SUMMARY$ ('1776769968981_1434265_20260331_1_Job_5b8b232f2abf420a93306cda0dc2f5be') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
