-- =====================================================================
-- Task: MKT_RISK_DR_NDEQ_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_DR_NDEQ_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_EXPOSURES(N_MIS_DATE_SKEY,N_UNDERLYING_SKEY,N_ACCT_SKEY,N_CONTRACT_SIZE,N_COUNTRY_SKEY,N_INSTR_TYPE_SKEY,N_NOTIONAL_AMT,N_POST_OFFSET_EXP_AMT,N_RUN_SKEY,V_COUPON_BASIS_PAY,V_COUPON_BASIS_RCV,D_CONTRACT_START_DATE,D_MATURITY_DATE,D_REPRICING_DATE,F_CAPITAL_CHARGE_EXCLUSION,F_DIVERSIFIED_FLAG,F_GMR_INDICATOR,F_INTERNAL_CUST_IND,F_PORTFOLIO_LIQUID_FLAG,F_QUALIFYING_INS_FLAG,F_REGULATORY_CAP_IND,F_SECURITIZED_FLAG,N_CONTRACT_ACCT_SKEY,N_BASEL_METHOD_SKEY,N_BASEL_RATING,N_BUSINESS_UNIT_SKEY,N_COMMODITY_SKEY,N_COUPON_FREQ_PAY,N_COUPON_FREQ_RCV,N_COUPON_PAY,N_COUPON_RCV,N_CURR_MKT_PRICE,N_CUST_SKEY,N_ENTITY_SKEY,N_GAAP_SKEY,N_IMPLIED_VOLATILITY,N_INDEX_SKEY,N_LEG_REP_SKEY,N_MARKET_CENTRE_SKEY,N_MR_ISSUER_TYPE_SKEY,N_ORIGINAL_MATURITY,N_PAR_VALUE,N_POSITION_SKEY,N_REG_CAP_PARTCP_VALUE,N_SEC_POOL_TYPE_SKEY,N_SETTLEMENT_DAYS,N_SHAREHOLDING_PERCENT,N_SPREAD_PAY,N_SPREAD_RCV,N_STD_UNIT_SKEY,N_UNDERLYING_FORWARD_PRICE,V_BUY_REC_CCY_CODE,V_DAY_COUNTER,V_EXP_RCY_CODE,V_SELL_PAY_CCY_CODE,N_RUN_PARAMETER_SETUP_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DR_ISSUE_MAPPING.N_UNDERLYING_SKEY),(SELECT MIN(DIM_EXPOSURE.n_acct_skey) FROM DIM_EXPOSURE WHERE DIM_EXPOSURE.n_contract_acct_skey = FCT_MARKET_RISK_EXPOSURES.n_acct_skey AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_EXPOSURE.D_RECORD_START_DATE AND DIM_EXPOSURE.D_RECORD_END_DATE ) + ROW_NUMBER() OVER (PARTITION BY FCT_MARKET_RISK_EXPOSURES.n_acct_skey ORDER BY FCT_MARKET_RISK_EXPOSURES.n_acct_skey) - 1,(FCT_MARKET_RISK_EXPOSURES.N_CONTRACT_SIZE*DR_ISSUE_MAPPING.n_conversion_factor),COALESCE(FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY,0),(SELECT DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY FROM DIM_INSTRUMENT_TYPE WHERE V_INSTR_TYPE_CODE = 'EQSPOTSPT' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_INSTRUMENT_TYPE.D_RECORD_START_DATE AND DIM_INSTRUMENT_TYPE.D_RECORD_END_DATE),(FCT_MARKET_RISK_EXPOSURES.N_NOTIONAL_AMT*DR_ISSUE_MAPPING.n_conversion_factor),(FCT_MARKET_RISK_EXPOSURES.N_POST_OFFSET_EXP_AMT*DR_ISSUE_MAPPING.n_conversion_factor),'870',FCT_MARKET_RISK_EXPOSURES.N_COUPON_FREQ_PAY,FCT_MARKET_RISK_EXPOSURES.V_COUPON_BASIS_RCV,FCT_MARKET_RISK_EXPOSURES.D_CONTRACT_START_DATE,FCT_MARKET_RISK_EXPOSURES.D_MATURITY_DATE,FCT_MARKET_RISK_EXPOSURES.D_REPRICING_DATE,FCT_MARKET_RISK_EXPOSURES.F_CAPITAL_CHARGE_EXCLUSION,FCT_MARKET_RISK_EXPOSURES.F_DIVERSIFIED_FLAG,FCT_MARKET_RISK_EXPOSURES.F_GMR_INDICATOR,FCT_MARKET_RISK_EXPOSURES.F_INTERNAL_CUST_IND,FCT_MARKET_RISK_EXPOSURES.F_PORTFOLIO_LIQUID_FLAG,FCT_MARKET_RISK_EXPOSURES.F_QUALIFYING_INS_FLAG,FCT_MARKET_RISK_EXPOSURES.F_REGULATORY_CAP_IND,FCT_MARKET_RISK_EXPOSURES.F_SECURITIZED_FLAG,to_char(FCT_MARKET_RISK_EXPOSURES.N_ACCT_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_BASEL_METHOD_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_BASEL_RATING),to_char(FCT_MARKET_RISK_EXPOSURES.N_BUSINESS_UNIT_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_COMMODITY_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_COUPON_FREQ_PAY),to_char(FCT_MARKET_RISK_EXPOSURES.N_COUPON_FREQ_RCV),to_char(FCT_MARKET_RISK_EXPOSURES.N_COUPON_PAY),to_char(FCT_MARKET_RISK_EXPOSURES.N_COUPON_RCV),to_char(FCT_MARKET_RISK_EXPOSURES.N_CURR_MKT_PRICE),to_char(FCT_MARKET_RISK_EXPOSURES.N_CUST_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_ENTITY_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_IMPLIED_VOLATILITY),to_char(FCT_MARKET_RISK_EXPOSURES.N_INDEX_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_LEG_REP_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_MARKET_CENTRE_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_MR_ISSUER_TYPE_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_ORIGINAL_MATURITY),to_char(FCT_MARKET_RISK_EXPOSURES.N_PAR_VALUE),to_char(FCT_MARKET_RISK_EXPOSURES.N_POSITION_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_REG_CAP_PARTCP_VALUE),to_char(FCT_MARKET_RISK_EXPOSURES.N_SEC_POOL_TYPE_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_SETTLEMENT_DAYS),to_char(FCT_MARKET_RISK_EXPOSURES.N_SHAREHOLDING_PERCENT),to_char(FCT_MARKET_RISK_EXPOSURES.N_SPREAD_PAY),to_char(FCT_MARKET_RISK_EXPOSURES.N_SPREAD_RCV),to_char(FCT_MARKET_RISK_EXPOSURES.N_STD_UNIT_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_UNDERLYING_FORWARD_PRICE),FCT_MARKET_RISK_EXPOSURES.V_BUY_REC_CCY_CODE,FCT_MARKET_RISK_EXPOSURES.V_DAY_COUNTER,FCT_MARKET_RISK_EXPOSURES.V_EXP_RCY_CODE,FCT_MARKET_RISK_EXPOSURES.V_SELL_PAY_CCY_CODE,to_char(RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY) FROM FCT_MARKET_RISK_EXPOSURES INNER JOIN DIM_DATES ON FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' INNER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.N_INSTR_TYPE_SKEY = DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY INNER JOIN DR_ISSUE_MAPPING ON FCT_MARKET_RISK_EXPOSURES.N_ACCT_SKEY = DR_ISSUE_MAPPING.N_DR_SKEY AND DR_ISSUE_MAPPING.N_RUN_SKEY = '870' AND FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY = DR_ISSUE_MAPPING.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 LOG ERRORS INTO FCT_MARKET_RISK_EXPOSURES$ ('1776769042960_67551738_20260331_1_Job_fcc46780bef442aa8d610ba0f39f99a5') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
