-- =====================================================================
-- Task: MKT_RISK_FOREX_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_FOREX_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_FOREX(N_COUNTRY_SKEY,N_MIS_DATE_SKEY,N_GAAP_SKEY,N_BASEL_METHOD_SKEY,N_ENTITY_SKEY,N_EXCHANGE_RATE,N_REP_LINE_SKEY,N_RUN_SKEY,N_SHAREHOLDING_PERCENT,N_RUN_PARAMETER_SETUP_SKEY,N_ASSETS_AMT_NCY,N_ASSET_ACCRUED_INTEREST_NCY,N_ASSET_ACCRUED_PROFIT_NCY,N_EXPOSURE_AMT_NCY,N_EXPOSURE_LIMIT_NCY,N_FOREX_DELTA_EQ_AMT,N_FWD_LONG_POSITION_AMT_NCY,N_FWD_SHORT_POSITION_AMT_NCY,N_IRRECOVERABLE_GUAR_AMT_NCY,N_LIABILITIES_AMT_NCY,N_LIAB_ACCRUED_INTEREST_NCY,N_LIABILITY_ACCRUED_PROFIT_NCY,N_NET_FORWARD_POSITION_AMT_NCY,N_NET_FUTURE_INEXP_HEDGE_NCY,N_OTHER_PROFIT_LOSS_AMT_NCY,N_SPOT_LONG_POSITION_AMT_NCY,N_SPOT_POSITION_AMT_NCY,N_SPOT_SHORT_POSITION_AMT_NCY,N_STRUCT_POS_AMT_NCY,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_COUNTRY.N_COUNTRY_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),(SELECT N_BASEL_METHOD_SKEY FROM DIM_BASEL_METHODOLOGY WHERE V_BASEL_METHOD_CODE = 'MRSTD' AND to_date('20260331','YYYYMMDD')  BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE),(SELECT FCT_ENTITY_INFO.N_ENTITY_SKEY FROM FCT_ENTITY_INFO LEFT OUTER JOIN DIM_DATES ON FCT_ENTITY_INFO.n_Mis_Date_Skey = DIM_DATES.N_DATE_SKEY WHERE FCT_ENTITY_INFO.V_ENTITY_CODE = STG_FOREX_EXPOSURES.V_LV_CODE AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD')),FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,(SELECT n_rep_line_skey from DIM_MARKET_RISK_REP_LINE where v_rep_line_code='FX' and to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE and D_RECORD_END_DATE),'870',CASE WHEN DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE = 'PRCS' THEN COALESCE(FCT_ENTITY_INFO.N_SHAREHOLDING_PERCENT, 1) ELSE 1 END,to_char(RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY),to_char(STG_FOREX_EXPOSURES.N_ASSETS_AMT),to_char(STG_FOREX_EXPOSURES.N_ASSET_ACCRUED_INTEREST),to_char(STG_FOREX_EXPOSURES.N_ASSET_ACCRUED_PROFIT),to_char(STG_FOREX_EXPOSURES.N_EXPOSURE_AMOUNT),to_char(STG_FOREX_EXPOSURES.N_EXPOSURE_LIMIT),to_char(STG_FOREX_EXPOSURES.N_FOREX_DELTA_EQ_AMT),to_char(STG_FOREX_EXPOSURES.N_FORWARD_LONG_POSITION_AMT),to_char(STG_FOREX_EXPOSURES.N_FORWARD_SHORT_POSITION_AMT),to_char(STG_FOREX_EXPOSURES.N_IRRECOVERABLE_GUARANTEE_AMT),to_char(STG_FOREX_EXPOSURES.N_LIABILITIES_AMT),to_char(STG_FOREX_EXPOSURES.N_LIABILITY_ACCRUED_INTEREST),to_char(STG_FOREX_EXPOSURES.N_LIABILITY_ACCRUED_PROFIT),to_char(STG_FOREX_EXPOSURES.N_NET_FORWARD_POSITION_AMT),to_char(STG_FOREX_EXPOSURES.N_NET_FUTURE_INC_EXP_HEDGE),to_char(STG_FOREX_EXPOSURES.N_OTHER_PROFIT_LOSS_AMT),to_char(STG_FOREX_EXPOSURES.N_SPOT_LONG_POSITION_AMT),to_char(STG_FOREX_EXPOSURES.N_SPOT_POSITION_AMT),to_char(STG_FOREX_EXPOSURES.N_SPOT_SHORT_POSITION_AMT),to_char(STG_FOREX_EXPOSURES.N_STRUCT_POS_AMT),STG_FOREX_EXPOSURES.V_CCY_CODE FROM STG_FOREX_EXPOSURES INNER JOIN DIM_RUN ON DIM_RUN.n_run_skey = '870' INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND STG_FOREX_EXPOSURES.fic_mis_date = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_GAAP ON STG_FOREX_EXPOSURES.v_gaap_code = DIM_GAAP.v_gaap_code AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE LEFT OUTER JOIN DIM_COUNTRY ON COALESCE(STG_FOREX_EXPOSURES.v_country_code, 'MSG') = DIM_COUNTRY.v_country_id AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_COUNTRY.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_COUNTRY.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN DIM_MARKET_RISK_REP_LINE ON STG_FOREX_EXPOSURES.v_rep_line_code = DIM_MARKET_RISK_REP_LINE.v_rep_line_code AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_MARKET_RISK_REP_LINE.D_RECORD_START_DATE, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_MARKET_RISK_REP_LINE.D_RECORD_END_DATE, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE INNER JOIN FCT_ENTITY_INFO ON STG_FOREX_EXPOSURES.V_LV_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND COALESCE(FCT_ENTITY_INFO.F_CAP_CONSL_ENTITY_IND, 'N') = 'Y' INNER JOIN DIM_BASEL_CAP_CONSL_APPR ON DIM_BASEL_CAP_CONSL_APPR.N_BASEL_CAP_CONSL_APPR_SKEY = FCT_ENTITY_INFO.N_BASEL_CAP_CONSL_APPR_SKEY LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = '870' AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_FOREX_EXPOSURES.V_CCY_CODE WHERE 1=1 AND 1=1 LOG ERRORS INTO FCT_MARKET_RISK_FOREX$ ('1776768404012_90244114_20260331_1_Job_5283f6998a904371ab0c8c8bf0f7715f') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
