-- =====================================================================
-- Task: MKT_RISK_WTDPOS_DURATION_APPROACH_IR
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_WTDPOS_DURATION_APPROACH_IR(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_CAPITAL(V_CCY_CODE,N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_GAAP_SKEY,N_IRC_BENCHMARK_SKEY,N_LONG_POSITION_AMT,N_REF_INDEX_SKEY,N_REP_LINE_SKEY,N_SHORT_POSTION_AMT,N_TIME_BAND_SKEY,N_TIME_ZONE_SKEY,N_WEIGHTED_LONG_POSITION_AMT,N_WEIGHTED_SHORT_POSITION_AMT,V_COMMODITY_GROUP_CODE)SELECT  /*+PARALLEL (4)*/ DIM_CURRENCY.V_ISO_CURRENCY_CD,to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),MAX(DIM_GAAP.n_gaap_skey),MAX((SELECT max(FSI_IRCS.Interest_Rate_Cd) FROM FSI_IRCS where FSI_IRCS.Irc_Name='OTH')),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code = 'LONG' THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END),MAX((SELECT max(n_Mkt_Var_Skey) FROM DIM_MARKET_VARIABLES WHERE v_Mkt_Var_Code='OTH')),MAX((SELECT MAX(n_rep_line_skey) from DIM_MARKET_RISK_REP_LINE where DIM_MARKET_RISK_REP_LINE.v_rep_line_code ='IR')),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code = 'SHORT' THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END)*-1,DIM_MR_TIME_BAND.N_BAND_SKEY,MAX(CASE WHEN DIM_MR_TIME_BAND.v_band_sub_category IN ( 'DBND1' ,'DBND2' ,'DBND3' ,'DBND4' ) THEN ( SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code = 'Z1' AND to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE ) WHEN DIM_MR_TIME_BAND.v_band_sub_category IN ( 'DBND5' ,'DBND6' ,'DBND7' ) THEN ( SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code = 'Z2' AND to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE ) WHEN DIM_MR_TIME_BAND.v_band_sub_category IN ( 'DBND8' ,'DBND9' ,'DBND10' ,'DBND11' ,'DBND12' ,'DBND13' ,'DBND14' ,'DBND15' ) THEN ( SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code = 'Z3' AND to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE ) END),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code like 'LONG' THEN FCT_MARKET_RISK_EXPOSURES.n_weighted_position_amt ELSE 0 END),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code like 'SHORT' THEN FCT_MARKET_RISK_EXPOSURES.n_weighted_position_amt ELSE 0 END)*-1,'NA' FROM FCT_MARKET_RISK_EXPOSURES LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_EXPOSURES.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.n_instr_type_skey = DIM_INSTRUMENT_TYPE.n_instr_type_skey LEFT OUTER JOIN DIM_BANDS DIM_MR_TIME_BAND ON FCT_MARKET_RISK_EXPOSURES.n_time_band_skey = DIM_MR_TIME_BAND.n_band_skey AND DIM_MR_TIME_BAND.v_Band_Type = 'MR TIME BAND' LEFT OUTER JOIN DIM_MARKET_RISK_POSITION ON FCT_MARKET_RISK_EXPOSURES.n_position_skey = DIM_MARKET_RISK_POSITION.n_position_skey /*LEFT OUTER JOIN DIM_TIME_DATE ON FCT_MARKET_RISK_EXPOSURES.fic_mis_date = DIM_TIME_DATE.fic_mis_date*/ LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_EXPOSURES.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_EXPOSURES.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN DIM_CURRENCY ON COALESCE(FCT_MARKET_RISK_EXPOSURES.v_buy_rec_ccy_code, FCT_MARKET_RISK_EXPOSURES.v_sell_pay_ccy_code) = DIM_CURRENCY.v_iso_currency_cd AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_CURRENCY.D_RECORD_START_DATE AND DIM_CURRENCY.D_RECORD_END_DATE LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_EXPOSURES.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON DIM_RUN.N_RUN_SKEY = FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND RUN_PARAMETERS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' AND DIM_MR_TIME_BAND.v_band_sub_category LIKE 'DBN%' AND DIM_MR_TIME_BAND.v_Band_Type = 'MR TIME BAND' AND DIM_INSTRUMENT_TYPE.V_BASEL_INSTR_TYPE_CODE_LVL1 = 'IR' AND COALESCE(FCT_MARKET_RISK_EXPOSURES.f_internal_cust_ind, 'N') = 'N' AND COALESCE(FCT_MARKET_RISK_EXPOSURES.f_gmr_indicator, 'Y') = 'Y' AND FCT_MARKET_RISK_EXPOSURES.n_var_port_skey IS NULL AND RUN_PARAMETERS.v_mrs_interest_rate_method = 'OPT1003' GROUP BY DIM_MR_TIME_BAND.N_BAND_SKEY, DIM_CURRENCY.v_iso_currency_cd, DIM_DATES.n_date_skey, DIM_RUN.N_RUN_SKEY LOG ERRORS INTO FCT_MARKET_RISK_CAPITAL$ ('1776769450111_5641549_20260331_1_Job_db19decae500494d99e23337910b94af') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
