-- =====================================================================
-- Task: MKT_RISK_WTDPOS_MATURITY_APPROACH_COMMODITY
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_WTDPOS_MATURITY_APPROACH_COMMODITY(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_CAPITAL(V_COMMODITY_GROUP_CODE,N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_GAAP_SKEY,N_IRC_BENCHMARK_SKEY,N_REF_INDEX_SKEY,N_REP_LINE_SKEY,N_TIME_BAND_SKEY,N_WEIGHTED_LONG_POSITION_AMT,N_WEIGHTED_SHORT_POSITION_AMT,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ DIM_COMMODITY.V_COMMODITY_GROUP_CODE,to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),MAX(DIM_GAAP.n_gaap_skey),MAX((SELECT max(FSI_IRCS.Interest_Rate_Cd) FROM FSI_IRCS where FSI_IRCS.Irc_Name='OTH')),MAX((SELECT max(n_Mkt_Var_Skey) FROM DIM_MARKET_VARIABLES WHERE v_Mkt_Var_Code='OTH')),MAX((SELECT MAX(n_rep_line_skey) from DIM_MARKET_RISK_REP_LINE where DIM_MARKET_RISK_REP_LINE.v_rep_line_code ='CO')),DIM_MR_TIME_BAND.N_BAND_SKEY,SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code like 'LONG' THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END),SUM(CASE WHEN DIM_MARKET_RISK_POSITION.v_position_code like 'SHORT' THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END)*-1,'NA' FROM FCT_MARKET_RISK_EXPOSURES LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_EXPOSURES.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.n_instr_type_skey = DIM_INSTRUMENT_TYPE.n_instr_type_skey LEFT OUTER JOIN DIM_BANDS DIM_MR_TIME_BAND ON FCT_MARKET_RISK_EXPOSURES.n_time_band_skey = DIM_MR_TIME_BAND.n_band_skey AND DIM_MR_TIME_BAND.v_Band_Type = 'MR TIME BAND' LEFT OUTER JOIN DIM_MARKET_RISK_POSITION ON FCT_MARKET_RISK_EXPOSURES.n_position_skey = DIM_MARKET_RISK_POSITION.n_position_skey /*LEFT OUTER JOIN DIM_TIME_DATE ON FCT_MARKET_RISK_EXPOSURES.fic_mis_date = DIM_TIME_DATE.fic_mis_date*/ LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_EXPOSURES.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_EXPOSURES.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN DIM_COMMODITY ON FCT_MARKET_RISK_EXPOSURES.n_commodity_skey = DIM_COMMODITY.n_commodity_skey LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_EXPOSURES.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON DIM_RUN.N_RUN_SKEY = FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND RUN_PARAMETERS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_EXPOSURES.n_run_skey = '870' AND DIM_INSTRUMENT_TYPE.V_BASEL_INSTR_TYPE_CODE_LVL1 = 'COM' AND FCT_MARKET_RISK_EXPOSURES.n_var_port_skey IS NULL AND RUN_PARAMETERS.v_mrs_commodity_risk_method = 'OPT1009' GROUP BY DIM_MR_TIME_BAND.n_band_skey, DIM_COMMODITY.v_commodity_group_code, DIM_DATES.n_date_skey, DIM_RUN.n_run_skey LOG ERRORS INTO FCT_MARKET_RISK_CAPITAL$ ('1776769403218_20957238_20260331_1_Job_88ac63d1f7524576a1c6a8fecaf7179f') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
