-- =====================================================================
-- Task: MKT_RISK_CAPITAL_CHARGE_COMDTY
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_CAPITAL_CHARGE_COMDTY(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_SUMMARY(N_MIS_DATE_SKEY,N_REP_LINE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_CAPITAL_CHARGE,N_COUNTRY_SKEY,N_GAAP_SKEY,N_GENERAL_RISK_CHARGE,N_LEG_REP_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_MARKET_RISK_REP_LINE.N_REP_LINE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),SUM(FCT_MARKET_RISK_COM_CAPITAL.n_capital_charge),MAX(DIM_COUNTRY.n_country_skey),MAX(DIM_GAAP.n_gaap_skey),0,MAX(DIM_ORG_STRUCTURE.N_ENTITY_SKEY) FROM FCT_MARKET_RISK_COM_CAPITAL LEFT OUTER JOIN DIM_MARKET_RISK_REP_LINE ON FCT_MARKET_RISK_COM_CAPITAL.N_REP_LINE_SKEY = DIM_MARKET_RISK_REP_LINE.N_REP_LINE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_COM_CAPITAL.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_COM_CAPITAL.N_COUNTRY_SKEY = DIM_COUNTRY.N_COUNTRY_SKEY LEFT OUTER JOIN DIM_DATES ON FCT_MARKET_RISK_COM_CAPITAL.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_COM_CAPITAL.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FCT_MARKET_RISK_COM_CAPITAL.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_ORG_STRUCTURE ON FCT_MARKET_RISK_COM_CAPITAL.N_LEG_REP_SKEY = DIM_ORG_STRUCTURE.N_ENTITY_SKEY AND DIM_ORG_STRUCTURE.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_COM_CAPITAL.N_BASEL_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY WHERE 1=1 AND 1=1 GROUP BY DIM_RUN.N_RUN_SKEY ,DIM_DATES.N_DATE_SKEY ,DIM_MARKET_RISK_REP_LINE.N_REP_LINE_SKEY LOG ERRORS INTO FCT_MARKET_RISK_SUMMARY$ ('1776769786431_59002201_20260331_1_Job_80766911116c4ecd9749e1397b1c4a30') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
