-- =====================================================================
-- Task: MKT_RISK_POSITION_MAPPING_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_POSITION_MAPPING_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into RISK_POSITION_MAPPING(N_MIS_DATE_SKEY,N_LONG_POSITION_ACCT_SKEY,N_RUN_SKEY,N_SHORT_POSITION_ACCT_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),DIM_EXPOSURE.n_acct_skey,'870',DIM_EXPOSURE1.n_acct_skey FROM STG_RISK_POSITION_MAPPING LEFT OUTER JOIN DIM_DATES ON STG_RISK_POSITION_MAPPING.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE INNER JOIN DIM_EXPOSURE ON DIM_EXPOSURE.V_EXPOSURE_ID = STG_RISK_POSITION_MAPPING.V_LONG_POSITION_EXPOSURE_ID AND STG_RISK_POSITION_MAPPING.FIC_MIS_DATE BETWEEN DIM_EXPOSURE.D_RECORD_START_DATE AND DIM_EXPOSURE.D_RECORD_END_DATE INNER JOIN DIM_EXPOSURE DIM_EXPOSURE1 ON DIM_EXPOSURE1.V_EXPOSURE_ID = STG_RISK_POSITION_MAPPING.V_SHORT_POSITION_EXPOSURE_ID AND STG_RISK_POSITION_MAPPING.FIC_MIS_DATE BETWEEN DIM_EXPOSURE1.D_RECORD_START_DATE AND DIM_EXPOSURE1.D_RECORD_END_DATE WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND STG_RISK_POSITION_MAPPING.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND DIM_EXPOSURE.V_ACCT_TYPE = 'MR' AND DIM_EXPOSURE1.V_ACCT_TYPE = 'MR' LOG ERRORS INTO RISK_POSITION_MAPPING$ ('1776768394359_95999547_20260331_1_Job_f05d001dc9444d35a059a923e459f2ef') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
