-- =====================================================================
-- Task: MKT_RISK_GR_DPLUS_OPTION_EQUITY
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_GR_DPLUS_OPTION_EQUITY(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_EQ_CAPITAL(N_COUNTRY_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_GAAP_SKEY,N_GENERAL_RISK_CHARGE,N_LEG_REP_SKEY,N_REP_LINE_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_COUNTRY.N_COUNTRY_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),MAX(DIM_GAAP.n_gaap_skey),SUM(ABS(CASE WHEN FCT_MARKET_RISK_EXPOSURES.n_gamma_impact_value < 0 THEN FCT_MARKET_RISK_EXPOSURES.n_gamma_impact_value ELSE 0 END ) ) + SUM(0.25*FCT_MARKET_RISK_EXPOSURES.n_implied_volatility*FCT_MARKET_RISK_EXPOSURES.n_vega_value*0.01),MAX(DIM_ORG_STRUCTURE.N_ENTITY_SKEY),(SELECT n_rep_line_skey FROM DIM_MARKET_RISK_REP_LINE WHERE v_rep_line_code = 'OPEQDP') FROM FCT_MARKET_RISK_EXPOSURES INNER JOIN DIM_DATES ON FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.N_INSTR_TYPE_SKEY = DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY = DIM_COUNTRY.N_COUNTRY_SKEY LEFT OUTER JOIN DIM_ORG_STRUCTURE ON FCT_MARKET_RISK_EXPOSURES.N_LEG_REP_SKEY = DIM_ORG_STRUCTURE.N_ENTITY_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_EXPOSURES.N_BASEL_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT OUTER JOIN DIM_MARKET_RISK_POSITION ON FCT_MARKET_RISK_EXPOSURES.N_POSITION_SKEY = DIM_MARKET_RISK_POSITION.N_POSITION_SKEY LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON DIM_RUN.N_RUN_SKEY = FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 AND ( DIM_INSTRUMENT_TYPE.V_BASEL_INSTR_TYPE_CODE_LVL1 = 'OPT' AND DIM_INSTRUMENT_TYPE.V_RISK_FACTOR_TYPE_CODE = 'EQ' ) AND FCT_MARKET_RISK_EXPOSURES.N_VAR_PORT_SKEY IS NULL AND ( COALESCE(DIM_RUN.V_JURISDICTION_CODE, 'MISSING') = 'BRAZIL' OR RUN_PARAMETERS.V_MRS_OPTIONS_METHOD = 'OPT1014' ) GROUP BY DIM_RUN.N_RUN_SKEY ,DIM_DATES.N_DATE_SKEY ,DIM_COUNTRY.N_COUNTRY_SKEY LOG ERRORS INTO FCT_MARKET_RISK_EQ_CAPITAL$ ('1776769662777_73348610_20260331_1_Job_8bf04a02a06443b989241a59c91b081a') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
