-- =====================================================================
-- Task: MKT_RISK_VAR_DATA_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_VAR_DATA_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MR_VAR_DATA(N_MIS_DATE_SKEY,N_GAAP_SKEY,F_CTP_INCORP_VAR,F_NONSEC_NONCTP_INCORP_VAR,F_SEC_NON_CTP_INCORP_VAR,N_ACTUAL_PROFIT_LOSS,N_COMPREHENSIVE_RISK_MEASURE,N_HYPOTHETICAL_PROFIT_LOSS,N_INCREMENTAL_RISK_CHARGE,N_RUN_SKEY,N_SVAR_VALUE,V_CRM_FREQUENCY,V_IRC_FREQUENCY,V_SVAR_FREQUENCY,D_VAR_EXECUTION_DATE,N_VAR_VALUE,N_VAR_PORT_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),LAST_VALUE(STG_MR_VAR_DATA.f_ctp_incorp_var IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.f_nonsec_nonctp_incorp_var IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.f_sec_non_ctp_incorp_var IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.n_actual_profit_loss IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.n_comprehensive_risk_measure IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code ,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.n_hypothetical_profit_loss IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.n_incremental_risk_charge IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),'870',LAST_VALUE(STG_MR_VAR_DATA.n_svar_value IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.v_crm_frequency IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.v_svar_frequency IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),LAST_VALUE(STG_MR_VAR_DATA.v_svar_frequency IGNORE NULLS) OVER(PARTITION BY STG_MR_VAR_DATA.v_gaap_code,STG_MR_VAR_DATA.fic_mis_date,STG_MR_VAR_DATA.v_var_port_code ORDER BY STG_MR_VAR_DATA.d_var_execution_date),STG_MR_VAR_DATA.D_VAR_EXECUTION_DATE,to_char(STG_MR_VAR_DATA.N_VAR_VALUE),to_char(VAR_PORTFOLIO_MASTER.N_VAR_PORT_SKEY) FROM STG_MR_VAR_DATA LEFT OUTER JOIN DIM_DATES ON DIM_DATES.d_calendar_date = STG_MR_VAR_DATA.fic_mis_date LEFT OUTER JOIN VAR_PORTFOLIO_MASTER ON VAR_PORTFOLIO_MASTER.v_var_port_code = STG_MR_VAR_DATA.v_var_port_code LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.v_gaap_code = STG_MR_VAR_DATA.v_gaap_code AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE WHERE 1=1 AND 1=1 AND STG_MR_VAR_DATA.fic_mis_date = to_date('20260331','YYYYMMDD') LOG ERRORS INTO FCT_MR_VAR_DATA$ ('1776769842743_84476454_20260331_1_Job_d3633995cacc422280c023bf3ad92054') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
