-- =====================================================================
-- Task: MKT_RISK_TB_POP_DURATION_APPROACH_IR
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_TB_POP_DURATION_APPROACH_IR(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_CAPITAL(V_CCY_CODE,N_MIS_DATE_SKEY,N_REP_LINE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_GAAP_SKEY,N_IRC_BENCHMARK_SKEY,N_NET_GAMMA_IMPACT,N_REF_INDEX_SKEY,N_TIME_BAND_SKEY,N_TIME_ZONE_SKEY,N_VEGA_CAPITAL_CHARGE,N_WEIGHTED_LONG_POSITION_AMT,N_WEIGHTED_SHORT_POSITION_AMT,V_COMMODITY_GROUP_CODE)SELECT  /*+PARALLEL (4)*/ DIM_CURRENCY.V_ISO_CURRENCY_CD,to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_MARKET_RISK_REP_LINE.N_REP_LINE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),MAX(DIM_GAAP.n_gaap_skey),MAX((SELECT max(FSI_IRCS.Interest_Rate_Cd) FROM FSI_IRCS where FSI_IRCS.Irc_Name='OTH')),0,MAX((SELECT max(n_Mkt_Var_Skey) FROM DIM_MARKET_VARIABLES WHERE v_Mkt_Var_Code='OTH')),DIM_MR_TIME_BAND.N_BAND_SKEY,MAX(CASE WHEN DIM_MR_TIME_BAND.v_band_sub_category IN ( 'DBND1' ,'DBND2' ,'DBND3' ,'DBND4' ) THEN ( SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code = 'Z1' AND to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE ) WHEN DIM_MR_TIME_BAND.v_band_sub_category IN ( 'DBND5' ,'DBND6' ,'DBND7' ) THEN ( SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code = 'Z2' AND to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE ) WHEN DIM_MR_TIME_BAND.v_band_sub_category IN ( 'DBND8' ,'DBND9' ,'DBND10' ,'DBND11' ,'DBND12' ,'DBND13' ,'DBND14' ,'DBND15' ) THEN ( SELECT n_time_zone_skey FROM DIM_TIME_ZONE WHERE v_time_zone_code = 'Z3' AND to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE AND D_RECORD_END_DATE ) END) ,0,0,0,'NA' FROM FCT_MARKET_RISK_CAPITAL LEFT OUTER JOIN DIM_BANDS DIM_MR_TIME_BAND ON FCT_MARKET_RISK_CAPITAL.n_time_band_skey <> DIM_MR_TIME_BAND.N_BAND_SKEY AND DIM_MR_TIME_BAND.v_Band_Type = 'MR TIME BAND' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_MR_TIME_BAND.D_RECORD_START_DATE AND DIM_MR_TIME_BAND.D_RECORD_END_DATE LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_MARKET_RISK_CAPITAL.n_mis_date_skey LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_CAPITAL.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_CAPITAL.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN DIM_CURRENCY ON FCT_MARKET_RISK_CAPITAL.v_ccy_code = DIM_CURRENCY.v_iso_currency_cd AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CURRENCY.D_RECORD_START_DATE AND DIM_CURRENCY.D_RECORD_END_DATE LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_CAPITAL.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_MARKET_RISK_REP_LINE ON FCT_MARKET_RISK_CAPITAL.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE.n_rep_line_skey WHERE 1=1 AND 1=1 AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_CAPITAL.n_run_skey = '870' AND DIM_MR_TIME_BAND.v_band_sub_category like 'DBN%' AND DIM_MR_TIME_BAND.v_Band_Type = 'MR TIME BAND' AND (DIM_CURRENCY.v_iso_currency_cd, DIM_MR_TIME_BAND.n_band_skey, DIM_MARKET_RISK_REP_LINE.n_rep_line_skey) NOT IN (SELECT v_ccy_code, n_time_band_skey, n_rep_line_skey FROM FCT_MARKET_RISK_CAPITAL WHERE FCT_MARKET_RISK_CAPITAL.n_mis_date_skey = DIM_DATES.n_date_skey AND FCT_MARKET_RISK_CAPITAL.n_run_skey = '870' AND NVL(v_ccy_code, 'NA') <> 'NA') AND DIM_MARKET_RISK_REP_LINE.v_Rep_Line_Code in ('IR', 'OPIR') AND EXISTS (SELECT 1 FROM RUN_PARAMETERS WHERE RUN_PARAMETERS.v_mrs_interest_rate_method = 'OPT1003' AND RUN_PARAMETERS.n_run_skey = '870' AND RUN_PARAMETERS.n_date_skey = DIM_DATES.n_date_skey) GROUP BY DIM_MR_TIME_BAND.n_band_skey, DIM_CURRENCY.v_iso_currency_cd, DIM_DATES.n_date_skey, DIM_RUN.n_run_skey, DIM_MARKET_RISK_REP_LINE.n_rep_line_skey LOG ERRORS INTO FCT_MARKET_RISK_CAPITAL$ ('1776769459284_29989053_20260331_1_Job_8d6bed7612174239acbee6c42bbc4d9e') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
