-- =====================================================================
-- Task: MKT_RISK_SIM_APP_OPTION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_SIM_APP_OPTION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_SUMMARY(N_BASEL_METHOD_SKEY,N_CAPITAL_CHARGE,N_COUNTRY_SKEY,N_GAAP_SKEY,N_GENERAL_RISK_CHARGE,N_LEG_REP_SKEY,N_REP_LINE_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),0,MAX(DIM_COUNTRY.n_country_skey),MAX(DIM_GAAP.n_gaap_skey),0,MAX(DIM_ORG_STRUCTURE.N_ENTITY_SKEY),CASE WHEN DIM_INSTRUMENT_TYPE.v_risk_factor_type_code IN ('IR') THEN 10 WHEN DIM_INSTRUMENT_TYPE.v_risk_factor_type_code IN ('EQ') THEN 11 WHEN DIM_INSTRUMENT_TYPE.v_instr_type_code IN ('XSOPTSGLD') THEN 13 WHEN DIM_INSTRUMENT_TYPE.v_risk_factor_type_code IN ('XS') THEN 12 WHEN DIM_INSTRUMENT_TYPE.v_risk_factor_type_code IN ('CM') THEN 14 END,to_char(FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY) FROM FCT_MARKET_RISK_EXPOSURES JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.N_INSTR_TYPE_SKEY = DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY = DIM_COUNTRY.N_COUNTRY_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_ORG_STRUCTURE ON FCT_MARKET_RISK_EXPOSURES.N_LEG_REP_SKEY = DIM_ORG_STRUCTURE.N_ENTITY_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_EXPOSURES.N_BASEL_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 AND DIM_INSTRUMENT_TYPE.V_BASEL_INSTR_TYPE_CODE_LVL1 = 'OPT' AND FCT_MARKET_RISK_EXPOSURES.N_VAR_PORT_SKEY IS NULL AND RUN_PARAMETERS.V_MRS_OPTIONS_METHOD = 'OPT1013' GROUP BY FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY ,FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY ,CASE  WHEN DIM_INSTRUMENT_TYPE.V_RISK_FACTOR_TYPE_CODE IN ('IR') THEN 10 WHEN DIM_INSTRUMENT_TYPE.V_RISK_FACTOR_TYPE_CODE IN ('EQ') THEN 11 WHEN DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE IN ('XSOPTSGLD') THEN 13 WHEN DIM_INSTRUMENT_TYPE.V_RISK_FACTOR_TYPE_CODE IN ('XS') THEN 12 WHEN DIM_INSTRUMENT_TYPE.V_RISK_FACTOR_TYPE_CODE IN ('CM') THEN 14 END LOG ERRORS INTO FCT_MARKET_RISK_SUMMARY$ ('1776769758572_35033317_20260331_1_Job_ced4ea3bb38c4b4dbe093cba71b31a07') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
