-- =====================================================================
-- Task: MKT_RISK_DEDUCTION_CALC_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_DEDUCTION_CALC_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_CALC_ACCT_HEAD(F_CAP_DED_IND,N_COUNTRY_SKEY,N_CALC_ACCT_HEAD_AMT,V_RISK_TYPE_CODE,N_ENTITY_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ CASE WHEN MAX(DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID) IN ('CAP875','CAP876', 'CAP877', 'CAP502') THEN 'N' ELSE 'Y' END,MAX(fct_market_risk_exposures.n_country_skey),SUM(FCT_MARKET_RISK_EXPOSURES.N_POST_OFFSET_EXP_AMT),'MR',to_char(FCT_MARKET_RISK_EXPOSURES.N_ENTITY_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_STD_ACCT_HEAD_SKEY) FROM FCT_MARKET_RISK_EXPOSURES LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FCT_MARKET_RISK_EXPOSURES.N_STD_ACCT_HEAD_SKEY WHERE 1=1 AND FCT_MARKET_RISK_EXPOSURES.N_STD_ACCT_HEAD_SKEY IS NOT NULL AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = to_date('20260331','YYYYMMDD') AND DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID NOT IN ('CAP928') GROUP BY FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey, FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY, FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY, FCT_MARKET_RISK_EXPOSURES.N_STD_ACCT_HEAD_SKEY, FCT_MARKET_RISK_EXPOSURES.N_ENTITY_SKEY LOG ERRORS INTO FCT_CALC_ACCT_HEAD$ ('1776771025835_61818896_20260331_1_JOB_6997886344776204') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
