-- =====================================================================
-- Task: MKT_RISK_SIM_COMDTY_DPLUS_COMDTY_OPT
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_SIM_COMDTY_DPLUS_COMDTY_OPT(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_COM_CAPITAL(V_COMMODITY_GROUP_CODE,N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_CAPITAL_CHARGE,N_COUNTRY_SKEY,N_GAAP_SKEY,N_GAMMA_CAPITAL_CHARGE,N_LEG_REP_SKEY,N_REP_LINE_SKEY,N_VEGA_CAPITAL_CHARGE)SELECT  /*+PARALLEL (4)*/ DIM_COMMODITY.V_COMMODITY_GROUP_CODE,to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),SUM (CASE WHEN DIM_INSTRUMENT_TYPE.v_derivative_type_code = 'OPTS' THEN FCT_MARKET_RISK_EXPOSURES.n_gamma_impact_value + (0.25*FCT_MARKET_RISK_EXPOSURES.n_implied_volatility* FCT_MARKET_RISK_EXPOSURES.n_vega_value*0.01) ELSE 0.15*ABS(CASE WHEN v_position_code = 'LONG' THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt WHEN v_position_code = 'SHORT' THEN -1*FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END ) + 0.03*(CASE WHEN v_position_code IN ('LONG', 'SHORT') THEN FCT_MARKET_RISK_EXPOSURES.n_post_offset_exp_amt ELSE 0 END) END),MAX(DIM_COUNTRY.n_country_skey),MAX(DIM_GAAP.n_gaap_skey),SUM(FCT_MARKET_RISK_EXPOSURES.n_gamma_impact_value),MAX(DIM_ORG_STRUCTURE.N_ENTITY_SKEY),MAX(CASE WHEN DIM_INSTRUMENT_TYPE.v_derivative_type_code = 'OPTS' THEN (SELECT n_rep_line_skey FROM DIM_MARKET_RISK_REP_LINE WHERE v_rep_line_code = 'OPCMDP') ELSE (SELECT n_rep_line_skey FROM DIM_MARKET_RISK_REP_LINE WHERE v_rep_line_code = 'CO') END),SUM(0.25*FCT_MARKET_RISK_EXPOSURES.n_implied_volatility*FCT_MARKET_RISK_EXPOSURES.n_vega_value*0.01) FROM FCT_MARKET_RISK_EXPOSURES LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.N_INSTR_TYPE_SKEY = DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY = DIM_COUNTRY.N_COUNTRY_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' AND FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_ORG_STRUCTURE ON FCT_MARKET_RISK_EXPOSURES.N_LEG_REP_SKEY = DIM_ORG_STRUCTURE.N_ENTITY_SKEY AND DIM_ORG_STRUCTURE.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_EXPOSURES.N_BASEL_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT OUTER JOIN DIM_COMMODITY ON FCT_MARKET_RISK_EXPOSURES.N_COMMODITY_SKEY = DIM_COMMODITY.N_COMMODITY_SKEY LEFT OUTER JOIN DIM_MARKET_RISK_POSITION ON FCT_MARKET_RISK_EXPOSURES.N_POSITION_SKEY = DIM_MARKET_RISK_POSITION.N_POSITION_SKEY LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 AND ( DIM_INSTRUMENT_TYPE.V_BASEL_INSTR_TYPE_CODE_LVL1 = 'COM' OR ( DIM_INSTRUMENT_TYPE.V_RISK_FACTOR_TYPE_CODE = 'CM' AND DIM_INSTRUMENT_TYPE.V_DERIVATIVE_TYPE_CODE = 'OPTS' ) ) AND FCT_MARKET_RISK_EXPOSURES.N_VAR_PORT_SKEY IS NULL AND ( COALESCE(DIM_RUN.V_JURISDICTION_CODE, 'MISSING') = 'BRAZIL' OR RUN_PARAMETERS.V_MRS_OPTIONS_METHOD = 'OPT1014' ) GROUP BY ( CASE  WHEN DIM_INSTRUMENT_TYPE.V_DERIVATIVE_TYPE_CODE = 'OPTS' THEN 0 ELSE 1 END ) ,DIM_RUN.N_RUN_SKEY ,DIM_DATES.N_DATE_SKEY ,DIM_COMMODITY.V_COMMODITY_GROUP_CODE LOG ERRORS INTO FCT_MARKET_RISK_COM_CAPITAL$ ('1776769500715_38123134_20260331_1_Job_d273be2d0c014e7581580925e4018721') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
