-- =====================================================================
-- Task: MKT_RISK_CR_DPLUS_OPTION_FOREX
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_CR_DPLUS_OPTION_FOREX(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_SUMMARY(N_MIS_DATE_SKEY,N_REP_LINE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_CAPITAL_CHARGE,N_COUNTRY_SKEY,N_GAAP_SKEY,N_GENERAL_RISK_CHARGE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_MARKET_RISK_REP_LINE.N_REP_LINE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),SUM(ABS(FCT_MARKET_RISK_FOREX.n_vega_capital_charge) + ABS(CASE WHEN FCT_MARKET_RISK_FOREX.n_gamma_capital_charge<0 THEN FCT_MARKET_RISK_FOREX.n_gamma_capital_charge ELSE 0 END)),MAX(DIM_COUNTRY.n_country_skey),MAX(DIM_GAAP.n_gaap_skey),0 FROM FCT_MARKET_RISK_FOREX LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_FOREX.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_FOREX.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_DATES ON FCT_MARKET_RISK_FOREX.n_mis_date_skey = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_FOREX.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_FOREX.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN DIM_MARKET_RISK_REP_LINE ON FCT_MARKET_RISK_FOREX.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE.n_rep_line_skey LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON DIM_RUN.N_RUN_SKEY = FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND RUN_PARAMETERS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_FOREX.n_run_skey = '870' AND DIM_MARKET_RISK_REP_LINE.v_rep_line_code = 'OPFXDP' AND (COALESCE(DIM_RUN.v_jurisdiction_code, 'MISSING') = 'BRAZIL' OR RUN_PARAMETERS.v_mrs_options_method = 'OPT1014') GROUP BY DIM_RUN.n_run_skey, DIM_DATES.n_date_skey, DIM_MARKET_RISK_REP_LINE.n_rep_line_skey LOG ERRORS INTO FCT_MARKET_RISK_SUMMARY$ ('1776769725035_27768744_20260331_1_Job_fdb157baf3ab4009ad2e9441848dacbe') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
