-- =====================================================================
-- Task: MKT_RISK_GR_DPLUS_OPTION_FOREX
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_GR_DPLUS_OPTION_FOREX(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_FOREX(V_CCY_CODE,N_MIS_DATE_SKEY,N_RUN_SKEY,N_BASEL_METHOD_SKEY,N_COUNTRY_SKEY,N_ENTITY_SKEY,N_EXCHANGE_RATE,N_EXPOSURE_AMT_NCY,N_GAAP_SKEY,N_GAMMA_CAPITAL_CHARGE,N_REP_LINE_SKEY,N_VEGA_CAPITAL_CHARGE)SELECT  /*+PARALLEL (4)*/ DIM_CURRENCY.V_ISO_CURRENCY_CD,to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),MAX(DIM_BASEL_METHODOLOGY.n_basel_method_skey),FCT_MARKET_RISK_EXPOSURES.n_country_skey,FCT_MARKET_RISK_EXPOSURES.n_entity_skey,MAX(FN_COM_DT_CCY_CONV_FACTOR(FCT_MARKET_RISK_EXPOSURES.V_CCY_CODE, (SELECT V_PARAM_VALUE_CODE FROM RUN_EXE_PARAMETERS WHERE V_PARAM_ID = 'RCY' AND N_RUN_SKEY = '870'), to_date('20260331','YYYYMMDD'), to_date('20260331','YYYYMMDD'), '870', (SELECT N_ENTITY_SKEY FROM FCT_ENTITY_INFO INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY WHERE DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND N_RUN_SKEY = '870' AND F_CAP_CONSL_PARENT_ENTITY_IND = 'Y'))),0,(SELECT FCT_ENTITY_INFO.N_GAAP_SKEY FROM FCT_ENTITY_INFO LEFT OUTER JOIN DIM_DATES ON FCT_ENTITY_INFO.n_Mis_Date_Skey = DIM_DATES.N_DATE_SKEY WHERE FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD')),SUM(FCT_MARKET_RISK_EXPOSURES.n_gamma_impact_value),(SELECT n_rep_line_skey FROM DIM_MARKET_RISK_REP_LINE WHERE v_rep_line_code = 'OPFXDP'),SUM(0.25*FCT_MARKET_RISK_EXPOSURES.n_implied_volatility*FCT_MARKET_RISK_EXPOSURES.n_vega_value*0.01) FROM FCT_MARKET_RISK_EXPOSURES LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON FCT_MARKET_RISK_EXPOSURES.N_INSTR_TYPE_SKEY = DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_EXPOSURES.N_COUNTRY_SKEY = DIM_COUNTRY.N_COUNTRY_SKEY LEFT OUTER JOIN DIM_DATES ON FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_EXPOSURES.N_BASEL_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY LEFT OUTER JOIN DIM_MARKET_RISK_POSITION ON FCT_MARKET_RISK_EXPOSURES.N_POSITION_SKEY = DIM_MARKET_RISK_POSITION.N_POSITION_SKEY LEFT OUTER JOIN DIM_CURRENCY ON ( FCT_MARKET_RISK_EXPOSURES.V_BUY_REC_CCY_CODE = DIM_CURRENCY.V_ISO_CURRENCY_CD OR FCT_MARKET_RISK_EXPOSURES.V_SELL_PAY_CCY_CODE = DIM_CURRENCY.V_ISO_CURRENCY_CD ) AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_CURRENCY.D_RECORD_START_DATE AND DIM_CURRENCY.D_RECORD_END_DATE /*LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON DIM_RUN_IDENTIFIER.N_RUN_IDENTIFIER_SKEY = FCT_MARKET_RISK_EXPOSURES.N_RUN_IDENTIFIER_SKEY LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND RUN_PARAMETERS.N_RUN_SKEY = '870' AND ( DIM_RUN.F_RUN_DEFINITION_MODE = 'U' OR ( DIM_RUN.F_RUN_DEFINITION_MODE = 'R' AND DIM_RUN_IDENTIFIER.V_RUN_IDENTIFIER_CODE = RUN_PARAMETERS.V_RUN_IDENTIFIER_CODE ) ) */ LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON DIM_RUN.N_RUN_SKEY = FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'MR' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND RUN_PARAMETERS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_EXPOSURES.n_run_skey = '870' AND ( DIM_INSTRUMENT_TYPE.v_basel_instr_type_code_lvl1 LIKE 'OPT' AND DIM_INSTRUMENT_TYPE.v_risk_factor_type_code = 'XS' ) AND FCT_MARKET_RISK_EXPOSURES.n_var_port_skey IS NULL AND ( COALESCE(DIM_RUN.v_jurisdiction_code, 'MISSING') = 'BRAZIL' OR RUN_PARAMETERS.v_mrs_options_method = 'OPT1014' ) GROUP BY DIM_RUN.n_run_skey ,DIM_DATES.N_DATE_SKEY ,DIM_CURRENCY.v_iso_currency_cd ,RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY ,FCT_MARKET_RISK_EXPOSURES.n_country_skey ,FCT_MARKET_RISK_EXPOSURES.N_ENTITY_SKEY LOG ERRORS INTO FCT_MARKET_RISK_FOREX$ ('1776769679437_35779756_20260331_1_Job_c7a752d994584df28e669e8672aae0c9') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
