-- =====================================================================
-- Task: MKT_RISK_REPORTING_POP_MAT_COM
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_REPORTING_POP_MAT_COM(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MARKET_RISK_REPORTING(N_MIS_DATE_SKEY,N_REP_LINE_SKEY,N_RUN_SKEY,N_COUNTRY_SKEY,N_OFFST_MW_TB_POS,N_OFFST_MW_TB_RW,N_OVERALL_NET_POS,N_OVERALL_NET_POS_RW,N_UNMATCHED_CARRIED_FWD_POS,N_UNMATCHED_CARRIED_FWD_RW,V_APPROACH_TYPE,V_CCY_CODE,V_COMMODITY_GROUP_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_MARKET_RISK_REP_LINE.N_REP_LINE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),((SELECT n_country_skey from DIM_COUNTRY WHERE v_country_id = 'US' AND DIM_DATES.D_CALENDAR_DATE between DIM_COUNTRY.d_record_start_date and DIM_COUNTRY.d_record_end_date)),SUM(n_offst_match_within_tb+n_offst_match_within_zone),MAX((SELECT v_param_value FROM REVELEUS_PARAMETER_MASTER WHERE v_param_code = 'CMMP')),SUM(CASE WHEN DIM_MR_TIME_BAND.v_band_sub_category = 'CBND7' THEN ABS(n_offst_unmatch_within_zone) ELSE 0 END ),((SELECT v_param_value FROM REVELEUS_PARAMETER_MASTER WHERE v_param_code = 'CMNU')),SUM(CASE WHEN DIM_MR_TIME_BAND.v_band_sub_category in ('CBND1', 'CBND2', 'CBND3', 'CBND4', 'CBND5', 'CBND6') THEN ABS(n_offst_unmatch_within_zone) ELSE 0 END ),MAX((SELECT v_param_value FROM REVELEUS_PARAMETER_MASTER WHERE v_param_code = 'CMUP')),'MAT','NA',FCT_MARKET_RISK_CAPITAL.V_COMMODITY_GROUP_CODE FROM FCT_MARKET_RISK_CAPITAL LEFT OUTER JOIN DIM_BANDS DIM_MR_TIME_BAND ON FCT_MARKET_RISK_CAPITAL.n_time_band_skey = DIM_MR_TIME_BAND.n_Band_Skey AND DIM_MR_TIME_BAND.v_Band_Type = 'MR TIME BAND' LEFT OUTER JOIN DIM_DATES ON FCT_MARKET_RISK_CAPITAL.n_mis_date_skey = DIM_DATES.N_DATE_SKEY LEFT OUTER JOIN DIM_RUN ON FCT_MARKET_RISK_CAPITAL.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_CAPITAL.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_CAPITAL.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_CAPITAL.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_MARKET_RISK_REP_LINE ON FCT_MARKET_RISK_CAPITAL.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE.n_rep_line_skey WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_MARKET_RISK_CAPITAL.n_run_skey = '870' AND DIM_MARKET_RISK_REP_LINE.v_rep_line_code = 'CO' AND DIM_MR_TIME_BAND.v_band_sub_category like 'CBN%' GROUP BY DIM_DATES.N_DATE_SKEY, DIM_DATES.D_CALENDAR_DATE, DIM_RUN.n_run_skey, FCT_MARKET_RISK_CAPITAL.v_commodity_group_code, DIM_MARKET_RISK_REP_LINE.n_rep_line_skey, DIM_COUNTRY.n_country_skey LOG ERRORS INTO FCT_MARKET_RISK_REPORTING$ ('1776769820362_41696164_20260331_1_Job_51d2798fd53245c2ba87c42b59c9a9d1') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
