-- =====================================================================
-- Task: MKT_RISK_BSKT_UNDERLYING_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_BSKT_UNDERLYING_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_UNDERLYING_DTL(N_MIS_DATE_SKEY,D_ISSUE_DATE,D_MATURITY_DATE,F_QUALIFYING_INS_FLAG,F_SECURITIZED_FLAG,N_COUPON_FREQ,N_COUPON,N_PAR_VALUE_NCY,N_INSTRUMENT_SKEY,V_CCY_CODE,V_DAY_COUNTER,V_RATING_ID,N_INSTR_TYPE_SKEY,N_ISSUE_SKEY,N_MR_ISSUER_TYPE_SKEY,N_CONTRACT_ACCT_SKEY,N_EXCHANGE_RATE,N_RESIDUAL_MATURITY,N_RUN_SKEY,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_CTD_CONVERSION_FACTOR,N_CURR_MKT_VALUE_NCY,N_OUTSTANDING_UNITS)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),DIM_INSTRUMENT_CONTRACT.D_EFFECTIVE_DATE,DIM_INSTRUMENT_CONTRACT.D_MATURITY_DATE,DIM_INSTRUMENT_CONTRACT.F_QUALIFYING_INS_FLAG,DIM_INSTRUMENT_CONTRACT.F_SECURITIZED_FLAG,to_char(DIM_INSTRUMENT_CONTRACT.N_COUPON_FREQUENCY),to_char(DIM_INSTRUMENT_CONTRACT.N_COUPON_RATE),to_char(DIM_INSTRUMENT_CONTRACT.N_FACE_VALUE),to_char(DIM_INSTRUMENT_CONTRACT.N_INSTRUMENT_SKEY),DIM_INSTRUMENT_CONTRACT.V_CCY_CODE,DIM_INSTRUMENT_CONTRACT.V_DAY_COUNTER,DIM_INSTRUMENT_CONTRACT.V_RATING_CODE,to_char(DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY),to_char(DIM_ISSUE.N_ISSUE_SKEY),to_char(DIM_MR_COUNTER_PARTY.N_COUNTER_PARTY_SKEY),(SELECT DIM_EXPOSURE.n_acct_skey FROM DIM_EXPOSURE WHERE DIM_EXPOSURE.v_exposure_id = STG_UNDERLYING_DTL.v_contract_instrument_code and STG_UNDERLYING_DTL.FIC_MIS_DATE between dim_exposure.d_record_start_date and dim_exposure.d_record_end_date),FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,CASE WHEN DIM_INSTRUMENT_CONTRACT.v_day_counter = 'Actual/360' THEN (((DIM_INSTRUMENT_CONTRACT.d_maturity_date - DIM_INSTRUMENT_CONTRACT.fic_mis_date) / 360)) WHEN DIM_INSTRUMENT_CONTRACT.v_day_counter = 'Actual/365' THEN (((DIM_INSTRUMENT_CONTRACT.d_maturity_date - DIM_INSTRUMENT_CONTRACT.fic_mis_date) / 365)) WHEN DIM_INSTRUMENT_CONTRACT.v_day_counter = 'Thirty/30' THEN DAYS360(DIM_INSTRUMENT_CONTRACT.d_maturity_date, DIM_INSTRUMENT_CONTRACT.fic_mis_date) / 360 ELSE (((DIM_INSTRUMENT_CONTRACT.d_maturity_date - DIM_INSTRUMENT_CONTRACT.fic_mis_date) / 365)) END,'870',to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_IDENTIFIER_SKEY),to_char(FCT_MARKET_RISK_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY),to_char(STG_CTD_MAPPING.N_CONVERSION_FACTOR),to_char(STG_UNDERLYING_DTL.N_CURR_MKT_VALUE),to_char(STG_UNDERLYING_DTL.N_OUTSTANDING_UNITS) FROM STG_UNDERLYING_DTL INNER JOIN DIM_DATES ON STG_UNDERLYING_DTL.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE AND STG_UNDERLYING_DTL.fic_mis_date = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_INSTRUMENT_TYPE ON STG_UNDERLYING_DTL.V_INSTRUMENT_TYPE_CD = DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_INSTRUMENT_TYPE.D_RECORD_START_DATE AND DIM_INSTRUMENT_TYPE.D_RECORD_END_DATE INNER JOIN DIM_INSTRUMENT_CONTRACT ON STG_UNDERLYING_DTL.v_Instrument_Code = DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_INSTRUMENT_CONTRACT.D_RECORD_START_DATE AND DIM_INSTRUMENT_CONTRACT.D_RECORD_END_DATE AND DIM_INSTRUMENT_CONTRACT.fic_mis_date = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_MR_COUNTER_PARTY ON DIM_MR_COUNTER_PARTY.V_COUNTER_PARTY_CODE = DIM_INSTRUMENT_CONTRACT.V_ISSUER_TYPE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_MR_COUNTER_PARTY.D_RECORD_START_DATE AND DIM_MR_COUNTER_PARTY.D_RECORD_END_DATE LEFT OUTER JOIN STG_CTD_MAPPING ON STG_UNDERLYING_DTL.V_INSTRUMENT_CODE = STG_CTD_MAPPING.V_UNDERLYING_BOND_CODE AND STG_CTD_MAPPING.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') INNER JOIN dim_exposure ON dim_exposure.v_exposure_id = STG_UNDERLYING_DTL.v_Contract_Instrument_Code AND to_date('20260331','YYYYMMDD') BETWEEN dim_exposure.d_record_start_date AND dim_exposure.d_record_end_date INNER JOIN FCT_MARKET_RISK_EXPOSURES ON FCT_MARKET_RISK_EXPOSURES.n_mis_date_skey = dim_dates.n_date_skey AND FCT_MARKET_RISK_EXPOSURES.n_acct_skey = dim_exposure.n_acct_skey AND FCT_MARKET_RISK_EXPOSURES.n_run_skey = '870' LEFT OUTER JOIN DIM_ISSUE ON COALESCE(STG_UNDERLYING_DTL.v_contract_instrument_code, DIM_EXPOSURE.V_EXPOSURE_ID) = DIM_ISSUE.v_issue_code AND to_date('20260331','YYYYMMDD') BETWEEN COALESCE(DIM_ISSUE.d_record_start_date, to_date('20260331','YYYYMMDD')) AND COALESCE(DIM_ISSUE.d_record_end_date, to_date('20260331','YYYYMMDD')) LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = '870' AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = DIM_INSTRUMENT_CONTRACT.V_CCY_CODE WHERE 1=1 AND 1=1 LOG ERRORS INTO FCT_UNDERLYING_DTL$ ('1776768575751_90221206_20260331_1_Job_bec6021aff5347e48f1ccce9dc12a255') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
