-- =====================================================================
-- Task: MKT_RISK_VAR_SUMMARY_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MKT_RISK_VAR_SUMMARY_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MR_VAR_SUMMARY_DATA(N_MIS_DATE_SKEY,N_BASEL_PREV_DAY_SVAR_VALUE,N_BASEL_PREV_DAY_VAR_VALUE,F_CTP_INCORP_VAR,F_NONSEC_NONCTP_INCORP_VAR,N_ACTUAL_PROFIT_LOSS,N_BASEL_SVAR_VALUE,N_BASEL_VAR_VALUE,N_COMPREHENSIVE_RISK_MEASURE,N_GAAP_SKEY,N_HYPOTHETICAL_PROFIT_LOSS,N_INCREMENTAL_RISK_CHARGE,N_RUN_SKEY,N_SVAR_VALUE,N_VAR_PORT_SKEY,N_VAR_VALUE,V_CRM_FREQUENCY,V_IRC_FREQUENCY,V_SVAR_FREQUENCY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),lag(n_svar_value,1) over(order by /*fic_mis_date*/ DIM_DATES.d_calendar_date),lag(n_var_value ,1) over(order by /*fic_mis_date*/ DIM_DATES.d_calendar_date),FCT_MR_VAR_DATA.F_CTP_INCORP_VAR,FCT_MR_VAR_DATA.F_NONSEC_NONCTP_INCORP_VAR,to_char(FCT_MR_VAR_DATA.N_ACTUAL_PROFIT_LOSS),to_char(FCT_MR_VAR_DATA.N_BASEL_SVAR_VALUE),to_char(FCT_MR_VAR_DATA.N_BASEL_VAR_VALUE),to_char(FCT_MR_VAR_DATA.N_COMPREHENSIVE_RISK_MEASURE),to_char(FCT_MR_VAR_DATA.N_GAAP_SKEY),to_char(FCT_MR_VAR_DATA.N_HYPOTHETICAL_PROFIT_LOSS),to_char(FCT_MR_VAR_DATA.N_INCREMENTAL_RISK_CHARGE),to_char(FCT_MR_VAR_DATA.N_RUN_SKEY),to_char(FCT_MR_VAR_DATA.N_SVAR_VALUE),to_char(FCT_MR_VAR_DATA.N_VAR_PORT_SKEY),to_char(FCT_MR_VAR_DATA.N_VAR_VALUE),FCT_MR_VAR_DATA.V_CRM_FREQUENCY,FCT_MR_VAR_DATA.V_IRC_FREQUENCY,FCT_MR_VAR_DATA.V_SVAR_FREQUENCY FROM FCT_MR_VAR_DATA LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_MR_VAR_DATA.n_mis_date_skey WHERE 1=1 AND 1=1 AND DIM_DATES.d_calendar_date =to_date('20260331','YYYYMMDD') AND FCT_MR_VAR_DATA.n_run_skey ='870' AND FCT_MR_VAR_DATA.d_var_execution_date = DIM_DATES.d_calendar_date LOG ERRORS INTO FCT_MR_VAR_SUMMARY_DATA$ ('1776769868624_73713918_20260331_1_Job_4079dbb343294f1d94c1334445814674') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
