-- =====================================================================
-- Task: MR_PC_Aggregation_of_Specific_Risk_Charge_to_Parent_Contracts
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MR_PC_Aggregation_of_Specific_Risk_Charge_to_Parent_Contracts(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_MARKET_RISK_EXPOSURES TT USING (   SELECT  /*+ PARALLEL(4) */ FCT_MARKET_RISK_EXPOSURES.N_ACCT_SKEY,FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY,FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY,FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY, MIN(FCT_MARKET_RISK_EXPOSURES.N_SPECIFIC_RISK_CHARGE) AS  T_1472209534402_0,   MIN(CASE  WHEN  ( ((      DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE  = 'EQSPOTSPT')) OR ((      DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE  = 'IRSPOTFLB')) OR ((      DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE  = 'IRSPOTFIB')) ) THEN 10 ELSE 11 END)  AS COND_1472209534402_10 ,  (SUM(COALESCE(CASE WHEN 1 = 1 THEN FCT_MKT_RISK_EXP_DETAILS.n_post_offset_exp_amt ELSE NULL END ,0) * COALESCE(CASE WHEN 1 = 1 THEN FCT_MKT_RISK_EXP_DETAILS.n_specific_risk_weight ELSE NULL END ,0))) AS EXP_1472209534402_10,MIN(FCT_MARKET_RISK_EXPOSURES.N_SPECIFIC_RISK_CHARGE) AS EXP_1472209534402_11  FROM  FCT_MARKET_RISK_EXPOSURES INNER JOIN DIM_RUN ON FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY INNER JOIN DIM_DATES ON FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY INNER JOIN FCT_MARKET_RISK_EXPOSURES FCT_MKT_RISK_EXP_DETAILS ON FCT_MKT_RISK_EXP_DETAILS.N_CONTRACT_ACCT_SKEY = FCT_MARKET_RISK_EXPOSURES.N_ACCT_SKEY AND FCT_MKT_RISK_EXP_DETAILS.N_RUN_SKEY = FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY AND FCT_MKT_RISK_EXP_DETAILS.N_MIS_DATE_SKEY = FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY AND FCT_MKT_RISK_EXP_DETAILS.N_GAAP_SKEY = FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY INNER JOIN DIM_INSTRUMENT_TYPE DIM_CONTRACT_INSTRUMENT_TYPE ON DIM_CONTRACT_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY = FCT_MARKET_RISK_EXPOSURES.N_INSTR_TYPE_SKEY LEFT OUTER JOIN DIM_MARKET_RISK_POSITION DIM_CONTRACT_RISK_POSITION ON DIM_CONTRACT_RISK_POSITION.N_POSITION_SKEY = FCT_MARKET_RISK_EXPOSURES.N_POSITION_SKEY LEFT OUTER JOIN DIM_INSTRUMENT_TYPE ON DIM_INSTRUMENT_TYPE.N_INSTR_TYPE_SKEY = FCT_MKT_RISK_EXP_DETAILS.N_INSTR_TYPE_SKEY LEFT OUTER JOIN DIM_MARKET_RISK_POSITION ON DIM_MARKET_RISK_POSITION.N_POSITION_SKEY = FCT_MKT_RISK_EXP_DETAILS.N_POSITION_SKEY  WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = TO_DATE('20260331','yyyymmdd') AND FCT_MKT_RISK_EXP_DETAILS.N_ACCT_SKEY IS NOT NULL)  AND ( (((      DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE  = 'EQSPOTSPT')) OR ((      DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE  = 'IRSPOTFLB')) OR ((      DIM_INSTRUMENT_TYPE.V_INSTR_TYPE_CODE  = 'IRSPOTFIB')))  )  GROUP BY FCT_MARKET_RISK_EXPOSURES.N_ACCT_SKEY,FCT_MARKET_RISK_EXPOSURES.N_RUN_SKEY,FCT_MARKET_RISK_EXPOSURES.N_GAAP_SKEY,FCT_MARKET_RISK_EXPOSURES.N_MIS_DATE_SKEY ) SS ON ( TT.N_ACCT_SKEY= SS.N_ACCT_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_SPECIFIC_RISK_CHARGE=  CASE  WHEN  COND_1472209534402_10=10 THEN EXP_1472209534402_10 ELSE EXP_1472209534402_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
