-- =====================================================================
-- Task: MR_SP_RW_MAPPING_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MR_SP_RW_MAPPING_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into MR_SP_RW_MAPPING(N_BASEL_RATING,N_MIS_DATE_SKEY,N_CATEGORY_SKEY,N_RUN_SKEY,N_SP_RW,N_TIME_BAND_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_CREDIT_RATING.N_BASEL_RATING),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_MR_SP_RW_CATEGORY.N_CATEGORY_SKEY),'870',CASE WHEN V_CATEGORY_CODE = 'OTH' AND DIM_BASEL_CREDIT_RATING.v_Rating_Desc IN ('AAA Equivalent','AA+ Equivalent','AA Equivalent','AA- Equivalent','A+ Equivalent','A Equivalent','A- Equivalent','BBB+ Equivalent','BBB Equivalent','BBB- Equivalent') THEN 0 END,DIM_MR_TIME_BAND.N_BAND_SKEY FROM DIM_MR_SP_RW_CATEGORY INNER JOIN DIM_BASEL_CREDIT_RATING ON 1=1 INNER JOIN DIM_BANDS DIM_MR_TIME_BAND ON 1=1 INNER JOIN DIM_DATES ON 1 = 1 WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_MR_SP_RW_CATEGORY.D_RECORD_START_DATE AND DIM_MR_SP_RW_CATEGORY.D_RECORD_END_DATE AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_BASEL_CREDIT_RATING.D_RECORD_START_DATE AND DIM_BASEL_CREDIT_RATING.D_RECORD_END_DATE AND DIM_MR_TIME_BAND.V_BAND_CATEGORY = 'RM' AND DIM_MR_TIME_BAND.V_BAND_TYPE = 'MR TIME BAND' AND (DIM_BASEL_CREDIT_RATING.n_basel_rating > 0 AND DIM_BASEL_CREDIT_RATING.n_basel_rating <= (SELECT n_basel_rating FROM DIM_BASEL_CREDIT_RATING WHERE v_rating_desc = 'Lower B- Equivalent'and to_date('20260331','YYYYMMDD') BETWEEN D_RECORD_START_DATE and D_RECORD_END_DATE) OR DIM_BASEL_CREDIT_RATING.v_rating_desc = 'Unrated') AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LOG ERRORS INTO MR_SP_RW_MAPPING$ ('1776768804004_77906750_20260331_1_Job_fd4932454cf4484ab5a3cc179fe96593') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
