-- =====================================================================
-- Task: MR_Sensitivity_Charge_Population_for_IR_Options_Delta_Plus_Method
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.MR_Sensitivity_Charge_Population_for_IR_Options_Delta_Plus_Method(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_MARKET_RISK_SUMMARY TT USING (   SELECT  /*+ PARALLEL(4) */ FCT_MARKET_RISK_SUMMARY.N_RUN_SKEY,FCT_MARKET_RISK_SUMMARY.N_REP_LINE_SKEY,FCT_MARKET_RISK_SUMMARY.N_GAAP_SKEY,FCT_MARKET_RISK_SUMMARY.N_MIS_DATE_SKEY, MIN(FCT_MARKET_RISK_SUMMARY.N_GAMMA_CAPITAL_CHARGE) AS  T_1371650312072_0,   MIN(CASE  WHEN  ( ((DIM_MARKET_RISK_REP_LINE.v_rep_line_code = 'OPIRDP')) ) THEN 10 ELSE 11 END)  AS COND_1371650312072_10 ,  (SUM(COALESCE(CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_IR_CAPITAL.n_gamma_capital_charge ELSE NULL END ,0))) AS EXP_1371650312072_10,MIN(FCT_MARKET_RISK_SUMMARY.N_GAMMA_CAPITAL_CHARGE) AS EXP_1371650312072_11 , MIN(FCT_MARKET_RISK_SUMMARY.N_VEGA_CAPITAL_CHARGE) AS  T_1371650312072_1,   MIN(CASE  WHEN  ( ((DIM_MARKET_RISK_REP_LINE.v_rep_line_code = 'OPIRDP')) ) THEN 20 ELSE 21 END)  AS COND_1371650312072_20 ,  (SUM(COALESCE(CASE WHEN 1 = 1 THEN FCT_MARKET_RISK_IR_CAPITAL.n_vega_capital_charge ELSE NULL END ,0))) AS EXP_1371650312072_20,MIN(FCT_MARKET_RISK_SUMMARY.N_VEGA_CAPITAL_CHARGE) AS EXP_1371650312072_21  FROM  FCT_MARKET_RISK_SUMMARY LEFT OUTER JOIN DIM_DATES ON FCT_MARKET_RISK_SUMMARY.n_mis_date_skey = DIM_DATES.n_date_skey JOIN DIM_RUN ON FCT_MARKET_RISK_SUMMARY.n_run_skey = DIM_RUN.n_run_skey AND DIM_RUN.n_run_skey = '870' LEFT OUTER JOIN DIM_COUNTRY ON FCT_MARKET_RISK_SUMMARY.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_GAAP ON FCT_MARKET_RISK_SUMMARY.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_MARKET_RISK_SUMMARY.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN DIM_MARKET_RISK_REP_LINE ON FCT_MARKET_RISK_SUMMARY.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE.n_rep_line_skey LEFT OUTER JOIN (FCT_MARKET_RISK_IR_CAPITAL INNER JOIN DIM_MARKET_RISK_REP_LINE DIM_MARKET_RISK_REP_LINE_1 ON FCT_MARKET_RISK_IR_CAPITAL.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE_1.n_rep_line_skey INNER JOIN DIM_CURRENCY ON FCT_MARKET_RISK_IR_CAPITAL.v_ccy_code = DIM_CURRENCY.v_iso_currency_cd) ON FCT_MARKET_RISK_IR_CAPITAL.n_rep_line_skey = FCT_MARKET_RISK_SUMMARY.n_rep_line_skey AND FCT_MARKET_RISK_IR_CAPITAL.n_mis_date_skey = FCT_MARKET_RISK_SUMMARY.n_mis_date_skey AND FCT_MARKET_RISK_IR_CAPITAL.n_run_skey = FCT_MARKET_RISK_SUMMARY.n_run_skey AND FCT_MARKET_RISK_IR_CAPITAL.n_Gaap_Skey = FCT_MARKET_RISK_SUMMARY.n_Gaap_Skey LEFT OUTER JOIN (FCT_MARKET_RISK_EQ_CAPITAL INNER JOIN DIM_MARKET_RISK_REP_LINE DIM_MARKET_RISK_REP_LINE_2 ON FCT_MARKET_RISK_EQ_CAPITAL.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE_2.n_rep_line_skey) ON FCT_MARKET_RISK_EQ_CAPITAL.n_rep_line_skey = FCT_MARKET_RISK_SUMMARY.n_rep_line_skey AND FCT_MARKET_RISK_EQ_CAPITAL.n_mis_date_skey = FCT_MARKET_RISK_SUMMARY.n_mis_date_skey AND FCT_MARKET_RISK_EQ_CAPITAL.n_run_skey = FCT_MARKET_RISK_SUMMARY.n_run_skey AND FCT_MARKET_RISK_EQ_CAPITAL.n_Gaap_Skey = FCT_MARKET_RISK_SUMMARY.n_Gaap_Skey LEFT OUTER JOIN (FCT_MARKET_RISK_COM_CAPITAL INNER JOIN DIM_MARKET_RISK_REP_LINE DIM_MARKET_RISK_REP_LINE_3 ON FCT_MARKET_RISK_COM_CAPITAL.n_rep_line_skey = DIM_MARKET_RISK_REP_LINE_3.n_rep_line_skey INNER JOIN ( SELECT distinct v_commodity_group_code, v_commodity_group_desc, d_record_start_date, d_record_end_date FROM DIM_COMMODITY ) DIM_COMMODITY ON FCT_MARKET_RISK_COM_CAPITAL.v_commodity_group_code = DIM_COMMODITY.v_commodity_group_code AND TO_DATE('20260331','yyyymmdd') between DIM_COMMODITY.D_RECORD_START_DATE and DIM_COMMODITY.d_Record_End_Date) ON FCT_MARKET_RISK_COM_CAPITAL.n_rep_line_skey = FCT_MARKET_RISK_SUMMARY.n_rep_line_skey AND FCT_MARKET_RISK_COM_CAPITAL.n_mis_date_skey = FCT_MARKET_RISK_SUMMARY.n_mis_date_skey AND FCT_MARKET_RISK_COM_CAPITAL.n_run_skey = FCT_MARKET_RISK_SUMMARY.n_run_skey AND FCT_MARKET_RISK_COM_CAPITAL.n_Gaap_Skey = FCT_MARKET_RISK_SUMMARY.n_Gaap_Skey  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd'))  AND ( (((DIM_MARKET_RISK_REP_LINE.v_rep_line_code = 'OPIRDP'))) OR (((DIM_MARKET_RISK_REP_LINE.v_rep_line_code = 'OPIRDP')))  )  GROUP BY FCT_MARKET_RISK_SUMMARY.N_RUN_SKEY,FCT_MARKET_RISK_SUMMARY.N_REP_LINE_SKEY,FCT_MARKET_RISK_SUMMARY.N_GAAP_SKEY,FCT_MARKET_RISK_SUMMARY.N_MIS_DATE_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_REP_LINE_SKEY= SS.N_REP_LINE_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_GAMMA_CAPITAL_CHARGE=  CASE  WHEN  COND_1371650312072_10=10 THEN EXP_1371650312072_10 ELSE EXP_1371650312072_11 END  , TT.N_VEGA_CAPITAL_CHARGE=  CASE  WHEN  COND_1371650312072_20=20 THEN EXP_1371650312072_20 ELSE EXP_1371650312072_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
