-- =====================================================================
-- Task: Multiple_Rating_Assessment_Eligible_Rating_and_RW_Flag_for_Exposures_with_Single_Distinct_RW
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Multiple_Rating_Assessment_Eligible_Rating_and_RW_Flag_for_Exposures_with_Single_Distinct_RW(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_MULTIPLE_RATING_PROCESSING TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_MULTIPLE_RATING_PROCESSING.N_ACCT_OR_MITIGANT_SKEY,FSI_MULTIPLE_RATING_PROCESSING.N_DIMENSION_SKEY,FSI_MULTIPLE_RATING_PROCESSING.N_RUN_SKEY,FSI_MULTIPLE_RATING_PROCESSING.N_MIS_DATE_SKEY,FSI_MULTIPLE_RATING_PROCESSING.N_RATING_SKEY,FSI_MULTIPLE_RATING_PROCESSING.V_PURPOSE,FSI_MULTIPLE_RATING_PROCESSING.V_PRC_DATA_TYPE,FSI_MULTIPLE_RATING_PROCESSING.F_RATING_TYPE_IND,FSI_MULTIPLE_RATING_PROCESSING.F_ST_LT_RATING_FLAG,FSI_MULTIPLE_RATING_PROCESSING.F_ORIGINAL_CREDIT_RATING_IND,FSI_MULTIPLE_RATING_PROCESSING.N_CAP_APPROACH_TYPE_SKEY,FSI_MULTIPLE_RATING_PROCESSING.N_CAP_RECORD_TYPE_SKEY,(FSI_MULTIPLE_RATING_PROCESSING.F_RATING_RW_ELIGIBILITY) AS  T_1529702140264_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1529702140264_10 ,  (CASE WHEN  ROW_NUMBER() OVER (PARTITION BY CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.F_RATING_TYPE_IND ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.N_MIS_DATE_SKEY ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.N_RUN_SKEY ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.N_DIMENSION_SKEY ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.V_PURPOSE ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.F_ORIGINAL_CREDIT_RATING_IND ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.V_PRC_DATA_TYPE ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.N_ACCT_OR_MITIGANT_SKEY ELSE NULL END ,CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.F_ST_LT_RATING_FLAG ELSE NULL END ,CASE WHEN 1=1 THEN FSI_MULTIPLE_RATING_PROCESSING.N_CAP_APPROACH_TYPE_SKEY ELSE NULL END ,CASE WHEN 1=1 THEN FSI_MULTIPLE_RATING_PROCESSING.N_CAP_RECORD_TYPE_SKEY ELSE NULL END  ORDER BY CASE WHEN 1 = 1 THEN FSI_MULTIPLE_RATING_PROCESSING.N_RATING_SKEY ELSE NULL END ) =1 THEN 'Y' ELSE 'N' END) AS EXP_1529702140264_10,(FSI_MULTIPLE_RATING_PROCESSING.F_RATING_RW_ELIGIBILITY) AS EXP_1529702140264_11  FROM  FSI_MULTIPLE_RATING_PROCESSING INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_MULTIPLE_RATING_PROCESSING.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_MULTIPLE_RATING_PROCESSING.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = TO_DATE('20260331','yyyymmdd') INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_MULTIPLE_RATING_PROCESSING.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_MULTIPLE_RATING_PROCESSING.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY  WHERE (1 = 1)  AND ((((COALESCE(FSI_MULTIPLE_RATING_PROCESSING.F_SINGLE_DIST_BASEL_RAT_FLAG,'N') = 'Y')) ) AND (((FSI_MULTIPLE_RATING_PROCESSING.F_BASEL_TYPE_IND = 'A')) ) AND (((FSI_MULTIPLE_RATING_PROCESSING.V_PRC_DATA_TYPE = 'NON-SEC')) ))  AND ((1=1) AND ( FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'INV_NON_SEC_EXP' OR FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'INV_NON_SEC_ULY' ) AND ( FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = 'NSSTD' ) AND (9=9) AND (3=3))  ) WHERE (   (COND_1529702140264_10 <> 11)  ) ) SS ON ( TT.N_ACCT_OR_MITIGANT_SKEY= SS.N_ACCT_OR_MITIGANT_SKEY AND TT.N_DIMENSION_SKEY= SS.N_DIMENSION_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RATING_SKEY= SS.N_RATING_SKEY AND TT.V_PURPOSE= SS.V_PURPOSE AND TT.V_PRC_DATA_TYPE= SS.V_PRC_DATA_TYPE AND TT.F_RATING_TYPE_IND= SS.F_RATING_TYPE_IND AND TT.F_ST_LT_RATING_FLAG= SS.F_ST_LT_RATING_FLAG AND TT.F_ORIGINAL_CREDIT_RATING_IND= SS.F_ORIGINAL_CREDIT_RATING_IND AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY AND TT.N_CAP_RECORD_TYPE_SKEY= SS.N_CAP_RECORD_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.F_RATING_RW_ELIGIBILITY=  CASE  WHEN  COND_1529702140264_10=10 THEN EXP_1529702140264_10 ELSE EXP_1529702140264_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
