-- =====================================================================
-- Task: NET_AGREEMENT_COLLATERALS_PLACED_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.NET_AGREEMENT_COLLATERALS_PLACED_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_NET_AGREEMENT_COLLATERALS(N_MIS_DATE_SKEY,N_COLLATERAL_SKEY,N_GAAP_SKEY,N_NETTING_AGREEMENT_SKEY,N_PARTY_SKEY,N_PARTY_TYPE_SKEY,N_COLLATERAL_TYPE_SKEY,F_MARGIN_PLACED_IND,N_EXCHANGE_RATE,N_MTM_VALUE,N_RESIDUAL_MATURITY,N_RUN_SKEY,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE,N_BASEL_TXN_TYPE_SKEY,N_STD_COLLATERAL_TYPE_SKEY,F_COLL_BANKRUPTCY_REMOTE_FLAG,F_COLL_SEGREGATED_IND,F_ONE_WAY_MARGIN_AGREEMENT,N_REMARGIN_FREQUENCY,V_CCY_CODE,V_MARGIN_TYPE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_EXPOSURE.N_ACCT_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),to_char(DIM_PARTY_TYPE.N_PARTY_TYPE_SKEY),to_char(DIM_PRODUCT.N_PROD_SKEY),'Y',FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,FSI_INSTR_VALUATION_DETAILS.N_FAIR_VALUE * A_FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,TRUNC(STG_PLACED_COLLATERAL.D_MATURITY_DATE - STG_PLACED_COLLATERAL.FIC_MIS_DATE)/365,'870',to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,to_char(FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY),FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE,to_char(FSI_PROD_TXN_TYPE_RECLASS.N_BASEL_TXN_TYPE_SKEY),to_char(FSI_REG_PROD_TYPE_RECLASS.N_BASEL_PROD_TYPE_SKEY),STG_PLACED_COLLATERAL.F_COLL_BANKRUPTCY_REMOTE_FLAG,STG_PLACED_COLLATERAL.F_COLL_SEGREGATED_IND,STG_PLACED_COLLATERAL.F_ONE_WAY_MARGIN_AGREEMENT,to_char(STG_PLACED_COLLATERAL.N_REMARGIN_FREQUENCY),STG_PLACED_COLLATERAL.V_CCY_CODE,STG_PLACED_COLLATERAL.V_MARGIN_TYPE FROM STG_PLACED_COLLATERAL JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND STG_PLACED_COLLATERAL.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_GAAP ON STG_PLACED_COLLATERAL.V_GAAP_CODE = DIM_GAAP.V_GAAP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE LEFT OUTER JOIN DIM_PARTY ON STG_PLACED_COLLATERAL.V_PARTY_CODE = DIM_PARTY.V_PARTY_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE LEFT OUTER JOIN DIM_PARTY_TYPE ON DIM_PARTY_TYPE.V_PARTY_TYPE_CODE = DIM_PARTY.V_PARTY_TYPE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY_TYPE.D_RECORD_START_DATE AND DIM_PARTY_TYPE.D_RECORD_END_DATE LEFT OUTER JOIN DIM_NETTING_AGREEMENT ON DIM_NETTING_AGREEMENT.V_NETTING_AGREEMENT_CODE = STG_PLACED_COLLATERAL.V_NETTING_AGREEMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_NETTING_AGREEMENT.D_RECORD_START_DATE AND DIM_NETTING_AGREEMENT.D_RECORD_END_DATE LEFT OUTER JOIN DIM_PRODUCT ON DIM_PRODUCT.V_PROD_CODE = STG_PLACED_COLLATERAL.V_PROD_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PRODUCT.D_RECORD_START_DATE AND DIM_PRODUCT.D_RECORD_END_DATE LEFT OUTER JOIN FSI_REG_PROD_TYPE_RECLASS ON FSI_REG_PROD_TYPE_RECLASS.N_RUN_SKEY = '870' AND FSI_REG_PROD_TYPE_RECLASS.N_PROD_SKEY = DIM_PRODUCT.N_PROD_SKEY LEFT OUTER JOIN FSI_PROD_TXN_TYPE_RECLASS ON FSI_PROD_TXN_TYPE_RECLASS.N_BASEL_PROD_TYPE_SKEY = FSI_REG_PROD_TYPE_RECLASS.N_BASEL_PROD_TYPE_SKEY AND FSI_PROD_TXN_TYPE_RECLASS.N_RUN_SKEY = '870' INNER JOIN FCT_ENTITY_INFO ON STG_PLACED_COLLATERAL.V_LV_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND COALESCE(FCT_ENTITY_INFO.F_CAP_CONSL_ENTITY_IND, 'N') = 'Y' INNER JOIN DIM_BASEL_CAP_CONSL_APPR ON DIM_BASEL_CAP_CONSL_APPR.N_BASEL_CAP_CONSL_APPR_SKEY = FCT_ENTITY_INFO.N_BASEL_CAP_CONSL_APPR_SKEY AND DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE IN ( 'FLCS' ,'PRCS' ) JOIN DIM_EXPOSURE ON STG_PLACED_COLLATERAL.V_POSTED_COLLATERAL_ID = DIM_EXPOSURE.V_EXPOSURE_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_EXPOSURE.D_RECORD_START_DATE AND DIM_EXPOSURE.D_RECORD_END_DATE LEFT OUTER JOIN FSI_INSTR_VALUATION_DETAILS ON FSI_INSTR_VALUATION_DETAILS.V_INSTRUMENT_CODE = STG_PLACED_COLLATERAL.V_INSTRUMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN FSI_INSTR_VALUATION_DETAILS.D_RECORD_START_DATE AND FSI_INSTR_VALUATION_DETAILS.D_RECORD_END_DATE LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = '870' AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_PLACED_COLLATERAL.V_CCY_CODE LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION A_FSI_CAP_CURRENCY_CONVERSION ON A_FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = '870' AND A_FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = FSI_INSTR_VALUATION_DETAILS.V_CCY_CODE LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY= '870' AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'NONSEC' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'OTH' WHERE 1=1 AND STG_PLACED_COLLATERAL.V_MARGIN_TYPE IN ( 'IM' ,'VM' ) LOG ERRORS INTO FSI_NET_AGREEMENT_COLLATERALS$ ('1776768175960_52924407_20260331_1_Job_1591194441055') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
