-- =====================================================================
-- Task: NET_AGREEMENT_COLLATERALS_RECEIVED_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.NET_AGREEMENT_COLLATERALS_RECEIVED_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_NET_AGREEMENT_COLLATERALS(N_BASEL_TXN_TYPE_SKEY,N_MIS_DATE_SKEY,N_GAAP_SKEY,N_COLLATERAL_SKEY,N_COLLATERAL_TYPE_SKEY,N_NETTING_AGREEMENT_SKEY,N_PARTY_SKEY,N_PARTY_TYPE_SKEY,F_MARGIN_PLACED_IND,N_EXCHANGE_RATE,N_MTM_VALUE,N_RESIDUAL_MATURITY,N_RUN_SKEY,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE,N_STD_COLLATERAL_TYPE_SKEY,N_STD_PARTY_TYPE_SKEY,F_COLL_SEGREGATED_IND,N_MIN_HOLDING_PERIOD,N_REMARGIN_FREQUENCY,V_CCY_CODE,V_MARGIN_TYPE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_TRANSACTION_TYPE.N_BASEL_TXN_TYPE_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_MITIGANT.N_MITIGANT_SKEY),to_char(DIM_MITIGANT_TYPE.N_MITIGANT_TYPE_SKEY),to_char(DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),to_char(DIM_PARTY_TYPE.N_PARTY_TYPE_SKEY),'N',FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,STG_MITIGANTS.N_MITIGANT_VALUE * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,TRUNC(STG_MITIGANTS.D_MATURITY_DATE - STG_MITIGANTS.FIC_MIS_DATE)/365,'870',to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,to_char(FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY),FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE,to_char(FSI_MITIGANT_TYPE_RECLASS.N_STD_MITIGANT_TYPE_SKEY),to_char(FSI_PARTY_TYPE_CLASSIFICATION.N_STANDARD_PARTY_TYPE_SKEY),STG_MITIGANTS.F_COLL_SEGREGATED_FLAG,to_char(STG_MITIGANTS.N_MIN_HOLDING_PERIOD),to_char(STG_MITIGANTS.N_REMARGIN_FREQUENCY),STG_MITIGANTS.V_CCY_CODE,STG_MITIGANTS.V_MARGIN_TYPE FROM STG_MITIGANTS JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' JOIN DIM_DATES ON STG_MITIGANTS.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') JOIN DIM_MITIGANT ON STG_MITIGANTS.V_MITIGANT_CODE = DIM_MITIGANT.V_MITIGANT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_MITIGANT.D_RECORD_START_DATE AND DIM_MITIGANT.D_RECORD_END_DATE LEFT OUTER JOIN DIM_GAAP ON STG_MITIGANTS.V_GAAP_CODE = DIM_GAAP.V_GAAP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE LEFT OUTER JOIN DIM_PARTY ON STG_MITIGANTS.V_ISSUER_CODE = DIM_PARTY.V_PARTY_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE JOIN DIM_PARTY_TYPE ON DIM_PARTY_TYPE.V_PARTY_TYPE_CODE = DIM_PARTY.V_PARTY_TYPE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY_TYPE.D_RECORD_START_DATE AND DIM_PARTY_TYPE.D_RECORD_END_DATE LEFT OUTER JOIN DIM_NETTING_AGREEMENT ON DIM_NETTING_AGREEMENT.V_NETTING_AGREEMENT_CODE = STG_MITIGANTS.V_NETTING_AGREEMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_NETTING_AGREEMENT.D_RECORD_START_DATE AND DIM_NETTING_AGREEMENT.D_RECORD_END_DATE LEFT OUTER JOIN DIM_MITIGANT_TYPE ON DIM_MITIGANT_TYPE.V_MITIGANT_TYPE = STG_MITIGANTS.V_MITIGANT_TYPE_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_MITIGANT_TYPE.D_RECORD_START_DATE AND DIM_MITIGANT_TYPE.D_RECORD_END_DATE LEFT OUTER JOIN FSI_MITIGANT_TYPE_RECLASS ON FSI_MITIGANT_TYPE_RECLASS.N_RUN_SKEY = '870' AND FSI_MITIGANT_TYPE_RECLASS.N_MITIGANT_TYPE_SKEY = DIM_MITIGANT_TYPE.N_MITIGANT_TYPE_SKEY LEFT OUTER JOIN FSI_MITIGANT_PROD_TYPE_RECLASS ON FSI_MITIGANT_PROD_TYPE_RECLASS.N_RUN_SKEY = '870' AND FSI_MITIGANT_PROD_TYPE_RECLASS.N_STD_MITIGANT_TYPE_SKEY = FSI_MITIGANT_TYPE_RECLASS.N_STD_MITIGANT_TYPE_SKEY LEFT OUTER JOIN FSI_PROD_TXN_TYPE_RECLASS ON FSI_PROD_TXN_TYPE_RECLASS.N_RUN_SKEY = '870' AND FSI_MITIGANT_PROD_TYPE_RECLASS.N_BASEL_PROD_TYPE_SKEY = FSI_PROD_TXN_TYPE_RECLASS.N_BASEL_PROD_TYPE_SKEY LEFT OUTER JOIN DIM_BASEL_TRANSACTION_TYPE ON DIM_BASEL_TRANSACTION_TYPE.N_BASEL_TXN_TYPE_SKEY = FSI_PROD_TXN_TYPE_RECLASS.N_BASEL_TXN_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY ='870' AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_MITIGANTS.V_CCY_CODE LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY ='870' AND DIM_DATES.n_date_skey = FSI_CAP_RUN_EXE_PARAMETERS.N_MIS_DATE_SKEY JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'NONSEC' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'OTH' LEFT OUTER JOIN FSI_PARTY_TYPE_CLASSIFICATION ON FSI_PARTY_TYPE_CLASSIFICATION.N_RUN_SKEY = '870' AND FSI_PARTY_TYPE_CLASSIFICATION.N_PARTY_TYPE_SKEY = DIM_PARTY_TYPE.N_PARTY_TYPE_SKEY WHERE 1=1 AND STG_MITIGANTS.V_MARGIN_TYPE IN ( 'IM' ,'VM' ) LOG ERRORS INTO FSI_NET_AGREEMENT_COLLATERALS$ ('1776768184957_19175989_20260331_1_Job_1591194444714') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
