-- =====================================================================
-- Task: Netting_Agreement_Details_Net_Independent_Collateral_Calculation_SA_CCR
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Netting_Agreement_Details_Net_Independent_Collateral_Calculation_SA_CCR(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_NETTING_AGREEMENT_DETAILS TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_NETTING_AGREEMENT_DETAILS.N_RUN_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_MIS_DATE_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_GAAP_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_NETTING_AGREEMENT_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_CAP_APPROACH_TYPE_SKEY, MIN(FSI_NETTING_AGREEMENT_DETAILS.N_NET_COLLATERAL_AMOUNT) AS  T_1432033013440_0,   MIN(CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1432033013440_10 ,  (SUM(CASE WHEN COALESCE(CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.f_margin_placed_ind ELSE NULL END ,'N') = 'N' THEN COALESCE(CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.n_mtm_value_post_haircut ELSE NULL END ,0) ELSE (CASE WHEN COALESCE(CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.f_coll_segregated_ind ELSE NULL END ,'N') = 'N' THEN -1*(COALESCE(CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.n_mtm_value_post_haircut ELSE NULL END ,0)) ELSE 0 END) END)) AS EXP_1432033013440_10,MIN(FSI_NETTING_AGREEMENT_DETAILS.N_NET_COLLATERAL_AMOUNT) AS EXP_1432033013440_11  FROM  FSI_NETTING_AGREEMENT_DETAILS INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_NETTING_AGREEMENT_DETAILS.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_NETTING_AGREEMENT_DETAILS.N_MIS_DATE_SKEY INNER JOIN FSI_NET_AGREEMENT_COLLATERALS ON FSI_NET_AGREEMENT_COLLATERALS.N_RUN_SKEY = FSI_NETTING_AGREEMENT_DETAILS.N_RUN_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.N_MIS_DATE_SKEY = FSI_NETTING_AGREEMENT_DETAILS.N_MIS_DATE_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.N_PARTY_SKEY = FSI_NETTING_AGREEMENT_DETAILS.N_PARTY_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.N_NETTING_AGREEMENT_SKEY = FSI_NETTING_AGREEMENT_DETAILS.N_NETTING_AGREEMENT_SKEY  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870')  AND ( (((1=1)))  )  GROUP BY FSI_NETTING_AGREEMENT_DETAILS.N_RUN_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_MIS_DATE_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_GAAP_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_NETTING_AGREEMENT_SKEY,FSI_NETTING_AGREEMENT_DETAILS.N_CAP_APPROACH_TYPE_SKEY ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_NETTING_AGREEMENT_SKEY= SS.N_NETTING_AGREEMENT_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_NET_COLLATERAL_AMOUNT=  CASE  WHEN  COND_1432033013440_10=10 THEN EXP_1432033013440_10 ELSE EXP_1432033013440_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
