-- =====================================================================
-- Task: Nettable_Pool_Maturity_Adjusted_EAD
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Nettable_Pool_Maturity_Adjusted_EAD(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_NETTABLE_POOL TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY,FSI_CAP_NETTABLE_POOL.N_RUN_SKEY,FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY,(FSI_CAP_NETTABLE_POOL.N_MATURITY_ADJ_EAD) AS  T_1628060742009_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1628060742009_10 ,  (CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_EFF_MATURITY ELSE NULL END *CASE WHEN 1 = 1 THEN FSI_CAP_NETTABLE_POOL.N_EAD_DISCOUNT_FACTOR ELSE NULL END *CASE WHEN 1=1 THEN FSI_CAP_SUB_EXPOSURES.N_EAD_POST_MITIGATION ELSE NULL END ) AS EXP_1628060742009_10,(FSI_CAP_NETTABLE_POOL.N_MATURITY_ADJ_EAD) AS EXP_1628060742009_11  FROM  FSI_CAP_NETTABLE_POOL INNER JOIN DIM_DATES ON FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY INNER JOIN DIM_RUN ON FSI_CAP_NETTABLE_POOL.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY INNER JOIN DIM_PARTY ON FSI_CAP_NETTABLE_POOL.N_CUST_SKEY = DIM_PARTY.N_PARTY_SKEY AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE INNER JOIN DIM_STANDARD_PARTY_TYPE ON FSI_CAP_NETTABLE_POOL.N_STANDARD_PARTY_TYPE_SKEY = DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_PARAMETER_SETUP_SKEY AND FSI_RUN_PARAMETER.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_RUN_PARAMETER.N_DATE_SKEY = FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_CAP_COUNTERPARTY_CVA ON FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY = FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY = FSI_CAP_NETTABLE_POOL.N_CUST_SKEY LEFT OUTER JOIN FSI_CAP_SUB_EXPOSURES ON FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY = FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY AND FSI_CAP_SUB_EXPOSURES.N_ACCT_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY LEFT OUTER JOIN DIM_STD_MITIGANT_TYPE ON DIM_STD_MITIGANT_TYPE.N_STD_MITIGANT_TYPE_SKEY = FSI_CAP_SUB_EXPOSURES.N_STD_MITIGANT_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_RECORD_TYPE_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FSI_CAP_NETTABLE_POOL.N_CVA_METHOD_SKEY = DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY  WHERE (COALESCE(DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_TYPE_CODE, 'UNCOV') = 'UNCOV')  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.N_RUN_SKEY = '870')  AND (((DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABHM') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABWH') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVACCR') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVAIMM') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVASTD') ))  ) WHERE (   (COND_1628060742009_10 <> 11)  ) ) SS ON ( TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_CAP_NETTABLE_POOL_SKEY= SS.N_CAP_NETTABLE_POOL_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_MATURITY_ADJ_EAD=  CASE  WHEN  COND_1628060742009_10=10 THEN EXP_1628060742009_10 ELSE EXP_1628060742009_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
