-- =====================================================================
-- Task: NETTING_AGREEMENT_DETAILS_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.NETTING_AGREEMENT_DETAILS_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_NETTING_AGREEMENT_DETAILS(N_MIS_DATE_SKEY,N_NETTING_AGREEMENT_SKEY,N_PARTY_SKEY,N_MARGIN_PERIOD_OF_RISK,N_MARGIN_THRESHOLD,N_MIN_TRANSFER_AMT,N_NET_EXPOSURE_AMOUNT,N_RUN_SKEY,N_ENTITY_SKEY,N_GAAP_SKEY,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE,N_EXCHANGE_RATE,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE,N_MARGIN_THRESHOLD_NCY,N_MIN_TRANSFER_AMT_NCY,N_NET_EXPOSURE_AMOUNT_NCY,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),(STG_NET_EXPOSURES.FIC_MIS_DATE - STG_NET_EXPOSURES.D_LAST_COLL_EXCHANGE_DATE)/365,STG_NET_EXPOSURES.N_COLL_THRESHOLD_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,STG_NET_EXPOSURES.N_MIN_TRANSFER_AMT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,STG_NET_EXPOSURES.N_NET_EXPOSURE_AMOUNT * FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,'870',to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),to_char(FCT_ENTITY_INFO.N_GAAP_SKEY),to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,to_char(FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE),to_char(FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY),FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE,to_char(STG_NET_EXPOSURES.N_COLL_THRESHOLD_AMT),to_char(STG_NET_EXPOSURES.N_MIN_TRANSFER_AMT),to_char(STG_NET_EXPOSURES.N_NET_EXPOSURE_AMOUNT),STG_NET_EXPOSURES.V_CCY_CODE FROM STG_NET_EXPOSURES INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = STG_NET_EXPOSURES.FIC_MIS_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.V_ENTITY_CODE = STG_NET_EXPOSURES.V_LV_CODE AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_PARTY ON DIM_PARTY.V_PARTY_ID = STG_NET_EXPOSURES.V_CUST_REF_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE INNER JOIN DIM_NETTING_AGREEMENT ON DIM_NETTING_AGREEMENT.V_NETTING_AGREEMENT_CODE = STG_NET_EXPOSURES.V_NETTING_AGREEMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_NETTING_AGREEMENT.D_RECORD_START_DATE AND DIM_NETTING_AGREEMENT.D_RECORD_END_DATE LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = '870' AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_NET_EXPOSURES.V_CCY_CODE LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'NONSEC' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'OTH' WHERE 1=1 AND NOT EXISTS ( SELECT 1 FROM FSI_NETTING_AGREEMENT_DETAILS WHERE FSI_NETTING_AGREEMENT_DETAILS.N_NETTING_AGREEMENT_SKEY = DIM_NETTING_AGREEMENT.N_NETTING_AGREEMENT_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_GAAP_SKEY = FCT_ENTITY_INFO.N_GAAP_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_NETTING_AGREEMENT_DETAILS.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY ) LOG ERRORS INTO FSI_NETTING_AGREEMENT_DETAILS$ ('1776768176496_1118597_20260331_1_Job_1594628161380') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
