-- =====================================================================
-- Task: NETTABLE_POOL_MASTER_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.NETTABLE_POOL_MASTER_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_NETTABLE_POOL_MASTER(FIC_MIS_DATE,N_CAP_NETTABLE_POOL_SKEY,V_CAP_NETTABLE_POOL_CODE,V_CAP_NETTABLE_POOL_DESC)SELECT  /*+PARALLEL (4)*/ to_date('20260331','YYYYMMDD'),SEQ_DIM_EXPOSURE.NEXTVAL,FSI_CAP_DERIVATIVES.V_CAP_NETTABLE_POOL_CODE,FSI_CAP_DERIVATIVES.V_CAP_NETTABLE_POOL_CODE FROM (SELECT DISTINCT N_MIS_DATE_SKEY, N_RUN_SKEY, N_CAP_APPROACH_TYPE_SKEY, V_CAP_NETTABLE_POOL_CODE, N_CAP_RECORD_TYPE_SKEY FROM FSI_CAP_DERIVATIVES WHERE FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY = TO_NUMBER(TO_CHAR(to_date('20260331','YYYYMMDD'), 'YYYYMMDD')) AND FSI_CAP_DERIVATIVES.N_RUN_SKEY = '870' AND FSI_CAP_DERIVATIVES.V_CAP_NETTABLE_POOL_CODE IS NOT NULL) FSI_CAP_DERIVATIVES INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_DERIVATIVES.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY WHERE ((1=1) AND ( FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'DRV_NON_SEC_EXP' ) AND ( FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = 'NSSTD' ) AND (9=9) AND (3=3)) AND NOT EXISTS ( SELECT 1 FROM FSI_CAP_NETTABLE_POOL_MASTER WHERE FSI_CAP_NETTABLE_POOL_MASTER.V_CAP_NETTABLE_POOL_CODE = FSI_CAP_DERIVATIVES.V_CAP_NETTABLE_POOL_CODE) LOG ERRORS INTO FSI_CAP_NETTABLE_POOL_MASTER$ ('1776769337705_34307539_20260331_1_Job_782788fd725248e2bfdcecc49dcaf605') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
