-- =====================================================================
-- Task: Nettable_Pool_Effective_Maturity_at_Counterparty_for_Derivatives
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Nettable_Pool_Effective_Maturity_at_Counterparty_for_Derivatives(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_CAP_NETTABLE_POOL TT USING (   SELECT  /*+ PARALLEL(4) */ FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY,FSI_CAP_NETTABLE_POOL.N_RUN_SKEY,FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY, MIN(FSI_CAP_NETTABLE_POOL.N_EFF_MATURITY) AS  T_1630473427669_0,   MIN(CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1630473427669_10 ,  (MAX(CASE WHEN COALESCE(CASE WHEN 1=1 THEN FSI_CAP_DERIVATIVES.n_notional_principal ELSE NULL END ,0) = 0 THEN 0 ELSE CASE WHEN 1=1 THEN FSI_CAP_DERIVATIVES.n_eff_maturity ELSE NULL END  / CASE WHEN 1=1 THEN FSI_CAP_DERIVATIVES.n_notional_principal ELSE NULL END  END)) AS EXP_1630473427669_10,MIN(FSI_CAP_NETTABLE_POOL.N_EFF_MATURITY) AS EXP_1630473427669_11  FROM  FSI_CAP_NETTABLE_POOL LEFT OUTER JOIN DIM_DATES ON FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY INNER JOIN ( SELECT FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY, FSI_CAP_DERIVATIVES.N_RUN_SKEY, FSI_CAP_DERIVATIVES.N_GAAP_SKEY, FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY, FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY, SUM(COALESCE(FSI_CAP_DERIVATIVES.N_EFF_MATURITY, FSI_CAP_DERIVATIVES.N_ORIGINAL_MATURITY, 0) * COALESCE(FSI_CAP_DERIVATIVES.N_NOTIONAL_PRINCIPAL, 0)) OVER ( PARTITION BY FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY ) N_EFF_MATURITY, SUM(COALESCE(FSI_CAP_DERIVATIVES.N_NOTIONAL_PRINCIPAL, 0)) OVER ( PARTITION BY FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY ) N_NOTIONAL_PRINCIPAL FROM FSI_CAP_DERIVATIVES WHERE FSI_CAP_DERIVATIVES.N_RUN_SKEY = '870' AND FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY = TO_NUMBER(TO_CHAR(TO_DATE('20260331','yyyymmdd'), 'yyyymmdd')) ) FSI_CAP_DERIVATIVES ON FSI_CAP_DERIVATIVES.N_CAP_NETTABLE_POOL_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY AND FSI_CAP_DERIVATIVES.N_MIS_DATE_SKEY = FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY AND FSI_CAP_DERIVATIVES.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_CAP_DERIVATIVES.N_GAAP_SKEY = FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY AND FSI_CAP_DERIVATIVES.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_PARAMETER_SETUP_SKEY AND FSI_RUN_PARAMETER.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_RUN_PARAMETER.N_DATE_SKEY = FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_RECORD_TYPE_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON DIM_BASEL_METHODOLOGY.N_BASEL_METHOD_SKEY = FSI_CAP_NETTABLE_POOL.N_CVA_METHOD_SKEY  WHERE (1 = 1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd'))  AND (((DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABHM') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVABWH') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVACCR') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVAIMM') or (DIM_BASEL_METHODOLOGY.V_BASEL_METHOD_CODE = 'CVASTD') ))  AND ( (((1=1)))  )  GROUP BY FSI_CAP_NETTABLE_POOL.N_MIS_DATE_SKEY,FSI_CAP_NETTABLE_POOL.N_RUN_SKEY,FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY,FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY ) SS ON ( TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_CAP_NETTABLE_POOL_SKEY= SS.N_CAP_NETTABLE_POOL_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_EFF_MATURITY=  CASE  WHEN  COND_1630473427669_10=10 THEN EXP_1630473427669_10 ELSE EXP_1630473427669_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
