-- =====================================================================
-- Task: Non_Sec_PD_Band_Skey_Assignment
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Non_Sec_PD_Band_Skey_Assignment(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_NON_SEC_EXPOSURES TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_NON_SEC_EXPOSURES.N_ACCT_SKEY,FCT_NON_SEC_EXPOSURES.N_RUN_SKEY,FCT_NON_SEC_EXPOSURES.N_GAAP_SKEY,FCT_NON_SEC_EXPOSURES.N_MIS_DATE_SKEY,(FCT_NON_SEC_EXPOSURES.N_PD_BAND_SKEY) AS  T_1348343363923_0,   (CASE  WHEN  ( ((CASE WHEN DIM_PD_BAND_A.V_BAND_TYPE = 'PD BAND' THEN RTRIM(LTRIM(TO_CHAR(DIM_PD_BAND_A.n_band_code))) END = '1')) OR ((CASE WHEN DIM_PD_BAND_A.V_BAND_TYPE = 'PD BAND' THEN RTRIM(LTRIM(TO_CHAR(DIM_PD_BAND_A.n_band_code))) END = '0')) ) THEN 10 ELSE 11 END)  AS COND_1348343363923_10 ,  (CASE WHEN 1 = 1 THEN DIM_PD_BAND_A.n_band_skey ELSE NULL END ) AS EXP_1348343363923_10,(FCT_NON_SEC_EXPOSURES.N_PD_BAND_SKEY) AS EXP_1348343363923_11  FROM  FCT_NON_SEC_EXPOSURES LEFT OUTER JOIN DIM_BASEL_ASSET_CLASS ON DIM_BASEL_ASSET_CLASS.n_basel_asset_class_skey = FCT_NON_SEC_EXPOSURES.n_basel_asset_class_skey LEFT OUTER JOIN DIM_BASEL_PRODUCT_TYPE ON DIM_BASEL_PRODUCT_TYPE.n_basel_prod_type_skey = FCT_NON_SEC_EXPOSURES.n_basel_prod_type_skey LEFT OUTER JOIN DIM_BANDS DIM_EXPECTED_LOSS_BAND_A ON FCT_NON_SEC_EXPOSURES.n_rwa_el_amt >= DIM_EXPECTED_LOSS_BAND_A.N_BAND_LOWER_BOUND_VALUE AND FCT_NON_SEC_EXPOSURES.n_rwa_el_amt <= DIM_EXPECTED_LOSS_BAND_A.N_BAND_UPPER_BOUND_VALUE AND DIM_EXPECTED_LOSS_BAND_A.v_band_type = 'EXPECTED LOSS BAND' 	 AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_EXPECTED_LOSS_BAND_A.D_RECORD_START_DATE AND DIM_EXPECTED_LOSS_BAND_A.D_RECORD_END_DATE LEFT OUTER JOIN DIM_BANDS DIM_RW_BAND_A ON FCT_NON_SEC_EXPOSURES.n_pre_mitigation_rw_ul > DIM_RW_BAND_A.N_BAND_LOWER_BOUND_VALUE AND FCT_NON_SEC_EXPOSURES.n_pre_mitigation_rw_ul <= DIM_RW_BAND_A.N_BAND_UPPER_BOUND_VALUE AND DIM_RW_BAND_A.v_band_type = 'RW BAND' 	 AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_RW_BAND_A.D_RECORD_START_DATE AND DIM_RW_BAND_A.D_RECORD_END_DATE LEFT OUTER JOIN DIM_BANDS DIM_PD_BAND_A ON FCT_NON_SEC_EXPOSURES.n_pd_percent >= DIM_PD_BAND_A.N_BAND_LOWER_BOUND_VALUE AND FCT_NON_SEC_EXPOSURES.n_pd_percent < DIM_PD_BAND_A.N_BAND_UPPER_BOUND_VALUE AND DIM_PD_BAND_A.v_band_type = 'PD BAND' 	 AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_PD_BAND_A.D_RECORD_START_DATE AND DIM_PD_BAND_A.D_RECORD_END_DATE LEFT OUTER JOIN DIM_BANDS DIM_LTV_BAND_A ON FCT_NON_SEC_EXPOSURES.n_exp_ltv_ratio >= DIM_LTV_BAND_A.N_BAND_LOWER_BOUND_VALUE AND FCT_NON_SEC_EXPOSURES.n_exp_ltv_ratio < DIM_LTV_BAND_A.N_BAND_UPPER_BOUND_VALUE AND DIM_LTV_BAND_A.V_BAND_TYPE = 'LTV BAND' 	 AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_LTV_BAND_A.D_RECORD_START_DATE AND DIM_LTV_BAND_A.D_RECORD_END_DATE LEFT OUTER JOIN DIM_BANDS DIM_DELINQUENCY_BAND_A ON FCT_NON_SEC_EXPOSURES.n_delq_days >= DIM_DELINQUENCY_BAND_A.N_BAND_LOWER_BOUND_VALUE AND FCT_NON_SEC_EXPOSURES.n_delq_days <= DIM_DELINQUENCY_BAND_A.N_BAND_UPPER_BOUND_VALUE AND DIM_DELINQUENCY_BAND_A.v_band_type = 'RETAIL-DELQ' 	 AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_DELINQUENCY_BAND_A.D_RECORD_START_DATE AND DIM_DELINQUENCY_BAND_A.D_RECORD_END_DATE LEFT OUTER JOIN DIM_BANDS DIM_DELINQUENCY_BAND_B ON FCT_NON_SEC_EXPOSURES.n_delq_days >= DIM_DELINQUENCY_BAND_B.N_BAND_LOWER_BOUND_VALUE AND FCT_NON_SEC_EXPOSURES.n_delq_days <= DIM_DELINQUENCY_BAND_B.N_BAND_UPPER_BOUND_VALUE AND DIM_DELINQUENCY_BAND_B.v_band_type = 'CORP-DELQ' 	 AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_DELINQUENCY_BAND_B.D_RECORD_START_DATE AND DIM_DELINQUENCY_BAND_B.D_RECORD_END_DATE LEFT OUTER JOIN DIM_RUN ON FCT_NON_SEC_EXPOSURES.n_run_skey = DIM_RUN.n_run_skey LEFT OUTER JOIN DIM_DATES ON FCT_NON_SEC_EXPOSURES.n_mis_date_skey = DIM_DATES.n_date_skey LEFT OUTER JOIN DIM_LOB ON DIM_LOB.n_lob_skey = FCT_NON_SEC_EXPOSURES.n_lob_skey LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON FCT_NON_SEC_EXPOSURES.n_run_identifier_skey = DIM_RUN_IDENTIFIER.n_run_identifier_skey LEFT OUTER JOIN RUN_PARAMETERS ON FCT_NON_SEC_EXPOSURES.n_run_parameter_setup_skey = RUN_PARAMETERS.n_run_parameter_setup_skey AND RUN_PARAMETERS.n_Run_Skey = FCT_NON_SEC_EXPOSURES.n_Run_Skey AND RUN_PARAMETERS.n_Date_Skey = FCT_NON_SEC_EXPOSURES.n_Mis_Date_Skey  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  ) WHERE (   (COND_1348343363923_10 <> 11)  ) ) SS ON ( TT.N_ACCT_SKEY= SS.N_ACCT_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_PD_BAND_SKEY=  CASE  WHEN  COND_1348343363923_10=10 THEN EXP_1348343363923_10 ELSE EXP_1348343363923_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
