-- =====================================================================
-- Task: Non_Sec_Risk_Weight_Band_Assignment
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Non_Sec_Risk_Weight_Band_Assignment(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_NON_SEC_EXPOSURES TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_NON_SEC_EXPOSURES.N_ACCT_SKEY,FCT_NON_SEC_EXPOSURES.N_RUN_SKEY,FCT_NON_SEC_EXPOSURES.N_GAAP_SKEY,FCT_NON_SEC_EXPOSURES.N_MIS_DATE_SKEY,(FCT_NON_SEC_EXPOSURES.N_RW_BAND_SKEY) AS  T_1348342905513_0,   (CASE  WHEN  ( (((1=1))) ) THEN 10 ELSE 11 END)  AS COND_1348342905513_10 ,  (null) AS EXP_1348342905513_10,(FCT_NON_SEC_EXPOSURES.N_RW_BAND_SKEY) AS EXP_1348342905513_11  FROM  FCT_NON_SEC_EXPOSURES INNER JOIN DIM_RUN ON DIM_RUN.n_run_skey = FCT_NON_SEC_EXPOSURES.n_run_skey AND DIM_RUN.n_run_skey='870' INNER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_NON_SEC_EXPOSURES.n_mis_date_skey AND DIM_DATES.D_CALENDAR_DATE =TO_DATE('20260331','yyyymmdd')  LEFT OUTER JOIN DIM_BANDS DIM_RW_BAND_A ON FCT_NON_SEC_EXPOSURES.n_post_mitigation_rw_ul > DIM_RW_BAND_A.N_BAND_LOWER_BOUND_VALUE AND FCT_NON_SEC_EXPOSURES.n_post_mitigation_rw_ul <= DIM_RW_BAND_A.N_BAND_UPPER_BOUND_VALUE AND DIM_RW_BAND_A.v_band_type = 'RW BAND' AND TO_DATE('20260331','yyyymmdd') BETWEEN DIM_RW_BAND_A.D_RECORD_START_DATE AND DIM_RW_BAND_A.D_RECORD_END_DATE LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON FCT_NON_SEC_EXPOSURES.n_run_identifier_skey = DIM_RUN_IDENTIFIER.n_run_identifier_skey  WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  ) WHERE (   (COND_1348342905513_10 <> 11)  ) ) SS ON ( TT.N_ACCT_SKEY= SS.N_ACCT_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_RW_BAND_SKEY=  CASE  WHEN  COND_1348342905513_10=10 THEN EXP_1348342905513_10 ELSE EXP_1348342905513_11 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
