-- =====================================================================
-- Task: OPS_RISK_RWA_STD_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.OPS_RISK_RWA_STD_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY,N_CAP_COMP_GROUP_SKEY,N_ENTITY,N_ORIG_STD_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_AMT,N_UPD_CAP_COMP_GROUP_SKEY,N_GAAP_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),to_char(DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,FCT_ENTITY_INFO.N_ENTITY_SKEY,CASE WHEN DIM_RUN.V_PRODUCT = 'CREC' THEN STG_STANDARD_ACCT_HEAD.N_AMOUNT_RCY  ELSE SUM(COALESCE(FCT_OPS_RISK_SUMMARY.N_RWA_AMT,0))END,CASE WHEN DIM_RUN.V_PRODUCT = 'CREC' THEN STG_STANDARD_ACCT_HEAD.N_AMOUNT_RCY  ELSE SUM(COALESCE(FCT_OPS_RISK_SUMMARY.N_RWA_AMT,0))END,DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,to_char(FCT_OPS_RISK_SUMMARY.N_GAAP_SKEY) FROM FCT_OPS_RISK_SUMMARY INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_OPS_RISK_SUMMARY.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_OPS_RISK_SUMMARY.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' AND TO_DATE(to_date('20260331','YYYYMMDD')) BETWEEN COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE,TO_DATE(to_date('20260331','YYYYMMDD'))) AND COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' AND DIM_DATES.N_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY LEFT OUTER JOIN STG_STANDARD_ACCT_HEAD ON STG_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP170' AND STG_STANDARD_ACCT_HEAD.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP170' AND TO_DATE(to_date('20260331','YYYYMMDD')) BETWEEN COALESCE(DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE,TO_DATE(to_date('20260331','YYYYMMDD'))) AND COALESCE(DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD')GROUP BY  DIM_DATES.N_DATE_SKEY,     DIM_RUN.N_RUN_SKEY,     FCT_OPS_RISK_SUMMARY.N_GAAP_SKEY,     DIM_RUN.V_PRODUCT,    DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,    FCT_ENTITY_INFO.N_ENTITY_SKEY,     DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,     STG_STANDARD_ACCT_HEAD.N_AMOUNT_RCY LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776771917264_14382679_20260331_1_JOB_6644791923853445') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
