-- =====================================================================
-- Task: OPS_RISK_SUMMARY_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.OPS_RISK_SUMMARY_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_OPS_RISK_SUMMARY(N_BASEL_METHOD_SKEY,N_ENTITY_SKEY,N_RWA_AMT,N_STANDARD_LOB_SKEY,N_BRANCH_SKEY,N_COUNTRY_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ MAX(FCT_OPS_RISK_DATA.n_basel_method_skey),(select n_entity_skey from fct_entity_info INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY=FCT_ENTITY_INFO.n_mis_date_skey where n_run_skey='870' and f_cap_consl_parent_entity_ind='Y' and DIM_DATES.D_CALENDAR_DATE=to_date('20260331','YYYYMMDD')),SUM(FCT_OPS_RISK_DATA.n_rwa_amt),MAX(FCT_OPS_RISK_DATA.N_STANDARD_LOB_SKEY),to_char(FCT_OPS_RISK_DATA.N_BRANCH_SKEY),to_char(FCT_OPS_RISK_DATA.N_COUNTRY_SKEY),to_char(FCT_OPS_RISK_DATA.N_GAAP_SKEY),to_char(FCT_OPS_RISK_DATA.N_MIS_DATE_SKEY),to_char(FCT_OPS_RISK_DATA.N_RUN_SKEY) FROM FCT_OPS_RISK_DATA LEFT OUTER JOIN DIM_GAAP ON FCT_OPS_RISK_DATA.n_gaap_skey = DIM_GAAP.n_gaap_skey LEFT OUTER JOIN DIM_COUNTRY ON FCT_OPS_RISK_DATA.n_country_skey = DIM_COUNTRY.n_country_skey LEFT OUTER JOIN DIM_GEOGRAPHY ON FCT_OPS_RISK_DATA.n_branch_skey = DIM_GEOGRAPHY.n_branch_skey LEFT OUTER JOIN DIM_LOB ON FCT_OPS_RISK_DATA.N_LOB_SKEY = DIM_LOB.N_LOB_SKEY LEFT OUTER JOIN DIM_STANDARD_LOB ON FCT_OPS_RISK_DATA.N_STANDARD_LOB_SKEY = DIM_STANDARD_LOB.N_STD_LOB_SKEY LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON FCT_OPS_RISK_DATA.n_basel_method_skey = DIM_BASEL_METHODOLOGY.n_basel_method_skey LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_OPS_RISK_DATA.n_entity_skey = FCT_ENTITY_INFO.n_entity_skey LEFT OUTER JOIN DIM_DATES ON FCT_OPS_RISK_DATA.n_mis_date_skey=DIM_DATES.N_DATE_SKEY WHERE 1=1 AND 1=1 AND FCT_OPS_RISK_DATA.n_run_skey= '870' AND DIM_DATES.D_CALENDAR_DATE=to_date('20260331','YYYYMMDD') AND FCT_OPS_RISK_DATA.n_rwa_amt IS NOT NULL AND FCT_ENTITY_INFO.n_run_skey= '870' AND FCT_ENTITY_INFO.n_mis_date_skey = dim_dates.n_date_skey GROUP BY FCT_OPS_RISK_DATA.n_run_skey, FCT_OPS_RISK_DATA.n_mis_date_skey, FCT_OPS_RISK_DATA.n_gaap_skey, FCT_OPS_RISK_DATA.n_country_skey, FCT_OPS_RISK_DATA.n_branch_skey LOG ERRORS INTO FCT_OPS_RISK_SUMMARY$ ('1776768505410_69892599_20260331_1_Job_74af074773bf4f13a7a7e021631faf49') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
