-- =====================================================================
-- Task: OPS_RISK_DATA_POPULATION_CSTM
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.OPS_RISK_DATA_POPULATION_CSTM(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_OPS_RISK_DATA(N_COUNTRY_SKEY,N_MIS_DATE_SKEY,N_GAAP_SKEY,N_BRANCH_SKEY,N_LOB_SKEY,N_ALPHA_PERCENT,N_EXCHANGE_RATE,N_RUN_SKEY,N_SHAREHOLDING_PERCENT,N_ENTITY_SKEY,D_FINANCIAL_YEAR,N_DISPOSAL_PROP_INC_AMT_NCY,N_INCOME_INSURANCE_CLAIM_NCY,N_INSURE_IRREGULAR_GAIN_NCY,N_INSURE_IRREGULAR_LOSS_NCY,N_LEGAL_SETTLE_INCOME_AMT_NCY,N_LOANS_ADVANCES_AMT_NCY,N_NET_INTEREST_INCOME_NCY,N_NET_NON_INT_INCOME_NCY,N_OPERATING_EXPENSES_NCY,N_PROVISION_AMT_NCY,N_REV_PROV_AMT_NCY,N_REV_WRITE_OFF_AMT_NCY,N_SEC_SALE_GAIN_LOSS_AFS_NCY,N_SEC_SALE_GAIN_LOSS_HTM_NCY,N_WRITE_OFF_AMT_NCY,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_COUNTRY.N_COUNTRY_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_GEOGRAPHY.N_BRANCH_SKEY),to_char(DIM_LOB.N_LOB_SKEY),0.15,FSI_CAP_CURRENCY_CONVERSION.N_EXCHANGE_RATE,'870',CASE WHEN DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE = 'PRCS' THEN COALESCE(FCT_ENTITY_INFO.N_SHAREHOLDING_PERCENT,1) ELSE 1 END,to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),STG_OPS_RISK_DATA.D_FINANCIAL_YEAR,to_char(STG_OPS_RISK_DATA.N_DISPOSAL_PROP_INCOME_AMT),to_char(STG_OPS_RISK_DATA.N_INCOME_INSURANCE_CLAIM),to_char(STG_OPS_RISK_DATA.N_INSURANCE_IRREGULAR_GAIN),to_char(STG_OPS_RISK_DATA.N_INSURANCE_IRREGULAR_LOSS),to_char(STG_OPS_RISK_DATA.N_LEGAL_SETTLE_INCOME_AMT),to_char(STG_OPS_RISK_DATA.N_LOANS_ADVANCES_AMT),to_char(STG_OPS_RISK_DATA.N_NET_INTEREST_INCOME),to_char(STG_OPS_RISK_DATA.N_NET_NON_INT_INCOME),to_char(STG_OPS_RISK_DATA.N_OPERATING_EXPENSES),to_char(STG_OPS_RISK_DATA.N_PROVISION_AMOUNT),to_char(STG_OPS_RISK_DATA.N_REV_PROV_AMT),to_char(STG_OPS_RISK_DATA.N_REV_WRITE_OFF_AMT),to_char(STG_OPS_RISK_DATA.N_SECURITY_SALE_GAIN_LOSS_AFS),to_char(STG_OPS_RISK_DATA.N_SECURITY_SALE_GAIN_LOSS_HTM),to_char(STG_OPS_RISK_DATA.N_WRITE_OFF_AMOUNT),STG_OPS_RISK_DATA.V_CCY_CODE FROM STG_OPS_RISK_DATA LEFT OUTER JOIN DIM_GAAP ON STG_OPS_RISK_DATA.V_GAAP_CODE = DIM_GAAP.V_GAAP_CODE LEFT OUTER JOIN DIM_COUNTRY ON STG_OPS_RISK_DATA.V_COUNTRY_CODE = DIM_COUNTRY.V_COUNTRY_ID LEFT OUTER JOIN DIM_GEOGRAPHY ON STG_OPS_RISK_DATA.V_BRANCH_CODE = DIM_GEOGRAPHY.V_ACCT_BRANCH_CODE LEFT OUTER JOIN DIM_LOB ON STG_OPS_RISK_DATA.V_LOB_CODE = DIM_LOB.V_LOB_CODE INNER JOIN(FCT_ENTITY_INFO LEFT OUTER JOIN DIM_BASEL_CAP_CONSL_APPR ON DIM_BASEL_CAP_CONSL_APPR.N_BASEL_CAP_CONSL_APPR_SKEY = FCT_ENTITY_INFO.N_BASEL_CAP_CONSL_APPR_SKEY) ON STG_OPS_RISK_DATA.V_LV_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_RUN_IDENTIFIER ON DIM_RUN_IDENTIFIER.V_RUN_IDENTIFIER_CODE = STG_OPS_RISK_DATA.V_RUN_IDENTIFIER_CODE LEFT OUTER JOIN DIM_DATES on dim_dates.d_calendar_date = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.n_Date_Skey = dim_dates.n_date_skey AND RUN_PARAMETERS.n_run_skey = '870' AND (DIM_RUN.f_run_definition_mode = 'U' OR (DIM_RUN.f_run_definition_mode = 'R' AND DIM_RUN_IDENTIFIER.v_run_identifier_code = RUN_PARAMETERS.v_run_identifier_code)) LEFT OUTER JOIN FSI_CAP_CURRENCY_CONVERSION ON FSI_CAP_CURRENCY_CONVERSION.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_CURRENCY_CONVERSION.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FSI_CAP_CURRENCY_CONVERSION.V_CCY_CODE = STG_OPS_RISK_DATA.V_CCY_CODE WHERE 1=1 AND STG_OPS_RISK_DATA.FIC_MIS_DATE = to_date('20260331','YYYYMMDD') AND STG_OPS_RISK_DATA.FIC_MIS_DATE BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE AND STG_OPS_RISK_DATA.FIC_MIS_DATE BETWEEN DIM_COUNTRY.D_RECORD_START_DATE AND DIM_COUNTRY.D_RECORD_END_DATE AND STG_OPS_RISK_DATA.FIC_MIS_DATE BETWEEN DIM_GEOGRAPHY.D_RECORD_START_DATE AND DIM_GEOGRAPHY.D_RECORD_END_DATE AND STG_OPS_RISK_DATA.FIC_MIS_DATE BETWEEN DIM_LOB.D_RECORD_START_DATE AND DIM_LOB.D_RECORD_END_DATE AND STG_OPS_RISK_DATA.FIC_MIS_DATE BETWEEN DIM_COUNTRY.D_RECORD_START_DATE AND DIM_COUNTRY.D_RECORD_END_DATE AND COALESCE(FCT_ENTITY_INFO.F_CAP_CONSL_ENTITY_IND,'N') = 'Y' AND DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE IN ('FLCS','PRCS') AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND FCT_ENTITY_INFO.n_mis_date_skey = dim_dates.n_date_skey AND STG_OPS_RISK_DATA.V_DATA_PROCESSING_TYPE = CASE WHEN fct_entity_info.n_basel_consl_optn_type_skey = 1 THEN 'C' WHEN fct_entity_info.n_basel_consl_optn_type_skey = 2 THEN 'A' END AND STG_OPS_RISK_DATA.V_LOB_CODE = 'ABLOR' LOG ERRORS INTO FCT_OPS_RISK_DATA$ ('1776768370132_60090787_20260331_1_Job_fa4e89d1da2545fab33e834c9af79d78') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
