-- =====================================================================
-- Task: OTH_PLACED_COLLATERAL_FSI_CAP_MITIGANTS_DATA_CREATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.OTH_PLACED_COLLATERAL_FSI_CAP_MITIGANTS_DATA_CREATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_MITIGANTS(N_MITIGANT_SKEY,N_ISSUE_SKEY,F_ELIGIBILITY_FLAG,V_APPROACH_TYPE,V_UNDERLYING_DATA_IDENTIFIER,N_CAP_APPROACH_TYPE_SKEY,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE,N_RUN_IDENTIFIER_SKEY,F_CLEARED_TRANSACTION_FLAG,N_CENTRAL_COUNTERPARTY_SKEY,N_MITIGANT_VALUE,N_COUNTRY_SKEY,N_EXCHANGE_RATE,N_GAAP_SKEY,N_INSTRUMENT_SKEY,N_MARGIN_TYPE_SKEY,N_MIS_DATE_SKEY,N_ISSUER_SKEY,N_REMARGIN_FREQUENCY,N_RESIDUAL_MATURITY,N_REVAL_FREQUENCY,N_RISK_WEIGHT,N_RUN_PARAMETER_SETUP_SKEY,N_RUN_SKEY,N_BASEL_ISSUER_TYPE_SKEY,N_STANDARD_ISSUER_TYPE_SKEY,N_VOLATILITY_HAIRCUT,V_CCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_EXPOSURE.N_ACCT_SKEY),to_char(DIM_ISSUE.N_ISSUE_SKEY),'Y',FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE,'OTH_PLCD_COLL',to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),to_char(FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY),FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE,to_char(FSI_CAP_REC_TYPE_APPR_TYPE_MAP.N_REC_TYPE_APPR_TYPE_MAP_SKEY),FSI_PLACED_COLLATERAL.F_CLEARED_TRANSACTION_FLAG,to_char(FSI_PLACED_COLLATERAL.N_CENTRAL_COUNTERPARTY_SKEY),to_char(FSI_PLACED_COLLATERAL.N_COLLATERAL_FAIR_VALUE),to_char(FSI_PLACED_COLLATERAL.N_COUNTRY_SKEY),to_char(FSI_PLACED_COLLATERAL.N_EXCHANGE_RATE),to_char(FSI_PLACED_COLLATERAL.N_GAAP_SKEY),to_char(FSI_PLACED_COLLATERAL.N_INSTRUMENT_SKEY),to_char(FSI_PLACED_COLLATERAL.N_MARGIN_TYPE_SKEY),to_char(FSI_PLACED_COLLATERAL.N_MIS_DATE_SKEY),to_char(FSI_PLACED_COLLATERAL.N_PARTY_SKEY),to_char(FSI_PLACED_COLLATERAL.N_REMARGIN_FREQUENCY),to_char(FSI_PLACED_COLLATERAL.N_RESIDUAL_MATURITY),to_char(FSI_PLACED_COLLATERAL.N_REVALUATION_FREQUENCY),to_char(FSI_PLACED_COLLATERAL.N_RISK_WEIGHT),to_char(FSI_PLACED_COLLATERAL.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_PLACED_COLLATERAL.N_RUN_SKEY),to_char(FSI_PLACED_COLLATERAL.N_STANDARD_PARTY_TYPE_SKEY),to_char(FSI_PLACED_COLLATERAL.N_STANDARD_PARTY_TYPE_SKEY),to_char(FSI_PLACED_COLLATERAL.N_VOLATILITY_HAIRCUT),FSI_PLACED_COLLATERAL.V_CCY_CODE FROM FSI_PLACED_COLLATERAL INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_PLACED_COLLATERAL.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' AND FSI_PLACED_COLLATERAL.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN DIM_EXPOSURE ON DIM_EXPOSURE.N_ACCT_SKEY = FSI_PLACED_COLLATERAL.N_POSTED_COLLATERAL_SKEY INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_PLACED_COLLATERAL.N_CAP_RECORD_TYPE_SKEY AND FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'OTH_PLACED_COLL_EXP' LEFT OUTER JOIN FSI_CAP_RUN_EXE_PARAMETERS ON FSI_CAP_RUN_EXE_PARAMETERS.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_RISK_SUB_TYPE = 'NONSEC' LEFT OUTER JOIN RUN_PARAMETERS ON RUN_PARAMETERS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = RUN_PARAMETERS.N_RUN_PARAMETER_SKEY INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE LEFT OUTER JOIN DIM_INSTRUMENT_CONTRACT ON DIM_INSTRUMENT_CONTRACT.N_INSTRUMENT_SKEY = FSI_PLACED_COLLATERAL.N_INSTRUMENT_SKEY LEFT OUTER JOIN DIM_ISSUE ON DIM_ISSUE.V_ISSUE_CODE = DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_ISSUE.D_RECORD_START_DATE AND DIM_ISSUE.D_RECORD_END_DATE LEFT JOIN FSI_CAP_REC_TYPE_APPR_TYPE_MAP ON FSI_CAP_REC_TYPE_APPR_TYPE_MAP.V_RECORD_TYPE = FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE AND FSI_CAP_REC_TYPE_APPR_TYPE_MAP.V_APPROACH_TYPE = FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE WHERE 1=1 AND ( CASE  WHEN DIM_ISSUE.V_ISSUE_CODE IS NULL THEN 1 WHEN DIM_ISSUE.V_ISSUE_CODE IS NOT NULL AND to_date('20260331','YYYYMMDD') BETWEEN DIM_ISSUE.D_RECORD_START_DATE AND DIM_ISSUE.D_RECORD_END_DATE THEN 2 END ) = ( CASE  WHEN DIM_ISSUE.V_ISSUE_CODE IS NULL THEN 1 WHEN DIM_ISSUE.V_ISSUE_CODE IS NOT NULL THEN 2 END ) AND ( CASE  WHEN DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE IS NULL THEN 1 WHEN DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE IS NOT NULL AND to_date('20260331','YYYYMMDD') BETWEEN DIM_INSTRUMENT_CONTRACT.D_RECORD_START_DATE AND DIM_INSTRUMENT_CONTRACT.D_RECORD_END_DATE THEN 2 END ) = ( CASE  WHEN DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE IS NULL THEN 1 WHEN DIM_INSTRUMENT_CONTRACT.V_INSTRUMENT_CODE IS NOT NULL THEN 2 END ) LOG ERRORS INTO FSI_CAP_MITIGANTS$ ('1776768469018_17865242_20260331_1_Job_18a196b26d44491e94135f89fcff4050') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
