-- =====================================================================
-- Task: OTHER_DEDUCTIONS_PHASE_IN_TREATMENT_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.OTHER_DEDUCTIONS_PHASE_IN_TREATMENT_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_PHASE_IN_TREATMENT(N_MIS_DATE_SKEY,N_RUN_SKEY,N_REG_ADJUSTMENT_PHASE_IN_AMT,N_ENTITY_SKEY,N_GAAP_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),STANDARD_ACCT_HEAD.DED_AMOUNT,FCT_ENTITY_INFO.N_ENTITY_SKEY,STANDARD_ACCT_HEAD.N_GAAP_SKEY,STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY FROM ( SELECT ENTITY_GAAP.N_RUN_SKEY N_RUN_SKEY, ENTITY_GAAP.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, ENTITY_GAAP.N_GAAP_SKEY N_GAAP_SKEY, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY N_STD_ACCT_HEAD_SKEY, 0 DED_AMOUNT FROM DIM_STANDARD_ACCT_HEAD, ( SELECT FCT_ENTITY_INFO.N_RUN_SKEY N_RUN_SKEY, FCT_ENTITY_INFO.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, FCT_ENTITY_INFO.N_GAAP_SKEY N_GAAP_SKEY FROM FCT_ENTITY_INFO LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FCT_ENTITY_INFO.N_GAAP_SKEY WHERE DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') GROUP BY FCT_ENTITY_INFO.N_RUN_SKEY, FCT_ENTITY_INFO.N_MIS_DATE_SKEY, FCT_ENTITY_INFO.N_GAAP_SKEY ) ENTITY_GAAP WHERE DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID IN ( 'CAP918', 'CAP919', 'CAP920', 'CAP925', 'CAP926', 'CAP927', 'CAP928', 'CAP861', 'CAP867', 'CAP946', 'CAP1553', 'CAP1556', 'CAP1559', 'CAP1562', 'CAP1551', 'CAP1554', 'CAP1557', 'CAP1560', 'CAP1552', 'CAP1555', 'CAP1558', 'CAP1561', 'CAP1539', 'CAP1542', 'CAP1545', 'CAP1548', 'CAP1540', 'CAP1543', 'CAP1546', 'CAP1549', 'CAP1541', 'CAP1544', 'CAP1547', 'CAP1550' ) AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE ) STANDARD_ACCT_HEAD JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = STANDARD_ACCT_HEAD.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY  AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' WHERE 1=1 LOG ERRORS INTO FSI_PHASE_IN_TREATMENT$ ('1776771220138_75608309_20260331_1_Job_54f091274c1e4a8f8f00531d4ee6c0e3') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
