-- =====================================================================
-- Task: PARTY_SHARE_HOLD_PERCENT_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.PARTY_SHARE_HOLD_PERCENT_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_PARTY_SHR_HLD_PERCENT(N_MIS_DATE_SKEY,N_GAAP_SKEY,N_ENTITY_SKEY,N_PARTY_SKEY,N_RUN_SKEY,F_REPORTING_ENTITY_FLAG,N_SHAREHOLDING_PERCENT)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_ORG_STRUCTURE.N_ENTITY_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),to_char(DIM_RUN.N_RUN_SKEY),FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND,to_char(STG_PARTY_SHR_HLD_PERCENT.N_SHAREHOLDING_PERCENT) FROM STG_PARTY_SHR_HLD_PERCENT INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = STG_PARTY_SHR_HLD_PERCENT.FIC_MIS_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.V_GAAP_CODE = STG_PARTY_SHR_HLD_PERCENT.V_GAAP_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_GAAP.D_RECORD_START_DATE AND DIM_GAAP.D_RECORD_END_DATE LEFT OUTER JOIN DIM_PARTY ON DIM_PARTY.V_PARTY_ID = STG_PARTY_SHR_HLD_PERCENT.V_INVESTED_PARTY_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE INNER JOIN FCT_ENTITY_INFO ON STG_PARTY_SHR_HLD_PERCENT.V_LV_CODE = FCT_ENTITY_INFO.V_ENTITY_CODE AND COALESCE(FCT_ENTITY_INFO.F_CAP_CONSL_ENTITY_IND, 'N') = 'Y' AND FCT_ENTITY_INFO.N_RUN_SKEY = '870' INNER JOIN DIM_ORG_STRUCTURE ON DIM_ORG_STRUCTURE.V_ENTITY_CODE = STG_PARTY_SHR_HLD_PERCENT.V_LV_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_ORG_STRUCTURE.D_RECORD_START_DATE AND DIM_ORG_STRUCTURE.D_RECORD_END_DATE INNER JOIN DIM_BASEL_CAP_CONSL_APPR ON DIM_BASEL_CAP_CONSL_APPR.N_BASEL_CAP_CONSL_APPR_SKEY = FCT_ENTITY_INFO.N_BASEL_CAP_CONSL_APPR_SKEY AND DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE IN ( 'FLCS' ,'PRCS' ) WHERE 1=1 LOG ERRORS INTO FCT_PARTY_SHR_HLD_PERCENT$ ('1776768067405_49519215_20260331_1_Job_b267b2e7a6f94cbcac8db3743f8ee279') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
