-- =====================================================================
-- Task: Post_Haircut_Collateral_Amount_for_Netting_Agreement_Collaterals_SA_CCR
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Post_Haircut_Collateral_Amount_for_Netting_Agreement_Collaterals_SA_CCR(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FSI_NET_AGREEMENT_COLLATERALS TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FSI_NET_AGREEMENT_COLLATERALS.N_RUN_SKEY,FSI_NET_AGREEMENT_COLLATERALS.N_MIS_DATE_SKEY,FSI_NET_AGREEMENT_COLLATERALS.N_GAAP_SKEY,FSI_NET_AGREEMENT_COLLATERALS.F_MARGIN_PLACED_IND,FSI_NET_AGREEMENT_COLLATERALS.N_COLLATERAL_SKEY,FSI_NET_AGREEMENT_COLLATERALS.N_CAP_APPROACH_TYPE_SKEY,(FSI_NET_AGREEMENT_COLLATERALS.N_MTM_VALUE_POST_HAIRCUT) AS  T_1431691591536_0,   (CASE  WHEN  ( (((COALESCE(FSI_NET_AGREEMENT_COLLATERALS.F_MARGIN_PLACED_IND, 'N') = 'Y' ))) ) THEN 10 WHEN  ( (((COALESCE(FSI_NET_AGREEMENT_COLLATERALS.F_MARGIN_PLACED_IND, 'N') = 'N'))) ) THEN 11 ELSE 12 END)  AS COND_1431691591536_10 ,  (CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.n_mtm_value ELSE NULL END  * (1+ CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.n_collateral_haircut ELSE NULL END )) AS EXP_1431691591536_10,(CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.n_mtm_value ELSE NULL END  * (1- CASE WHEN 1 = 1 THEN FSI_NET_AGREEMENT_COLLATERALS.n_collateral_haircut ELSE NULL END )) AS EXP_1431691591536_11,(FSI_NET_AGREEMENT_COLLATERALS.N_MTM_VALUE_POST_HAIRCUT) AS EXP_1431691591536_12  FROM  FSI_NET_AGREEMENT_COLLATERALS INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_MITIGANT_TYPE ON DIM_MITIGANT_TYPE.N_MITIGANT_TYPE_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_COLLATERAL_TYPE_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.F_MARGIN_PLACED_IND = 'N' LEFT OUTER JOIN DIM_STD_MITIGANT_TYPE ON DIM_STD_MITIGANT_TYPE.N_STD_MITIGANT_TYPE_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_STD_COLLATERAL_TYPE_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.F_MARGIN_PLACED_IND = 'N' LEFT OUTER JOIN DIM_STANDARD_PARTY_TYPE ON DIM_STANDARD_PARTY_TYPE.N_STANDARD_PARTY_TYPE_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_STD_PARTY_TYPE_SKEY LEFT OUTER JOIN DIM_BASEL_CREDIT_RATING ON DIM_BASEL_CREDIT_RATING.N_BASEL_RATING = coalesce(FSI_NET_AGREEMENT_COLLATERALS.N_BASEL_RATING,22) LEFT OUTER JOIN FSI_PARTY_TYPE_CLASSIFICATION ON FSI_NET_AGREEMENT_COLLATERALS.N_RUN_SKEY = FSI_PARTY_TYPE_CLASSIFICATION.N_RUN_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.N_MIS_DATE_SKEY = FSI_PARTY_TYPE_CLASSIFICATION.N_MIS_DATE_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.N_PARTY_TYPE_SKEY = FSI_PARTY_TYPE_CLASSIFICATION.N_PARTY_TYPE_SKEY LEFT OUTER JOIN DIM_PRODUCT ON DIM_PRODUCT.N_PROD_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_COLLATERAL_TYPE_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.F_MARGIN_PLACED_IND = 'Y' LEFT OUTER JOIN DIM_BASEL_PRODUCT_TYPE ON DIM_BASEL_PRODUCT_TYPE.N_BASEL_PROD_TYPE_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_STD_COLLATERAL_TYPE_SKEY AND FSI_NET_AGREEMENT_COLLATERALS.F_MARGIN_PLACED_IND = 'Y' INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_NET_AGREEMENT_COLLATERALS.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_BASEL_RATING_BAND_MAP ON FSI_BASEL_RATING_BAND_MAP.N_BASEL_RATING = DIM_BASEL_CREDIT_RATING.N_BASEL_RATING AND FSI_BASEL_RATING_BAND_MAP.N_RUN_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_RUN_SKEY AND FSI_BASEL_RATING_BAND_MAP.N_MIS_DATE_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_MIS_DATE_SKEY AND FSI_BASEL_RATING_BAND_MAP.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN DIM_REG_CAP_RATING ON DIM_REG_CAP_RATING.N_REG_CAP_RATING_SKEY = FSI_BASEL_RATING_BAND_MAP.N_REG_CAP_RATING_SKEY LEFT OUTER JOIN DIM_BASEL_TRANSACTION_TYPE ON DIM_BASEL_TRANSACTION_TYPE.N_BASEL_TXN_TYPE_SKEY = FSI_NET_AGREEMENT_COLLATERALS.N_BASEL_TXN_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_DISCRETE_VALUE A_PROCESSING_TYPE ON FSI_BASEL_RATING_BAND_MAP.V_PROCESSING_TYPE = A_PROCESSING_TYPE.V_CAP_DISCRETE_VALUE AND A_PROCESSING_TYPE.V_CAP_VALUE_TYPE = 'PROCESSING_TYPE'   WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND FSI_BASEL_RATING_BAND_MAP.V_PROCESSING_TYPE = 'NONSEC')  AND (((CASE WHEN A_PROCESSING_TYPE.V_CAP_VALUE_TYPE = 'PROCESSING_TYPE' THEN A_PROCESSING_TYPE.V_CAP_DISCRETE_VALUE END = 'NONSEC') ))  AND ((1=1) AND ( FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = 'NSSTD' ) AND (9=9) AND (3=3))  ) WHERE (   (COND_1431691591536_10 <> 12)  ) ) SS ON ( TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY AND TT.F_MARGIN_PLACED_IND= SS.F_MARGIN_PLACED_IND AND TT.N_COLLATERAL_SKEY= SS.N_COLLATERAL_SKEY AND TT.N_CAP_APPROACH_TYPE_SKEY= SS.N_CAP_APPROACH_TYPE_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_MTM_VALUE_POST_HAIRCUT=  CASE  WHEN  COND_1431691591536_10=10 THEN EXP_1431691591536_10 WHEN  COND_1431691591536_10=11 THEN EXP_1431691591536_11 ELSE EXP_1431691591536_12 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
