-- =====================================================================
-- Task: POST_PHASE_IN_AMOUNT_STD_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.POST_PHASE_IN_AMOUNT_STD_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_MIS_DATE_SKEY,N_RUN_SKEY,N_CAP_COMP_GROUP_SKEY,N_FORECAST_DATE_SKEY,N_ORIG_STD_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_AMT,N_UPD_CAP_COMP_GROUP_SKEY,V_STRESS_SCENARIO_CODE,N_ENTITY,N_GAAP_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY,FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY,COALESCE(FSI_PHASE_IN_TREATMENT.N_BALANCE_PHASE_IN_AMT,0),COALESCE(FSI_PHASE_IN_TREATMENT.N_BALANCE_PHASE_IN_AMT,0),FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY,FSI_PHASE_IN_TREATMENT.V_STRESS_SCENARIO_CODE,to_char(FSI_PHASE_IN_TREATMENT.N_ENTITY_SKEY),to_char(FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY),to_char(FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY) FROM FSI_PHASE_IN_TREATMENT LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_PHASE_IN_TREATMENT.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY= FSI_PHASE_IN_TREATMENT.n_mis_date_skey LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FSI_PHASE_IN_TREATMENT.N_STD_ACCT_HEAD_SKEY WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND coalesce(FSI_PHASE_IN_TREATMENT.N_BAL_CAP_COMP_GROUP_SKEY,-9999) != -9999 LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776771596137_1129049_20260331_1_Job_d620e74532f34a2cbfc8b083cdc61e7a') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
