-- =====================================================================
-- Task: PREV_QTR_CET1_STANDARD_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.PREV_QTR_CET1_STANDARD_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_EXP_STD_ACCT_HEAD(N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY,N_CAP_APPROACH_TYPE_SKEY,N_CAP_COMP_GROUP_SKEY,N_CAP_RECORD_TYPE_SKEY,N_STD_ACCT_HEAD_AMT,V_RECORD_TYPE,N_GAAP_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),to_char(DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),'-1',DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,'-1',COALESCE(FSAH_PREV.N_STD_ACCT_HEAD_AMT,0),'FSAH_ENTRY',to_char(FCT_ENTITY_INFO.N_GAAP_SKEY) FROM FCT_ENTITY_INFO LEFT JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY LEFT JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY LEFT JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID IN ('CAP1916') AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE LEFT JOIN DIM_STANDARD_ACCT_HEAD DSAH_PREV ON DSAH_PREV.V_STD_ACCT_HEAD_ID IN ('CAP841') AND to_date('20260331','YYYYMMDD') BETWEEN DSAH_PREV.D_RECORD_START_DATE AND DSAH_PREV.D_RECORD_END_DATE LEFT JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE IN ('OTH') AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE LEFT JOIN DIM_CAPITAL_COMP_GROUP DIM_CAPITAL_COMP_GROUP_UPD ON DIM_CAPITAL_COMP_GROUP_UPD.V_CAP_COMP_GROUP_CODE IN ('OTH') AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP_UPD.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP_UPD.D_RECORD_END_DATE INNER JOIN ( SELECT DIM_RUN.N_RUN_SKEY, DIM_RUN.FIC_MIS_DATE, DIM_RUN.V_RUN_ID, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'LE' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_ENTITY_CODE, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'CONSOTYPE' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_CONSOLIDATION_TYPE, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'RCY' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_RCY_CODE, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'BASEL_CONF_ID' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_BASEL_CONF_ID FROM RUN_EXE_PARAMETERS INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = RUN_EXE_PARAMETERS.N_RUN_SKEY WHERE DIM_RUN.N_RUN_SKEY = '870' GROUP BY DIM_RUN.N_RUN_SKEY, DIM_RUN.FIC_MIS_DATE, DIM_RUN.V_RUN_ID ) CURR_RUN_SKEY ON CURR_RUN_SKEY.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT JOIN ( SELECT DIM_RUN.N_RUN_SKEY, DIM_RUN.FIC_MIS_DATE, DIM_RUN.V_RUN_ID, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'LE' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_ENTITY_CODE, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'CONSOTYPE' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_CONSOLIDATION_TYPE, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'RCY' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_RCY_CODE, MAX(CASE WHEN RUN_EXE_PARAMETERS.V_PARAM_ID = 'BASEL_CONF_ID' THEN RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE END) V_BASEL_CONF_ID FROM RUN_EXE_PARAMETERS INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = RUN_EXE_PARAMETERS.N_RUN_SKEY GROUP BY DIM_RUN.N_RUN_SKEY, DIM_RUN.FIC_MIS_DATE, DIM_RUN.V_RUN_ID ) PREV_RUN_SKEY ON CURR_RUN_SKEY.V_RUN_ID = PREV_RUN_SKEY.V_RUN_ID AND CURR_RUN_SKEY.V_ENTITY_CODE = PREV_RUN_SKEY.V_ENTITY_CODE AND CURR_RUN_SKEY.V_CONSOLIDATION_TYPE = PREV_RUN_SKEY.V_CONSOLIDATION_TYPE AND CURR_RUN_SKEY.V_RCY_CODE = PREV_RUN_SKEY.V_RCY_CODE AND CURR_RUN_SKEY.V_BASEL_CONF_ID = PREV_RUN_SKEY.V_BASEL_CONF_ID AND TO_CHAR(PREV_RUN_SKEY.FIC_MIS_DATE, 'YYYYMMDD') = TO_CHAR(last_day(add_months(TRUNC(to_date('20260331','YYYYMMDD'), 'Q'), - 1)), 'YYYYMMDD') LEFT JOIN FCT_STANDARD_ACCT_HEAD FSAH_PREV ON FSAH_PREV.N_RUN_SKEY = PREV_RUN_SKEY.N_RUN_SKEY AND FSAH_PREV.N_STD_ACCT_HEAD_SKEY = DSAH_PREV.N_STD_ACCT_HEAD_SKEY AND FSAH_PREV.N_MIS_DATE_SKEY = TO_NUMBER(TO_CHAR(PREV_RUN_SKEY.FIC_MIS_DATE, 'YYYYMMDD')) WHERE 1=1 AND 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' AND DIM_RUN.V_JURISDICTION_CODE = 'APRA' AND NOT EXISTS ( SELECT 1 FROM FCT_CAPITAL_ACCT_HEAD FCT_CAPITAL_ACCT_HEAD_EX LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD DIM_STANDARD_ACCT_HEAD_EX ON DIM_STANDARD_ACCT_HEAD_EX.N_STD_ACCT_HEAD_SKEY = FCT_CAPITAL_ACCT_HEAD_EX.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_DATES DIM_DATES_EX ON DIM_DATES_EX.N_DATE_SKEY = FCT_CAPITAL_ACCT_HEAD_EX.N_MIS_DATE_SKEY WHERE FCT_CAPITAL_ACCT_HEAD_EX.N_RUN_SKEY = '870' AND DIM_DATES_EX.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_STANDARD_ACCT_HEAD_EX.V_STD_ACCT_HEAD_ID IN ('CAP1916') AND FCT_CAPITAL_ACCT_HEAD_EX.N_FORECAST_DATE_SKEY = FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY ) LOG ERRORS INTO FSI_CAP_EXP_STD_ACCT_HEAD$ ('1776770926034_13523613_20260331_1_JOB_6649379887717590') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
