-- =====================================================================
-- Task: RATING_RECLASSIFICATION_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.RATING_RECLASSIFICATION_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_RATING_CLASSIFICATION(N_EXTERNAL_RATING_SKEY,N_MIS_DATE_SKEY,N_INTERNAL_RATING_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CREDIT_RATING.N_CREDIT_RATING_SKEY),to_char(DIM_DATES.N_DATE_SKEY),CASE WHEN DIM_CREDIT_RATING.V_RATING_SRC_CODE = 'INT' THEN DIM_CREDIT_RATING.N_CREDIT_RATING_SKEY ELSE NULL END,'870' FROM DIM_CREDIT_RATING LEFT OUTER JOIN DIM_DATES ON 1=1 WHERE 1=1 AND DIM_DATES.d_calendar_date=to_date('20260331','YYYYMMDD') LOG ERRORS INTO FSI_RATING_CLASSIFICATION$ ('1776768101033_47925241_20260331_1_Job_6521229baa0148328b11a31b9058ca31') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
