-- =====================================================================
-- Task: REFERENCE_ENTITY_RISK_PARAM_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.REFERENCE_ENTITY_RISK_PARAM_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CDS_REF_ENTITY_RISK_PARAM(N_MIS_DATE_SKEY,N_PARTY_SKEY,N_RUN_SKEY,N_PD_PERCENT,V_REF_ENTITY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_PARTY.N_PARTY_SKEY),'870',to_char(STG_PARTY_DETAILS.N_PD_PERCENT),STG_PARTY_DETAILS.V_PARTY_ID FROM STG_PARTY_DETAILS INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = STG_PARTY_DETAILS.FIC_MIS_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_PARTY ON DIM_PARTY.V_PARTY_ID = STG_PARTY_DETAILS.V_PARTY_ID AND to_date('20260331','YYYYMMDD') BETWEEN DIM_PARTY.D_RECORD_START_DATE AND DIM_PARTY.D_RECORD_END_DATE WHERE 1=1 AND 1=1 LOG ERRORS INTO FSI_CDS_REF_ENTITY_RISK_PARAM$ ('1776770702261_70326522_20260331_1_JOB_16291125382105') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
