-- =====================================================================
-- Task: REG_ADJUSTMENT_RWA_STD_ACCT_HEAD_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.REG_ADJUSTMENT_RWA_STD_ACCT_HEAD_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_UPD_CAP_COMP_GROUP_SKEY,N_MIS_DATE_SKEY,N_GAAP_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY,N_FORECAST_DATE_SKEY,N_ORIG_STD_ACCT_HEAD_AMT,N_STD_ACCT_HEAD_AMT,V_STRESS_SCENARIO_CODE,N_ENTITY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_RUN.N_RUN_SKEY),to_char(DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),REG_ADJUST_RWA.N_FORECAST_DATE_SKEY,SUM(REG_ADJUST_RWA.N_STD_ACCT_HEAD_AMT),SUM(REG_ADJUST_RWA.N_STD_ACCT_HEAD_AMT),REG_ADJUST_RWA.V_STRESS_SCENARIO_CODE,to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY) FROM ( SELECT FSI_PHASE_IN_TREATMENT.N_RUN_SKEY N_RUN_SKEY, FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY N_GAAP_SKEY, FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY, FSI_PHASE_IN_TREATMENT.V_STRESS_SCENARIO_CODE, SUM(COALESCE(FSI_PHASE_IN_TREATMENT.N_RISK_WEIGHTED_ASSET, 0)) N_STD_ACCT_HEAD_AMT FROM FSI_PHASE_IN_TREATMENT INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_PHASE_IN_TREATMENT.N_RUN_SKEY and DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') GROUP BY FSI_PHASE_IN_TREATMENT.N_RUN_SKEY, FSI_PHASE_IN_TREATMENT.N_MIS_DATE_SKEY, FSI_PHASE_IN_TREATMENT.N_GAAP_SKEY, FSI_PHASE_IN_TREATMENT.N_FORECAST_DATE_SKEY, FSI_PHASE_IN_TREATMENT.V_STRESS_SCENARIO_CODE UNION ALL SELECT FSI_THRESHOLD_TREATMENT.N_RUN_SKEY N_RUN_SKEY, FSI_THRESHOLD_TREATMENT.N_MIS_DATE_SKEY N_MIS_DATE_SKEY, FSI_THRESHOLD_TREATMENT.N_GAAP_SKEY N_GAAP_SKEY, FSI_THRESHOLD_TREATMENT.N_FORECAST_DATE_SKEY, FSI_THRESHOLD_TREATMENT.V_STRESS_SCENARIO_CODE, SUM(COALESCE(FSI_THRESHOLD_TREATMENT.N_RISK_WEIGHTED_ASSET, 0)) N_STD_ACCT_HEAD_AMT FROM FSI_THRESHOLD_TREATMENT INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_THRESHOLD_TREATMENT.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_THRESHOLD_TREATMENT.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') GROUP BY FSI_THRESHOLD_TREATMENT.N_RUN_SKEY, FSI_THRESHOLD_TREATMENT.N_MIS_DATE_SKEY, FSI_THRESHOLD_TREATMENT.N_GAAP_SKEY, FSI_THRESHOLD_TREATMENT.N_FORECAST_DATE_SKEY, FSI_THRESHOLD_TREATMENT.V_STRESS_SCENARIO_CODE ) REG_ADJUST_RWA INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = REG_ADJUST_RWA.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = REG_ADJUST_RWA.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = REG_ADJUST_RWA.N_GAAP_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP959' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FCT_ENTITY_INFO.N_FORECAST_DATE_SKEY = REG_ADJUST_RWA.N_FORECAST_DATE_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') GROUP BY DIM_RUN.N_RUN_SKEY, DIM_DATES.N_DATE_SKEY, DIM_GAAP.N_GAAP_SKEY, REG_ADJUST_RWA.N_FORECAST_DATE_SKEY, REG_ADJUST_RWA.V_STRESS_SCENARIO_CODE,  DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY, FCT_ENTITY_INFO.N_ENTITY_SKEY ,DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776771926334_99244149_20260331_1_JOB_6644791923860605') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
