-- =====================================================================
-- Task: REP_BANK_PARTY_SHARE_HOLD_PERCENT_CREATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.REP_BANK_PARTY_SHARE_HOLD_PERCENT_CREATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_PARTY_SHR_HLD_PERCENT(N_MIS_DATE_SKEY,N_GAAP_SKEY,N_RUN_SKEY,F_REPORTING_ENTITY_FLAG,N_ENTITY_SKEY,N_PARTY_SKEY,N_SHAREHOLDING_PERCENT)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_GAAP.N_GAAP_SKEY),to_char(DIM_RUN.N_RUN_SKEY),'Y',REP_BNK_PARTY_SHR_HOLD_PER_CR.N_ENTITY_SKEY,REP_BNK_PARTY_SHR_HOLD_PER_CR.N_PARTY_SKEY,'0' FROM (SELECT DISTINCT FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY, (SELECT FCT_ENTITY_INFO.N_ENTITY_SKEY FROM FCT_ENTITY_INFO LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY WHERE FCT_ENTITY_INFO.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y') N_ENTITY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_PARTY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY FROM FCT_PARTY_SHR_HLD_PERCENT LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY WHERE FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') MINUS SELECT FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_ENTITY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_PARTY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY FROM FCT_PARTY_SHR_HLD_PERCENT LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY WHERE FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FCT_PARTY_SHR_HLD_PERCENT.F_REPORTING_ENTITY_FLAG = 'Y') REP_BNK_PARTY_SHR_HOLD_PER_CR LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = REP_BNK_PARTY_SHR_HOLD_PER_CR.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = REP_BNK_PARTY_SHR_HOLD_PER_CR.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = REP_BNK_PARTY_SHR_HOLD_PER_CR.N_GAAP_SKEY WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') LOG ERRORS INTO FCT_PARTY_SHR_HLD_PERCENT$ ('1776768076414_75857512_20260331_1_Job_d9065c0f086a482d8b3ef6daf992e3b1') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
