-- =====================================================================
-- Task: REQ_CNTR_CYC_BUFFER_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.REQ_CNTR_CYC_BUFFER_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_REQUIRED_CNTR_CYC_BUFFER(N_BENCHMARK_CNTR_CYC_BUFFER,N_EXPOSURE_AMT,N_RWA_AMT,N_COUNTRY_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ MAX(FSI_BENCHMARK_CNTR_CYC_BUFFER.N_BENCHMARK_CNTR_CYC_BUFFER),sum(coalesce(FSI_COUNTRYWISE_RISK_SUMMARY.n_ead_amount,0)),sum(coalesce(FSI_COUNTRYWISE_RISK_SUMMARY.n_rwa_amount,0)),to_char(FSI_COUNTRYWISE_RISK_SUMMARY.N_COUNTRY_SKEY),to_char(FSI_COUNTRYWISE_RISK_SUMMARY.N_MIS_DATE_SKEY),to_char(FSI_COUNTRYWISE_RISK_SUMMARY.N_RUN_SKEY) FROM FSI_COUNTRYWISE_RISK_SUMMARY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY=FSI_COUNTRYWISE_RISK_SUMMARY.N_MIS_DATE_SKEY INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY=FSI_COUNTRYWISE_RISK_SUMMARY.N_RUN_SKEY INNER JOIN DIM_ORG_STRUCTURE ON FSI_COUNTRYWISE_RISK_SUMMARY.N_ENTITY_SKEY = DIM_ORG_STRUCTURE.N_ENTITY_SKEY INNER JOIN DIM_COUNTRY ON FSI_COUNTRYWISE_RISK_SUMMARY.N_COUNTRY_SKEY = DIM_COUNTRY.N_COUNTRY_SKEY LEFT OUTER JOIN FSI_BENCHMARK_CNTR_CYC_BUFFER ON DIM_COUNTRY.V_COUNTRY_ID = FSI_BENCHMARK_CNTR_CYC_BUFFER.V_COUNTRY_ID AND DIM_ORG_STRUCTURE.V_CAPITAL_ADEQUACY_REGULATOR = FSI_BENCHMARK_CNTR_CYC_BUFFER.V_CAPITAL_ADEQUACY_REGULATOR AND to_date('20260331','YYYYMMDD') BETWEEN FSI_BENCHMARK_CNTR_CYC_BUFFER.D_START_DATE AND FSI_BENCHMARK_CNTR_CYC_BUFFER.D_END_DATE WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY = '870' GROUP BY FSI_COUNTRYWISE_RISK_SUMMARY.N_COUNTRY_SKEY, FSI_COUNTRYWISE_RISK_SUMMARY.N_MIS_DATE_SKEY, FSI_COUNTRYWISE_RISK_SUMMARY.N_RUN_SKEY LOG ERRORS INTO FSI_REQUIRED_CNTR_CYC_BUFFER$ ('1776772039566_19587316_20260331_1_Job_b140d1f2592f486ba42f98e4bcb8b5ac') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
