-- =====================================================================
-- Task: RESECURITIZED_DEDUCTIONS_STD_ACCT_HEAD_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.RESECURITIZED_DEDUCTIONS_STD_ACCT_HEAD_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_STD_ACCT_HEAD_SKEY,N_ENTITY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),DIM_STD_ACCT_HEAD_TGT.N_STD_ACCT_HEAD_SKEY,to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),to_char(FCT_SEC_EXPOSURES.N_GAAP_SKEY),to_char(FCT_SEC_EXPOSURES.N_MIS_DATE_SKEY),to_char(FCT_SEC_EXPOSURES.N_RUN_SKEY) FROM FCT_SEC_EXPOSURES INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_SEC_EXPOSURES.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON FCT_SEC_EXPOSURES.N_STD_ACCT_HEAD_SKEY = DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_SEC_EXPOSURES.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON FCT_SEC_EXPOSURES.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO ON FCT_SEC_EXPOSURES.N_RUN_SKEY = FCT_ENTITY_INFO.N_RUN_SKEY AND FCT_SEC_EXPOSURES.N_MIS_DATE_SKEY = FCT_ENTITY_INFO.N_MIS_DATE_SKEY AND FCT_SEC_EXPOSURES.N_ENTITY_SKEY = FCT_ENTITY_INFO.N_ENTITY_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' LEFT OUTER JOIN FSI_SETUP_CAPITAL_HEAD ON FSI_SETUP_CAPITAL_HEAD.V_STD_ACCT_HEAD_ID = ('CAP936') AND FSI_SETUP_CAPITAL_HEAD.V_CAPITAL_ADEQUACY_REGULATOR = FCT_ENTITY_INFO.V_CAPITAL_ADEQUACY_REGULATOR AND DIM_DATES.D_CALENDAR_DATE BETWEEN FSI_SETUP_CAPITAL_HEAD.D_START_DATE AND FSI_SETUP_CAPITAL_HEAD.D_END_DATE LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD DIM_STD_ACCT_HEAD_TGT ON DIM_STD_ACCT_HEAD_TGT.V_STD_ACCT_HEAD_ID = ( CASE WHEN DIM_RUN.V_JURISDICTION_CODE = 'APRA' THEN 'CAP1908' ELSE 'CAP570' END ) AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STD_ACCT_HEAD_TGT.D_RECORD_START_DATE AND DIM_STD_ACCT_HEAD_TGT.D_RECORD_END_DATE LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' AND TO_DATE(to_date('20260331','YYYYMMDD')) BETWEEN COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE,TO_DATE(to_date('20260331','YYYYMMDD'))) AND COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD')  AND FCT_SEC_EXPOSURES.F_RESECURITIZED_FLAG = 'Y' GROUP BY FCT_SEC_EXPOSURES.N_GAAP_SKEY, FCT_SEC_EXPOSURES.N_MIS_DATE_SKEY, FCT_SEC_EXPOSURES.N_RUN_SKEY, DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID,FSI_SETUP_CAPITAL_HEAD.N_CAPITAL_COMPONENT_VALUE, DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY, DIM_STD_ACCT_HEAD_TGT.N_STD_ACCT_HEAD_SKEY, FCT_ENTITY_INFO.N_ENTITY_SKEY LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776771768737_65106073_20260331_1_Job_20883bc632384fd4a265a4365d37b86b') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
