-- =====================================================================
-- Task: RUN_PARAMETERS_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.RUN_PARAMETERS_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into RUN_PARAMETERS(N_MIS_DATE_SKEY,V_BASEL_OR_CAP_CHRG_LEVEL,V_CCR_IR_BUCKET_OFFSET,V_CRM_COLLATERAL_APPROACH,V_CRM_COLLATERAL_APPROACH_OTD,V_NS_LST_APPROACH,V_UNUTL_CASH_MARGIN_OPTION,N_DATE_SKEY,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_RUN_PARAMETER_SKEY,N_RUN_SKEY,V_AOCI_OPT_OUT_ELECTION_OPTION,V_CORRELATION_CALC_OPTION_SME,V_CRD_RW_REDUCTION_OPTION,V_CRM_GUAR_AND_CD_APPROACH,V_CRM_METHOD,V_CVA_ALT_APRCH_SUP_APRV,V_CVA_CDS_INDEX_DECOMPOSITION,V_CVA_INCLUDE_SFT,V_CVA_METHOD,V_DATA_SOURCE,V_DFC_ALT_CALC_SUP_APRV,V_DFC_RWA_APPROCH,V_DVA_ADJUSTMENT_OR_DED_IND,V_EQUITY_RW_OR_DEDUCTION,V_EQ_OTC_CCR_APPLICABILITY,V_EXP_ADJ_PROVISIONS,V_FAILED_TRADE_WAIVER,V_FIDUCIARY_ASSET_DERECOG_OPT,V_GAAP_OFFSET_OPTION,V_GSIB_SURCHARGE_METHOD,V_IAA_APPROVAL,V_INC_INT_TXN_IN_CVA_CAP_CHRG,V_INDIRECT_EXP_CALC_APRCH_FLT,V_INT_TRANS_RW_METHOD,V_LTV_LOAN_AMT_OPTION,V_MRS_COMMODITY_RISK_METHOD,V_MRS_INTEREST_RATE_METHOD,V_MRS_OPTIONS_METHOD,V_MTM_T0_ICVA_OPTION,V_NATIONAL_DISCRETION,V_NFIR_EXPLICIT_MAT_ADJ,V_NIR_1YR_MAT_CORP_PR,V_NIR_BOLI_FUND_APP,V_NIR_DEFAULT_RISK_APP,V_NIR_DIL_RISK_IMMATERIAL,V_NIR_EQUITY_APPROACH,V_NIR_EQ_INVST_FUND_APP,V_NIR_EQ_NON_INVST_FUND_APP,V_NIR_SL_PREF_RW,V_NON_DVP_EXP_RW_REDUCTION_OPT,V_NON_SEC_APPROACH,V_NSS_0_RW_FOR_GOLD,V_NSS_100PCT_RW_CORP,V_NSS_BORROWER_CCY_RAT_MDB,V_NSS_ECA_FOR_SOVERIGN,V_NSS_LOWER_RW_CRE,V_NSS_PASTDUE_FOR_NONPASTDUE,V_NSS_RW_OPTION_BANK,V_NSS_RW_OPTION_DPSE,V_NS_HAIRCUT_METHOD,V_NS_OTC_METHOD,V_NS_SFT_METHOD,V_OEM_ADD_ON_OPTION,V_PLACED_COLL_AS_RCV_ASSET,V_PSE_SOV_FUND_GNRL_INT_INVST,V_QUAL_HLD_FIN_SEC_OPTION,V_RUN_IDENTIFIER_CODE,V_RUN_PARAMETERS_SETUP_DESC,V_RUN_PARAMETER_SETUP_CODE,V_RW_OPTION_EXT_RATING,V_SACCR_MULTI_RISK_APPROACH,V_SCP_RW_OR_DEDUCTION,V_SEC_ERBA_APPROACH_SUP_APRV,V_SEC_METHODOLOGY,V_SEC_UNCOND_CF_PMT_DATE_AVAIL,V_SEGMENT_CODE,V_SSF_SIMPLE_N_LGD,V_SUP_APPR_CB_ULY_INST)SELECT  /*+PARALLEL (4)*/ FSI_RUN_PARAMETER.N_DATE_SKEY,FSI_RUN_PARAMETER.V_BASEL_OR_CAP_CHRG_LEVEL,FSI_RUN_PARAMETER.V_CCR_IR_BUCKET_OFFSET,FSI_RUN_PARAMETER.V_CRM_METHOD,FSI_RUN_PARAMETER.V_CRM_METHOD,FSI_RUN_PARAMETER.V_NS_LST_APPROACH,FSI_RUN_PARAMETER.V_UNUTL_CASH_MARGIN_OPTION,to_char(FSI_RUN_PARAMETER.N_DATE_SKEY),to_char(FSI_RUN_PARAMETER.N_RUN_IDENTIFIER_SKEY),to_char(FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_RUN_PARAMETER.N_RUN_PARAMETER_SKEY),to_char(FSI_RUN_PARAMETER.N_RUN_SKEY),FSI_RUN_PARAMETER.V_AOCI_OPT_OUT_ELECTION_OPTION,FSI_RUN_PARAMETER.V_CORRELATION_CALC_OPTION_SME,FSI_RUN_PARAMETER.V_CRD_RW_REDUCTION_OPTION,FSI_RUN_PARAMETER.V_CRM_GUAR_AND_CD_APPROACH,FSI_RUN_PARAMETER.V_CRM_METHOD,FSI_RUN_PARAMETER.V_CVA_ALT_APRCH_SUP_APRV,FSI_RUN_PARAMETER.V_CVA_CDS_INDEX_DECOMPOSITION,FSI_RUN_PARAMETER.V_CVA_INCLUDE_SFT,FSI_RUN_PARAMETER.V_CVA_METHOD,FSI_RUN_PARAMETER.V_DATA_SOURCE,FSI_RUN_PARAMETER.V_DFC_ALT_CALC_SUP_APRV,FSI_RUN_PARAMETER.V_DFC_RWA_APPROCH,FSI_RUN_PARAMETER.V_DVA_ADJUSTMENT_OR_DED_IND,FSI_RUN_PARAMETER.V_EQUITY_RW_OR_DEDUCTION,FSI_RUN_PARAMETER.V_EQ_OTC_CCR_APPLICABILITY,FSI_RUN_PARAMETER.V_EXP_ADJ_PROVISIONS,FSI_RUN_PARAMETER.V_FAILED_TRADE_WAIVER,FSI_RUN_PARAMETER.V_FIDUCIARY_ASSET_DERECOG_OPT,FSI_RUN_PARAMETER.V_GAAP_OFFSET_OPTION,FSI_RUN_PARAMETER.V_GSIB_SURCHARGE_METHOD,FSI_RUN_PARAMETER.V_IAA_APPROVAL,FSI_RUN_PARAMETER.V_INC_INT_TXN_IN_CVA_CAP_CHRG,FSI_RUN_PARAMETER.V_INDIRECT_EXP_CALC_APRCH_FLT,FSI_RUN_PARAMETER.V_INT_TRANS_RW_METHOD,FSI_RUN_PARAMETER.V_LTV_LOAN_AMT_OPTION,FSI_RUN_PARAMETER.V_MRS_COMMODITY_RISK_METHOD,FSI_RUN_PARAMETER.V_MRS_INTEREST_RATE_METHOD,FSI_RUN_PARAMETER.V_MRS_OPTIONS_METHOD,FSI_RUN_PARAMETER.V_MTM_T0_ICVA_OPTION,FSI_RUN_PARAMETER.V_NATIONAL_DISCRETION,FSI_RUN_PARAMETER.V_NFIR_EXPLICIT_MAT_ADJ,FSI_RUN_PARAMETER.V_NIR_1YR_MAT_CORP_PR,FSI_RUN_PARAMETER.V_NIR_BOLI_FUND_APP,FSI_RUN_PARAMETER.V_NIR_DEFAULT_RISK_APP,FSI_RUN_PARAMETER.V_NIR_DIL_RISK_IMMATERIAL,FSI_RUN_PARAMETER.V_NIR_EQUITY_APPROACH,FSI_RUN_PARAMETER.V_NIR_EQ_INVST_FUND_APP,FSI_RUN_PARAMETER.V_NIR_EQ_NON_INVST_FUND_APP,FSI_RUN_PARAMETER.V_NIR_SL_PREF_RW,FSI_RUN_PARAMETER.V_NON_DVP_EXP_RW_REDUCTION_OPT,FSI_RUN_PARAMETER.V_NON_SEC_APPROACH,FSI_RUN_PARAMETER.V_NSS_0_RW_FOR_GOLD,FSI_RUN_PARAMETER.V_NSS_100PCT_RW_CORP,FSI_RUN_PARAMETER.V_NSS_BORROWER_CCY_RAT_MDB,FSI_RUN_PARAMETER.V_NSS_ECA_FOR_SOVERIGN,FSI_RUN_PARAMETER.V_NSS_LOWER_RW_CRE,FSI_RUN_PARAMETER.V_NSS_PASTDUE_FOR_NONPASTDUE,FSI_RUN_PARAMETER.V_NSS_RW_OPTION_BANK,FSI_RUN_PARAMETER.V_NSS_RW_OPTION_DPSE,FSI_RUN_PARAMETER.V_NS_HAIRCUT_METHOD,FSI_RUN_PARAMETER.V_NS_OTC_METHOD,FSI_RUN_PARAMETER.V_NS_SFT_METHOD,FSI_RUN_PARAMETER.V_OEM_ADD_ON_OPTION,FSI_RUN_PARAMETER.V_PLACED_COLL_AS_RCV_ASSET,FSI_RUN_PARAMETER.V_PSE_SOV_FUND_GNRL_INT_INVST,FSI_RUN_PARAMETER.V_QUAL_HLD_FIN_SEC_OPTION,FSI_RUN_PARAMETER.V_RUN_IDENTIFIER_CODE,FSI_RUN_PARAMETER.V_RUN_PARAMETERS_SETUP_DESC,FSI_RUN_PARAMETER.V_RUN_PARAMETER_SETUP_CODE,FSI_RUN_PARAMETER.V_RW_OPTION_EXT_RATING,FSI_RUN_PARAMETER.V_SACCR_MULTI_RISK_APPROACH,FSI_RUN_PARAMETER.V_SCP_RW_OR_DEDUCTION,FSI_RUN_PARAMETER.V_SEC_ERBA_APPROACH_SUP_APRV,FSI_RUN_PARAMETER.V_SEC_METHODOLOGY,FSI_RUN_PARAMETER.V_SEC_UNCOND_CF_PMT_DATE_AVAIL,FSI_RUN_PARAMETER.V_SEGMENT_CODE,FSI_RUN_PARAMETER.V_SSF_SIMPLE_N_LGD,FSI_RUN_PARAMETER.V_SUP_APPR_CB_ULY_INST FROM FSI_RUN_PARAMETER WHERE 1=1 AND FSI_RUN_PARAMETER.N_RUN_SKEY = '870' AND NOT EXISTS (SELECT 1 FROM RUN_PARAMETERS WHERE RUN_PARAMETERS.N_RUN_PARAMETER_SETUP_SKEY = FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY) LOG ERRORS INTO RUN_PARAMETERS$ ('1776767908350_97559229_20260331_1_Job_1608577659316') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
