-- =====================================================================
-- Task: SCP_RISK_WEIGHT_MAPPING_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.SCP_RISK_WEIGHT_MAPPING_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_RW_MAP_MASTER(N_BASEL_RATING,N_MIS_DATE_SKEY,F_BASEL_TYPE_IND,N_BASEL_TYPE_SKEY,F_ST_LT_RATING_FLAG,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_CREDIT_RATING.N_BASEL_RATING),to_char(DIM_DATES.N_DATE_SKEY),'P',-1,F_ST_LT_RATING_FLAG,'870' FROM DIM_BASEL_CREDIT_RATING,DIM_DATES,(SELECT 'L' F_ST_LT_RATING_FLAG FROM sys.DUAL UNION SELECT 'S' F_ST_LT_RATING_FLAG FROM sys.DUAL), (FSI_BASEL_EXEC_APPR_DETAILS JOIN FSI_RUN_PARAMETER ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE = 'COMMON' AND FSI_RUN_PARAMETER.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = FSI_RUN_PARAMETER.N_RUN_PARAMETER_SKEY ) WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND to_date('20260331','YYYYMMDD') BETWEEN DIM_BASEL_CREDIT_RATING.D_RECORD_START_DATE AND DIM_BASEL_CREDIT_RATING.D_RECORD_END_DATE AND COALESCE(DIM_BASEL_CREDIT_RATING.F_BASEL_RATING_TYPE_IND,'L') = CASE WHEN COALESCE(FSI_RUN_PARAMETER.V_SHORT_TERM_EXPOSURES,'OPT-YES') = 'OPT-YES' THEN COALESCE(DIM_BASEL_CREDIT_RATING.F_BASEL_RATING_TYPE_IND,'L') ELSE 'L' END LOG ERRORS INTO FSI_RW_MAP_MASTER$ ('1776768211841_28378862_20260331_1_Job_d72881c46ca3448d944c0a4da0f1c5c1') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
