-- =====================================================================
-- Task: Shareholding_Percent_Multiplication_of_Balance_sheet_Attribute_for_Operational_Risk
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Shareholding_Percent_Multiplication_of_Balance_sheet_Attribute_for_Operational_Risk(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_OPS_RISK_DATA TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_OPS_RISK_DATA.D_FINANCIAL_YEAR,FCT_OPS_RISK_DATA.N_RUN_SKEY,FCT_OPS_RISK_DATA.N_MIS_DATE_SKEY,FCT_OPS_RISK_DATA.N_ENTITY_SKEY,FCT_OPS_RISK_DATA.N_LOB_SKEY,FCT_OPS_RISK_DATA.N_GAAP_SKEY,(FCT_OPS_RISK_DATA.N_LOANS_ADVANCES_AMT) AS  T_1351544874096_0,   (CASE  WHEN  ( ((1=1)) ) THEN 10 ELSE 11 END)  AS COND_1351544874096_10 ,  (CASE WHEN 1 = 1 THEN FCT_OPS_RISK_DATA.n_shareholding_percent ELSE NULL END *CASE WHEN 1 = 1 THEN FCT_OPS_RISK_DATA.n_loans_advances_amt ELSE NULL END  ) AS EXP_1351544874096_10,(FCT_OPS_RISK_DATA.N_LOANS_ADVANCES_AMT) AS EXP_1351544874096_11 ,(FCT_OPS_RISK_DATA.N_NET_NON_INT_INCOME) AS  T_1351544874096_1,   (CASE  WHEN  ( ((1=1)) ) THEN 20 ELSE 21 END)  AS COND_1351544874096_20 ,  (CASE WHEN 1 = 1 THEN FCT_OPS_RISK_DATA.n_shareholding_percent ELSE NULL END *CASE WHEN 1 = 1 THEN FCT_OPS_RISK_DATA.n_net_non_int_income ELSE NULL END ) AS EXP_1351544874096_20,(FCT_OPS_RISK_DATA.N_NET_NON_INT_INCOME) AS EXP_1351544874096_21  FROM  FCT_OPS_RISK_DATA LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FCT_OPS_RISK_DATA .n_mis_date_skey LEFT OUTER JOIN DIM_RUN ON DIM_RUN.n_run_skey = FCT_OPS_RISK_DATA.n_run_skey LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.n_gaap_skey = FCT_OPS_RISK_DATA.n_gaap_skey LEFT OUTER JOIN DIM_GEOGRAPHY ON DIM_GEOGRAPHY.n_branch_skey = FCT_OPS_RISK_DATA.n_branch_skey LEFT OUTER JOIN DIM_BASEL_METHODOLOGY ON DIM_BASEL_METHODOLOGY.n_basel_method_skey = FCT_OPS_RISK_DATA.n_basel_method_skey LEFT OUTER JOIN DIM_COUNTRY ON DIM_COUNTRY.n_country_skey = FCT_OPS_RISK_DATA.n_country_skey LEFT OUTER JOIN DIM_LOB ON DIM_LOB.n_lob_skey = FCT_OPS_RISK_DATA.n_lob_skey /*LEFT OUTER JOIN DIM_INTERNAL_LOB ON DIM_INTERNAL_LOB.n_int_lob_skey = FCT_OPS_RISK_DATA.n_internal_lob_skey */ LEFT OUTER JOIN DIM_STANDARD_LOB ON DIM_STANDARD_LOB.n_std_lob_skey = FCT_OPS_RISK_DATA.n_standard_lob_skey    WHERE (1=1)  AND (DIM_DATES.D_CALENDAR_DATE=TO_DATE('20260331','yyyymmdd') AND DIM_RUN.n_run_skey = '870')  ) WHERE (   (COND_1351544874096_10 <> 11)   OR  (COND_1351544874096_20 <> 21) ) ) SS ON ( TT.D_FINANCIAL_YEAR= SS.D_FINANCIAL_YEAR AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_LOB_SKEY= SS.N_LOB_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY) WHEN MATCHED THEN UPDATE SET  TT.N_LOANS_ADVANCES_AMT=  CASE  WHEN  COND_1351544874096_10=10 THEN EXP_1351544874096_10 ELSE EXP_1351544874096_11 END  , TT.N_NET_NON_INT_INCOME=  CASE  WHEN  COND_1351544874096_20=20 THEN EXP_1351544874096_20 ELSE EXP_1351544874096_21 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
