-- =====================================================================
-- Task: Significant_Investment_in_Party_for_Reporting_Bank_Identification
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.Significant_Investment_in_Party_for_Reporting_Bank_Identification(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    MERGE  INTO FCT_PARTY_SHR_HLD_PERCENT TT USING (   SELECT * FROM (  SELECT  /*+ PARALLEL(4) */ FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY,FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY,FCT_PARTY_SHR_HLD_PERCENT.N_PARTY_SKEY,FCT_PARTY_SHR_HLD_PERCENT.N_ENTITY_SKEY,FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY,(FCT_PARTY_SHR_HLD_PERCENT.F_SIGNIFICANT_INVESTMENT_IND) AS  T_1383040749234_0,   (CASE  WHEN  ( ((((FCT_PARTY_SHR_HLD_PERCENT.N_REP_ENTITY_SHR_HLD_PCT >= .1)))) ) THEN 10 WHEN  ( ((((FCT_PARTY_SHR_HLD_PERCENT.N_REP_ENTITY_SHR_HLD_PCT < .1)))) ) THEN 11 ELSE 12 END)  AS COND_1383040749234_10 ,  ('Y') AS EXP_1383040749234_10,('N') AS EXP_1383040749234_11,(FCT_PARTY_SHR_HLD_PERCENT.F_SIGNIFICANT_INVESTMENT_IND) AS EXP_1383040749234_12  FROM  FCT_PARTY_SHR_HLD_PERCENT INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY INNER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY INNER JOIN (SELECT FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY, FCT_ENTITY_INFO_REP_BNK.N_ENTITY_SKEY N_ENTITY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_PARTY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY, SUM((CASE WHEN FCT_PARTY_SHR_HLD_PERCENT.F_REPORTING_ENTITY_FLAG = 'Y' OR DIM_BASEL_CAP_CONSL_APPR.V_BASEL_CAP_CONSL_APPR_CODE = 'FLCS' THEN 1 ELSE FCT_ENTITY_INFO.N_SHAREHOLDING_PERCENT END) * FCT_PARTY_SHR_HLD_PERCENT.N_SHAREHOLDING_PERCENT) N_REP_ENTITY_SHR_HLD_PCT FROM FCT_PARTY_SHR_HLD_PERCENT INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY INNER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY LEFT OUTER JOIN(FCT_ENTITY_INFO LEFT OUTER JOIN DIM_BASEL_CAP_CONSL_APPR ON DIM_BASEL_CAP_CONSL_APPR.N_BASEL_CAP_CONSL_APPR_SKEY = FCT_ENTITY_INFO.N_BASEL_CAP_CONSL_APPR_SKEY) ON FCT_ENTITY_INFO.N_ENTITY_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_ENTITY_SKEY AND FCT_ENTITY_INFO.N_RUN_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY AND FCT_ENTITY_INFO.N_MIS_DATE_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY AND FCT_ENTITY_INFO.N_GAAP_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY LEFT OUTER JOIN FCT_ENTITY_INFO FCT_ENTITY_INFO_REP_BNK ON FCT_ENTITY_INFO_REP_BNK.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND FCT_ENTITY_INFO_REP_BNK.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FCT_ENTITY_INFO_REP_BNK.N_GAAP_SKEY = DIM_GAAP.N_GAAP_SKEY AND FCT_ENTITY_INFO_REP_BNK.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' GROUP BY FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY, FCT_ENTITY_INFO_REP_BNK.N_ENTITY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_PARTY_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY, FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY) REP_BNK_SHR_HOLD_PERCENT ON REP_BNK_SHR_HOLD_PERCENT.N_ENTITY_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_ENTITY_SKEY AND REP_BNK_SHR_HOLD_PERCENT.N_RUN_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_RUN_SKEY AND REP_BNK_SHR_HOLD_PERCENT.N_MIS_DATE_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_MIS_DATE_SKEY AND REP_BNK_SHR_HOLD_PERCENT.N_GAAP_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_GAAP_SKEY AND REP_BNK_SHR_HOLD_PERCENT.N_PARTY_SKEY = FCT_PARTY_SHR_HLD_PERCENT.N_PARTY_SKEY  WHERE (1=1)  AND (DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.d_calendar_date = TO_DATE('20260331','yyyymmdd'))  ) WHERE (   (COND_1383040749234_10 <> 12)  ) ) SS ON ( TT.N_MIS_DATE_SKEY= SS.N_MIS_DATE_SKEY AND TT.N_RUN_SKEY= SS.N_RUN_SKEY AND TT.N_PARTY_SKEY= SS.N_PARTY_SKEY AND TT.N_ENTITY_SKEY= SS.N_ENTITY_SKEY AND TT.N_GAAP_SKEY= SS.N_GAAP_SKEY) WHEN MATCHED THEN UPDATE SET  TT.F_SIGNIFICANT_INVESTMENT_IND=  CASE  WHEN  COND_1383040749234_10=10 THEN EXP_1383040749234_10 WHEN  COND_1383040749234_10=11 THEN EXP_1383040749234_11 ELSE EXP_1383040749234_12 END;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
