-- =====================================================================
-- Task: SIGNIFICANT_INVST_THRESHOLD_TREATMENT_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.SIGNIFICANT_INVST_THRESHOLD_TREATMENT_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_THRESHOLD_TREATMENT(N_ORIGINAL_AMOUNT,N_STD_ACCT_HEAD_SKEY,N_FORECAST_DATE_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,V_STRESS_SCENARIO_CODE)SELECT  /*+PARALLEL (4)*/ SUM(COALESCE(FSI_NON_REG_CONSL_ENTITY_INVST.N_CET1_INVESTMENT_AMOUNT, 0) ),DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,to_char(FSI_NON_REG_CONSL_ENTITY_INVST.N_FORECAST_DATE_SKEY),to_char(FSI_NON_REG_CONSL_ENTITY_INVST.N_GAAP_SKEY),to_char(FSI_NON_REG_CONSL_ENTITY_INVST.N_MIS_DATE_SKEY),to_char(FSI_NON_REG_CONSL_ENTITY_INVST.N_RUN_SKEY),FSI_NON_REG_CONSL_ENTITY_INVST.V_STRESS_SCENARIO_CODE FROM FSI_NON_REG_CONSL_ENTITY_INVST INNER JOIN DIM_RUN ON FSI_NON_REG_CONSL_ENTITY_INVST.N_RUN_SKEY = '870' AND DIM_RUN.N_RUN_SKEY = FSI_NON_REG_CONSL_ENTITY_INVST.N_RUN_SKEY LEFT JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_NON_REG_CONSL_ENTITY_INVST.n_mis_date_skey LEFT JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FSI_NON_REG_CONSL_ENTITY_INVST.N_GAAP_SKEY LEFT JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP928' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE WHERE 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_NON_REG_CONSL_ENTITY_INVST.F_SIGNIFICANT_INVESTMENT_IND = 'Y' GROUP BY FSI_NON_REG_CONSL_ENTITY_INVST.N_RUN_SKEY, FSI_NON_REG_CONSL_ENTITY_INVST.n_mis_date_skey, FSI_NON_REG_CONSL_ENTITY_INVST.N_GAAP_SKEY,  FSI_NON_REG_CONSL_ENTITY_INVST.N_FORECAST_DATE_SKEY, FSI_NON_REG_CONSL_ENTITY_INVST.V_STRESS_SCENARIO_CODE, DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LOG ERRORS INTO FSI_THRESHOLD_TREATMENT$ ('1776771451087_59905837_20260331_1_Job_c5ef5d04d7be4cd198a00b013b943c14') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
