-- =====================================================================
-- Task: SINGLE_NAME_CDS_HEDGE_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.SINGLE_NAME_CDS_HEDGE_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_MITIGANTS(N_MIS_DATE_SKEY,N_MITIGANT_SKEY,N_RUN_SKEY,F_CVA_HEDGE,N_STD_MITIGANT_TYPE_SKEY,N_MITIGANT_VALUE,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE,N_PARENT_CDS_INDEX_SKEY,N_RESIDUAL_MATURITY,N_RUN_PARAMETER_SETUP_SKEY,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE,N_REF_ENTITY_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_MITIGANT.N_MITIGANT_SKEY),to_char(DIM_RUN.N_RUN_SKEY),'Y',DIM_STD_MITIGANT_TYPE.n_std_mitigant_type_skey,FSI_CAP_MITIGANTS.n_mitigant_value* FSI_CDS_INDEX_COMPOSITION.n_weightage_percent,to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,to_char(FSI_CAP_MITIGANTS.N_MITIGANT_SKEY),to_char(FSI_CAP_MITIGANTS.N_RESIDUAL_MATURITY),to_char(FSI_CAP_MITIGANTS.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY),FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE,to_char(FSI_CDS_INDEX_COMPOSITION.N_PARTY_SKEY) FROM FSI_CDS_INDEX_COMPOSITION FSI_CDS_INDEX_COMPOSITION INNER JOIN DIM_DATES ON FSI_CDS_INDEX_COMPOSITION.D_EFFECTIVE_DATE = DIM_DATES.D_CALENDAR_DATE AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_MITIGANT DIM_MITIGANT_INDEX ON DIM_MITIGANT_INDEX.V_MITIGANT_CODE = FSI_CDS_INDEX_COMPOSITION.V_CDS_INDEX_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_MITIGANT_INDEX.D_RECORD_START_DATE AND DIM_MITIGANT_INDEX.D_RECORD_END_DATE INNER JOIN DIM_MITIGANT ON DIM_MITIGANT.V_MITIGANT_CODE = CONCAT ( CONCAT ( 'INXCMP_' ,DIM_MITIGANT_INDEX.N_MITIGANT_SKEY ) ,CONCAT ( '_' ,FSI_CDS_INDEX_COMPOSITION.N_PARTY_SKEY ) ) AND to_date('20260331','YYYYMMDD') BETWEEN DIM_MITIGANT.D_RECORD_START_DATE AND DIM_MITIGANT.D_RECORD_END_DATE INNER JOIN FSI_CAP_MITIGANTS ON FSI_CAP_MITIGANTS.N_MITIGANT_SKEY = DIM_MITIGANT_INDEX.N_MITIGANT_SKEY AND FSI_CAP_MITIGANTS.N_RUN_SKEY = '870' INNER JOIN FSI_CAP_COUNTERPARTY_CVA ON FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY = FSI_CDS_INDEX_COMPOSITION.N_PARTY_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY = '870' LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_PARAMETER_SETUP_SKEY = FSI_CAP_MITIGANTS.N_RUN_PARAMETER_SETUP_SKEY AND FSI_RUN_PARAMETER.N_RUN_SKEY = '870' LEFT OUTER JOIN DIM_STD_MITIGANT_TYPE ON DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_TYPE_CODE = 'CDS' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STD_MITIGANT_TYPE.D_RECORD_START_DATE AND DIM_STD_MITIGANT_TYPE.D_RECORD_END_DATE JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND V_RISK_SUB_TYPE = 'CCR' INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE INNER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'MITIGANT' WHERE 1=1 AND 1=1 AND FSI_RUN_PARAMETER.V_CVA_CDS_INDEX_DECOMPOSITION IN ( 'OPT0065' ,'OPT0267' ,'OPT0367' ) LOG ERRORS INTO FSI_CAP_MITIGANTS$ ('1776770678733_71836393_20260331_1_JOB_1630667217450') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
