-- =====================================================================
-- Task: SINGLE_NAME_CDS_MITIGANT_DATA_CREATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.SINGLE_NAME_CDS_MITIGANT_DATA_CREATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into DIM_MITIGANT(FIC_MIS_DATE,D_RECORD_END_DATE,D_RECORD_START_DATE,F_LATEST_RECORD_INDICATOR,N_MITIGANT_SKEY,V_MITIGANT_CODE,V_MITIGANT_DESC)SELECT  /*+PARALLEL (4)*/ DIM_DATES.D_CALENDAR_DATE,TO_DATE('12/31/9999','MM/DD/YYYY'),DIM_DATES.D_CALENDAR_DATE,'Y',SEQ_DIM_MITIGANT.nextval,concat(concat('INXCMP_',dim_mitigant_index.n_mitigant_skey),concat('_',FSI_CDS_INDEX_COMPOSITION.N_PARTY_SKEY)),CONCAT ( CONCAT( FSI_CDS_INDEX_COMPOSITION.v_cds_index_code ,'_') ,FSI_CDS_INDEX_COMPOSITION.v_ref_entity_code ) FROM FSI_CDS_INDEX_COMPOSITION INNER JOIN DIM_DATES ON FSI_CDS_INDEX_COMPOSITION.D_EFFECTIVE_DATE =DIM_DATES.D_CALENDAR_DATE INNER JOIN DIM_MITIGANT DIM_MITIGANT_INDEX ON DIM_MITIGANT_INDEX.V_MITIGANT_CODE = FSI_CDS_INDEX_COMPOSITION.V_CDS_INDEX_CODE INNER JOIN FSI_CAP_MITIGANTS ON FSI_CAP_MITIGANTS.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND DIM_MITIGANT_INDEX.N_MITIGANT_SKEY = FSI_CAP_MITIGANTS.N_MITIGANT_SKEY INNER JOIN FSI_CAP_COUNTERPARTY_CVA ON FSI_CAP_COUNTERPARTY_CVA.N_COUNTERPARTY_SKEY = FSI_CDS_INDEX_COMPOSITION.N_PARTY_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_MIS_DATE_SKEY = DIM_DATES.N_DATE_SKEY AND FSI_CAP_COUNTERPARTY_CVA.N_RUN_SKEY = FSI_CAP_MITIGANTS.N_RUN_SKEY INNER JOIN DIM_RUN ON FSI_CAP_MITIGANTS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_MITIGANT_INDEX.D_RECORD_START_DATE AND DIM_MITIGANT_INDEX.D_RECORD_END_DATE AND DIM_RUN.N_RUN_SKEY = '870' AND NOT EXISTS (SELECT 1 FROM DIM_MITIGANT DIM_MITIGANT_COMP WHERE DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_MITIGANT_COMP.D_RECORD_START_DATE AND DIM_MITIGANT_COMP.D_RECORD_END_DATE AND DIM_MITIGANT_COMP.V_MITIGANT_CODE = concat(concat('INXCMP_',dim_mitigant_index.n_mitigant_skey),concat('_',FSI_CDS_INDEX_COMPOSITION.N_PARTY_SKEY))) LOG ERRORS INTO DIM_MITIGANT$ ('1776770669735_99381114_20260331_1_JOB_1630667214671') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
