-- =====================================================================
-- Task: SOVEREIGN_RATINGS_POPULATION
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.SOVEREIGN_RATINGS_POPULATION(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_SOVEREIGN_RATING_DETAILS(N_SOVEREIGN_SKEY,N_RATING_SKEY,N_MIS_DATE_SKEY,V_PURPOSE,N_BASEL_RATING_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_COUNTRY.N_COUNTRY_SKEY),to_char(DIM_CREDIT_RATING.N_CREDIT_RATING_SKEY),to_char(DIM_DATES.N_DATE_SKEY),'Domestic',to_char(FSI_RATING_CLASSIFICATION.N_BASEL_RATING),to_char(FSI_RATING_CLASSIFICATION.N_RUN_SKEY) FROM STG_SOVEREIGN_RATING_DETAILS LEFT OUTER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = STG_SOVEREIGN_RATING_DETAILS.FIC_MIS_DATE INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_CREDIT_RATING ON STG_SOVEREIGN_RATING_DETAILS.V_RATING_CODE = DIM_CREDIT_RATING.V_CREDIT_RATING_CODE AND STG_SOVEREIGN_RATING_DETAILS.V_RATING_SRC_CODE = DIM_CREDIT_RATING.V_RATING_SRC_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CREDIT_RATING.D_RECORD_START_DATE AND DIM_CREDIT_RATING.D_RECORD_END_DATE INNER JOIN ( SELECT DISTINCT FIC_MIS_DATE ,V_CREDIT_RATING_AGENCY ,V_CREDIT_RATING_NAME ,V_JURISDICTION_CODE ,F_REG_ALLOWED_AGENCY_FLAG ,F_BANK_ALLOWED_AGENCY_FLAG FROM FSI_CREDIT_RATING_JUIRSDICTION ) FSI_CREDIT_RATING_JUIRSDICTION ON FSI_CREDIT_RATING_JUIRSDICTION.FIC_MIS_DATE = DIM_DATES.D_CALENDAR_DATE AND FSI_CREDIT_RATING_JUIRSDICTION.V_CREDIT_RATING_AGENCY = DIM_CREDIT_RATING.V_CREDIT_RATING_AGENCY AND FSI_CREDIT_RATING_JUIRSDICTION.V_CREDIT_RATING_NAME = DIM_CREDIT_RATING.V_RATING_SRC_CODE AND FSI_CREDIT_RATING_JUIRSDICTION.V_JURISDICTION_CODE = DIM_RUN.V_JURISDICTION_CODE AND COALESCE(FSI_CREDIT_RATING_JUIRSDICTION.F_REG_ALLOWED_AGENCY_FLAG, 'N') = 'Y' AND COALESCE(FSI_CREDIT_RATING_JUIRSDICTION.F_BANK_ALLOWED_AGENCY_FLAG, 'N') = 'Y' INNER JOIN FSI_RATING_CLASSIFICATION ON DIM_CREDIT_RATING.N_CREDIT_RATING_SKEY = FSI_RATING_CLASSIFICATION.N_EXTERNAL_RATING_SKEY AND FSI_RATING_CLASSIFICATION.N_MIS_DATE_SKEY = DIM_DATES.n_date_skey AND FSI_RATING_CLASSIFICATION.N_RUN_SKEY = '870' INNER JOIN DIM_COUNTRY ON STG_SOVEREIGN_RATING_DETAILS.V_COUNTRY_CODE = DIM_COUNTRY.V_COUNTRY_ID LEFT OUTER JOIN FSI_BASEL_EXEC_APPR_DETAILS ON FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.V_APPROACH_TYPE_CODE = 'COMMON' LEFT OUTER JOIN FSI_RUN_PARAMETER ON FSI_RUN_PARAMETER.N_RUN_SKEY = '870' AND FSI_BASEL_EXEC_APPR_DETAILS.N_RUN_PARAMETER_SKEY = FSI_RUN_PARAMETER.N_RUN_PARAMETER_SKEY WHERE 1=1 AND STG_SOVEREIGN_RATING_DETAILS.fic_mis_date = to_date('20260331','YYYYMMDD') AND STG_SOVEREIGN_RATING_DETAILS.fic_mis_date BETWEEN COALESCE(DIM_COUNTRY.d_record_start_date, STG_SOVEREIGN_RATING_DETAILS.fic_mis_date) AND COALESCE(DIM_COUNTRY.d_record_end_date, STG_SOVEREIGN_RATING_DETAILS.fic_mis_date) AND COALESCE(DIM_CREDIT_RATING.F_ST_LT_RATING_FLAG,'L') = CASE WHEN COALESCE(FSI_RUN_PARAMETER.V_SHORT_TERM_EXPOSURES,'OPT-YES') = 'OPT-YES' THEN COALESCE(DIM_CREDIT_RATING.F_ST_LT_RATING_FLAG,'L') ELSE 'L' END GROUP BY FSI_RATING_CLASSIFICATION.N_RUN_SKEY,DIM_DATES.N_DATE_SKEY,DIM_COUNTRY.N_COUNTRY_SKEY,DIM_CREDIT_RATING.N_CREDIT_RATING_SKEY,FSI_RATING_CLASSIFICATION.N_BASEL_RATING LOG ERRORS INTO FSI_SOVEREIGN_RATING_DETAILS$ ('1776768157033_97309389_20260331_1_JOB_12690961373705694') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
