-- =====================================================================
-- Task: STD_ACCT_HEAD_PHASE_IN_TREATMENT_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.STD_ACCT_HEAD_PHASE_IN_TREATMENT_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_PHASE_IN_TREATMENT(N_REG_ADJUSTMENT_PHASE_IN_AMT,N_ENTITY_SKEY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ COALESCE(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT, 0),to_char(FCT_STANDARD_ACCT_HEAD.N_ENTITY),to_char(FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY),to_char(FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY),to_char(FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY),to_char(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY) FROM FCT_STANDARD_ACCT_HEAD INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY INNER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY INNER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY = FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY LEFT OUTER JOIN FSI_SETUP_CAPITAL_SOURCE ON DIM_RUN.V_JURISDICTION_CODE = FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE AND FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND (COALESCE(FSI_SETUP_CAPITAL_SOURCE.V_SOURCE_TABLE, 'X') <> 'STG_GL_DATA' AND FSI_SETUP_CAPITAL_SOURCE.F_ELIGIBLE_FOR_TRANSITION = 'Y' AND FSI_SETUP_CAPITAL_SOURCE.V_INITIAL_CAP_COMP_GROUP_CODE IN ('DEDCET1','DEDAT1','DEDT2')) LOG ERRORS INTO FSI_PHASE_IN_TREATMENT$ ('1776771211139_54086390_20260331_1_Job_6b52ace9e4b847ea953ff4989fcd7b17') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
