-- =====================================================================
-- Task: STD_ACCT_HEAD_THRESHOLD_TREATMENT_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.STD_ACCT_HEAD_THRESHOLD_TREATMENT_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_THRESHOLD_TREATMENT(N_ORIGINAL_AMOUNT,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_STD_ACCT_HEAD_SKEY)SELECT  /*+PARALLEL (4)*/ COALESCE(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_AMT, 0),to_char(FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY),to_char(FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY),to_char(FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY),to_char(FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY) FROM FCT_STANDARD_ACCT_HEAD LEFT OUTER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FCT_STANDARD_ACCT_HEAD.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_STANDARD_ACCT_HEAD.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_GAAP ON DIM_GAAP.N_GAAP_SKEY = FCT_STANDARD_ACCT_HEAD.N_GAAP_SKEY LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FCT_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY  LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY = FCT_STANDARD_ACCT_HEAD.N_CAP_COMP_GROUP_SKEY WHERE 1=1 AND DIM_RUN.N_RUN_SKEY = '870' AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND ((DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID IN ('CAP861', 'CAP867') AND DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'DEDCET1' )) LOG ERRORS INTO FSI_THRESHOLD_TREATMENT$ ('1776771460165_24856320_20260331_1_Job_cbce3b81a34d42849510ba863f92d635') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
