-- =====================================================================
-- Task: SUB_EXPOSURES_INVESTMENT_UNCOV_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.SUB_EXPOSURES_INVESTMENT_UNCOV_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_SUB_EXPOSURES(N_MIS_DATE_SKEY,N_STD_MITIGANT_TYPE_SKEY,F_DRAWN_EXP_FLAG,F_ELIGIBILITY_FLAG,N_CAPITAL_UL,N_DM_MITIGANT_SKEY,N_EFFECTIVE_ASSET_CLASS_SKEY,N_LGD_PERCENT,N_MITIGANT_SKEY,N_MITIGANT_VALUE,N_MTG_TREATMENT_TYPE_SKEY,N_NET_MITIGANT_VALUE,N_PD_PERCENT,N_EAD_PRE_MITIGATION,N_RISK_WEIGHT,N_RUN_SKEY,N_BASEL_ISSUER_TYPE_SKEY,V_EXPOSURE_TYPE,N_CAP_APPROACH_TYPE_SKEY,V_APPROACH_TYPE,F_EXP_DEFAULTED_FLAG,F_PAST_DUE_FLAG,N_ACCT_SKEY,N_BASEL_ASSET_CLASS_SKEY,N_BASEL_PROD_TYPE_SKEY,N_BASEL_TXN_TYPE_SKEY,N_CCF_PERCENT,N_CCF_PERCENT_DRAWN,N_EFFECTIVE_COUNTRY_SKEY,N_CUST_ANNUAL_SALES,N_EAD_PRE_MITIGATION_DRAWN,N_EFF_MATURITY,N_GAAP_SKEY,N_INSTR_OTH_VALUATION_ADJ_AMT,N_INSTR_VALUATION_ADJ_AMOUNT,N_MIN_HOLDING_PERIOD_EXP,N_ORIGINAL_ASSET_CLASS_SKEY,N_ORIGINAL_MATURITY_EXP,N_RESIDUAL_MATURITY_EXP,N_RUN_PARAMETER_SETUP_SKEY,N_RWA_UL_AMT,N_EAD_PRE_MITIGATION_UNDRAWN,V_ACCOUNT_POOL_ID,V_CCY_CODE,V_PRODUCT_BOOK_CODE,N_CAP_RECORD_TYPE_SKEY,V_RECORD_TYPE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_STD_MITIGANT_TYPE.N_STD_MITIGANT_TYPE_SKEY),'Y','Y',FSI_CAP_INVESTMENT_EXPOSURES.n_pre_mitigation_capital_ul,( -1 * FSI_CAP_INVESTMENT_EXPOSURES.N_ACCT_SKEY),FSI_CAP_INVESTMENT_EXPOSURES.N_BASEL_ASSET_CLASS_SKEY,FSI_CAP_INVESTMENT_EXPOSURES.N_LGD_PERCENT_PRE_CRM,( -1 * FSI_CAP_INVESTMENT_EXPOSURES.N_ACCT_SKEY),COALESCE(FSI_CAP_INVESTMENT_EXPOSURES.n_pre_crm_post_vol_hc_ead , FSI_CAP_INVESTMENT_EXPOSURES.n_ead_pre_mitigation ),dim_mitigant_treatment_type.n_mtg_treatment_type_skey,COALESCE(FSI_CAP_INVESTMENT_EXPOSURES.n_pre_crm_post_vol_hc_ead , FSI_CAP_INVESTMENT_EXPOSURES.n_ead_pre_mitigation ),FSI_CAP_INVESTMENT_EXPOSURES.N_PD_PERCENT,COALESCE(FSI_CAP_INVESTMENT_EXPOSURES.n_pre_crm_post_vol_hc_ead , FSI_CAP_INVESTMENT_EXPOSURES.n_ead_pre_mitigation ),FSI_CAP_INVESTMENT_EXPOSURES.n_pre_mitigation_rw_ul,'870',FSI_CAP_INVESTMENT_EXPOSURES.n_std_counterparty_type_skey,'NON-SEC',to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY),FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,FSI_CAP_INVESTMENT_EXPOSURES.F_EXP_DEFAULTED_FLAG,FSI_CAP_INVESTMENT_EXPOSURES.F_PAST_DUE_FLAG,to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_ACCT_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_BASEL_ASSET_CLASS_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_BASEL_PROD_TYPE_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_BASEL_TXN_TYPE_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_CCF_PERCENT),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_CCF_PERCENT_DRAWN),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_COUNTRY_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_CUST_ANNUAL_SALES),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_DRAWN_EAD_PRE_MITIGATION),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_EFF_MATURITY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_GAAP_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_INSTR_OTH_VALUATION_ADJ_AMT),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_INSTR_VALUATION_ADJ_AMOUNT),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_MIN_HOLDING_PERIOD),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_ORIGINAL_ASSET_CLASS_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_ORIGINAL_MATURITY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_RESIDUAL_MATURITY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_RWA_UL_AMT),to_char(FSI_CAP_INVESTMENT_EXPOSURES.N_UNDRAWN_EAD_PRE_MITIGATION),FSI_CAP_INVESTMENT_EXPOSURES.V_ACCOUNT_POOL_ID,FSI_CAP_INVESTMENT_EXPOSURES.V_CCY_CODE,FSI_CAP_INVESTMENT_EXPOSURES.V_PRODUCT_BOOK_CODE,to_char(FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY),FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE FROM FSI_CAP_INVESTMENT_EXPOSURES INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' AND FSI_CAP_INVESTMENT_EXPOSURES.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_INVESTMENT_EXPOSURES.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_STD_MITIGANT_TYPE ON DIM_STD_MITIGANT_TYPE.v_std_mitigant_type_code = 'UNCOV' AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_STD_MITIGANT_TYPE.D_RECORD_START_DATE AND DIM_STD_MITIGANT_TYPE.D_RECORD_END_DATE LEFT OUTER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_INVESTMENT_EXPOSURES.N_CAP_RECORD_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_INVESTMENT_EXPOSURES.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN dim_mitigant_treatment_type ON dim_mitigant_treatment_type.v_mtg_treatment_type_code='OTH' AND TO_DATE(to_date('20260331','YYYYMMDD')) BETWEEN COALESCE(DIM_MITIGANT_TREATMENT_TYPE.D_RECORD_START_DATE,TO_DATE(to_date('20260331','YYYYMMDD'))) AND COALESCE(DIM_MITIGANT_TREATMENT_TYPE.D_RECORD_END_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) WHERE ((1=1) AND ( FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'BNK_NON_SEC_EXP' OR FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'DRV_NON_SEC_EXP' OR FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'INV_NON_SEC_EXP' OR FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'SFT_NON_SEC_EXP' ) AND (9=9) AND (3=3)) AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_CAP_INVESTMENT_EXPOSURES.V_RECORD_TYPE = 'INV_NON_SEC_EXP' LOG ERRORS INTO FSI_CAP_SUB_EXPOSURES$ ('1776770200265_56022829_20260331_1_Job_2cb00eb6a47e434daf40d1074cea5b59') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
