-- =====================================================================
-- Task: SUB_EXP_COUNTRYWISE_CREDIT_RISK_SUMMARY
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.SUB_EXP_COUNTRYWISE_CREDIT_RISK_SUMMARY(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_COUNTRYWISE_RISK_SUMMARY(N_BASEL_CONSL_OPTN_TYPE_SKEY,N_RISK_TYPE_SKEY,N_EAD_AMOUNT,N_RWA_AMOUNT,V_APPROACH_CODE,N_ENTITY_SKEY,N_COUNTRY_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY),to_char(DIM_RISK_TYPE.N_RISK_TYPE_SKEY),0,0,'STD',to_char(FCT_ENTITY_INFO.N_ENTITY_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_EFFECTIVE_COUNTRY_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY) FROM FSI_CAP_SUB_EXPOSURES INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY INNER JOIN FCT_ENTITY_INFO ON FCT_ENTITY_INFO.N_RUN_SKEY = FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY AND FCT_ENTITY_INFO.F_CAP_CONSL_PARENT_ENTITY_IND = 'Y' INNER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY = FCT_ENTITY_INFO.N_BASEL_CONSL_OPTN_TYPE_SKEY LEFT OUTER JOIN DIM_RISK_TYPE ON UPPER(DIM_RISK_TYPE.V_RISK_TYPE_ID) = 'CR' AND DIM_DATES.D_CALENDAR_DATE BETWEEN DIM_RISK_TYPE.D_RECORD_START_DATE AND DIM_RISK_TYPE.D_RECORD_END_DATE WHERE 1=1 AND FSI_CAP_SUB_EXPOSURES.N_EFFECTIVE_COUNTRY_SKEY IS NOT NULL AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND DIM_RUN.N_RUN_SKEY = '870' GROUP BY FSI_CAP_SUB_EXPOSURES.N_EFFECTIVE_COUNTRY_SKEY, FCT_ENTITY_INFO.N_ENTITY_SKEY, FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY, FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY, DIM_RISK_TYPE.N_RISK_TYPE_SKEY,DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY LOG ERRORS INTO FSI_COUNTRYWISE_RISK_SUMMARY$ ('1776771996375_93113905_20260331_1_Job_3c88618b220f45559b3702a26110ed88') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
