-- =====================================================================
-- Task: T2T_FCT_CCP_DETAILS_STD_ACCT_HEAD_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_FCT_CCP_DETAILS_STD_ACCT_HEAD_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_EXP_STD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_STD_ACCT_HEAD_SKEY,N_CAP_APPROACH_TYPE_SKEY,N_CAP_RECORD_TYPE_SKEY,N_STD_ACCT_HEAD_AMT,V_RECORD_TYPE,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(dim_standard_acct_head.N_STD_ACCT_HEAD_SKEY),'-1','-1',SUM(N_ENTITY_RWA_AMOUNT),'CCP_EXPOSURE',to_char(FCT_CCP_DETAILS.N_GAAP_SKEY),to_char(FCT_CCP_DETAILS.N_MIS_DATE_SKEY),to_char(FCT_CCP_DETAILS.N_RUN_SKEY) FROM FCT_CCP_DETAILS INNER JOIN DIM_RUN ON FCT_CCP_DETAILS.N_RUN_SKEY = '870' AND DIM_RUN.N_RUN_SKEY = FCT_CCP_DETAILS.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FCT_CCP_DETAILS.N_MIS_DATE_SKEY LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE AND DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE LEFT OUTER JOIN DIM_STANDARD_ACCT_HEAD ON V_STD_ACCT_HEAD_ID = 'CAP500' AND to_date('20260331','YYYYMMDD') BETWEEN DIM_STANDARD_ACCT_HEAD.D_RECORD_START_DATE AND DIM_STANDARD_ACCT_HEAD.D_RECORD_END_DATE WHERE 1=1 AND 1=1 GROUP BY fct_ccp_details.N_MIS_DATE_SKEY, fct_ccp_details.N_RUN_SKEY, fct_ccp_details.N_GAAP_SKEY,DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY,DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY LOG ERRORS INTO FSI_CAP_EXP_STD_ACCT_HEAD$ ('1776770863357_65152094_20260331_1_JOB_6649379887792071') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
