-- =====================================================================
-- Task: T2T_MITIGANTS_FSI_CAP_MITIGANT
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_MITIGANTS_FSI_CAP_MITIGANT(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_MITIGANTS(F_CLEARED_TRANSACTION_FLAG,F_COLL_COVERS_ALL_LOSSES,F_CVA_HEDGE,F_DIL_RISK_MITIGANT_FLAG,F_ELIGIBILITY_FLAG,F_ELIG_MUTUAL_FUND_IND,F_ELIG_NON_MAIN_INDEX_IND,F_EQUITY_TRADED_FLAG,F_FINANCIAL_ENTITY_IND,F_INVESTMENT_GRADE_FLAG,F_MAIN_INDEX_IND,F_RESTRUC_COV_IND,F_RE_SECURITIZED_FLAG,F_SECURITIZED_FLAG,F_SENIOR_COLL_FLAG,F_ST_LT_RATING_FLAG,F_UNRATED_DEB_SEC_ELG_FLAG,N_BASEL_ISSUER_RATING,N_BASEL_ISSUER_TYPE_SKEY,N_BASEL_RATING,N_BASEL_SOVEREIGN_RATING,N_BASIS_RISK_WEIGHT,N_CDS_INDEX_RATING,N_CDS_INDEX_WEIGHT,N_CENTRAL_COUNTERPARTY_SKEY,N_CLEARING_MEMBER_SKEY,N_COUNTRY_SKEY,N_CRM_METHOD_SKEY,N_EXCHANGE_RATE,N_EXCHANGE_RATE_AVC,N_FAIR_VALUE_RCY,N_FOREX_HAIRCUT,N_GAAP_SKEY,N_GROUP_ASSET_SIZE,N_GROUP_ASSET_SIZE_IN_AVC_CCY,N_HEDGE_DISCOUNT_FACTOR,N_HOLDING_PERIOD,N_INITIAL_BASEL_RATING,N_INSTRUMENT_SKEY,N_ISSUER_SKEY,N_ISSUER_TYPE_SKEY,N_ISSUE_SKEY,N_LGD_PERCENT,N_MIN_HOLDING_PERIOD,N_MIS_DATE_SKEY,N_MITIGANT_MIN_COLL_LEVEL,N_MITIGANT_SKEY,N_MITIGANT_TYPE_SKEY,N_MITIGANT_VALUE,N_NETTING_AGREEMENT_SKEY,N_ORIGINAL_MATURITY,N_PD_PERCENT,N_REF_ENTITY_SKEY,N_REMARGIN_FREQUENCY,N_RESIDUAL_MATURITY,N_REVAL_FREQUENCY,N_RISK_WEIGHT,N_RISK_WEIGHT_METHOD,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_RUN_SKEY,N_SHAREHOLDING_PERCENT,N_STANDARD_ISSUER_TYPE_SKEY,N_STD_MITIGANT_TYPE_SKEY,N_VALUE_OF_MITIGANT_RCY,N_VOLATILITY_HAIRCUT,V_CCY_CODE,V_MITIGANT_SENIORITY_LEVEL,V_UNDERLYING_DATA_IDENTIFIER)SELECT  /*+PARALLEL (4)*/ FSI_CAP_MITIGANTS.F_CLEARED_TRANSACTION_FLAG,FSI_CAP_MITIGANTS.F_COLL_COVERS_ALL_LOSSES,FSI_CAP_MITIGANTS.F_CVA_HEDGE,FSI_CAP_MITIGANTS.F_DIL_RISK_MITIGANT_FLAG,FSI_CAP_MITIGANTS.F_ELIGIBILITY_FLAG,FSI_CAP_MITIGANTS.F_ELIG_MUTUAL_FUND_IND,FSI_CAP_MITIGANTS.F_ELIG_NON_MAIN_INDEX_IND,FSI_CAP_MITIGANTS.F_EQUITY_TRADED_FLAG,FSI_CAP_MITIGANTS.F_FINANCIAL_ENTITY_IND,FSI_CAP_MITIGANTS.F_INVESTMENT_GRADE_FLAG,FSI_CAP_MITIGANTS.F_MAIN_INDEX_IND,FSI_CAP_MITIGANTS.F_RESTRUC_COV_IND,FSI_CAP_MITIGANTS.F_RE_SECURITIZED_FLAG,FSI_CAP_MITIGANTS.F_SECURITIZED_FLAG,FSI_CAP_MITIGANTS.F_SENIOR_COLL_FLAG,FSI_CAP_MITIGANTS.F_ST_LT_RATING_FLAG,FSI_CAP_MITIGANTS.F_UNRATED_DEB_SEC_ELG_FLAG,to_char(FSI_CAP_MITIGANTS.N_BASEL_ISSUER_RATING),to_char(FSI_CAP_MITIGANTS.N_BASEL_ISSUER_TYPE_SKEY),to_char(FSI_CAP_MITIGANTS.N_BASEL_RATING),to_char(FSI_CAP_MITIGANTS.N_BASEL_SOVEREIGN_RATING),to_char(FSI_CAP_MITIGANTS.N_BASIS_RISK_WEIGHT),to_char(FSI_CAP_MITIGANTS.N_CDS_INDEX_RATING),to_char(FSI_CAP_MITIGANTS.N_CDS_INDEX_WEIGHT),to_char(FSI_CAP_MITIGANTS.N_CENTRAL_COUNTERPARTY_SKEY),to_char(FSI_CAP_MITIGANTS.N_CLEARING_MEMBER_SKEY),to_char(FSI_CAP_MITIGANTS.N_COUNTRY_SKEY),to_char(FSI_CAP_MITIGANTS.N_CRM_METHOD_SKEY),to_char(FSI_CAP_MITIGANTS.N_EXCHANGE_RATE),to_char(FSI_CAP_MITIGANTS.N_EXCHANGE_RATE_AVC),to_char(FSI_CAP_MITIGANTS.N_FAIR_VALUE_RCY),to_char(FSI_CAP_MITIGANTS.N_FOREX_HAIRCUT),to_char(FSI_CAP_MITIGANTS.N_GAAP_SKEY),to_char(FSI_CAP_MITIGANTS.N_GROUP_ASSET_SIZE),to_char(FSI_CAP_MITIGANTS.N_GROUP_ASSET_SIZE_IN_AVC_CCY),to_char(FSI_CAP_MITIGANTS.N_HEDGE_DISCOUNT_FACTOR),to_char(FSI_CAP_MITIGANTS.N_HOLDING_PERIOD),to_char(FSI_CAP_MITIGANTS.N_INITIAL_BASEL_RATING),to_char(FSI_CAP_MITIGANTS.N_INSTRUMENT_SKEY),to_char(FSI_CAP_MITIGANTS.N_ISSUER_SKEY),to_char(FSI_CAP_MITIGANTS.N_ISSUER_TYPE_SKEY),to_char(FSI_CAP_MITIGANTS.N_ISSUE_SKEY),to_char(FSI_CAP_MITIGANTS.N_LGD_PERCENT),to_char(FSI_CAP_MITIGANTS.N_MIN_HOLDING_PERIOD),to_char(FSI_CAP_MITIGANTS.N_MIS_DATE_SKEY),to_char(FSI_CAP_MITIGANTS.N_MITIGANT_MIN_COLL_LEVEL),to_char(FSI_CAP_MITIGANTS.N_MITIGANT_SKEY),to_char(FSI_CAP_MITIGANTS.N_MITIGANT_TYPE_SKEY),to_char(FSI_CAP_MITIGANTS.N_MITIGANT_VALUE),to_char(FSI_CAP_MITIGANTS.N_NETTING_AGREEMENT_SKEY),to_char(FSI_CAP_MITIGANTS.N_ORIGINAL_MATURITY),to_char(FSI_CAP_MITIGANTS.N_PD_PERCENT),to_char(FSI_CAP_MITIGANTS.N_REF_ENTITY_SKEY),to_char(FSI_CAP_MITIGANTS.N_REMARGIN_FREQUENCY),to_char(FSI_CAP_MITIGANTS.N_RESIDUAL_MATURITY),to_char(FSI_CAP_MITIGANTS.N_REVAL_FREQUENCY),to_char(FSI_CAP_MITIGANTS.N_RISK_WEIGHT),to_char(FSI_CAP_MITIGANTS.N_RISK_WEIGHT_METHOD),to_char(FSI_CAP_MITIGANTS.N_RUN_IDENTIFIER_SKEY),to_char(FSI_CAP_MITIGANTS.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_CAP_MITIGANTS.N_RUN_SKEY),to_char(FSI_CAP_MITIGANTS.N_SHAREHOLDING_PERCENT),to_char(FSI_CAP_MITIGANTS.N_STANDARD_ISSUER_TYPE_SKEY),to_char(FSI_CAP_MITIGANTS.N_STD_MITIGANT_TYPE_SKEY),to_char(FSI_CAP_MITIGANTS.N_VALUE_OF_MITIGANT_RCY),to_char(FSI_CAP_MITIGANTS.N_VOLATILITY_HAIRCUT),FSI_CAP_MITIGANTS.V_CCY_CODE,FSI_CAP_MITIGANTS.V_MITIGANT_SENIORITY_LEVEL,FSI_CAP_MITIGANTS.V_UNDERLYING_DATA_IDENTIFIER FROM FSI_CAP_MITIGANTS INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY      = FSI_CAP_MITIGANTS.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE =to_date('20260331','YYYYMMDD') WHERE 1=1 AND TO_DATE(FSI_CAP_MITIGANTS.N_MIS_DATE_SKEY,'YYYYMMDD') = to_date('20260331','YYYYMMDD') AND FSI_CAP_MITIGANTS.V_RECORD_TYPE='MITIGANT' AND FSI_CAP_MITIGANTS.N_RUN_SKEY='870' LOG ERRORS INTO FCT_MITIGANTS$ ('1776772131218_17535939_20260331_1_Job_1588845068510') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
