-- =====================================================================
-- Task: T2T_BASEL_CREDIT_RATING_BAND_MAP_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_BASEL_CREDIT_RATING_BAND_MAP_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_BASEL_RATING_BAND_MAP(N_BASEL_RATING,N_MIS_DATE_SKEY,N_REG_CAP_RATING_SKEY,N_RUN_SKEY,N_REG_RATING_SKEY,V_PROCESSING_TYPE,N_CAP_APPROACH_TYPE_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_BASEL_CREDIT_RATING.N_BASEL_RATING),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_REG_CAP_RATING.N_REG_CAP_RATING_SKEY),to_char(DIM_RUN.N_RUN_SKEY),ALIAS_DIM_BASEL_CREDIT_RATING.N_BASEL_RATING,FSI_BASEL_RATING_MAP_MASTER.V_PROCESSING_TYPE,to_char(FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY) FROM FSI_BASEL_RATING_MAP_MASTER INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.V_JURISDICTION_CODE = FSI_BASEL_RATING_MAP_MASTER.V_JURISDICTION_CODE AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_REG_CAP_RATING ON FSI_BASEL_RATING_MAP_MASTER.V_REG_CAP_RATING = DIM_REG_CAP_RATING.V_REG_CAP_RATING AND FSI_BASEL_RATING_MAP_MASTER.FIC_MIS_DATE BETWEEN DIM_REG_CAP_RATING.D_RECORD_START_DATE AND DIM_REG_CAP_RATING.D_RECORD_END_DATE INNER JOIN DIM_BASEL_CREDIT_RATING ON DIM_BASEL_CREDIT_RATING.V_BASEL_RATING_CODE = FSI_BASEL_RATING_MAP_MASTER.V_BASEL_RATING_CODE AND FSI_BASEL_RATING_MAP_MASTER.FIC_MIS_DATE BETWEEN DIM_BASEL_CREDIT_RATING.D_RECORD_START_DATE AND DIM_BASEL_CREDIT_RATING.D_RECORD_END_DATE LEFT OUTER JOIN DIM_BASEL_CREDIT_RATING ALIAS_DIM_BASEL_CREDIT_RATING ON ALIAS_DIM_BASEL_CREDIT_RATING.V_BASEL_RATING_CODE = FSI_BASEL_RATING_MAP_MASTER.V_REG_RATING AND FSI_BASEL_RATING_MAP_MASTER.FIC_MIS_DATE BETWEEN ALIAS_DIM_BASEL_CREDIT_RATING.D_RECORD_START_DATE AND ALIAS_DIM_BASEL_CREDIT_RATING.D_RECORD_END_DATE INNER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE = FSI_BASEL_RATING_MAP_MASTER.V_APPROACH_TYPE WHERE 1=1 LOG ERRORS INTO FSI_BASEL_RATING_BAND_MAP$ ('1776768255011_21878359_20260331_1_Job_1599133267784') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
