-- =====================================================================
-- Task: T2T_FSI_CAP_NET_POOL_SUB_EXPOSURES
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_FSI_CAP_NET_POOL_SUB_EXPOSURES(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_SUB_EXPOSURES(F_DRAWN_EXP_FLAG,F_ELIGIBILITY_FLAG,N_CAPITAL_UL,N_DM_MITIGANT_SKEY,N_EAD_PRE_MITIGATION,N_EAD_PRE_MITIGATION_DRAWN,N_EAD_PRE_MITIGATION_UNDRAWN,N_EFFECTIVE_ASSET_CLASS_SKEY,N_MTG_TREATMENT_TYPE_SKEY,N_NET_MITIGANT_VALUE,N_RISK_WEIGHT,N_VOLATILITY_HAIRCUT,V_EXPOSURE_TYPE,V_APPROACH_TYPE,N_ACCT_SKEY,N_MIS_DATE_SKEY,N_MITIGANT_SKEY,N_RUN_SKEY,F_MITIGANT_SECURITIZED_FLAG,N_BASEL_ISSUER_RATING,N_BASEL_ISSUER_TYPE_SKEY,N_HOLDING_PERIOD,N_LGD_PERCENT,N_MIN_HOLDING_PERIOD_MTG,N_MITIGANT_VALUE,N_REMARGIN_FREQUENCY_MTG,N_REVAL_FREQUENCY_MTG,N_STD_MITIGANT_TYPE_SKEY,V_ISSUER_CCY_CODE,N_BASEL_ASSET_CLASS_SKEY,N_BASEL_PROD_TYPE_SKEY,N_CAP_APPROACH_TYPE_SKEY,N_CAP_RECORD_TYPE_SKEY,N_EXPOSURE_PARTY_SKEY,N_EFF_MATURITY,N_GAAP_SKEY,N_MIN_HOLDING_PERIOD_EXP,N_ORIGINAL_ASSET_CLASS_SKEY,N_RESIDUAL_MATURITY_EXP,N_RUN_PARAMETER_SETUP_SKEY,V_ACCOUNT_POOL_ID,V_CCY_CODE,V_RECORD_TYPE)SELECT  /*+PARALLEL (4)*/ 'Y','Y',CASE WHEN DIM_STD_MITIGANT_TYPE.v_std_mitigant_type_code = 'UNCOV' THEN FSI_CAP_NETTABLE_POOL.n_pool_pre_crm_cap_ul END,FSI_CAP_MITIGANTS.N_MITIGANT_SKEY,COALESCE(FSI_CAP_NETTABLE_POOL.n_exp_amt,0),COALESCE(FSI_CAP_NETTABLE_POOL.N_EXP_AMT,0),0,FSI_CAP_NETTABLE_POOL.N_BASEL_ASSET_CLASS_SKEY,'-1',COALESCE(FSI_CAP_MITIGANTS.N_MITIGANT_VALUE,0),CASE WHEN DIM_STD_MITIGANT_TYPE.v_std_mitigant_type_code = 'UNCOV' THEN FSI_CAP_NETTABLE_POOL.n_risk_weight ELSE FSI_CAP_MITIGANTS.n_risk_weight END,0,'NON-SEC',FSI_CAP_APPROACH_TYPE_MASTER.V_APPROACH_TYPE,to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_ACCT_SKEY),to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_MIS_DATE_SKEY),to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_MITIGANT_SKEY),to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY),FSI_CAP_MITIGANTS.F_SECURITIZED_FLAG,to_char(FSI_CAP_MITIGANTS.N_BASEL_ISSUER_RATING),to_char(FSI_CAP_MITIGANTS.N_BASEL_ISSUER_TYPE_SKEY),to_char(FSI_CAP_MITIGANTS.N_HOLDING_PERIOD),to_char(FSI_CAP_MITIGANTS.N_LGD_PERCENT),to_char(FSI_CAP_MITIGANTS.N_MIN_HOLDING_PERIOD),to_char(FSI_CAP_MITIGANTS.N_MITIGANT_VALUE),to_char(FSI_CAP_MITIGANTS.N_REMARGIN_FREQUENCY),to_char(FSI_CAP_MITIGANTS.N_REVAL_FREQUENCY),to_char(FSI_CAP_MITIGANTS.N_STD_MITIGANT_TYPE_SKEY),FSI_CAP_MITIGANTS.V_CCY_CODE,to_char(FSI_CAP_NETTABLE_POOL.N_BASEL_ASSET_CLASS_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_BASEL_PROD_TYPE_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_CAP_RECORD_TYPE_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_CUST_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_EFF_MATURITY),to_char(FSI_CAP_NETTABLE_POOL.N_GAAP_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_MIN_HOLDING_PERIOD),to_char(FSI_CAP_NETTABLE_POOL.N_ORIGINAL_ASSET_CLASS_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_RESIDUAL_MATURITY),to_char(FSI_CAP_NETTABLE_POOL.N_RUN_PARAMETER_SETUP_SKEY),FSI_CAP_NETTABLE_POOL.V_ACCOUNT_POOL_ID,FSI_CAP_NETTABLE_POOL.V_CCY_CODE,FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE FROM FSI_CAP_EXP_MITIGANT_MAPPING INNER JOIN FSI_CAP_NETTABLE_POOL ON FSI_CAP_EXP_MITIGANT_MAPPING.n_mis_date_skey = FSI_CAP_NETTABLE_POOL.n_mis_date_skey AND FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY = FSI_CAP_NETTABLE_POOL.N_RUN_SKEY AND FSI_CAP_EXP_MITIGANT_MAPPING.N_ACCT_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY  LEFT OUTER JOIN ( FSI_CAP_MITIGANTS INNER JOIN DIM_STD_MITIGANT_TYPE ON FSI_CAP_MITIGANTS.N_STD_MITIGANT_TYPE_SKEY = DIM_STD_MITIGANT_TYPE.N_STD_MITIGANT_TYPE_SKEY ) ON FSI_CAP_EXP_MITIGANT_MAPPING.n_mis_date_skey = FSI_CAP_MITIGANTS.N_MIS_DATE_SKEY AND FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY = FSI_CAP_MITIGANTS.N_RUN_SKEY AND FSI_CAP_EXP_MITIGANT_MAPPING.N_MITIGANT_SKEY = FSI_CAP_MITIGANTS.N_MITIGANT_SKEY LEFT OUTER JOIN DIM_RUN ON DIM_RUN.n_run_skey = '870' LEFT OUTER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY = FSI_CAP_EXP_MITIGANT_MAPPING.n_mis_date_skey   LEFT OUTER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY  = FSI_CAP_NETTABLE_POOL.N_CAP_RECORD_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_NETTABLE_POOL.N_CAP_APPROACH_TYPE_SKEY WHERE ((1=1) AND ( FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'BNK_NON_SEC_EXP' OR FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'DRV_NON_SEC_EXP' OR FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'INV_NON_SEC_EXP' OR FSI_CAP_RECORD_TYPE_MASTER.V_RECORD_TYPE = 'SFT_NON_SEC_EXP' ) AND (9=9) AND (3=3)) AND 1=1 AND /*Condition DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_CATEGORY <> 'COLL' will restrict any mitigant associated with derivative and SFT to move to sub exposures, unless it is a guarantee*/ DIM_STD_MITIGANT_TYPE.V_STD_MITIGANT_CATEGORY <> 'COLL' AND COALESCE(FSI_CAP_MITIGANTS.F_DIL_RISK_MITIGANT_FLAG, 'N') <> 'Y'  AND COALESCE(FSI_CAP_EXP_MITIGANT_MAPPING.f_eligibility_flag, 'N') = 'Y' AND COALESCE(FSI_CAP_MITIGANTS.f_eligibility_flag, 'N') = 'Y'  AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD')  AND FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY = '870' AND FSI_CAP_MITIGANTS.V_RECORD_TYPE = 'MITIGANT' LOG ERRORS INTO FSI_CAP_SUB_EXPOSURES$ ('1776770218322_47505648_20260331_1_Job_1585235514920') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
