-- =====================================================================
-- Task: T2T_SUB_EXPOSURES_FCT_SUB_EXPOSURES
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_SUB_EXPOSURES_FCT_SUB_EXPOSURES(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_SUB_EXPOSURES(F_DRAWN_EXP_FLAG,F_MITIGANT_SECURITIZED_FLAG,F_PAST_DUE_FLAG,F_SECURITIZED_FLAG,N_ACCT_SKEY,N_ALLOCATION_RANK,N_BANK_BASE_ROLE_SKEY,N_BASEL_ASSET_CLASS_SKEY,N_BASEL_ISSUER_RATING,N_BASEL_ISSUER_TYPE_SKEY,N_BASEL_PROD_TYPE_SKEY,N_BASEL_TXN_TYPE_SKEY,N_CAPITAL_UL,N_CORRELATION_FACTOR,N_CUST_ANNUAL_SALES,N_DM_MITIGANT_SKEY,N_DOUBLE_DEFAULT_GUARANTOR_PD,N_EAD_POST_MITIGATION,N_EAD_PRE_MITIGATION,N_EFFECTIVE_ASSET_CLASS_SKEY,N_EFFECTIVE_COUNTRY_SKEY,N_EFF_MATURITY,N_EXP_COVERED_FACTOR,N_EXP_SENIORITY,N_FOREX_HAIRCUT,N_GAAP_SKEY,N_HOLDING_PERIOD,N_LGD_PERCENT,N_MATURITY_MISMATCH_HAIRCUT,N_MIN_HOLDING_PERIOD_EXP,N_MIN_HOLDING_PERIOD_MTG,N_MIS_DATE_SKEY,N_MITIGANT_MIN_COLL_LEVEL,N_MITIGANT_OVER_COLL_LEVEL,N_MITIGANT_POST_HAIRCUT_AMT,N_MITIGANT_SKEY,N_MITIGANT_VALUE,N_MTG_TREATMENT_TYPE_SKEY,N_NET_MITIGANT_VALUE,N_ORIGINAL_MATURITY_EXP,N_PD_PERCENT,N_POOL_ID,N_REMARGIN_FREQUENCY_MTG,N_RESIDUAL_MATURITY,N_RESIDUAL_MATURITY_EXP,N_RESIDUAL_MATURITY_MTG,N_REVAL_FREQUENCY_MTG,N_RISK_WEIGHT,N_RUN_IDENTIFIER_SKEY,N_RUN_PARAMETER_SETUP_SKEY,N_RUN_SKEY,N_RWA_EL_AMT,N_RWA_UL_AMT,N_STD_MITIGANT_TYPE_SKEY,N_VOLATILITY_HAIRCUT,V_CCY_CODE,V_EXPOSURE_TYPE,V_EXP_MIT_POOL_CARDINALITY,V_ISSUER_CCY_CODE,V_PRODUCT_BOOK_CODE)SELECT  /*+PARALLEL (4)*/ FSI_CAP_SUB_EXPOSURES.F_DRAWN_EXP_FLAG,FSI_CAP_SUB_EXPOSURES.F_MITIGANT_SECURITIZED_FLAG,FSI_CAP_SUB_EXPOSURES.F_PAST_DUE_FLAG,FSI_CAP_SUB_EXPOSURES.F_SECURITIZED_FLAG,to_char(FSI_CAP_SUB_EXPOSURES.N_ACCT_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_ALLOCATION_RANK),to_char(FSI_CAP_SUB_EXPOSURES.N_BANK_BASE_ROLE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_BASEL_ASSET_CLASS_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_BASEL_ISSUER_RATING),to_char(FSI_CAP_SUB_EXPOSURES.N_BASEL_ISSUER_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_BASEL_PROD_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_BASEL_TXN_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_CAPITAL_UL),to_char(FSI_CAP_SUB_EXPOSURES.N_CORRELATION_FACTOR),to_char(FSI_CAP_SUB_EXPOSURES.N_CUST_ANNUAL_SALES),to_char(FSI_CAP_SUB_EXPOSURES.N_DM_MITIGANT_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_DOUBLE_DEFAULT_GUARANTOR_PD),to_char(FSI_CAP_SUB_EXPOSURES.N_EAD_POST_MITIGATION),to_char(FSI_CAP_SUB_EXPOSURES.N_EAD_PRE_MITIGATION),to_char(FSI_CAP_SUB_EXPOSURES.N_EFFECTIVE_ASSET_CLASS_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_EFFECTIVE_COUNTRY_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_EFF_MATURITY),to_char(FSI_CAP_SUB_EXPOSURES.N_EXP_COVERED_FACTOR),to_char(FSI_CAP_SUB_EXPOSURES.N_EXP_SENIORITY),to_char(FSI_CAP_SUB_EXPOSURES.N_FOREX_HAIRCUT),to_char(FSI_CAP_SUB_EXPOSURES.N_GAAP_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_HOLDING_PERIOD),to_char(FSI_CAP_SUB_EXPOSURES.N_LGD_PERCENT),to_char(FSI_CAP_SUB_EXPOSURES.N_MATURITY_MISMATCH_HAIRCUT),to_char(FSI_CAP_SUB_EXPOSURES.N_MIN_HOLDING_PERIOD_EXP),to_char(FSI_CAP_SUB_EXPOSURES.N_MIN_HOLDING_PERIOD_MTG),to_char(FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_MITIGANT_MIN_COLL_LEVEL),to_char(FSI_CAP_SUB_EXPOSURES.N_MITIGANT_OVER_COLL_LEVEL),to_char(FSI_CAP_SUB_EXPOSURES.N_MITIGANT_POST_HAIRCUT_AMT),to_char(FSI_CAP_SUB_EXPOSURES.N_MITIGANT_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_MITIGANT_VALUE),to_char(FSI_CAP_SUB_EXPOSURES.N_MTG_TREATMENT_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_NET_MITIGANT_VALUE),to_char(FSI_CAP_SUB_EXPOSURES.N_ORIGINAL_MATURITY_EXP),to_char(FSI_CAP_SUB_EXPOSURES.N_PD_PERCENT),to_char(FSI_CAP_SUB_EXPOSURES.N_POOL_ID),to_char(FSI_CAP_SUB_EXPOSURES.N_REMARGIN_FREQUENCY_MTG),to_char(FSI_CAP_SUB_EXPOSURES.N_RESIDUAL_MATURITY),to_char(FSI_CAP_SUB_EXPOSURES.N_RESIDUAL_MATURITY_EXP),to_char(FSI_CAP_SUB_EXPOSURES.N_RESIDUAL_MATURITY_MTG),to_char(FSI_CAP_SUB_EXPOSURES.N_REVAL_FREQUENCY_MTG),to_char(FSI_CAP_SUB_EXPOSURES.N_RISK_WEIGHT),to_char(FSI_CAP_SUB_EXPOSURES.N_RUN_IDENTIFIER_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_RUN_PARAMETER_SETUP_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_RWA_EL_AMT),to_char(FSI_CAP_SUB_EXPOSURES.N_RWA_UL_AMT),to_char(FSI_CAP_SUB_EXPOSURES.N_STD_MITIGANT_TYPE_SKEY),to_char(FSI_CAP_SUB_EXPOSURES.N_VOLATILITY_HAIRCUT),FSI_CAP_SUB_EXPOSURES.V_CCY_CODE,FSI_CAP_SUB_EXPOSURES.V_EXPOSURE_TYPE,FSI_CAP_SUB_EXPOSURES.V_EXP_MIT_POOL_CARDINALITY,FSI_CAP_SUB_EXPOSURES.V_ISSUER_CCY_CODE,FSI_CAP_SUB_EXPOSURES.V_PRODUCT_BOOK_CODE FROM FSI_CAP_SUB_EXPOSURES INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_DATES ON DIM_DATES.N_DATE_SKEY      = FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY AND DIM_DATES.D_CALENDAR_DATE =to_date('20260331','YYYYMMDD') WHERE 1=1 AND TO_DATE(FSI_CAP_SUB_EXPOSURES.N_MIS_DATE_SKEY,'YYYYMMDD') = to_date('20260331','YYYYMMDD') AND FSI_CAP_SUB_EXPOSURES.N_RUN_SKEY='870' LOG ERRORS INTO FCT_SUB_EXPOSURES$ ('1776772132293_78430627_20260331_1_Job_1588845183366') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
