-- =====================================================================
-- Task: T2T_FSI_ACCOUNT_PURPOSE_RECLASS_DATA_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_FSI_ACCOUNT_PURPOSE_RECLASS_DATA_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_ACCOUNT_PURPOSE_RECLASS(N_ACCOUNT_PURPOSE_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY,N_REG_CAP_ACCT_PURPOSE_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_ACCOUNT_PURPOSE.N_ACCOUNT_PURPOSE_SKEY),to_char(DIM_DATES.N_DATE_SKEY),to_char(DIM_RUN.N_RUN_SKEY),-1 FROM DIM_ACCOUNT_PURPOSE INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.n_run_skey = 870 WHERE 1=1 LOG ERRORS INTO FSI_ACCOUNT_PURPOSE_RECLASS$ ('1776767880879_78964867_20260331_1_Job_1585059509485') REJECT LIMIT 50;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
