-- =====================================================================
-- Task: T2T_BNK_DEDUCTION_STD_ACCT_HEAD_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_BNK_DEDUCTION_STD_ACCT_HEAD_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FCT_STANDARD_ACCT_HEAD(N_CAP_COMP_GROUP_SKEY,N_STD_ACCT_HEAD_SKEY,N_STD_ACCT_HEAD_AMT,N_ENTITY,N_GAAP_SKEY,N_MIS_DATE_SKEY,N_RUN_SKEY)SELECT  /*+PARALLEL (4)*/ to_char(DIM_CAPITAL_COMP_GROUP.N_CAP_COMP_GROUP_SKEY),to_char(DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY),SUM(COALESCE(FSI_CAP_BANKING_EXPOSURES.N_EXP_DED_AMT,0)),to_char(FSI_CAP_BANKING_EXPOSURES.N_ENTITY_SKEY),to_char(FSI_CAP_BANKING_EXPOSURES.N_GAAP_SKEY),to_char(FSI_CAP_BANKING_EXPOSURES.N_MIS_DATE_SKEY),to_char(FSI_CAP_BANKING_EXPOSURES.N_RUN_SKEY) FROM FSI_CAP_BANKING_EXPOSURES INNER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FSI_CAP_BANKING_EXPOSURES.n_mis_date_skey AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = FSI_CAP_BANKING_EXPOSURES.N_RUN_SKEY AND DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_STANDARD_ACCT_HEAD ON DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY = FSI_CAP_BANKING_EXPOSURES.N_STD_ACCT_HEAD_SKEY AND  DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID = 'CAP599' JOIN FSI_SETUP_CAPITAL_SOURCE ON FSI_SETUP_CAPITAL_SOURCE.V_STD_ACCT_HEAD_ID = DIM_STANDARD_ACCT_HEAD.V_STD_ACCT_HEAD_ID AND FSI_SETUP_CAPITAL_SOURCE.V_JURISDICTION_CODE = DIM_RUN.V_JURISDICTION_CODE LEFT OUTER JOIN DIM_CAPITAL_COMP_GROUP ON TO_DATE(to_date('20260331','YYYYMMDD')) BETWEEN COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_START_DATE,TO_DATE(to_date('20260331','YYYYMMDD'))) AND  COALESCE(DIM_CAPITAL_COMP_GROUP.D_RECORD_END_DATE, TO_DATE(to_date('20260331','YYYYMMDD'))) AND DIM_CAPITAL_COMP_GROUP.V_CAP_COMP_GROUP_CODE = 'OTH' WHERE 1=1 AND 1=1 GROUP BY FSI_CAP_BANKING_EXPOSURES.n_mis_date_skey ,FSI_CAP_BANKING_EXPOSURES.N_RUN_SKEY ,FSI_CAP_BANKING_EXPOSURES.N_GAAP_SKEY ,DIM_STANDARD_ACCT_HEAD.N_STD_ACCT_HEAD_SKEY,dim_capital_comp_group.n_cap_comp_group_skey, FSI_CAP_BANKING_EXPOSURES.N_ENTITY_SKEY LOG ERRORS INTO FCT_STANDARD_ACCT_HEAD$ ('1776770890435_3998506_20260331_1_JOB_6649379887733249') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
