-- =====================================================================
-- Task: T2T_FSI_CAP_JCY_CONVERSION_POP
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_FSI_CAP_JCY_CONVERSION_POP(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_JCY_CONVERSION(V_CCY_CODE,N_MIS_DATE_SKEY,V_RATE_DATA_SOURCE_CD,N_RUN_SKEY,N_EXCHANGE_RATE)SELECT  /*+PARALLEL (4)*/ DIM_CURRENCY.V_ISO_CURRENCY_CD,to_char(DIM_DATES.N_DATE_SKEY),DIM_ORG_STRUCTURE.V_RATE_DATA_SOURCE_CD,to_char(DIM_RUN.N_RUN_SKEY),FN_COM_DT_CCY_CONV_FACTOR(DIM_CURRENCY.V_ISO_CURRENCY_CD, FSI_SETUP_JURISDICTION_INFO.V_CCY_CODE, to_date('20260331','YYYYMMDD'), to_date('20260331','YYYYMMDD'), '870', DIM_ORG_STRUCTURE.N_ENTITY_SKEY) FROM DIM_CURRENCY INNER JOIN DIM_DATES ON DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND to_date('20260331','YYYYMMDD') BETWEEN DIM_CURRENCY.D_RECORD_START_DATE AND DIM_CURRENCY.D_RECORD_END_DATE INNER JOIN DIM_RUN ON DIM_RUN.N_RUN_SKEY = '870' INNER JOIN RUN_EXE_PARAMETERS ON RUN_EXE_PARAMETERS.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND RUN_EXE_PARAMETERS.V_PARAM_ID = 'LE' INNER JOIN DIM_ORG_STRUCTURE ON DIM_ORG_STRUCTURE.V_ENTITY_CODE = RUN_EXE_PARAMETERS.V_PARAM_VALUE_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_ORG_STRUCTURE.D_RECORD_START_DATE AND DIM_ORG_STRUCTURE.D_RECORD_END_DATE LEFT OUTER JOIN RUN_EXE_PARAMETERS RUN_EXE_PARAMETERS_RCY ON RUN_EXE_PARAMETERS_RCY.N_RUN_SKEY = DIM_RUN.N_RUN_SKEY AND RUN_EXE_PARAMETERS_RCY.V_PARAM_ID = 'RCY' LEFT OUTER JOIN FSI_SETUP_JURISDICTION_INFO ON FSI_SETUP_JURISDICTION_INFO.V_JURISDICTION_CODE = coalesce(DIM_RUN.V_JURISDICTION_CODE,'BIS') WHERE 1=1 LOG ERRORS INTO FSI_CAP_JCY_CONVERSION$ ('1776767985406_16062448_20260331_1_Job_1586644437997') REJECT LIMIT 0;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
