-- =====================================================================
-- Task: T2T_SFT_NET_POOL_EXP_MITIGANT_MAPPING
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_SFT_NET_POOL_EXP_MITIGANT_MAPPING(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_EXP_MITIGANT_MAPPING(F_NETTABILITY_FLAG,F_ELIGIBILITY_FLAG,N_CAP_APPROACH_TYPE_SKEY,N_MIS_DATE_SKEY,N_MITIGANT_SKEY,N_RUN_SKEY,V_APPROACH_TYPE,V_MITIGANT_SENIORITY_LEVEL,N_BASEL_ISSUER_TYPE_SKEY,N_ACCT_SKEY,N_RUN_PARAMETER_SETUP_SKEY)SELECT  /*+PARALLEL (4)*/ 'Y',FSI_CAP_EXP_MITIGANT_MAPPING.F_ELIGIBILITY_FLAG,to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_CAP_APPROACH_TYPE_SKEY),to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_MIS_DATE_SKEY),to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_MITIGANT_SKEY),to_char(FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY),FSI_CAP_EXP_MITIGANT_MAPPING.V_APPROACH_TYPE,FSI_CAP_EXP_MITIGANT_MAPPING.V_MITIGANT_SENIORITY_LEVEL,to_char(FSI_CAP_MITIGANTS.N_BASEL_ISSUER_TYPE_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY),to_char(FSI_CAP_NETTABLE_POOL.N_RUN_PARAMETER_SETUP_SKEY) FROM FSI_CAP_EXP_MITIGANT_MAPPING INNER JOIN ( FSI_CAP_SFT_EXPOSURES INNER JOIN FSI_CAP_NETTABLE_POOL ON FSI_CAP_NETTABLE_POOL.n_mis_date_skey = FSI_CAP_SFT_EXPOSURES.n_mis_date_skey AND FSI_CAP_NETTABLE_POOL.N_RUN_SKEY = FSI_CAP_SFT_EXPOSURES.N_RUN_SKEY AND FSI_CAP_NETTABLE_POOL.N_CAP_NETTABLE_POOL_SKEY = FSI_CAP_SFT_EXPOSURES.N_CAP_NETTABLE_POOL_SKEY ) ON FSI_CAP_EXP_MITIGANT_MAPPING.n_mis_date_skey = FSI_CAP_SFT_EXPOSURES.n_mis_date_skey AND FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY = FSI_CAP_SFT_EXPOSURES.N_RUN_SKEY AND FSI_CAP_EXP_MITIGANT_MAPPING.N_ACCT_SKEY = FSI_CAP_SFT_EXPOSURES.N_ACCT_SKEY INNER JOIN FSI_CAP_MITIGANTS ON FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY = FSI_CAP_MITIGANTS.N_RUN_SKEY AND FSI_CAP_EXP_MITIGANT_MAPPING.n_mis_date_skey = FSI_CAP_MITIGANTS.N_MIS_DATE_SKEY AND FSI_CAP_EXP_MITIGANT_MAPPING.N_MITIGANT_SKEY = FSI_CAP_MITIGANTS.N_MITIGANT_SKEY LEFT OUTER JOIN DIM_RUN ON DIM_RUN.n_run_skey = FSI_CAP_EXP_MITIGANT_MAPPING.N_RUN_SKEY LEFT OUTER JOIN DIM_DATES ON DIM_DATES.n_date_skey = FSI_CAP_EXP_MITIGANT_MAPPING.n_mis_date_skey LEFT OUTER JOIN FSI_CAP_APPROACH_TYPE_MASTER ON FSI_CAP_APPROACH_TYPE_MASTER.N_CAP_APPROACH_TYPE_SKEY = FSI_CAP_EXP_MITIGANT_MAPPING.N_CAP_APPROACH_TYPE_SKEY LEFT OUTER JOIN FSI_CAP_RECORD_TYPE_MASTER ON FSI_CAP_RECORD_TYPE_MASTER.N_CAP_RECORD_TYPE_SKEY = FSI_CAP_MITIGANTS.N_CAP_RECORD_TYPE_SKEY WHERE 1=1 AND 1=1 AND DIM_DATES.D_CALENDAR_DATE = to_date('20260331','YYYYMMDD') AND FSI_CAP_NETTABLE_POOL.n_mis_date_skey = DIM_DATES.N_DATE_SKEY AND FSI_CAP_NETTABLE_POOL.N_RUN_SKEY = '870' AND FSI_CAP_NETTABLE_POOL.F_NETTABILITY_FLAG = 'Y' /*START - SFT mitigants are present in both 'MITIGANT' and 'SFT_MITIGANT' partition.Hence to avoid duplicate records in the query,SFT mitigants should be picked only from one partition.Hence the below filter.*/ AND FSI_CAP_MITIGANTS.V_RECORD_TYPE = 'MITIGANT' /*END*/ LOG ERRORS INTO FSI_CAP_EXP_MITIGANT_MAPPING$ ('1776770209444_97462472_20260331_1_Job_1589819016690') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
