-- =====================================================================
-- Task: T2T_FSI_CAP_RUN_EXE_PARAMETERS
-- Schema: OFSERM
-- Wrapped: 2026-04-23
-- Source: OFSAA execution log / metadata extraction
-- =====================================================================
CREATE OR REPLACE FUNCTION OFSERM.T2T_FSI_CAP_RUN_EXE_PARAMETERS(
    P_V_BATCH_ID         VARCHAR2,
    P_V_MIS_DATE         VARCHAR2,
    P_V_RUN_ID           VARCHAR2,
    P_V_PROCESS_ID       VARCHAR2,
    P_V_RUN_EXECUTION_ID VARCHAR2,
    P_N_RUN_SKEY         VARCHAR2,
    P_V_TASK_ID          VARCHAR2
) RETURN VARCHAR2 AUTHID CURRENT_USER AS

    ld_mis_date   DATE          := TO_DATE(P_V_MIS_DATE, 'YYYYMMDD');
    ln_mis_date   NUMBER        := TO_NUMBER(P_V_MIS_DATE);
    ln_run_skey   NUMBER(5)     := TO_NUMBER(SUBSTR(P_N_RUN_SKEY, 8, LENGTH(P_N_RUN_SKEY)));
    lv_run_id     VARCHAR2(64)  := SUBSTR(P_V_RUN_ID, 8, LENGTH(P_V_RUN_ID));

BEGIN

    insert /*+APPEND*/ into FSI_CAP_RUN_EXE_PARAMETERS(N_RUN_SKEY,F_INCREMENTAL_RUN_FLAG,F_IS_BANK_APPLICABLE,F_IS_CRED_DERIVATE_APPLICABLE,F_IS_CR_APPLICABLE,F_IS_INV_APPLICABLE,F_IS_MIXED_EXECUTION,F_IS_MR_APPLICABLE,F_IS_NONSEC_APPLICABLE,F_IS_OR_APPLICABLE,F_IS_SEC_APPLICABLE,F_IS_SFT_APPLICABLE,F_PORTFOLIO_BASED_FLAG,N_BASEL_CONF_DEF_ID,N_BASEL_CONSL_TYPE_SKEY,N_ENTITY_SKEY,N_MIS_DATE_SKEY,V_BASEL_CONF_DEF_ID,V_JURISDICTION_CODE,V_RCY_CODE)SELECT  /*+PARALLEL (4)*/ to_char(DIM_RUN.N_RUN_SKEY),CASE WHEN RUN_EXE_PARAMETERS.EXP_DATA = 'INCR' THEN 'Y' ELSE 'N' END,'Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','N',TO_NUMBER(RUN_EXE_PARAMETERS.BASEL_CONF_ID),DIM_BASEL_CONSL_OPTION_TYPE.N_BASEL_CONSL_OPTN_TYPE_SKEY,DIM_ORG_STRUCTURE.N_ENTITY_SKEY,to_char(to_date('20260331','YYYYMMDD'),'YYYYMMDD'),RUN_EXE_PARAMETERS.BASEL_CONF_ID,FSI_RUN_PARAM_DEFINITION_B.V_JURISDICTION_ID,RUN_EXE_PARAMETERS.RCY FROM DIM_RUN INNER JOIN ( SELECT LE, FIC_MIS_DATE, BASEL_CONF_ID, PREV_MIS_DATE, EXP_DATA, SIGCUR, IS_BACKDATED_EXEC, CONSOTYPE, RCY FROM ( SELECT V_PARAM_VALUE_CODE, V_PARAM_ID FROM RUN_EXE_PARAMETERS WHERE N_RUN_SKEY = '870' ) PIVOT(MAX(V_PARAM_VALUE_CODE) FOR V_PARAM_ID IN ( 'LE' AS LE, 'FIC_MIS_DATE' AS FIC_MIS_DATE, 'BASEL_CONF_ID' AS BASEL_CONF_ID, 'PREV_MIS_DATE' AS PREV_MIS_DATE, 'EXP_DATA' AS EXP_DATA, 'SIGCUR' AS SIGCUR, 'IS_BACKDATED_EXEC' AS IS_BACKDATED_EXEC, 'CONSOTYPE' AS CONSOTYPE, 'RCY' AS RCY )) ) RUN_EXE_PARAMETERS on DIM_RUN.N_RUN_SKEY = '870' INNER JOIN DIM_BASEL_CONSL_OPTION_TYPE ON RUN_EXE_PARAMETERS.CONSOTYPE = DIM_BASEL_CONSL_OPTION_TYPE.V_BASEL_CONSL_OPTN_TYPE_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_BASEL_CONSL_OPTION_TYPE.D_RECORD_START_DATE AND DIM_BASEL_CONSL_OPTION_TYPE.D_RECORD_END_DATE INNER JOIN DIM_ORG_STRUCTURE ON RUN_EXE_PARAMETERS.LE = DIM_ORG_STRUCTURE.V_ENTITY_CODE AND to_date('20260331','YYYYMMDD') BETWEEN DIM_ORG_STRUCTURE.D_RECORD_START_DATE AND DIM_ORG_STRUCTURE.D_RECORD_END_DATE INNER JOIN FSI_RUN_PARAM_DEFINITION_B ON FSI_RUN_PARAM_DEFINITION_B.N_RUN_PARAM_DEFN_ID = RUN_EXE_PARAMETERS.BASEL_CONF_ID WHERE 1=1 LOG ERRORS INTO FSI_CAP_RUN_EXE_PARAMETERS$ ('1776767885178_79105500_20260331_1_Job_1579254449141') REJECT LIMIT UNLIMITED;

    COMMIT;
    RETURN 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'FAIL: ' || SQLERRM;
END;
/
